ktor-components/src/org/jetbrains/ktor/components/Container.kt, ktor-components/src/org/jetbrains/ktor/components/DataStructures.kt, ktor-components/src/org/jetbrains/ktor/components/ReflectionScanner.kt, ktor-components/src/org/jetbrains/ktor/components/Registry.kt, ktor-components/src/org/jetbrains/ktor/components/Storage.kt, ktor-core/src/org/jetbrains/ktor/application/ApplicationRequestHeaders.kt, ktor-core/test/org/jetbrains/ktor/tests/application/ApplicationRequestHeaderTest.kt
- cleanup
- fix NumberFormatException if Host header has no port specified
=> Minor cleanup and fix

ktor-core/src/org/jetbrains/ktor/http/Application.kt, ktor-core/src/org/jetbrains/ktor/http/ContentTypes.kt, ktor-core/src/org/jetbrains/ktor/http/HttpUrlEncoded.kt, ktor-core/test/org/jetbrains/ktor/tests/http/ContentTypeMatchTest.kt, ktor-core/test/org/jetbrains/ktor/tests/http/ContentTypeTest.kt, ktor-core/test/org/jetbrains/ktor/tests/http/UrlEncodedTest.kt, ktor-netty/src/org/jetbrains/ktor/netty/NettyApplicationRequest.kt, ktor-servlet/src/org/jetbrains/ktor/servlet/ServletApplicationRequest.kt
- parse urlencoded content function
- content charset shortcut property
- netty should handle urlencoded parameters
=> Urlencoded content

ktor-core/src/org/jetbrains/ktor/http/Compression.kt, ktor-core/src/org/jetbrains/ktor/testing/TestHost.kt, ktor-core/test/org/jetbrains/ktor/tests/http/CompressionTest.kt
Support for gzip/deflate, configurable compression conditions (to be able to disable compression in cases), simple conditions (by size, compress stream)
=> Response compression

ktor-samples/ktor-samples-websocket/src/org/jetbrains/ktor/samples/chat/ChatServer.kt
=> use more idiomatic name memberLeft

ktor-hosts/ktor-jetty/src/org/jetbrains/ktor/jetty/JettyApplicationHost.kt
Allows configuration of ie. custom threadpool for jetty.
=> Inject factory method for the jetty Server object.

README.md
I didn't know how to import. so it is better.
=> more kindly

ktor-core/src/org/jetbrains/ktor/pipeline/PipelinePhase.kt, ktor-core/src/org/jetbrains/ktor/routing/RoutingPath.kt, ktor-core/src/org/jetbrains/ktor/sessions/SessionSerializerReflection.kt, ktor-core/src/org/jetbrains/ktor/sessions/SessionTrackerByValue.kt, ktor-core/src/org/jetbrains/ktor/util/Text.kt
I was reading over the code of Ktor for further understanding and found some small cleanups, which I applied. Hopefully it is helpful :3
=> Numerous small cleanups while reading over code.

ktor-features/ktor-auth/src/org/jetbrains/ktor/auth/OAuth.kt, ktor-features/ktor-auth/src/org/jetbrains/ktor/auth/OAuth2.kt, ktor-features/ktor-auth/test/org/jetbrains/ktor/tests/auth/OAuth2.kt
Fixed typo in OAuth authentication feature (grand type to grant type)
=> Fixed typo in OAuth feature

ktor-samples/README.md
* Fix indentation: A single space indent does not render as a nested bullet point on Github. Padded to 4 spaces total indentation.
* Capitalize sentences for consistency.
* Wrap code in tick marks.
=> Fix indentation, capitalize sentences, add code ticks

ktor-core-tests/test/org/jetbrains/ktor/tests/session/SessionTest.kt, ktor-core/src/org/jetbrains/ktor/sessions/SessionTransportTransformerDigest.kt, ktor-core/src/org/jetbrains/ktor/util/Crypto.kt, ktor-features/ktor-auth/src/org/jetbrains/ktor/auth/DigestAuth.kt, ktor-features/ktor-auth/src/org/jetbrains/ktor/auth/SimpleAuth.kt, ktor-features/ktor-auth/test/org/jetbrains/ktor/tests/auth/DigestTest.kt
Timing attack on HMAC is possible otherwise
=> Use MessageDigest.isEqual to compare hashes

ktor-features/ktor-locations/src/org/jetbrains/ktor/locations/Locations.kt, ktor-features/ktor-locations/test/org/jetbrains/ktor/tests/locations/LocationsTest.kt
=> Allow objects in locations for parameterless paths

ktor-core-tests/test/org/jetbrains/ktor/tests/http/CallLoggingTest.kt
This PR adds several new unit tests for the `CallLogging` feature.
=> CallLogging Feature Tests

ktor-core/src/org/jetbrains/ktor/routing/RoutingBuilder.kt
Fix the document of `Route.patch` described as building PUT request.
=> Fix document of Route.patch

ktor-features/ktor-metrics/build.gradle, ktor-features/ktor-metrics/src/io/ktor/metrics/Metrics.kt
should fix #223. Furthermore it adds additional jvm specific metrics.
=> Metrics improvement

README.md
fixed some dead links on readme
=> fix README dead links

ktor-features/ktor-jackson/src/io/ktor/jackson/JacksonConverter.kt, ktor-features/ktor-jackson/test/io/ktor/tests/jackson/JacksonTest.kt, ktor-samples/build.gradle, ktor-samples/ktor-samples-jackson/build.gradle, ktor-samples/ktor-samples-jackson/src/io/ktor/samples/jackson/JacksonApplication.kt
Like discussed with @orangy, a small DSL to make the configuration of the Jackson Converter easy.
=> Adopt jackson to provide a useful DSL

ktor-server/ktor-server-core/src/io/ktor/features/CallLogging.kt, ktor-server/ktor-server-core/src/io/ktor/features/DefaultHeaders.kt
(they are used in HelloApplication sample)
=> A bit of top-level docs for CallLogging & DefaultHeaders features

ktor-samples/ktor-samples-kweet/src/io/ktor/samples/kweet/Login.kt
Without this patch any credential check fails.
=> (fix) Incorrect credential check in ktor-sample-kweet app

ktor-samples/ktor-samples-gson/README.md, ktor-samples/ktor-samples-json/README.md
This continues #176 since it was outdated
=> Adding readme file with gson usage instructions

ktor-server/ktor-server-core/src/io/ktor/sessions/SessionTransportCookie.kt
=> Set cookie's domain and path on sessions.clear()

ktor-http/src/io/ktor/http/URLBuilder.kt, ktor-http/src/io/ktor/http/URLUtils.kt, ktor-http/test/io/ktor/tests/http/UrlTest.kt
- Url: Construction from full URL, Url.fullUrl, Url.toString
- URLBuilder.takeFrom: Consder user and password too
=> Url and URLBuilder improvements

ktor-server/ktor-server-core/src/io/ktor/response/ResponseHeaders.kt, ktor-server/ktor-server-netty/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt, ktor-server/ktor-server-netty/src/io/ktor/server/netty/http2/NettyHttp2ApplicationResponse.kt, ktor-utils/src/io/ktor/util/pipeline/Pipeline.kt
Small performance improvements, ~6-7% on Netty load test
=> Performance improvements

ktor-http/src/io/ktor/http/URLBuilder.kt, ktor-http/src/io/ktor/http/URLUtils.kt, ktor-http/test/io/ktor/tests/http/UrlTest.kt
=> Fix Url.fullPath and unifies URLBuilder and Url code

ktor-client/ktor-client-android/test/io/ktor/client/engine/android/CommonTests.kt, ktor-client/ktor-client-apache/test/io/ktor/client/engine/apache/CommonTests.kt, ktor-client/ktor-client-cio/test/io/ktor/client/engine/cio/CommonTests.kt, ktor-client/ktor-client-core/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-okhttp/test/io/ktor/client/engine/okhttp/CommonTests.kt, ktor-client/ktor-client-tests/src/io/ktor/client/tests/AttributesTest.kt
In my case I need to pass some attributes from call and get them after receive response in order to add logs and record metrics
=> [ktor-client] Pass AttributesBuilder through interceptor pipelines

ktor-server/ktor-server-core/src/io/ktor/http/content/OutputStreamContent.kt, ktor-server/ktor-server-core/src/io/ktor/response/ApplicationResponseFunctions.kt, ktor-server/ktor-server-jetty/test/io/ktor/tests/server/jetty/MultipleDispatchOnTimeout.kt, ktor-server/ktor-server-servlet/src/io/ktor/server/servlet/KtorServlet.kt, ktor-server/ktor-server-test-host/src/io/ktor/server/testing/EngineStressSuite.kt, ktor-server/ktor-server-test-host/src/io/ktor/server/testing/EngineTestSuite.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/CompressionTest.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/HeadTest.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/http/RespondWriteTest.kt
Also, rename `respondWrite` to `respondTextWriter`
=> Add respondOutputStream function for binary output 

ktor-server/ktor-server-netty/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/src/io/ktor/server/netty/NettyChannelInitializer.kt
=> Provide user-defined function to configure Netty's HttpServerCodec

ktor-client/ktor-client-features/ktor-client-websocket/test/io/ktor/client/features/websocket/WebSocketTest.kt, ktor-http/ktor-http-cio/src/io/ktor/http/cio/websocket/Frame.kt, ktor-http/ktor-http-cio/src/io/ktor/http/cio/websocket/WebSocketSession.kt
To simplify sending frames and to read the bytes of a frame.
=> Add convenience methods to the WebSockets API

ktor-client/ktor-client-features/ktor-client-json/src/io/ktor/client/features/json/serializer/KotlinxSerializer.kt
This permits setting non-strict mode, for instance.
=> Allows customizing JSON instance

ktor-client/ktor-client-okhttp/src/io/ktor/client/engine/okhttp/OkUtils.kt
=> ktor-client-okhttp: Prevent duplicate cancellation

ktor-server/ktor-server-core/src/io/ktor/sessions/SessionTransportTransformerMessageAuthentication.kt
https://codahale.com/a-lesson-in-timing-attacks/
=> Do a constant time comparison when verifying HMAC

README.md
=> Add 'Reporting Security Vulnerabilities' to README

ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/test/io/ktor/tests/http/CodecTest.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionProvider.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTrackerById.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTrackerByValue.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransportCookie.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransportHeader.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/Sessions.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/sessions/SessionTest.kt
=> Fix incorrect url encoding for some characters (#1094)

ktor-features/ktor-auth-jwt/build.gradle, ktor-features/ktor-auth/build.gradle
=> rm junit compile-time dependency from ktor-auth*

ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
Fixes https://github.com/ktorio/ktor/issues/1201
=> Fix bug of adding unexpected trailing slash (#1201)

build.gradle, gradle.properties, gradle/publish.gradle, gradle/wrapper/gradle-wrapper.properties
- update gradle
- remove bintray publish plugin
=> Migrate to gradle 5.6.1

ktor-features/ktor-metrics/build.gradle, ktor-features/ktor-metrics/jvm/test/io/ktor/metrics/dropwizard/DropwizardMetricsTests.kt
**Subsystem**
ktor-features/ktor-metrics
**Motivation**
https://github.com/ktorio/ktor/issues/1003
**Solution**
Bump the drop wizard version
=> Update dropwizard version

ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/Endpoint.kt
Fixes #1358
Name resolution now honors JVM rules (system properties `networkaddress.cache.ttl` and `networkaddress.cache.negative.ttl`)
=> Postpone (and don't cache) name resolution in cio client

ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/CIOEngine.kt
**Subsystem**
CIO Client
**Motivation**
We have a cycling dependency on close between `CIOEngine` and `Endpoint` and hanging tests as a result.
**Solution**
Break cycling dependency moving `endpoints.forEach { (_, endpoint) -> endpoint.close() }` from `invokeOnCompletion` section.
=> Remove cyclic dependency between CIEngine and Endpoint.

binary-compatibility-validator/reference-public-api/ktor-client-core.txt, binary-compatibility-validator/reference-public-api/ktor-http.txt, gradle.properties, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRedirectTest.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt
=> Don't send Authorization after redirect

ktor-client/ktor-client-android/jvm/test/io/ktor/client/engine/android/AndroidHttpsTest.kt, ktor-client/ktor-client-android/jvm/test/io/ktor/client/engine/android/AndroidProxyTest.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOHttpsTest.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIORequestTest.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-jackson/jvm/test/io/ktor/client/features/json/tests/JacksonTest.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-json-tests/jvm/src/io/ktor/client/features/json/tests/JsonTest.kt, ktor-client/ktor-client-features/ktor-client-logging/common/test/io/ktor/client/features/logging/CommonLoggingTest.kt, ktor-client/ktor-client-features/ktor-client-logging/jvm/test/io/ktor/client/features/logging/JvmLoggingTest.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/RequestTests.kt, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/CommonClientTestUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CallValidatorTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CharsetTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/FeaturesTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpClientCallTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRedirectMockedTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/MockedTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/UserAgentTest.kt, ktor-client/ktor-client-tests/js/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/BuildersTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/CookiesTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/FormsTest.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/HttpRedirectMockedTest.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/features/CookiesTest.kt, ktor-client/ktor-client-tests/posix/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt, ktor-io/common/test/io/ktor/utils/io/tests/ByteChannelBuildersTest.kt
=> Cleanup client test loaders

gradle/native.gradle
**Subsystem**
Gradle scripts
**Motivation**
Ios tests don't work.
**Solution**
See changes
=> Fix Ios test runner.

ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt
**Subsystem**
Http Mock Engine
**Motivation**
#1505 InvocatioCounter was not thread safe for http client mock engine
**Solution**
Add a lock surrounding the important code paths. I did not make use of SynchronizedLists because i want only protect some parts of the code. For instance reading history is not required to be thread safe.
=> Improve ktor-client-mock engine to be thread safe #1505

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientLoader.kt
**Subsystem**
Tests
**Motivation**
Windows doesn't provide the correct behavior for this test.
=> Skip "connection refused" tests on Windows.

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidURLConnectionUtils.kt
**Subsystem**
Client, Android.
**Motivation**
Sometimes Android throws ConnectException instead of SocketTimeoutException in case of connecting exception. We need to handle it.
=> Add ConnectException (as timeout exception) handling into AndroidURLConnectionUtils.

ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpTimeout.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt
**Subsystem**
Client, HttpTimeout feature.
**Motivation**
Wrong message formatting in `HttpRequestTimeoutException`.
=> Fix HttpRequestTimeoutException message (URL Builder).

ktor-io/common/src/io/ktor/utils/io/bits/ByteOrder.kt
=> Fix Short.highByte always return 0

ktor-features/ktor-html-builder/build.gradle
=> Update kotlinx-html version to 0.7.1.

ktor-utils/jvm/src/io/ktor/util/InputJvm.kt, ktor-utils/jvm/test/io/ktor/tests/utils/InputJvmTest.kt
**Subsystem**
`ktor-utils`
**Motivation**
Solves #1347 
**Solution**
Straightforward fix. Added tests also for other InputStream methods.
=> Fix InputStream wrapper for Input (#1347)

ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/DefaultWebSocketTest.kt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/RawWebSocketTest.kt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSessionImpl.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Frame.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/RawWebSocket.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketReader.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketSessionJvm.kt
=> Fix maxFrameSize for fragmented packets

gradle.properties, ktor-client/ktor-client-apache/build.gradle.kts
**Subsystem**
ktor-client-apache
**Motivation**
https://github.com/ktorio/ktor/issues/1018
**Solution**
https://github.com/ktorio/ktor/issues/1018#issuecomment-565975741
=> Fixes CPU 100% Apache Ktor Http Client #1018

binary-compatibility-validator/reference-public-api/ktor-http-cio.txt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/WebSocketEngineSuite.kt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/websocket/CloseReason.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSessionImpl.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationCall.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationRequest.kt
**Subsystem**
`ktor-http`, `ktor-http-cio`, websockets.
**Motivation**
https://github.com/ktorio/ktor/issues/1275#issuecomment-589670631
**Solution**
Cancel `closeReason` in case incoming channel is closed.
=> Fix DefaultWebSocketSession that does not complete closeReason on disconnection.

ktor-io/jvm/src/io/ktor/utils/io/charsets/UTF.kt, ktor-io/jvm/test/io/ktor/utils/io/charsets/UTFTest.kt
**Subsystem**
ktor-io
**Motivation**
The issue described in https://github.com/ktorio/ktor/issues/1718.
=> Fix UTF8 parsing (#1718).

ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpTimeout.kt
=> Remove wrong usages of SharedImmutable annotation

ktor-features/ktor-websockets/api/ktor-websockets.api, ktor-features/ktor-websockets/jvm/src/io/ktor/websocket/Routing.kt
**Subsystem**
Server, Routing
**Motivation**
The issue described in #1075.
=> Improve WebSocket routing API (Fix #1075).

build.gradle, gradle.properties, gradle/publish.gradle, ktor-client/ktor-client-features/ktor-client-tracing/api/ktor-client-tracing.api, ktor-client/ktor-client-features/ktor-client-tracing/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-tracing/common/src/EngineWIthTracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/common/src/IncomingChannelTracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/common/src/OutgoingChannelTracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/common/src/Tracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/common/src/TracingWrapper.kt, ktor-client/ktor-client-features/ktor-client-tracing/common/src/WebSocketSessionTracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/jvm/test/TestTracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/jvm/test/TracingWrapperTest.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/AndroidManifest.xml, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/KtorInspectorWebSocketFrame.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/KtorInspectorWebSocketRequest.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/KtorInspectorWebSocketResponse.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/KtorInterceptorHeaders.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/KtorInterceptorRequest.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/KtorInterceptorResponse.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/src/io/ktor/client/features/tracing/StethoTracer.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/android/test/io/ktor/client/features/tracing/StethoTracerTest.kt, ktor-client/ktor-client-features/ktor-client-tracing/ktor-client-tracing-stetho/build.gradle.kts, settings.gradle
**Subsystem**
Http Client Core, Http Client Features
=> HTTP Client tracing using Stetho Android library

.idea/vcs.xml
**Subsystem**
Undefined
**Motivation**
Quick navigation from IDEA Git log to GitHub issues/PRs
**Solution**
Before - `#1482`, `#1637`
After - #1482, #1637
=> GitHub issue/pr links in IDEA Git log

ktor-client/ktor-client-features/ktor-client-json/ktor-client-json-tests/jvm/test/KotlinxSerializerTest.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-serialization/common/src/io/ktor/client/features/json/serializer/KotlinxSerializer.kt
**Subsystem**
Ktor client, serialization, JSON.
**Motivation**
Problem described in https://github.com/ktorio/ktor/issues/1800.
=> Fix deserialization issue in client (Fix #1800).

gradle/posix.gradle
https://youtrack.jetbrains.com/issue/KT-39302
=> Fix cinterop publishing

ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpCallValidator.kt
**Subsystem**
Client
**Motivation**
Fixes #1345
**Solution**
Reverse the order of validators and exception handlers as the documentation to this feature claims.
=> Fixes #1345

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/UploadTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientTestServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Upload.kt, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/test/io/ktor/tests/http/ContentTypeTest.kt
=> Fix issues with blank content type

ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpStatementTest.kt
=> Fix saved call early completion

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-io/common/src/io/ktor/utils/io/Coroutines.kt, ktor-io/common/test/io/ktor/utils/io/ReaderTest.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
=> Fix exception logged twice in CIO launch channel

gradle.properties, ktor-client/ktor-client-features/ktor-client-json/ktor-client-json-tests/jvm/test/KotlinxSerializerTest.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-serialization/common/src/io/ktor/client/features/json/serializer/KotlinxSerializer.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-serialization/common/test/ContextualSerializationTest.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/JsonSupport.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/SerializationConverter.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/SerializerLookup.kt, ktor-features/ktor-serialization/jvm/test/io/ktor/tests/serialization/JsonTest.kt, ktor-features/ktor-serialization/jvm/test/io/ktor/tests/serialization/SerializationTest.kt
=> Update to new serialization API

ktor-io/common/src/io/ktor/utils/io/core/AbstractInput.kt
**Subsystem**
Core
**Motivation**
These assertions have never failed and they extremely slowdown performance
=> Remove debug assertions

ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
=> Fix parsing of url with space at start

ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultResponseValidation.kt, ktor-client/ktor-client-core/posix/test/ExceptionsTest.kt, ktor-io/common/src/io/ktor/utils/io/concurrent/Shared.kt, ktor-io/js/src/io/ktor/utils/io/concurrent/SharedJs.kt, ktor-io/jvm/src/io/ktor/utils/io/concurrent/SharedJvm.kt, ktor-io/posix/src/io/ktor/utils/io/concurrent/SharedNative.kt
Fix [KTOR-916](https://youtrack.jetbrains.com/issue/KTOR-916)
=> Fix nullable response breaking change

ktor-client/ktor-client-core/build.gradle.kts, ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/AcceptAllCookiesStorage.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/ConstantCookiesStorage.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/CookiesStorage.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/HttpCookies.kt, ktor-client/ktor-client-core/common/test/CookiesTest.kt, ktor-http/common/src/io/ktor/http/Cookie.kt
Fix [`#KTOR-917`](https://youtrack.jetbrains.com/issue/KTOR-917)
=> Fix ktor client cookie encoding

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettySpecificTest.kt
[`#KTOR-939`](https://youtrack.jetbrains.com/issue/KTOR-939)
=> Fix netty resource leak

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/CIOEngineConfig.kt
=> Update public API for bug #2030(#KTOR-1009)

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/utils/CoroutineUtils.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/utils/CoroutineUtilsJs.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/utils/CoroutineDispatcherUtils.kt, ktor-client/ktor-client-core/posix/src/io/ktor/client/utils/CoroutineUtilsPosix.kt
=> Add runtime check for kotlin-native mt coroutines

gradle.properties, gradle/wrapper/gradle-wrapper.properties
Fixes [#KTOR-1027](https://youtrack.jetbrains.com/issue/KTOR-1027)
=> #KTOR-1027 Update versions

ktor-utils/common/src/io/ktor/util/collections/ConcurrentList.kt, ktor-utils/common/test/io/ktor/util/ConcurrentListTest.kt
Fix increase capacity and add test
=> KTOR-1034 Fix ConcurrentList increaseCapacity

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/ChunkedTest.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
Ignore content length during parsing.
=> KTOR-1036 Ignore content-length if transfer-encoding is chunked

gradle.properties
**Subsystem**
Client/Server
**Motivation**
Use a new version of coroutines. Closes https://youtrack.jetbrains.com/issue/KTOR-1064
=> Bump coroutines version

ktor-client/ktor-client-core/common/test/HttpStatementTest.kt, ktor-client/ktor-client-core/common/test/TestUtils.kt, ktor-http/common/src/io/ktor/http/HttpUrlEncoded.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLUtils.kt, ktor-http/common/test/io/ktor/tests/http/CodecTest.kt
=> Fix HttpStatement.toString

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheHttpRequest.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/CurlClientEngine.kt, ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/ResponseUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/CookiesMockTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/CookiesTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestTcpServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Proxy.kt, ktor-http/common/src/io/ktor/http/Headers.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/CIOHeaders.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/internals/Tokenizer.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt
=> Skip invalid cookies instead of failing

gradle/compatibility.gradle, ktor-features/ktor-auth-jwt/api/ktor-auth-jwt.api, ktor-features/ktor-auth-ldap/api/ktor-auth-ldap.api, ktor-features/ktor-freemarker/api/ktor-freemarker.api, ktor-features/ktor-gson/api/ktor-gson.api, ktor-features/ktor-html-builder/api/ktor-html-builder.api, ktor-features/ktor-jackson/api/ktor-jackson.api, ktor-features/ktor-locations/api/ktor-locations.api, ktor-features/ktor-metrics-micrometer/api/ktor-metrics-micrometer.api, ktor-features/ktor-metrics/api/ktor-metrics.api, ktor-features/ktor-mustache/api/ktor-mustache.api, ktor-features/ktor-pebble/api/ktor-pebble.api, ktor-features/ktor-serialization/api/ktor-serialization.api, ktor-features/ktor-server-sessions/api/ktor-server-sessions.api, ktor-features/ktor-thymeleaf/api/ktor-thymeleaf.api, ktor-features/ktor-velocity/api/ktor-velocity.api, ktor-features/ktor-webjars/api/ktor-webjars.api, ktor-server/ktor-server-cio/api/ktor-server-cio.api, ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-jetty/api/ktor-server-jetty.api, ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-servlet/api/ktor-server-servlet.api, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-tomcat/api/ktor-server-tomcat.api
Fixes [KTOR-1065](https://youtrack.jetbrains.com/issue/KTOR-1065)
=>  Enable binary compatibility validator in all modules

ktor-client/ktor-client-core/common/test/HttpStatementTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/CookiesTest.kt
Fixes [KTOR-1069](https://youtrack.jetbrains.com/issue/KTOR-1069)
=> KTOR-1069 Fix js test data and disable cookie test for js

CHANGELOG.md, gradle.properties
Fixes [KTOR-968](https://youtrack.jetbrains.com/issue/KTOR-968)
=> Release 1.4.1

gradle.properties
Fix [KTOR-1088](https://youtrack.jetbrains.com/issue/KTOR-1088)
=> KTOR-1088 Set heap to 4g

README.md
**Subsystem**
No subsystem
**Motivation**
Slack & Kotlin links 
**Solution**
Shields
=> Add Kotlin & Slack shields

.idea/vcs.xml
**Subsystem**
No subsystem
**Motivation**
Fast issue access from Git log
**Solution**
=> Add YouTrack issue links navigation

CONTRIBUTING.md, githook/prepare-commit-msg
Fixes [KTOR-927](https://youtrack.jetbrains.com/issue/KTOR-927)
=> KTOR-927 Add git hook to check commit message

ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/Logging.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/FullFormTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpStatementTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/utils/Logging.kt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/TomcatWebSocketTest.kt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/WebSocketEngineSuite.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/ServerPipelineTest.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/tests/ConnectionTests.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-server/ktor-server-tomcat/jvm/test/io/ktor/tests/server/tomcat/TomcatEngineTest.kt, ktor-utils/common/src/io/ktor/util/collections/ConcurrentList.kt, ktor-utils/common/src/io/ktor/util/collections/internal/ConcurrentListSlice.kt
[KTOR-1090](https://youtrack.jetbrains.com/issue/KTOR-1090)
=> KTOR-1090 Mute or fix flaky tests

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIORequestTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/FeaturesTest.kt
Fixes [KTOR-446](https://youtrack.jetbrains.com/issue/KTOR-446), #1720
=> Fix CIO hanging due to Endpoint timeout

README.md
Fixed Ktor logo in readme since the site asset is inaccessible
=> fix Ktor logo

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/http/URLBuilderTest.kt
**Subsystem**
Common
**Motivation**
[URLBuilder to append paths to currently encoded path](https://youtrack.jetbrains.com/issue/KTOR-403)
=> Provide method to add part to existing url path

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheResponseConsumer.kt, ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/NoOpControl.kt, ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/ResponseConsumerTest.kt
Fixes [KTOR-717](https://youtrack.jetbrains.com/issue/KTOR-717)
=> KTOR-717 Fix Apache client freeze

ktor-client/ktor-client-core/common/src/io/ktor/client/features/observer/ResponseObserver.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ResponseObserverTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientTestServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Download.kt
Fixes [KTOR-1095](https://youtrack.jetbrains.com/issue/KTOR-1095)
=> KTOR-1095 Fix freeze in ResponseObserver

CONTRIBUTING.md
Add information about different types of contributions we accept, along with steps and guidelines.
=> KTOR-1024 Update guides to highlight all types of contributions.

ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
Fixes KTOR-604
Fixes #1204 
Rebased #1253
=> KTOR-604 Add file and mailto protocols support

build.gradle, settings.gradle
Fixes [KTOR-1169](https://youtrack.jetbrains.com/issue/KTOR-1169)
It should help according to this guide: https://docs.gradle.org/current/userguide/declaring_repositories.html
=> KTOR-1169 Set lowest priority to jcenter

gradle.properties
Fixes [KTOR-1171](https://youtrack.jetbrains.com/issue/KTOR-1171)
=> KTOR-1171 Update serialization to 1.0.0

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/FormDataContent.kt, ktor-client/ktor-client-core/common/test/MultiPartFormDataContentTest.kt
Fixes [KTOR-879](https://youtrack.jetbrains.com/issue/KTOR-879)
=> KTOR-879 Fix multipart form data client header

gradle/publish.gradle
Fixes [KTOR-974](https://youtrack.jetbrains.com/issue/KTOR-974)
=> KTOR-974 Migrate publication to mavenCentral

ktor-server/ktor-server-core/jvm/src/io/ktor/features/HttpsRedirect.kt
=> KTOR-1215 Add explicit visibility modifier

gradle/publish.gradle
=> KTOR-974 Fix mavenCentral publication parameters

build.gradle, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, buildSrc/src/main/kotlin/CacheRedirector.kt, gradle.properties, settings.gradle
=> KTOR-1227 Enable build cache and cache redirector

gradle.properties, ktor-client/ktor-client-features/ktor-client-json/ktor-client-serialization/common/src/io/ktor/client/features/json/serializer/KotlinxSerializer.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-serialization/js/src/SerializerInitializer.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-serialization/posix/src/SerializerInitializer.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/JsonSupport.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/SerializerLookup.kt
**Subsystem**
ktor-serialization (Server), ktor-client-serialization
**Motivation**
[KTOR-1214](https://youtrack.jetbrains.com/issue/KTOR-1214) Update kotlinx.serialization to 1.0.1
**Solution**
Update versions and cleanup relevant annotations and IDE warnings
=> KTOR-1214 Update kotlinx.serialization to 1.0.1

buildScripts/cleanupKeysWindows.ps1, buildScripts/prepareKeysWindows.ps1
Add comments to PowerShell files referencing TeamCity issue. Add alias for gpg2
=> KTOR-1241 Build Scripts for Windows 

buildScripts/prepareKeysWindows.ps1
=> KTOR-1241 Add extension to alias for GPG

ktor-client/ktor-client-cio/api/ktor-client-cio.api, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/CIOEngineConfig.kt
Fixes [KTOR-1240](https://youtrack.jetbrains.com/issue/KTOR-1240)
=> KTOR-1240 Fix socket timeout

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt
Remove flaky test for Windows.
=> KTOR-1252 Remove flaky test

ktor-client/ktor-client-mock/api/ktor-client-mock.api, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/MockedTests.kt
Fixes [KTOR-341](https://youtrack.jetbrains.com/issue/KTOR-341)
Fixes #1945
=> KTOR-341 Add tests to check correct url escaping

ktor-client/ktor-client-tests/posix/src/io/ktor/client/tests/utils/ClientLoaderNative.kt
=> KTOR-1252 Fix native test ignore

ktor-server/ktor-server-test-host/build.gradle
Fixes [KTOR-890](https://youtrack.jetbrains.com/issue/KTOR-890)
=> KTOR-890 Remove ktor-server-test-host indirectly dependency

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestBase.kt
Remove the outdated class check
=> KTOR-1266 Fix missing ALPN class for http2 tests

ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyUtilityTest.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
=> KTOR-1116 Fix chunked transfer encoding handling

build.gradle, gradle/compatibility.gradle, gradle/jvm.gradle, gradle/posix.gradle, ktor-client/ktor-client-tests/build.gradle.kts, ktor-io/common/src/io/ktor/utils/io/core/AbstractInput.kt, ktor-io/common/src/io/ktor/utils/io/core/internal/UTF8.kt, ktor-utils/build.gradle.kts, ktor-utils/jvm/src/io/ktor/util/internal/LockFreeLinkedList.kt, settings.gradle
To be used in specific kotlinx-train CI configuration. It's needed for faster adoption of JVM IR compiler.
=> Add build parameter to build ktor with JVM IR compiler

ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt, ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/HttpUrlEncoded.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/http/UrlEncodedTest.kt
Fixes [KTOR-1236](https://youtrack.jetbrains.com/issue/KTOR-1236)
=> KTOR-1236 Remove unnecessary escaping in the query parameter value

ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedState.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractInput.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractInputSharedState.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractOutput.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractOutputSharedState.kt, ktor-io/common/src/io/ktor/utils/io/core/Buffer.kt, ktor-io/common/src/io/ktor/utils/io/core/BufferSharedState.kt, ktor-io/js/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedStateJs.kt, ktor-io/js/src/io/ktor/utils/io/core/AbstractInputSharedStateJs.kt, ktor-io/js/src/io/ktor/utils/io/core/AbstractOutputSharedStateJs.kt, ktor-io/js/src/io/ktor/utils/io/core/BufferSharedStateJs.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedStateJvm.kt, ktor-io/jvm/src/io/ktor/utils/io/core/AbstractInputSharedStateJvm.kt, ktor-io/jvm/src/io/ktor/utils/io/core/AbstractOutputSharedStateJvm.kt, ktor-io/jvm/src/io/ktor/utils/io/core/BufferSharedStateJvm.kt, ktor-io/posix/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedStateNative.kt, ktor-io/posix/src/io/ktor/utils/io/core/AbstractInputSharedStateNative.kt, ktor-io/posix/src/io/ktor/utils/io/core/AbstractOutputSharedState.kt, ktor-io/posix/src/io/ktor/utils/io/core/BufferSharedStateNative.kt
Remove shared in perf critical io
Fixes [KTOR-1290](https://youtrack.jetbrains.com/issue/KTOR-1290)
=> KTOR-1290 Specialize shared usage to native platform in perf

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkUtils.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/HttpClientTest.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt, ktor-io/common/src/io/ktor/utils/io/internal/SequentialCopyTo.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
**Subsystem**
Client, engines
**Motivation**
[Handle failure in reading request body](https://youtrack.jetbrains.com/issue/KTOR-1367)
=> KTOR-1367 Handle failure in reading request body

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIO.kt, ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationResponse.kt, ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/HttpServer.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOHttpClientTest.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/RAWExample.kt
=> KTOR-1371 Fix formatting in ktor-server-cio to conform to ktlint

ktor-client/ktor-client-core/common/src/io/ktor/network/sockets/TimeoutExceptionsCommon.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Serializer.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelCtor.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannel.kt, ktor-io/common/src/io/ktor/utils/io/bits/Memory.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/RingBufferCapacity.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/features/MultipleRangeWriter.kt, ktor-utils/jvm/src/io/ktor/util/Deflater.kt, ktor-utils/jvm/test/io/ktor/tests/utils/DeflaterReadChannelTest.kt
Fixes [KTOR-1268](https://youtrack.jetbrains.com/issue/KTOR-1268)
=> KTOR-1268 Fix `readRemaining` lost bytes

ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt
=> KTOR-1381 Remove copyTo usage from ServerPipeline.kt

gradle/publish.gradle
=> Do not add JAR without classifier

gradle/jdk.gradle, gradle/jvm.gradle, gradle/versions.gradle, ktor-client/build.gradle.kts, ktor-client/ktor-client-features/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-auth-basic/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-auth/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-encoding/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-json/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-logging/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-websockets/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-websockets/common/test/io/ktor/client/tests/features/WebSocketRemoteTest.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpRequestBodyPublisher.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt, settings.gradle
**Subsystem**
ktor-client-java, ktor-client-*
**Known issues**
- Test `JavaClientTest.testErrorInWritingPropagates` is failing
- Test `RoutingResolveTest.testMalformedPath` is failing (cc @rsinukov)
- settings.gradle contains copyrights in the middle of the file (added by IDEA automatically) - will be fixed
- still there is a duplication: ktor-features and ktor-client-tests contains the list of clients in buildscripts, but it's better anyway than before where we had the list in every feature module
=> Fix building master

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt
Change was lost in rebase, bringing it back
=> KTOR-1413 Fix failing testMalformedPath test

ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-server/ktor-server-servlet/api/ktor-server-servlet.api
=> KTOR-1499 add lost api dumps

ktor-features/ktor-auth-jwt/jvm/test/io/ktor/auth/jwt/JWTAuthTest.kt, ktor-features/ktor-auth/jvm/src/io/ktor/auth/Headers.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/BasicAuthTest.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/DigestTest.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt, ktor-http/common/src/io/ktor/http/parsing/ParseException.kt
**Subsystem**
Server
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-1406
=> KTOR-1406 Throw ParseException on invalid header and handle it as 400

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/websocket/CloseReason.kt
**Solution**
Plus one case of [KT-43901](https://youtrack.jetbrains.com/issue/KT-43901)
=> KT-43901 Use WA for Enum.values in companion object in CloseReason.kt

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/HttpClientTest.kt
=> KTOR-1392 Fix more flaky tests

README.md
=> KTOR-1173 Update description and add reference to JetBrains.

ktor-client/ktor-client-okhttp/api/ktor-client-okhttp.api, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpConfig.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpWebsocketSessionTest.kt
Fixes [KTOR-951](https://youtrack.jetbrains.com/issue/KTOR-951)
=> KTOR-951 Add `webSocketFactory` In OkHttp engine config

ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CallLoggingTest.kt
[KTOR-1582 CallLoggingTest is flaky](https://youtrack.jetbrains.com/issue/KTOR-1582)
=> KTOR-1582 Improve flaky test and provide more debug info

ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/FrameParser.kt
Relates to [KTOR-1392](https://youtrack.jetbrains.com/issue/KTOR-1392)
=> KTOR-1392 Fix flaky test due to early cancel

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultTransform.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
ktor-http, ktor-server-cio
**Motivation**
[KTOR-1590 Server losing channel exceptions at receive](https://youtrack.jetbrains.com/issue/KTOR-1590)
**Solution**
- Fix losing exception
- Fix exception handling: we should wrap channel errors to ChannelIOException for proper logging
- Prevent call handling in this case
- Fix test to not allow receiving any value in this case
=> Fix server receive exception handling

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt
**Subsystem**
ktor-http
**Motivation**
#1882 
**Solution**
Create a conditional to check if the status-code is a valid response (between 100 and 599)
=> KTOR-370 Fix status code response accepting any numeric value (#1882)

README.md
**Subsystem**
README
**Motivation**
Bintray version is outdated
**Solution**
Use maven central version
=> Update version badge (use maven central version)

.idea/codeStyles/Project.xml
Since IDEA 2020.3 we have project.xml file changed. I propose to commit this change if we all have this.
=> Update IDEA's project.xml

ktor-client/ktor-client-core/build.gradle.kts, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngineBase.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/utils/CoroutineDispatcherUtils.kt, ktor-client/ktor-client-core/jvm/test/HttpClientEngineTest.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt
Fix [KTOR-1661](https://youtrack.jetbrains.com/issue/KTOR-1661)
=> KTOR-1661 Fix early dispatcher close

ktor-client/ktor-client-features/ktor-client-websockets/common/test/io/ktor/client/tests/features/WebSocketRemoteTest.kt
=> KTOR-1392 Remove echo.websocket.org due to timeouts and 404

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/utils/Logging.kt
Added test to verify fixed behaviour
Fixes [KTOR-426](https://youtrack.jetbrains.com/issue/KTOR-426)
=> KTOR-426 Add test to check body logging in post request with json

ktor-client/ktor-client-core/js/src/io/ktor/client/features/websocket/JsWebSocketSession.kt
Adding a test by the fix for OkHttp introduced some kind instability inside of JS testing infrastructure. We should stop sending reserved close codes to the JS engine as well
=> KTOR-1374 Avoid using reserved status codes in JS engine

ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/SerializationConverter.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/SerializerLookup.kt, ktor-features/ktor-serialization/jvm/test/io/ktor/tests/serialization/SerializationTest.kt
**Subsystem**
Server, serialization
**Motivation**
[KTOR-1795](https://youtrack.jetbrains.com/issue/KTOR-1795)
**Solution**
Move the `try/catch` block to the one level above.
=> KTOR-1795 Fix serialization failure due to types mismatch

ktor-features/ktor-metrics/jvm/src/io/ktor/metrics/dropwizard/DropwizardMetrics.kt, ktor-features/ktor-metrics/jvm/test/io/ktor/metrics/dropwizard/DropwizardMetricsTests.kt
**Subsystem**
Server, metrics 
**Motivation**
[Adding existing DropWizard metrics registry to Ktor crashes the app](https://youtrack.jetbrains.com/issue/KTOR-1798)
=> KTOR-1798 Check that DropwizardMetrics registry doesn't have metric before adding it

ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/test/io/ktor/tests/http/HeadersTest.kt
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-1797
=> KTOR-1797 Add check for unescaped quote inside quoted header parameter

ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/JsonSupport.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Pipeline.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSession.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSessionImpl.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Frame.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/PingPong.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/RawWebSocket.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Serializer.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/UtilsJvm.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketReader.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketWriter.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerRequestScope.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/features/HttpsRedirect.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionSerializerReflection.kt
**Subsystem**
ktor-server-core, ktor-http-cio
-81 errors
=> KTOR-1371 Cleanup codestyle in ktor-server

gradle/publish.gradle
=> KTOR-1660 Publishing EAP to Space

ktor-test-dispatcher/macosX64/src/TestMacosX64.kt
https://youtrack.jetbrains.com/issue/KTOR-1989
=> Fix code style errors in ktor-test-dispatcher

ktor-server/ktor-server-core/build.gradle, ktor-server/ktor-server-core/jvm/src/io/ktor/features/DefaultHeaders.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/features/DefaultHeadersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-1976
=> Default Headers feature adds duplicated Server header

README.md
replaced links to old docs with new ones, fixed 404 for the plugin
=> fix links to docs

ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/ExceptionsJvmTest.kt, ktor-test-dispatcher/iosArm32/src/TestIosArm32.kt, ktor-test-dispatcher/iosArm64/src/TestIosArm64.kt, ktor-test-dispatcher/iosX64/src/TestIosX64.kt, ktor-test-dispatcher/tvosArm64/src/TestTvosArm64.kt, ktor-test-dispatcher/tvosX64/src/TestTvosX64.kt, ktor-test-dispatcher/watchosArm32/src/TestWatchosArm32.kt, ktor-test-dispatcher/watchosArm64/src/TestWatchosArm64.kt, ktor-test-dispatcher/watchosX86/src/TestWatchosX86.kt
https://youtrack.jetbrains.com/issue/KTOR-2028
=> Fix rest code style errors

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClientConfig.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultResponseValidation.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpCallValidator.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CallValidatorTest.kt
**Subsystem**
Client
**Motivation**
[Custom response validation is not running when the default is disabled](https://youtrack.jetbrains.com/issue/KTOR-2007)
=> KTOR-2007 Fix running custom response validation without default one

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIORequestTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2000
=> Changing `requestTimeoutMillis` in config of HttpTimeout feature doesn't change the CIO's timeout

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCall.kt
**Subsystem**
**Motivation**
[KTOR-1801 server/netty: IllegalReferenceCountException](https://youtrack.jetbrains.com/issue/KTOR-1801)
Sometimes, the Netty engines does call termination twice (from different contexts). The underlying implementation does unsafe things so double disposal is not allowed. The double release is a very unlikely case this is why we don't face it in tests.
**Solution**
Use atomic flag to ensure we only release it once.
**Problem**
This is very time-sensitive issue and there is no way to write a stable test for this.
=> KTOR-1801 Fix Netty IllegalReferenceCountException

build.gradle, gradle.properties, gradle/jvm.gradle, gradle/posix.gradle, gradle/wrapper/gradle-wrapper.properties
=> KTOR-1639 Update kotlin to 1.4.30

gradle.properties, ktor-network/build.gradle.kts, ktor-network/jvm/test/io/ktor/network/sockets/tests/ClientSocketTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2060
=> Fix flaky ClientSocketTest.testSelfConnect[jvm]

CONTRIBUTING.md
=> add info about docs contributing

build.gradle
Fixes [KTOR-2206](https://youtrack.jetbrains.com/issue/KTOR-2206)
=> KTOR-2206 Fix dokkaWebsite build

CHANGELOG.md, gradle.properties
=> Changelog 1.5.2 and version bump

ktor-server/ktor-server-netty/build.gradle, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyConfigurationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2078
=> NettyApplicationEngine: providing a configureBootstrap in the configuration throws IllegalStateException: group set already

ktor-features/ktor-server-sessions/build.gradle, ktor-features/ktor-server-sessions/jvm/src/io/ktor/sessions/CacheStorage.kt, ktor-features/ktor-server-sessions/jvm/test/io/ktor/tests/sessions/CacheTest.kt
https://youtrack.jetbrains.com/issue/KTOR-1452
=> Unexpected exception when using Session feature: "Using blocking primitives on this dispatcher is not allowed"

ktor-server/ktor-server-core/build.gradle, ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/features/CORSTest.kt
https://youtrack.jetbrains.com/issue/KTOR-469
=> CORS origin validation

gradle.properties
[KTOR-2238 Upgrade kotlinx.serialization to 1.1.0](https://youtrack.jetbrains.com/issue/KTOR-2238)
Changelog:
https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.1.0-RC
https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.1.0
=> Upgrade kotlinx.serialization to 1.1.0

ktor-client/ktor-client-java/jvm/test/io/ktor/client/engine/java/JavaEngineTests.kt
**Subsystem**
ktor-client-java
**Motivation**
[KTOR-2098 Fix flaky JavaEngineTests.testThreadLeak[jvm] ](https://youtrack.jetbrains.com/issue/KTOR-2098)
**Solution**
Filter threads more precisely by filtering them by name.
=> Fix testThreadLeak

ktor-client/ktor-client-android/jvm/test/io/ktor/client/engine/android/UrlConnectionUtilsTest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpTimeout.kt, ktor-network/jvm/src/io/ktor/network/sockets/NIOSocketImpl.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/Sessions.kt
=> KTOR-2284 Fix grammar mistakes in exception messages

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt
https://youtrack.jetbrains.com/issue/KTOR-2173
=> KTOR-2173 Update docs for FormPart

gradle.properties
=> KTOR-2336 Update Kotlin to 1.4.31

ktor-features/ktor-velocity/api/ktor-velocity.api, ktor-features/ktor-velocity/build.gradle, ktor-features/ktor-velocity/jvm/src/io/ktor/velocity/Velocity.kt, ktor-features/ktor-velocity/jvm/src/io/ktor/velocity/VelocityTools.kt, ktor-features/ktor-velocity/jvm/test/io/ktor/tests/velocity/VelocityTest.kt, ktor-features/ktor-velocity/jvm/test/io/ktor/tests/velocity/VelocityToolsTest.kt, ktor-features/ktor-velocity/jvm/test/resources/test-template.vhtml
**Subsystem**
Server ktor-features/ktor-velocity
**Motivation**
Velocity templating is not very useful without being able to use the standard Velocity Tools.
**Solution**
This PR adds a VelocityTool feature. It is used as follow:
```kotlin
install(VelocityTools) {
engine {
// whatever engine configuration you need
setProperty("resource.loader", "string")
addProperty("resource.loader.string.name", "myRepo")
addProperty("resource.loader.string.class", StringResourceLoader::class.java.name)
addProperty("resource.loader.string.repository.name", "myRepo")
}
addDefaultTools() // add a default tool
tool("foo", MyCustomTool::class.java) // add a custom tool
}
```
The PR also fixes a few things:
- fix feature key name
- [tests] remove the need for a premature initialization of the engine (to avoid …
=> KTOR-2345 Review ktor velocity feature

ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestTcpServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/CloseableGroup.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/OverridingClassLoader.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/internal/CallableUtils.kt
Fix [KTOR-2214](https://youtrack.jetbrains.com/issue/KTOR-2214)
=> Fix autoreload with embedded server

ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-core/common/test/HttpRequestBuilderTest.kt
**Subsystem**
Client
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-2389
=> KTOR-2389 Keep attributes when creating HttpRequestBuilder from HttpRequest or RequestData

ktor-http/common/test/io/ktor/tests/http/CodecTest.kt
**Subsystem**
Codecs
**Motivation**
Additional test to clarify behavior of encodeURLPath in case one might refactor later (related to my next PR)
**Solution**
Added a few test methods.
=> Added additional tests of CodecTest.encodeURLPath()

CHANGELOG.md
YT ticket had wrong release version set
=> Remove change that had wrong release set

gradle.properties, ktor-io/common/src/io/ktor/utils/io/core/BytePacketBuilder.kt, ktor-io/posix/test/io/ktor/utils/io/SharedSetNative.kt
=> KTOR-2458 Update netty to 4.1.63.Final

ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-network/api/ktor-network.api, ktor-network/common/src/io/ktor/network/sockets/SocketOptions.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-utils/api/ktor-utils.api, ktor-utils/common/src/io/ktor/util/Attributes.kt
=> KTOR-2524 expose new public API

ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedState.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannel.kt, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/common/src/io/ktor/utils/io/ChannelLittleEndian.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractInput.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractOutput.kt, ktor-io/common/src/io/ktor/utils/io/core/Input.kt, ktor-io/common/src/io/ktor/utils/io/core/Output.kt, ktor-io/js/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedStateJs.kt, ktor-io/js/src/io/ktor/utils/io/ByteReadChannelJs.kt, ktor-io/js/src/io/ktor/utils/io/ByteWriteChannelJs.kt, ktor-io/js/src/io/ktor/utils/io/core/InputJs.kt, ktor-io/js/src/io/ktor/utils/io/core/OutputJs.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedStateJvm.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/core/InputJvm.kt, ktor-io/jvm/src/io/ktor/utils/io/core/OutputJvm.kt, ktor-io/posix/src/io/ktor/utils/io/ByteChannelSequentialBaseSharedStateNative.kt, ktor-io/posix/src/io/ktor/utils/io/ByteReadChannelNative.kt, ktor-io/posix/src/io/ktor/utils/io/ByteWriteChannelNative.kt, ktor-io/posix/src/io/ktor/utils/io/core/InputNative.kt, ktor-io/posix/src/io/ktor/utils/io/core/OutputNative.kt
=> KTOR-1094 Drop byte order

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosUtils.kt
**Subsystem**
Client iOS
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-2566
**Solution**
Subclass from IOException
=> KTOR-2566 Subclass IosHttpRequestException from IOException

ktor-features/ktor-html-builder/jvm/src/io/ktor/html/RespondHtml.kt, ktor-features/ktor-html-builder/jvm/test/io/ktor/tests/html/HtmlContentTest.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
Fix [KTOR-756](https://youtrack.jetbrains.com/issue/KTOR-756)
=> KTOR-756 Fix exception swallow in html builder

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/Route.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/routing/RouteTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2427
=> KTOR-2427 fix trailing slash toString

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt
https://youtrack.jetbrains.com/issue/KTOR-2590
=> KTOR-2590 Add non inline method to receive response body

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheResponseConsumer.kt, ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/content/ObservableContent.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/BodyProgress.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/ObservableBody.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ObservableBodyTest.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannel.kt, ktor-io/common/src/io/ktor/utils/io/core/internal/UTF8.kt, ktor-io/js/src/io/ktor/utils/io/ByteReadChannelJs.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/posix/src/io/ktor/utils/io/ByteChannelNative.kt, ktor-io/posix/src/io/ktor/utils/io/ByteReadChannelNative.kt
**Subsystem**
Client
**Motivation**
[Client upload/download progress observer/handler/interceptor](https://youtrack.jetbrains.com/issue/KTOR-400)
The upload part is here, download will follow in the next PR
API:
```kotlin
val response: HttpResponse = client.post("$TEST_SERVER/content/echo") {
body = observableBodyOf(content) { bytesSendTotal: Long, contentLength: Long -> ... }
}
```
=> KTOR-400 Upload progress observer

ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt
**Subsystem**
ktor-io / iconv integration
**Motivation**
[KTOR-2681 Avoid using Kotlin_Arrays_getShortArrayAddressOfElement](https://youtrack.jetbrains.com/issue/KTOR-2681)
**Solution**
Use stdlib's `addressOf` instead our implementation. Originally there was no such function in stdlib so we had to implement it.
=> KTOR-2681 Migrate to stdlib CharArray.addressOf

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironment.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettySpecificTest.kt
Fix [KTOR-803](https://youtrack.jetbrains.com/issue/KTOR-803)
Fix #336
=> KTOR-803 Fix Netty bind freeze

gradle.properties, ktor-features/ktor-websockets/api/ktor-websockets.api, ktor-http/ktor-http-cio/api/ktor-http-cio.api, ktor-network/jvm/src/io/ktor/network/sockets/DatagramSendChannel.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-utils/api/ktor-utils.api, ktor-utils/jvm/test/io/ktor/tests/utils/PipelineTest.kt
Fix [KTOR-2600](https://youtrack.jetbrains.com/issue/KTOR-2600)
=> KTOR-2600 Update Kotlin and libraries to 1.5.0

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpConfig.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkUtils.kt
Fix [KTOR-449](https://github.com/ktorio/ktor/issues/1708)
Fix #1708
=> KTOR-449 Workaround OkHttp connection problem

ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractInput.kt, ktor-io/common/src/io/ktor/utils/io/core/AbstractOutput.kt, ktor-io/jvm/src/io/ktor/utils/io/core/IoBufferJVM.kt
Fixes [KTOR-1094](http://youtrack.jetbrains.com/issue/KTOR-1094)
=> KTOR-1094 Add missing deprecations for 2.0.0

ktor-features/ktor-locations/jvm/src/io/ktor/locations/BackwardCompatibleImpl.kt, ktor-features/ktor-locations/jvm/test/io/ktor/tests/locations/LocationsTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
Fix [KTOR-2723](https://youtrack.jetbrains.com/issue/KTOR-2723)
=> KTOR-2723 Fix exception during Location instance creation

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpRequest.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HeadersTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/UploadTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Headers.kt
Fix [KTOR-556](https://youtrack.jetbrains.com/issue/KTOR-556)
=> KTOR-556 Add Content-Length header for NoContent

ktor-client/ktor-client-core/common/src/io/ktor/client/content/ObservableContent.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/BodyProgressTest.kt
* Fix `InvalidMutabilityException` on observing `WriteChannelContent`
* FIx hanging of observer
* Add more tests
=> KTOR-400 Fix hanging upload observer

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
Fix [KTOR-379](https://youtrack.jetbrains.com/issue/KTOR-379)
=> KTOR-379 Add Host header verification

gradle/versions.gradle
=> Fix build scripts

ktor-server/ktor-server-core/jvm/src/io/ktor/features/CallLogging.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CallLoggingTest.kt
Fix [KTOR-806](https://youtrack.jetbrains.com/issue/KTOR-806)
=> KTOR-806 Change default log-level to INFO

README.md
**Subsystem**
Docs
**Motivation**
People need to know what kotlin version should be used
**Solution**
Update the README.md
=> docs: indicate the kotlin stdlib version properly

ktor-utils/jvm/src/io/ktor/util/PlatformUtils.kt
Fix [KTOR-2727](https://youtrack.jetbrains.com/issue/KTOR-2727)
=> KTOR-2727 Disable development mode on -ea flag

ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOEngineTest.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/internal/CallableUtils.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/JettyEngineTest.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/CompressionTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ConfigTestSuite.kt, ktor-server/ktor-server-tomcat/jvm/test/io/ktor/tests/server/tomcat/TomcatEngineTest.kt
Fix [KTOR-2586](https://youtrack.jetbrains.com/issue/KTOR-2586)
=> KTOR-2586 Fix module start twice; Fix starting exception

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt
Fix [KTOR-2513](https://youtrack.jetbrains.com/issue/KTOR-2513)
=> KTOR-2513 Fix name resolution retry regression

ktor-features/ktor-metrics-micrometer/api/ktor-metrics-micrometer.api, ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt, ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt
Fix [KTOR-1781](https://youtrack.jetbrains.com/issue/KTOR-1792)
=> KTOR-1781 Set default registry for MicrometerMetrics feature

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultEnginePipeline.kt
Fix [KTOR-2691](https://youtrack.jetbrains.com/issue/KTOR-2691)
=> KTOR-2691 Fix ConnectException message, change level to debug

gradle/darwin.gradle, gradle/posix.gradle, gradle/publish.gradle, ktor-test-dispatcher/watchosX64/src/TestWatchosX64.kt
Fix https://youtrack.jetbrains.com/issue/KTOR-2678
Tested using `./gradlew watchosX64Test` and the build was successful.
=> KTOR-2678 Add support for watchosX64 target

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt
**Subsystem**
Server - core
**Motivation**
I saw a issue #2006 and that sounds good for me too.
There is an open pull requests from Mar/2021 #2407 by @jgabrielfreitas, but the issue has not been resolved since. I think this task is perfect as a first contribution to open source.
**Solution**
The solution has 2 types of logs:
- For the first loading calculating time between start of `init` and receiving the `ApplicationStarted` event.
- For the auto-reload calculating time between receiving `ApplicationStarting` and `ApplicationStarted` events.
=> KTOR-2816 Adding application startup and hot-reloading time log

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOEngineTest.kt, ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngine.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironment.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/JettyEngineTest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyConfigurationTest.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ConnectionTestSuite.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt, ktor-server/ktor-server-tomcat/jvm/test/io/ktor/tests/server/tomcat/TomcatEngineTest.kt
Fixes https://youtrack.jetbrains.com/issue/KTOR-686
=> KTOR-686 Add local network address function to engine

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
=> KTOR-1629 Fix failing and not compiling tests

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-333
=> KTOR-333 Fix CIO hanging when `call.respond()` was not called

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CharsetTest.kt, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-io/common/test/io/ktor/utils/io/CharsetsTest.kt, ktor-io/js/src/io/ktor/utils/io/charsets/CharsetJS.kt
Fix https://youtrack.jetbrains.com/issue/KTOR-2645
=> KTOR-2645 Fix charset exception in client

ktor-http/common/src/io/ktor/http/HttpHeaders.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/features/OriginConnectionPoint.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/OriginConnectionPointTest.kt
Added without public API changes. A proper config will be available in the next minor release.
=> KTOR-2788 Add support for X-Forwarded-Port

ktor-utils/build.gradle.kts, ktor-utils/js/src/io/ktor/util/CryptoJs.kt, ktor-utils/js/test/io.ktor.util/CryptoTest.kt
https://youtrack.jetbrains.com/issue/KTOR-409
=> crypto is undefined in IE11

ktor-server/ktor-server-core/jvm/src/io/ktor/features/DoubleReceive.kt
https://youtrack.jetbrains.com/issue/KTOR-2631
=> Refactor DoubleReceive feature

README.md, gradle.properties, ktor-features/ktor-jackson/jvm/test/io/ktor/tests/jackson/JacksonTest.kt, ktor-server/ktor-server-tomcat/build.gradle.kts
Fix [KTOR-2875](https://youtrack.jetbrains.com/issue/KTOR-2875)
=> KTOR-2875 Update versions

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/RequestProducerTest.kt
https://youtrack.jetbrains.com/issue/KTOR-1405
=> NPE in ApacheRequestProducer when "http://" is requested

settings.gradle
Fix [KTOR-2884](https://youtrack.jetbrains.com/issue/KTOR-2884)
=> KTOR-2884 Enable GE cache for builds

ktor-server/ktor-server-host-common/build.gradle.kts, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt, ktor-server/ktor-server-host-common/jvm/test/io/ktor/tests/hosts/ApplicationEngineEnvironmentReloadingTests.kt
https://youtrack.jetbrains.com/issue/KTOR-1854
=> "ApplicationEngineEnvironment was not started" when accessing application before server is started

ktor-server/ktor-server-core/jvm/src/io/ktor/features/OriginConnectionPoint.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/OriginConnectionPointTest.kt
[KTOR-2918](https://youtrack.jetbrains.com/issue/KTOR-2918)
=> KTOR-2918 Support list of ports in X-Forwarded-Port

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/internal/CallableUtils.kt
Fix [KTOR-2924](https://youtrack.jetbrains.com/issue/KTOR-2924)
=> KTOR-2924 Fix server API level for Android

ktor-io/common/src/io/ktor/utils/io/pool/Pool.kt, ktor-io/posix/test/io/ktor/utils/io/SingleInstancePoolTest.kt
Fix [KTOR-2883](https://youtrack.jetbrains.com/issue/KTOR-2883)
=> KTOR-2883 Fix SingleInstancePool freeze

.idea/codeStyles/Project.xml, gradle.properties, gradle/wrapper/gradle-wrapper.properties, ktor-client/ktor-client-core/common/src/io/ktor/client/features/websocket/WebSockets.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/WebSocketMockTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/WebSocketTest.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/WebSocketJvmTest.kt
Fix [KTOR-2388](https://youtrack.jetbrains.com/issue/KTOR-2388)
=> KTOR-2388 Fix empty WebSocket extension header

ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/cache/HttpCacheEntry.kt, ktor-client/ktor-client-tests/posix/test/io/ktor/client/tests/InvalidMutabilityExceptionTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2033
=> InvalidMutabilityException when using withContext and SavedHttpCall

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/request/utils.kt
authorization
**Subsystem**
Client RequestBuilder Common
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-2876
**Solution**
Added shortcuts
=> KTOR-2876 Add shortcut functions for basic and bearer A

THIRDPARTY.md
KTOR-2605 Add list of third-party libraries used
=> KTOR-2605 Add THIRDPARTY.md

ktor-server/ktor-server-servlet/build.gradle.kts, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletApplicationEngine.kt, ktor-server/ktor-server-servlet/jvm/test-resources/test.conf, ktor-server/ktor-server-servlet/jvm/test/io/ktor/tests/servlet/HoconTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3020
=> HOCON config not resolved in ServletApplicationEngine

ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
Adding tests for already fixed behaviour
=> KTOR-699 Add tests for resolving relative urls

ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/RequestProducerTest.kt, ktor-client/ktor-client-cio/api/ktor-client-cio.api, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/plugins/websocket/buildersCio.kt, ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/builders.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/Headers.kt, ktor-http/common/src/io/ktor/http/Parameters.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/Url.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt, ktor-http/js/src/io/ktor/http/URLBuilderJs.kt, ktor-http/jvm/src/io/ktor/http/URLBuilderJvm.kt, ktor-http/posix/src/io/ktor/http/URLBuilderPosix.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2Handler.kt, ktor-utils/api/ktor-utils.api, ktor-utils/common/src/io/ktor/util/StringValues.kt, ktor-utils/common/test/io/ktor/util/StringValuesBuilderTest.kt
* Change defaults in UrlBuilder and helper functions
* Fix location.origin usage in browser
* Allow building url and parameters multiple times
=> KTOR-1345 KTOR-453 Fix multiple issues with UrlBuilder 

ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTrackerById.kt
**Subsystem**
Server/Sessions
**Motivation**
Found this apparent bug when looking at the code. There was already an issue opened [here](https://youtrack.jetbrains.com/issue/KTOR-2584).
**Solution**
Actually remove the invalid session as described in the comment above.
=> KTOR-2584 Remove invalid session id

buildSrc/src/main/kotlin/JsConfiguration.kt
Fix [KTOR-2981](https://youtrack.jetbrains.com/issue/KTOR-2981)
=> KTOR-2981 Drop npm publication

README.md, build.gradle.kts, gradle.properties, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/WebSocketTest.kt, ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/DefaultWebSocketTest.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/ServerPipelineTest.kt, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/common/src/io/ktor/utils/io/core/Experimental.kt, ktor-io/js/src/io/ktor/utils/io/ByteWriteChannelJs.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/posix/src/io/ktor/utils/io/ByteWriteChannelNative.kt, ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt
Fix [KTOR-3101](https://youtrack.jetbrains.com/issue/KTOR-3103)
=>  KTOR-3103 Update Kotlin and Coroutines versions

ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/src/io/ktor/http/Mimes.kt, ktor-http/common/test/io/ktor/tests/http/ContentTypeTest.kt
Fix [KTOR-3080](https://youtrack.jetbrains.com/issue/KTOR-3080)
=> KTOR-3080 Fix ContentType parser to disallow spaces inside

ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/bits/MemoryFactory.kt, ktor-io/common/src/io/ktor/utils/io/core/BufferFactory.kt, ktor-network/build.gradle.kts, ktor-network/common/test/io/ktor/network/sockets/tests/TcpSocketTest.kt, ktor-network/common/test/io/ktor/network/sockets/tests/UDPSocketTest.kt, ktor-network/js/test/io/ktor/network/sockets/tests/UDPSocketTestJs.kt, ktor-network/jvm/test/io/ktor/network/sockets/tests/UDPSocketTestJvm.kt, ktor-network/posix/interop/network.def, ktor-network/posix/src/io/ktor/network/selector/SelectUtils.kt, ktor-network/posix/src/io/ktor/network/selector/WorkerSelectorManager.kt, ktor-network/posix/src/io/ktor/network/sockets/CIOReader.kt, ktor-network/posix/src/io/ktor/network/sockets/CIOWriter.kt, ktor-network/posix/src/io/ktor/network/sockets/ConnectUtilsNative.kt, ktor-network/posix/src/io/ktor/network/sockets/DatagramSendChannel.kt, ktor-network/posix/src/io/ktor/network/sockets/DatagramSocketImpl.kt, ktor-network/posix/src/io/ktor/network/sockets/NativeSocketOptions.kt, ktor-network/posix/src/io/ktor/network/sockets/TCPServerSocketNative.kt, ktor-network/posix/src/io/ktor/network/sockets/TCPSocketBuilderNative.kt, ktor-network/posix/src/io/ktor/network/sockets/TCPSocketNative.kt, ktor-network/posix/src/io/ktor/network/sockets/UDPSocketBuilderNative.kt, ktor-network/posix/src/io/ktor/network/util/Pools.kt, ktor-network/posix/src/io/ktor/network/util/SocketAddress.kt, ktor-network/posix/src/io/ktor/network/util/SocketUtils.kt, ktor-network/posix/test/io/ktor/network/sockets/tests/UDPSocketTestPosix.kt
**Subsystem**
Client/server, ktor-network
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-1159
**Solution**
Add implementation for UDP sockets on native.
=> KTOR-1159 Add support for UDP sockets on native

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpCallValidator.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRedirect.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpSend.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/Auth.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt
API examples 
```
install(HttpRequestRetry) {
retryOnServerErrors(3)
exponentialDelay()
}
```
```
install(HttpRequestRetry) {
retryOnException(3)
constantDelay(millis = 5000)
}
```
```
install(HttpRequestRetry) {
maxRetries = 3
retryIf { request, response -> response.status.value.let { it in 500..599 } }
retryOnExceptopmIf { request, cause -> cause is IoException }
}
```
Per request config
```
val request = HttpRequestBuilder {
url(...)
retry { noRetry() }
}
```
=> KTOR-572 Retry on HttpCode or network error

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/internal/CallableUtils.kt
Fix [KTOR-2987](https://youtrack.jetbrains.com/issue/KTOR-2987)
=> KTOR-2987 Fix autoreload for GraalVM

ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOHttpsTest.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt
Fix [KTOR-3166](https://youtrack.jetbrains.com/issue/KTOR-3166)
@Stexxe please let me know if you have an idea we could test it
=> KTOR-3166 Fix watcher access on Android

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CommonHttpClientTest.kt, ktor-legacy/ktor-client-legacy/common/src/io/ktor/client/features/HttpClientFeature.kt, ktor-legacy/ktor-client-legacy/common/src/io/ktor/client/features/json/JsonFeature.kt, ktor-legacy/ktor-server-legacy/jvm/src/io/ktor/application/ApplicationFeature.kt
Legacy modules should have an old naming
=> KTOR-2370 KTOR-2795 Fix feature naming in legacy modules

ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/MultipartTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3173
=> MultiPartData.readAllParts throws IOException when the epilogue is omitted

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/AuthTokenHolder.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BearerAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTokenHolderTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Auth.kt
https://youtrack.jetbrains.com/issue/KTOR-3325
=> KTOR-3325 Queue refresh token requests

gradle/darwin.gradle
**Subsystem**
**Motivation**
**Solution**
@e5l
=> Add missing Apple silicon targets to 1.6.5

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationRequest.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/request/ApplicationRequest.kt, ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationRequest.kt, ktor-server/ktor-server-servlet/api/ktor-server-servlet.api, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletApplicationRequest.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationRequest.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-3297
=> KTOR-3297 Add raw query parameters to a request

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/api/ktor-server-metrics-micrometer.api, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt
**Subsystem**
**Motivation**
[Add possibility to fully configure metricName](https://youtrack.jetbrains.com/issue/KTOR-3302)
**Solution**
Description of solution is present in issue.
=> KTOR-3302 | improve configuration of metric mame for http requests

ktor-utils/jvm/src/io/ktor/util/debug/IntellijIdeaDebugDetector.kt
https://youtrack.jetbrains.com/issue/KTOR-3426
(see also: https://github.com/Kotlin/kotlinx.coroutines/issues/948)
=> KTOR-3426 Set IJ debugger check to false for Android

gradle.properties
Fix [KTOR-3469](https://youtrack.jetbrains.com/issue/KTOR-3469)
=> KTOR-3469 Enable compatibility variant publication

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BasicAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/BasicProviderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3472
=> Basic auth not sending second request

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpHeadersMap.kt, ktor-http/ktor-http-cio/posix/src/io/ktor/http/cio/internals/CharArrayBuilderNative.kt, ktor-io/common/src/io/ktor/utils/io/internal/SequentialCopyTo.kt, ktor-server/ktor-server-cio/jvmAndNix/test/io/ktor/tests/server/cio/CIOEngineTest.kt, ktor-server/ktor-server-test-suites/jvmAndNix/src/io/ktor/server/testing/HttpServerCommonTestSuite.kt, ktor-utils/common/test/io/ktor/util/ChannelTest.kt
* Fix flush in `copyTo`
* Fix chunked response in CIO
=> KTOR-3492 KTOR-3503 Native CIO server fixes

ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestServer.kt, ktor-server/ktor-server-cio/build.gradle.kts, ktor-server/ktor-server-core/jvmAndNix/test-resources/logback-test.xml, ktor-server/ktor-server-host-common/build.gradle.kts, ktor-server/ktor-server-plugins/build.gradle.kts
https://youtrack.jetbrains.com/issue/KTOR-3466
=> KTOR-3466 Change log level from `INFO` to `ERROR` for tests

CHANGELOG.md, build.gradle.kts, buildSrc/src/main/kotlin/KotlinExtensions.kt, gradle.properties, gradle/jvm.gradle, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-features/ktor-client-auth/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/BasicProviderTest.kt, ktor-client/ktor-client-features/ktor-client-encoding/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-json/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-websockets/build.gradle.kts, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-io/common/src/io/ktor/utils/io/ExceptionUtils.kt, ktor-io/js/src/io/ktor/utils/io/ByteChannelJS.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialJVM.kt, ktor-io/posix/src/io/ktor/utils/io/ByteChannelNative.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CallLoggingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/sessions/SessionTest.kt
Fix [KTOR-3532](https://youtrack.jetbrains.com/issue/KTOR-3532)
=> KTOR-3532 1.6.7 eap

CHANGELOG.md
=> Changelog: Fix Youtrack links for 1.6.7

gradle.properties, ktor-bom/build.gradle.kts
Fix [KTOR-3550](https://youtrack.jetbrains.com/issue/KTOR-3550)
Fix [KTOR-3594](https://youtrack.jetbrains.com/issue/KTOR-3594)
=> Ugrade Netty to 4.1.72.Final

CHANGELOG.md, gradle.properties
Fix [KTOR-3320](https://youtrack.jetbrains.com/issue/KTOR-3320)
=> Release 2.0.0-beta-1

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/HttpHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-forwarded-header/api/ktor-server-forwarded-header.api, ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/ForwardHeaderSupport.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/plugins/OriginConnectionPointTest.kt
https://youtrack.jetbrains.com/issue/KTOR-565
=> KTOR-565 Add option to choose value for X-Forwarded-* and Forwarded headers

ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/sessions/SessionTest.kt
**Subsystem**
Server, TestEngine
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-3614
**Solution**
Add protocol handling
=> KTOR-3614 Add protocol support to testApplication

ktor-server/ktor-server-plugins/ktor-server-thymeleaf/api/ktor-server-thymeleaf.api, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/src/io/ktor/server/thymeleaf/Thymeleaf.kt, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/test-resources/templates/fragments.html, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/test-resources/templates/fragments_insert_test.html, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/test/io/ktor/server/thymeleaf/ThymeleafTest.kt
**Motivation**
[KTOR-3624](https://youtrack.jetbrains.com/issue/KTOR-3624)
**Solution**
Add support for returning fragments by name
=> KTOR-3624 Returning Thymeleaf fragments from Routes

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3634
=> KTOR-3634 Retry-after header value should be in seconds

ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3618
=> KTOR-3618 Fix double slash when appending segments

ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/ApplicationEngine.kt
Fix [KTOR-3505](https://youtrack.jetbrains.com/issue/KTOR-3505)
=> KTOR-3505 Add defaults to stop method

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CreatePluginUtils.kt, ktor-server/ktor-server-plugins/ktor-server-default-headers/jvm/src/io/ktor/server/plugins/defaultheaders/DefaultHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-default-headers/jvm/test/io/ktor/tests/plugins/DefaultHeadersTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/plugins/DefaultHeadersTest.kt
Convert DefaultHeaders plugin to new API
=> Convert DefaultHeaders plugin to new API

gradle.properties
https://logback.qos.ch/news.html
=> KTOR-3733 Update logback to 1.2.10

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CallFailedHook.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CreatePluginUtils.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/Hook.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/ShutdownHook.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/application/HooksTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3740
=> KTOR-3740 Support routing scoped plugins in hooks

buildSrc/src/main/kotlin/TargetsConfig.kt, gradle/wrapper/gradle-wrapper.properties, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PluginsTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PostTest.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannel.kt, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/common/src/io/ktor/utils/io/core/Builder.kt, ktor-io/common/src/io/ktor/utils/io/core/BytePacketBuilder.kt, ktor-io/common/src/io/ktor/utils/io/core/Output.kt, ktor-io/common/test/io/ktor/utils/io/ByteBufferChannelScenarioTest.kt, ktor-io/common/test/io/ktor/utils/io/BytePacketBuildTest.kt, ktor-io/common/test/io/ktor/utils/io/BytePacketReadTest.kt, ktor-io/common/test/io/ktor/utils/io/BytePacketStringTest.kt, ktor-io/common/test/io/ktor/utils/io/PrimitiveCodecTest.kt, ktor-io/common/test/io/ktor/utils/io/ReadTextCommonTest.kt, ktor-io/common/test/io/ktor/utils/io/ReadUntilDelimiterTest.kt, ktor-io/js/src/io/ktor/utils/io/ByteReadChannelJs.kt, ktor-io/js/src/io/ktor/utils/io/core/PacketJS.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/core/PacketJVM.kt, ktor-io/jvm/test/io/ktor/utils/io/BytePacketBuildTestExtended.kt, ktor-io/jvm/test/io/ktor/utils/io/BytePacketReaderWriterTest.kt, ktor-io/posix/src/io/ktor/utils/io/ByteReadChannelNative.kt, ktor-io/posix/src/io/ktor/utils/io/core/Platform.kt, ktor-io/posix/test/io/ktor/utils/io/BytePacketBuilderExtendedTest.kt
Fix [KTOR-3632](https://youtrack.jetbrains.com/issue/KTOR-3632)
=> KTOR-3632 Drop headerSizeHint

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClientConfig.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/test/KotlinxSerializerTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/HttpRedirectMockedTest.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt
Fix [KTOR-3479](https://youtrack.jetbrains.com/issue/KTOR-3479)
=> KTOR-3479 Disable response validation by default

ktor-utils/jvm/src/io/ktor/util/debug/IntellijIdeaDebugDetectorJvm.kt
https://youtrack.jetbrains.com/issue/KTOR-3690
=> KTOR-3690 Fix NoClassDefFoundError on android in debugger detector

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/ApplicationPluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/PluginPhases.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/RelativePluginBuilder.kt, ktor-server/ktor-server-plugins/ktor-server-auto-head-response/api/ktor-server-auto-head-response.api, ktor-server/ktor-server-plugins/ktor-server-auto-head-response/jvmAndNix/src/io/ktor/server/plugins/autohead/AutoHeadResponse.kt, ktor-server/ktor-server-plugins/ktor-server-caching-headers/jvmAndNix/src/io/ktor/server/plugins/cachingheaders/CachingHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt
Fix [KTOR-3670](https://youtrack.jetbrains.com/issue/KTOR-3670)
=> KTOR-3670 Rewrite Auto Head to New Plugins API

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/ClassCastExceptionTest.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/KotlinTimeJvm.kt, ktor-server/ktor-server-plugins/ktor-server-hsts/jvmAndNix/src/io/ktor/server/plugins/hsts/KotlinTimeJvm.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/KotlinTimeJvm.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/src/io/ktor/server/websocket/KotlinDurations.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/sessions/SessionTest.kt, ktor-utils/common/src/io/ktor/util/date/Date.kt, ktor-utils/common/test/io/ktor/util/GMTDateTest.kt
Fix [KTOR-3595](https://youtrack.jetbrains.com/issue/KTOR-3595)
=> KTOR-3595 Drop ExperimentalTime

ktor-server/ktor-server-plugins/ktor-server-partial-content/api/ktor-server-partial-content.api, ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/PartialContent.kt
https://youtrack.jetbrains.com/issue/KTOR-3667
=> KTOR-3665 Rewrite PartialContent to New Plugins API

ktor-server/ktor-server-plugins/ktor-server-call-id/api/ktor-server-call-id.api, ktor-server/ktor-server-plugins/ktor-server-call-id/jvmAndNix/src/io/ktor/server/plugins/callid/CallId.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CallLoggingTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CallIdTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3352
=> KTOR-3352 Rewrite CallId to New Plugins API

ktor-server/ktor-server-plugins/ktor-server-http-redirect/api/ktor-server-http-redirect.api, ktor-server/ktor-server-plugins/ktor-server-http-redirect/jvmAndNix/src/io/ktor/server/plugins/httpsredirect/HttpsRedirect.kt
https://youtrack.jetbrains.com/issue/KTOR-3668
=> KTOR-3668 Rewrite HttpsRedirect to New Plugins API

ktor-server/ktor-server-plugins/ktor-server-webjars/api/ktor-server-webjars.api, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/WebjarsUtils.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/test/io/ktor/server/webjars/WebjarsTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3667
=> KTOR-3667 Rewrite WebJars plugin to new API

gradle.properties, ktor-server/ktor-server-plugins/ktor-server-call-id/api/ktor-server-call-id.api, ktor-server/ktor-server-plugins/ktor-server-call-id/jvm/src/io/ktor/server/plugins/callid/CallIdJvm.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/api/ktor-server-call-logging.api, ktor-server/ktor-server-plugins/ktor-server-call-logging/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLoggingConfig.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCEntryUtils.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCHook.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCProvider.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/CallLoggingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/sessions/AutoSerializerTest.kt
Fix [KTOR-3351](https://youtrack.jetbrains.com/issue/KTOR-3351)
=> KTOR-3351 Rewrite CallLogging

ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlClientEngine.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlProcessor.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlCallbacks.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlMultiApiHandler.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlRaw.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpStatementTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PluginsTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PostTest.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannel.kt, ktor-io/js/src/io/ktor/utils/io/ByteReadChannelJs.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/posix/src/io/ktor/utils/io/ByteChannelNative.kt, ktor-io/posix/src/io/ktor/utils/io/ByteReadChannelNative.kt, ktor-io/posix/src/io/ktor/utils/io/ByteWriteChannelNative.kt
=> KTOR-2931 Support streaming of body in curl

ktor-server/ktor-server-plugins/ktor-server-sessions/api/ktor-server-sessions.api, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/CacheStorage.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/DirectoryStorage.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/SessionStorage.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/SessionStorageMemory.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/SessionTrackerById.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/test/io/ktor/tests/sessions/CacheTest.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/test/io/ktor/tests/sessions/DirectorySessionStorageTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/sessions/SessionTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3336
Simplify cookies' cache to store strings and compare value before invalidating cache.
=> KTOR-3336 Fixes invalidating cookies cache on every request

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/ApplicationCall.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/ApplicationPluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/Interceptions.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/KtorCallContexts.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/PluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/RelativePluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt, ktor-server/ktor-server-host-common/jvm/test/io/ktor/tests/hosts/ReceiveBlockingPrimitiveTest.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/DefaultTransform.kt, ktor-server/ktor-server-host-common/nix/src/io/ktor/server/engine/DefaultTransformNix.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/RequestConverter.kt, ktor-server/ktor-server-plugins/ktor-server-double-receive/jvmAndNix/src/io/ktor/server/plugins/doublereceive/DoubleReceive.kt, ktor-server/ktor-server-plugins/ktor-server-double-receive/jvmAndNix/src/io/ktor/server/plugins/doublereceive/DoubleReceiveConfig.kt, ktor-server/ktor-server-plugins/ktor-server-double-receive/jvmAndNix/src/io/ktor/server/plugins/doublereceive/ReceiveHooks.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/ApplicationRequestContentTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
Fix [KTOR-3785](https://youtrack.jetbrains.com/issue/KTOR-3785)
=> KTOR-3785 Drop ApplicationReceiveRequest

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/FormDataContent.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt, ktor-client/ktor-client-core/common/test/MultiPartFormDataContentTest.kt, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/Generators.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/content/Multipart.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationRequest.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-3825
=> KTOR-3825 multipart/form-data requests: No way of streaming data asynchronously

ktor-io/jvm/src/io/ktor/utils/io/internal/ReadWriteBufferState.kt
Fix [KTOR-3801](https://youtrack.jetbrains.com/issue/KTOR-3801)
=> KTOR-3801 Clarify exception message

ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-utils/jvm/src/io/ktor/util/debug/IntellijIdeaDebugDetectorJvm.kt
Fix [KTOR-3653](https://youtrack.jetbrains.com/issue/KTOR-3834)
=> KTOR-3653 Handle any generic failures in CIO and debugger flag

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-plugins/ktor-client-websockets/common/test/io/ktor/client/tests/plugins/WebSocketRemoteTest.kt
Fix [KTOR-1726](https://youtrack.jetbrains.com/issue/KTOR-1726)
=> KTOR-1726 Replace specify pattern for JSON.stringify

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpCallValidator.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CallValidatorTest.kt
[KTOR-3652](https://youtrack.jetbrains.com/issue/KTOR-3652)
**Solution**
Create new method `handleResponseExceptionWithRequest` providing request
=> KTOR-3652 handleResponseException should have access to request to provide valuable information in exceptions

gradle.properties, ktor-server/ktor-server-plugins/ktor-server-call-id/api/ktor-server-call-id.api, ktor-server/ktor-server-plugins/ktor-server-call-id/jvm/src/io/ktor/server/plugins/callid/CallIdJvm.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/api/ktor-server-call-logging.api, ktor-server/ktor-server-plugins/ktor-server-call-logging/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLoggingConfig.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCEntryUtils.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCHook.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCProvider.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/CallLoggingTest.kt
Dropped because of the force push, reverted
=> KTOR-3351 Rewrite CallLogging to new plugins API

ktor-client/ktor-client-core/build.gradle.kts, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/ResponseObserver.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/plugins/observer/ResponseObserverContextJs.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/observer/ResponseObserverContextJvm.kt, ktor-client/ktor-client-core/posix/src/io/ktor/client/plugins/observer/ResponseObserverContextPosix.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/utils/Logging.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/LoggingTestJvm.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCEntryUtils.kt, ktor-utils/common/src/io/ktor/util/ByteChannels.kt, ktor-utils/jvm/src/io/ktor/util/Deflater.kt, ktor-utils/jvm/src/io/ktor/util/cio/ReadersJvm.kt
https://youtrack.jetbrains.com/issue/KTOR-2435
=> KTOR-2435 Fix MDC context in client response body logging

ktor-server/ktor-server-plugins/ktor-server-caching-headers/api/ktor-server-caching-headers.api, ktor-server/ktor-server-plugins/ktor-server-caching-headers/jvmAndNix/src/io/ktor/server/plugins/cachingheaders/CachingHeaders.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CachingHeadersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3758
=> KTOR-3758 Add call to CachingHeadersConfig.options callback

ktor-server/ktor-server-plugins/ktor-server-html-builder/api/ktor-server-html-builder.api, ktor-server/ktor-server-plugins/ktor-server-html-builder/jvm/src/io/ktor/server/html/Template.kt, ktor-server/ktor-server-plugins/ktor-server-html-builder/jvm/test/io/ktor/server/html/PlaceholderListTest.kt
**Subsystem**
ktor-server-html-builder
**Motivation**
[KTOR-3940](https://youtrack.jetbrains.com/issue/KTOR-3940)
**Solution**
Added `size` property and `isNotEmpty` method that reuse existing methods of `PlaceholderList`
=> KTOR-3940 Add isNotEmpty() and size methods to PlaceholderList

ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/utils/Logging.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/NettyHttpResponsePipeline.kt
https://youtrack.jetbrains.com/issue/KTOR-3987
=> KTOR-3987 Remove mutex from call logging

CHANGELOG.md
**Subsystem**
**Motivation**
**Solution**
@e5l
=> KTOR-2872 Add reverting to changelog

ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CORSTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3979
=> KTOR-3979 CORS `allowHeadersPrefixed` should ignore case

ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/AuthenticationInterceptors.kt, ktor-server/ktor-server-plugins/ktor-server-caching-headers/jvmAndNix/src/io/ktor/server/plugins/cachingheaders/CachingHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ContentNegotiation.kt, ktor-server/ktor-server-plugins/ktor-server-default-headers/jvm/src/io/ktor/server/plugins/defaultheaders/DefaultHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-double-receive/jvmAndNix/src/io/ktor/server/plugins/doublereceive/DoubleReceive.kt, ktor-server/ktor-server-plugins/ktor-server-jte/jvm/src/io/ktor/server/jte/Jte.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt
https://youtrack.jetbrains.com/issue/KTOR-4022
=> KTOR-4022 Add more KtorDsl annotations

ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ShutDownUrl.kt
https://youtrack.jetbrains.com/issue/KTOR-4025
=> KTOR-4025 Move ApplicationCallPlugin to companion object

ktor-server/ktor-server-plugins/ktor-server-cors/api/ktor-server-cors.api, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CORSTest.kt
Fix [KTOR-3980](https://youtrack.jetbrains.com/issue/KTOR-3980)
=> KTOR-3980 Adjust CORS configuration names

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheEntry.kt
Fix [KTOR-3984](https://youtrack.jetbrains.com/issue/KTOR-3984)
=> KTOR-3984 Change HttpClientCall fields visibility

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/ApplicationPlugin.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CreatePluginUtils.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/Hook.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/PluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/PluginInstance.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/RouteScopedPlugin.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/hooks/CommonHooks.kt
Updated API docs for custom plugins:
- added links to main docs
- fixed some code samples
- fixed some working and grammar
=> KTOR-4029 update API docs for plugins

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/HostsRoutingBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/IgnoreTrailingSlash.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/LocalPortRoutingBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Route.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Routing.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingApplicationCall.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingPath.kt
Added links to main docs, fixed grammar
=> KTOR-4053 update API docs for Routing

ktor-client/ktor-client-plugins/ktor-client-logging/build.gradle.kts, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/ObservingUtils.kt, ktor-client/ktor-client-plugins/ktor-client-logging/jvm/test/io/ktor/client/plugins/logging/LoggingJsonTest.kt
Fix [KTOR-3970](https://youtrack.jetbrains.com/issue/KTOR-3970)
=> KTOR-3970 Fix freeze in response observer

ktor-client/ktor-client-mock/api/ktor-client-mock.api, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngineConfig.kt
Fix [KTOR-3230](https://youtrack.jetbrains.com/issue/KTOR-3230)
=> KTOR-3230 Allow overriding dispatcher in MockEngine

ktor-network/jvm/src/io/ktor/network/selector/ActorSelectorManager.kt, ktor-network/jvm/src/io/ktor/network/selector/InterestSuspensionsMap.kt, ktor-network/jvm/src/io/ktor/network/selector/JvmSelector.kt, ktor-network/jvm/src/io/ktor/network/selector/LockFreeMPSCQueue.kt, ktor-network/jvm/src/io/ktor/network/selector/SelectableJvm.kt, ktor-network/jvm/src/io/ktor/network/selector/SelectorManager.kt, ktor-network/jvm/src/io/ktor/network/selector/SelectorManagerSupport.kt, ktor-network/jvmAndNix/src/io/ktor/network/selector/SelectorManagerCommon.kt, ktor-network/nix/src/io/ktor/network/selector/SelectorManager.kt
Fix [KTOR-506](https://youtrack.jetbrains.com/issue/KTOR-506)
=> KTOR-506 Fix selector manager

ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationRequestTest.kt
Fix [KTOR-3489](https://youtrack.jetbrains.com/issue/KTOR-3489)
=> KTOR-3489 Fix freeze with WriteChannelContent in test client

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CreatePluginUtils.kt
**Subsystem**
Server core docs
**Motivation**
**Solution**
=> Docs: Use createRouteScopedPlugin

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/UserAgent.kt
**Subsystem**
Client UserAgent Plugin
**Motivation**
Just fix comment
**Solution**
Just fix comment
=> Fix comment

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/ResponseObserver.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Content.kt
https://youtrack.jetbrains.com/issue/KTOR-3916
=> KTOR-3916 Fix combination of HttpCache and Logging plugins

ktor-server/ktor-server-plugins/ktor-server-default-headers/jvm/src/io/ktor/server/plugins/defaultheaders/DefaultHeaders.kt, ktor-server/ktor-server-test-suites/build.gradle.kts, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerJvmTestSuite.kt
Fix [KTOR-1452](https://youtrack.jetbrains.com/issue/KTOR-4152)
=> KTOR-4152 Fix double headers with DefaultHeaders plugin

ktor-server/ktor-server-plugins/ktor-server-conditional-headers/jvmAndNix/src/io/ktor/server/plugins/conditionalheaders/ConditionalHeaders.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/ConditionalHeadersTests.kt
https://youtrack.jetbrains.com/issue/KTOR-4163
=> KTOR-4163 Fix double header in ConditionalHeaders

build.gradle.kts, gradle.properties, ktor-server/ktor-server-plugins/ktor-server-status-pages/api/ktor-server-status-pages.api, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/test/io/ktor/server/plugins/statuspages/StatusPagesTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4191
=> KTOR-4191 Add `content` param to StatusPages

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/builders.kt, ktor-client/ktor-client-plugins/ktor-client-websockets/common/test/io/ktor/client/tests/plugins/WebSocketTest.kt
Fix [KTOR-4175](https://youtrack.jetbrains.com/issue/KTOR-4175)
=> KTOR-4175 Fix wss default port

buildSrc/src/main/kotlin/Publication.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/hooks/CommonHooks.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/test/io/ktor/server/plugins/statuspages/StatusPagesTest.kt
Fix [KTOR-4155](https://youtrack.jetbrains.com/issue/KTOR-4155)
=> KTOR-4155 Fix CallFailed exception swallow if call is not handled

build.gradle.kts
Fix [KTOR-4194](https://youtrack.jetbrains.com/issue/KTOR-4194)
=> KTOR-4194 Fix dokka publication

ktor-client/ktor-client-cio/jvm/src/io/ktor/client/plugins/websocket/cio/buildersCio.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/WebSocketReader.kt
Fix [KTOR-4166](https://youtrack.jetbrains.com/issue/KTOR-4166/Raw-Web-Socket-Connection-Suspending-Forever)
=> KTOR-4166 Prevent raw web socket session from freeze

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultRequest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/builders.kt, ktor-client/ktor-client-core/common/test/DefaultRequestTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4142
https://youtrack.jetbrains.com/issue/KTOR-4154
=> KTOR-4154 KTOR-4142 Default request host and port

gradle.properties, gradle/libs.versions.toml
Fix [KTOR-4221](https://youtrack.jetbrains.com/issue/KTOR-4221/Update-Kotlin-to-1.6.21)
=> KTOR-4221 Update kotlin to 1.6.21

ktor-io/common/test/io/ktor/utils/io/ByteChannelTest.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
Fix [KTOR-4218](https://youtrack.jetbrains.com/issue/KTOR-4218)
=> KTOR-4218 Fix read operation cancellation in channel

ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Routing.kt
**Subsystem**
Server Resources Plugin
**Motivation**
[Call `Route.handle` in 3rd party code](https://youtrack.jetbrains.com/issue/KTOR-4200/Resources:-Make-%60Route.handle%60-public)
**Solution**
Make it public
=> KTOR-4200 Make Route.handle in server-resources public

gradle.properties, gradle/libs.versions.toml
Fix [KTOR-4240](https://youtrack.jetbrains.com/issue/KTOR-4240/Update-Coroutines-to-1.6.1)
=> KTOR-4240 Update coroutines to 1.6.1

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt
Fix [KTOR-755](https://youtrack.jetbrains.com/issue/KTOR-755/embeddedServer-for-CIO-and-Netty-inconsistency)
=> KTOR-755 Use daemon threads in Netty engine

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpTimeout.kt
**Subsystem**
Client
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-4261/Explanation-on-request,-connection,-and-socket-missing-in-KDoc
**Solution**
Inline some of the information from https://ktor.io/docs/timeout.html.
=> Include explanations on request, connection, and socket in KDoc

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingResolveContext.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4280
=> KTOR-4280 Routes with tailcard should not count for specific http error codes

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/AbstractClientContentNegotiationTest.kt, ktor-shared/ktor-serialization/common/src/WebsocketContentConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/test/ClientGsonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/src/JacksonWebsocketContentConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ClientJacksonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-cbor/jvm/test/CborClientKotlinxSerializationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/jvm/test/JsonClientKotlinxSerializationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/jvm/test/XmlClientKotlinxSerializationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4248
=> KTOR-4248 Add more tests for WS converter

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ShutDownUrl.kt, ktor-server/ktor-server-plugins/ktor-server-method-override/jvmAndNix/src/io/ktor/server/plugins/methodoverride/XHttpMethodOverride.kt, ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/PartialContent.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Resources.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt, ktor-shared/ktor-resources/common/src/io/ktor/resources/Resource.kt
Updated API docs for several plugins and added links to main docs.
=> KTOR-4126 update API docs

ktor-client/ktor-client-plugins/ktor-client-resources/common/test/ResourcesTest.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3953
=> KTOR-3953 Encode slash in path parameter of UrlBuilder

buildSrc/src/main/kotlin/Codestyle.kt, gradle/libs.versions.toml, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ClientHeadersTest.kt, ktor-http/common/test/io/ktor/tests/http/CommonHeadersTest.kt, ktor-http/ktor-http-cio/api/ktor-http-cio.api, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HeaderParserTest.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTestUtils.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/RequestParserTest.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/ResponseParserTest.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/HeadersJvmTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/HeadersServerTest.kt, ktor-utils/posix/test/io/ktor/util/MultiWorkerDispatcherTest.kt
Fix [KTOR-380](https://youtrack.jetbrains.com/issue/KTOR-380)
Fix [KTOR-382](https://youtrack.jetbrains.com/issue/KTOR-382)
Fix [KTOR-369](https://youtrack.jetbrains.com/issue/KTOR-369)
=> HTTP Parser Fixes

ktor-server/ktor-server-plugins/ktor-server-caching-headers/api/ktor-server-caching-headers.api, ktor-server/ktor-server-plugins/ktor-server-caching-headers/jvmAndNix/src/io/ktor/server/plugins/cachingheaders/CachingHeaders.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CachingHeadersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-457
=> KTOR-457 Support setting caching options on call

gradle/libs.versions.toml
Fix [KTOR-4339](https://youtrack.jetbrains.com/issue/KTOR-4339/Update-Netty-to-4-1-77-Final)
=> KTOR-4339 Update Netty to 4.1.77.Final

gradle/libs.versions.toml
**Subsystem**
Server requests and authentication
**Motivation**
https://github.com/ktorio/ktor/issues/3002
**Solution**
update the version
=> updating to newest jwt version

ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngineConfig.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinSession.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
Fix [KTOR-583](https://youtrack.jetbrains.com/issue/KTOR-583/IosClientEngine-URLSession-access)
=> KTOR-583 Allow setting custom session for Darwin engine

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpPlainText.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinWebsocketSession.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinResponseReader.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/contentnegotiation/ContentNegotiation.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/test/io/ktor/client/plugins/ContentNegotiationTests.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/JsonContentNegotiationTest.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/src/io/ktor/client/plugins/json/JsonPlugin.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/test/KotlinxSerializerTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ApplicationResponseFunctions.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/DefaultTransform.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ContentNegotiationConfig.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/ContentNegotiationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/test/ServerGsonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ServerJacksonTest.kt
Default transform of string should happen after `ContentNegotiation`
=> Fixes for receiving and sending plain json string

ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt
https://youtrack.jetbrains.com/issue/KTOR-4373
=> KTOR-4373 External services should use config from environment

ktor-client/ktor-client-curl/desktop/interop/libcurl.def, ktor-client/ktor-client-curl/desktop/interop/libcurl_arm64.def, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinResponseReader.kt, ktor-java-modules-test/build.gradle.kts
Fix [KTOR-4358](https://youtrack.jetbrains.com/issue/KTOR-4358/Unable-to-build-project-on-Mac)
=> KTOR-4358 Fix project configuration

CHANGELOG.md, gradle.properties
Fix [KTOR-4289](https://youtrack.jetbrains.com/issue/KTOR-4289/Release-2-0-2)
=> KTOR-4289 Release 2.0.2

CHANGELOG.md, gradle/libs.versions.toml
Fix [KTOR-4394](https://youtrack.jetbrains.com/issue/KTOR-4394)
=> KTOR-4394 Update Jackson to 2.13.3

ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIORequestTest.kt, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt
https://youtrack.jetbrains.com/issue/KTOR-4347
=> KTOR-4347 Fix url normalization in CIO engine

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/contentnegotiation/ContentNegotiation.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/test/io/ktor/client/plugins/ContentNegotiationTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ClientHeadersTest.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ResponseConverter.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/ContentNegotiationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4399
https://youtrack.jetbrains.com/issue/KTOR-4383
https://youtrack.jetbrains.com/issue/KTOR-4269
=> KTOR-4383 KTOR-4399 Fix sending default types with ContentNegotiation

ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4412
=> KTOR-4412 Fixed UrlBuilder escapes fragment parameters

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/UrlEncodedTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/ContentNegotiationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4426
=> KTOR-4426 receiveText should return raw text body

ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/test/io/ktor/tests/resources/ResourcesTest.kt, ktor-shared/ktor-resources/common/src/io/ktor/resources/serialization/ResourcesFormat.kt
https://youtrack.jetbrains.com/issue/KTOR-4424
=> KTOR-4424 Support value classes in resources plugin

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestHttpClientEngineBridgeJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/DelegatingTestClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt, ktor-server/ktor-server-test-host/nix/src/io/ktor/server/testing/client/TestHttpClientEngineBridgeNix.kt
https://youtrack.jetbrains.com/issue/KTOR-4436
=> KTOR-4436 Add support for timeouts in test client engine

build.gradle.kts, gradle.properties, gradle/libs.versions.toml
Fix [KTOR-4451](https://youtrack.jetbrains.com/issue/KTOR-4451/Update-KotlinxCoroutines-to-1621)
=> KTOR-4451 Update kotlinx.coroutines to 1.6.2

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpPlainText.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpSend.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTypeTest.kt, ktor-http/common/src/io/ktor/http/HttpHeaders.kt
Fix [KTOR-620](https://youtrack.jetbrains.com/issue/KTOR-620/Content-Type-in-a-request-headers)
=> KTOR-620 Allow to set ContentType header

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/logging/Logging.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/logging/MDCProviderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4448
=> KTOR-4448 Fix accessing MDCProvider in empty application

ktor-server/ktor-server-config-yaml/api/ktor-server-config-yaml.api, ktor-server/ktor-server-config-yaml/jvmAndNix/src/io/ktor/server/config/yaml/YamlConfig.kt, ktor-server/ktor-server-config-yaml/jvmAndNix/test/YamlConfigTest.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/config/HoconApplicationConfig.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/config/HoconConfigTest.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/ApplicationConfig.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MapApplicationConfig.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MergedApplicationConfig.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/config/MapApplicationConfigTest.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/config/MergedApplicationConfigTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4416
=> KTOR-4416 Add `toMap` for `ApplicationConfig`

buildSrc/build.gradle.kts, gradle.properties, gradle/libs.versions.toml
Fix [KTOR-4450](https://youtrack.jetbrains.com/issue/KTOR-4450/Update-Kotlin-to-170)
=> KTOR-4450 Update Kotlin to 1.7.0

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/RequestBodyHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1Handler.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestBaseJvm.kt
https://youtrack.jetbrains.com/issue/KTOR-4397
=> KTOR-4397 Disable auto read in Netty engine

buildSrc/build.gradle.kts, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvmAndNix/test/EndpointTest.kt
Fix [KTOR-4473](https://youtrack.jetbrains.com/issue/KTOR-4473/Fix-a-Typo-in-CIO-Timeout-Configuration)
=> KTOR-4473 Fix a typo in the CIO timeout configuration

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/plugins/DefaultTransformJs.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/DefaultTransformersJvm.kt, ktor-client/ktor-client-core/posix/src/io/ktor/client/plugins/DefaultTransformIos.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/contentnegotiation/ContentNegotiation.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/test/io/ktor/client/plugins/ContentNegotiationTests.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/js/src/DefaultIgnoredTypesJs.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/jvm/src/DefaultIgnoredTypesJvm.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/posix/src/DefaultIgnoredTypesNix.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/DefaultTransformTest.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/DefaultTransformJvm.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/logging/MDCProviderTest.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvm/src/DefaultIgnoredTypesJvm.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ContentNegotiationConfig.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ResponseConverter.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/nix/src/DefaultIgnoredTypesNix.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/ContentNegotiationTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/ContentNegotiationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4511
=> KTOR-4511 Ignore ByteReadChannel for server response and client request

ktor-http/common/src/io/ktor/http/URLUtils.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt, ktor-utils/common/src/io/ktor/util/StringValues.kt
https://youtrack.jetbrains.com/issue/KTOR-4573
=> KTOR-4573 Fixed parameters of cloned UrlBuilder affect parameters of an original builder

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngineJvm.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestHttpClientEngineBridgeJvm.kt, ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4572
=> KTOR-4572 Fixed concurrent requests in TestApplication

buildSrc/src/main/kotlin/test/server/tests/Cache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4127
=> KTOR-4127 HttpCache ignores only-if-cached directive

ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/AuthenticationInterceptors.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/AuthBuildersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4618
=> KTOR-4618 Fix nesting of Authentication providers

ktor-server/ktor-server-plugins/ktor-server-auth/api/ktor-server-auth.api, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuthProcedure.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/OAuth2Test.kt
https://youtrack.jetbrains.com/issue/KTOR-2128
=> KTOR-2128 add extra parameters property for auth0 authorisation and receiving token

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/StreamRequestBody.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/RequestTests.kt
https://youtrack.jetbrains.com/issue/KTOR-4637
=> KTOR-4637 Override isOneShot for streaming body types in OkHttp

buildSrc/src/main/kotlin/test/server/tests/Encoding.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/test/ContentEncodingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4653
=> KTOR-4653 Fix receiving compressed byte array

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-plugins/ktor-client-resources/common/src/io/ktor/client/plugins/resources/builders.kt, ktor-client/ktor-client-plugins/ktor-client-resources/common/test/ResourcesTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4658
=> KTOR-4658 Fixed Client resources plugin miss builders for PATCH method

kotlin-js-store/yarn.lock
=> Upgrade yarn.lock

buildSrc/src/main/kotlin/test/server/tests/Headers.kt, ktor-client/ktor-client-darwin/build.gradle.kts, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinSession.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4719
=> KTOR-4719 Fixed Darwin configureRequest

CHANGELOG.md, gradle.properties
https://youtrack.jetbrains.com/issue/KTOR-4738
=> Release 2.1.0

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/LocalFileContent.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/http/content/LocalFileContentTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4707
=> KTOR-4707 Fix check for existence in LocalFileContent

ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/src/io/ktor/server/auth/jwt/JWTAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/src/io/ktor/server/auth/jwt/JWTUtils.kt
https://youtrack.jetbrains.com/issue/KTOR-636
=> KTOR-636 Log JWT exceptions in trace level

ktor-client/ktor-client-core/common/src/io/ktor/client/engine/Utils.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTypeTest.kt
Fix [KTOR-1407](https://youtrack.jetbrains.com/issue/KTOR-1407)
=> KTOR-1407 Fix Setting Custom Content-Type Header

ktor-client/ktor-client-mock/build.gradle.kts, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockUtils.kt, ktor-client/ktor-client-mock/common/test/MockUtilsTest.kt
Fix [KTOR-2126](https://youtrack.jetbrains.com/issue/KTOR-2126)
=> KTOR-2126 Fix OutgoingContent.toByteArray for big WriteChannelContent

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ResponseCookies.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/SessionTransportCookie.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/SessionsBuilder.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/test/io/ktor/tests/sessions/SessionTransportCookieTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/sessions/SessionTest.kt
Fix [KTOR-437](https://youtrack.jetbrains.com/issue/KTOR-437)
=> KTOR-437 Bypass cookie properties to the clear header

ktor-io/jvm/src/io/ktor/utils/io/jvm/javaio/Blocking.kt, ktor-io/jvm/test/io/ktor/utils/io/BlockingAdaptersOnProhibitedThreadTest.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt, ktor-server/ktor-server-host-common/jvm/test/io/ktor/tests/hosts/ReceiveBlockingPrimitiveTest.kt
Fix [KTOR-4736](https://youtrack.jetbrains.com/issue/KTOR-4736)
=> KTOR-4736 Replace fail with warning in blocking stream adapters

ktor-client/ktor-client-core/common/src/io/ktor/client/engine/Utils.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTypeTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/engine/UtilsTest.kt
[KTOR-4782](https://youtrack.jetbrains.com/issue/KTOR-4782/Fix-Merging-Date-Headers-on-the-Client)
=> KTOR-4782 Fix merging date headers

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/application/ApplicationCallReceiveTest.kt
Fix [KTOR-4771](https://youtrack.jetbrains.com/issue/KTOR-4771)
=> KTOR-4771 Fix Receive Non-Nullable null Message

ktor-shared/ktor-websockets/common/src/io/ktor/websocket/WebSocketExtensionHeader.kt, ktor-shared/ktor-websockets/common/test/io/ktor/tests/http/cio/websocket/WebSocketExtensionHeaderTest.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/WebSocketDeflateExtension.kt, ktor-shared/ktor-websockets/jvm/test/WebSocketDeflateTest.kt
Fix [KTOR-3189](https://youtrack.jetbrains.com/issue/KTOR-3189/parseWebSocketExtensions-not-correct)
Fix [KTOR-4696](https://youtrack.jetbrains.com/issue/KTOR-4696/WebSocketDeflateExtension-not-following-RFC)
=> KTOR-3189 KTOR-4696 Fix WS Extensions and Deflate Issues

ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/EngineMain.kt, ktor-server/ktor-server-cio/jvmAndNix/test/io/ktor/tests/server/cio/TestConnectorInterfaceUsed.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/EngineContextCancellationHelper.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ClientCertTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ConfigTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ConnectionTestSuite.kt
[KTOR-4032](https://youtrack.jetbrains.com/issue/KTOR-4032)
=> KTOR-4032 Fix netty timeout

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/OAuth2Test.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/FormAuth.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/ApplicationRequestContentTest.kt
Fix [KTOR-4772](https://youtrack.jetbrains.com/issue/KTOR-4772/)
=> KTOR-4772 Deprecatre receiveOrNull

ktor-io/posix/src/io/ktor/utils/io/pool/DefaultPool.kt
Fix [KTOR-4772](https://youtrack.jetbrains.com/issue/KTOR-4772/)
=> KTOR-4772 Deprecate atomicfu in public API

ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4819
https://youtrack.jetbrains.com/issue/KTOR-4773
=> KTOR-4773 KTOR-4819 Add ability to start application from `testApplication` block

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCEntryUtils.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/CallLoggingTest.kt
Fix [KTOR-550](https://youtrack.jetbrains.com/issue/KTOR-550/)
=> KTOR-550 Fix MDC exception crash request

CHANGELOG.md, gradle.properties
https://youtrack.jetbrains.com/issue/KTOR-4851
=> Release 2.1.1

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ApplicationResponseFunctions.kt, ktor-server/ktor-server-test-suites/jvmAndNix/src/io/ktor/server/testing/suites/HttpServerCommonTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-1538
=> KTOR-1538 ApplicationCall.respondRedirect should have overload for Url

buildSrc/src/main/kotlin/test/server/tests/Cache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheEntry.kt, ktor-client/ktor-client-core/common/test/ShouldValidateTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4894
=> KTOR-4894 Fixed HttpCache client plugin ignoring Request Cache-Control directives

CHANGELOG.md, gradle.properties
https://youtrack.jetbrains.com/issue/KTOR-4921
=> Release 2.1.2

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpTimeout.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4652
=> KTOR-4652 Add flag to enable retrying on request timeout

ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/test/io/ktor/tests/http/RenderSetCookieTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4722
=> KTOR-4722 renderSetCookieHeader should not encode extensions

ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt
https://youtrack.jetbrains.com/issue/KTOR-4925
Adding test is complicated, because we need a real proxy server running on another host.
=> KTOR-4925 Fix CIO tunneling.

gradle/libs.versions.toml
Should hopefully address memory leaks fixed as of https://github.com/Kotlin/kotlinx.coroutines/issues/3351 in coroutines
**Subsystem**
**Motivation**
https://github.com/Kotlin/kotlinx.coroutines/issues/3351
**Solution**
Bump coroutines to later version
=> Bump coroutines in libs.versions.toml

ktor-shared/ktor-serialization/ktor-serialization-jackson/api/ktor-serialization-jackson.api, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/src/JacksonConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ClientJacksonTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4904
=> KTOR-4904 Add option to support requests with Content-Length header in Jackson

ktor-server/ktor-server-plugins/ktor-server-compression/jvm/src/io/ktor/server/plugins/compression/Compression.kt
Fix [KTOR-2521](https://youtrack.jetbrains.com/issue/KTOR-4521/Add-Debug-Logging-to-Compression-Plugin)
=> KTOR-4521 Add Logging for Compression Plugin

ktor-server/ktor-server-plugins/ktor-server-default-headers/jvm/src/io/ktor/server/plugins/defaultheaders/DefaultHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-default-headers/jvm/test/io/ktor/tests/plugins/DefaultHeadersTest.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/DefaultWebSocketSession.kt
https://youtrack.jetbrains.com/issue/KTOR-4990
=> KTOR-4990 Fix duplication of default headers

ktor-http/js/src/io/ktor/http/URLBuilderJs.kt
https://youtrack.jetbrains.com/issue/KTOR-4993
Adding test is problematic, because bug is reproduced only inside iframe
=> KTOR-4993 Fix UrlBuilder origin in iframe

ktor-server/ktor-server-plugins/ktor-server-double-receive/jvmAndNix/src/io/ktor/server/plugins/doublereceive/DoubleReceive.kt
Fix [KTOR-4530](https://youtrack.jetbrains.com/issue/KTOR-4530/Add-Debug-Logging-to-Double-Receive-Plugin)
=> KTOR-4530 Add logging for DoubleReceive

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/WebSockets.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/src/io/ktor/server/websocket/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/src/io/ktor/server/websocket/WebSockets.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/DefaultWebSocketSession.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/PingPong.kt
Fix [KTOR-4528](https://youtrack.jetbrains.com/issue/KTOR-4528/Add-Debug-Logging-to-WebSockets-Plugin)
=> KTOR-4528 Add WebSockets Logging

ktor-server/ktor-server-plugins/ktor-server-call-id/jvmAndNix/src/io/ktor/server/plugins/callid/CallId.kt
Fix [KTOR-4520](https://youtrack.jetbrains.com/issue/KTOR-4520/Add-Debug-Logging-to-Call-Id)
=> KTOR-4520 Add Debug Logging To CallId Plugin

ktor-server/ktor-server-plugins/ktor-server-sessions/jvmAndNix/src/io/ktor/server/sessions/BeforeSendHook.kt, ktor-server/ktor-server-plugins/ktor-server-sessions/jvmAndNix/src/io/ktor/server/sessions/Sessions.kt
Fix [KTOR-4526](https://youtrack.jetbrains.com/issue/KTOR-4526/Add-Debug-Logging-to-Sessions-Plugin)
=> KTOR-4526 Add Sessions Logging

ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/BodyTransformedHook.kt, ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/PartialContent.kt, ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/PartialContentUtils.kt, ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/PartialOutgoingContent.kt
Fix [KTOR-4525](https://youtrack.jetbrains.com/issue/KTOR-4525/Add-Debug-Logging-to-PartialContent-Plugin)
=> KTOR-4525 Add PartialContent Logging

ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORSUtils.kt
Fix [KTOR-4236](https://youtrack.jetbrains.com/issue/KTOR-4236/CORS-Plugin-should-log-reason-for-returning-403-Forbidden-errors)
=> KTOR-4236 Add CORS logging

ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt
Fix [KTOR-4527](https://youtrack.jetbrains.com/issue/KTOR-4527/Add-Debug-Logging-to-Status-Pages-Plugin)
=> KTOR-4527 Add Logging for StatusPages Plugin

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Routing.kt, ktor-utils/api/ktor-utils.api, ktor-utils/common/src/io/ktor/util/logging/Logger.kt, ktor-utils/jvm/src/io/ktor/util/logging/LoggerJvm.kt, ktor-utils/posix/src/io/ktor/util/logging/LoggerNative.kt
Fix [KTOR-4524](https://youtrack.jetbrains.com/issue/KTOR-4524/Add-Debug-Logging-to-Routing)
=> KTOR-4524 Add logging for Routing

ktor-utils/posix/src/io/ktor/util/logging/KtorSimpleLoggerNative.kt, ktor-utils/posix/src/io/ktor/util/logging/LogLevelNative.kt, ktor-utils/posix/src/io/ktor/util/logging/LoggerNative.kt
Fix [KTOR-4998](https://youtrack.jetbrains.com/issue/KTOR-4998/Add-Env-Variable-to-Change-Log-Level-on-Native-Server)
=> KTOR-4998 Add Log Level Flag for Native

ktor-server/ktor-server-host-common/jvm/test/io/ktor/tests/hosts/ReceiveBlockingPrimitiveTest.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/DefaultTransform.kt
Fix [KTOR-4529](https://youtrack.jetbrains.com/issue/KTOR-4529/Add-Debug-Logging-to-Default-Transformers)
=> KTOR-4529 Add logging for default transformations

buildSrc/src/main/kotlin/test/server/ClientTestServer.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngine.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinWebsocketSession.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinResponseReader.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinSession.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5094
=> KTOR-5094 Fix using `handleChallenge` for Websockets connections in Darwin

ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ContentNegotiation.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/RequestConverter.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ResponseConverter.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/test/RequestConverterTest.kt
Fix [KTOR-4518](https://youtrack.jetbrains.com/issue/KTOR-4518/Add-Debug-Logging-to-ContentNegotiation)
=> KTOR-4518 Add Logging for ContentNegotiation plugin

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestLifecycle.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
https://youtrack.jetbrains.com/issue/KTOR-5099
=> KTOR-5099 Fix memory leak in HttpRequestRetry plugin

ktor-server/ktor-server-plugins/ktor-server-html-builder/jvmAndNix/src/io/ktor/server/html/RespondHtml.kt, ktor-server/ktor-server-plugins/ktor-server-html-builder/jvmAndNix/test/io/ktor/tests/html/HtmlBuilderTest.kt, ktor-server/ktor-server-plugins/ktor-server-html-builder/jvmAndNix/test/io/ktor/tests/html/HtmlContentTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5107
=> KTOR-5107 Fix `StatusPages` handling error in `respondHtml`

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CreatePluginUtils.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/PluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/RouteScopedPluginBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/application/ApplicationPluginTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5112
=> KTOR-5112 Add the ability to access the route inside a route-scoped plugin

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MergedApplicationConfig.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/config/MergedApplicationConfigTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5143
=> KTOR-5143 Fix merging config lists

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheLegacy.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/DisabledCacheStorage.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/HttpCacheStorage.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/UnlimitedCacheStorage.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/cache/storage/FileCacheStorage.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheLegacyStorageTest.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/FileCacheTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2579
Everything with suffix `Legacy` is moving of old storage related things to new files.
=> KTOR-2579 Add file based http cache storage for client

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/ClientHook.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/ClientPluginBuilder.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/ClientPluginInstance.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/CommonHooks.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/CreatePluginUtils.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/KtorCallContexts.kt, ktor-client/ktor-client-core/common/test/ClientPluginsTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5161
=> KTOR-5161 New client plugins API

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/ClientPluginBuilder.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/CommonHooks.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/api/CreatePluginUtils.kt
Fixed some issues in API docs for custom plugins: code snippet markup, grammar, etc.
=> KTOR-5175 review API docs for custom plugins

ktor-server/ktor-server-plugins/ktor-server-openapi/jvm/src/io/ktor/server/plugins/openapi/OpenAPI.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/swagger/Swagger.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test-resources/documentation.json, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test-resources/openapi/documentation.yaml, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test/io/ktor/server/swagger/SwaggerTest.kt, which-server/which-server-plugins/which-server-swagger/jvm/test/io/which/server/swagger/SwaggerTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5150/Support-serving-OpenAPI-from-resources
=> KTOR-5150 Change OpenAPI resources path to openapi/documentation.yaml

ktor-client/ktor-client-core/common/test/CookiesTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CookiesTest.kt, ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/sessions/SessionTestJvm.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CookiesTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/URIEncodingCookiesTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/sessions/SessionTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5168
=> KTOR-5168 Fix session transformer when value has space

ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt
https://youtrack.jetbrains.com/issue/KTOR-5186
=> Logging: the plugin instantiates the default logger even when a custom one is provided

ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/src/io/ktor/server/auth/jwt/JWTAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/test/io/ktor/server/auth/jwt/JWTPayloadHolderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5098
=> JWT: JWTPayloadHolder.getListClaim() throws NPE when specified claim is absent

build.gradle.kts
Fix [KTOR-5119](https://youtrack.jetbrains.com/issue/KTOR-5119/Update-to-Dokka-1.7.20)
=> KTOR-5119 Update Dokka to 1.7.20

ktor-server/ktor-server-plugins/ktor-server-status-pages/api/ktor-server-status-pages.api, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPagesUtils.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/test/io/ktor/server/plugins/statuspages/StatusPagesTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4502
=> KTOR-721 Provide way to customize unhandled responses

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/src/io/ktor/http/Mimes.kt
**Subsystem**
Server
**Motivation**
Bug
**Solution**
Fix and add [Font types](https://www.iana.org/assignments/media-types/media-types.xhtml#font)
=> KTOR-5311 Fix font content type and gzip

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/KtorCallContexts.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/hooks/CommonHooks.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ApplicationSendPipeline.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/ContentNegotiation.kt, ktor-server/ktor-server-plugins/ktor-server-freemarker/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-freemarker/jvm/src/io/ktor/server/freemarker/FreeMarker.kt, ktor-server/ktor-server-plugins/ktor-server-freemarker/jvm/test/io/ktor/tests/freemarker/FreeMarkerTest.kt, ktor-server/ktor-server-plugins/ktor-server-jte/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-jte/jvm/src/io/ktor/server/jte/Jte.kt, ktor-server/ktor-server-plugins/ktor-server-jte/jvm/test/io/ktor/tests/jte/JteTest.kt, ktor-server/ktor-server-plugins/ktor-server-mustache/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-mustache/jvm/src/io/ktor/server/mustache/Mustache.kt, ktor-server/ktor-server-plugins/ktor-server-mustache/jvm/test-resources/index.hbs, ktor-server/ktor-server-plugins/ktor-server-mustache/jvm/test/io/ktor/server/mustache/MustacheTest.kt, ktor-server/ktor-server-plugins/ktor-server-pebble/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/test/io/ktor/server/pebble/PebbleTest.kt, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/src/io/ktor/server/thymeleaf/Thymeleaf.kt, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/test/io/ktor/server/thymeleaf/ThymeleafTest.kt, ktor-server/ktor-server-plugins/ktor-server-velocity/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-velocity/jvm/src/io/ktor/server/velocity/Velocity.kt, ktor-server/ktor-server-plugins/ktor-server-velocity/jvm/test/io/ktor/tests/velocity/VelocityTest.kt
**Subsystem**
Server
**Motivation**
Bug
**Solution**
Invoke template plugins (`Mustache`, `Jte` etc) in the new `Content` phase which is before `ContentNegotiation`
=> KTOR-5337 Conflict between `ContentNegotiation` and  template plugins

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultRequest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultResponseValidation.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpCallValidator.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpPlainText.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRedirect.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestLifecycle.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpTimeout.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/UserAgent.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheEntry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheLegacy.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cookies/HttpCookies.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt, ktor-client/ktor-client-core/common/test/ShouldValidateTest.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-shared/ktor-resources/common/test/io/ktor/tests/resources/PathPatternSerializationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5264/
=> KTOR-5264 Add trace logs for core plugins

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MapApplicationConfig.kt, ktor-server/ktor-server-host-common/jvm/test/io/ktor/tests/hosts/CommandLineTest.kt
**Subsystem**
Server
**Motivation**
[KTOR-5100](https://youtrack.jetbrains.com/issue/KTOR-5100)
=> KTOR-5100 Fix command line array properties

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/Headers.kt, ktor-http/common/src/io/ktor/http/Parameters.kt, ktor-http/common/test/io/ktor/tests/http/CommonHeadersTest.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingBuilder.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/http/ParametersTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-419/Allow-passing-multiple-acceptable-content-types-to-accept-route-selector
https://youtrack.jetbrains.com/issue/KTOR-627/Update-Parameters-and-Headers-DSL-to-be-consistent-with-stdlib
=> Minor API improvements

ktor-server/ktor-server-plugins/ktor-server-call-logging/api/ktor-server-call-logging.api, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLoggingConfig.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/CallLoggingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-1250/Log-HTTP-request-time
=> KTOR-1250 Log HTTP request time on server

ktor-server/ktor-server-plugins/ktor-server-auth/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth1a.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/OAuth2Test.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuthCommon.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuthProcedure.kt, ktor-server/ktor-server-plugins/ktor-server-auth/nix/src/OAuthNative.kt
https://youtrack.jetbrains.com/issue/KTOR-1144/Make-OAuth2-functionality-of-the-ktor-auth-feature-to-be-common-client-feature
No new code, only moving and splitting to expect/actual
=> KTOR-1144 Make OAuth2 functionality multiplatform

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt
**Solution**
https://github.com/reactor/reactor-netty/issues/2167#issuecomment-1111128564
=> KTOR-5370 fix tcpKeepAlive option on Netty

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/RequestBodyHandler.kt
https://youtrack.jetbrains.com/issue/KTOR-3455
https://youtrack.jetbrains.com/issue/KTOR-4475
=> KTOR-3455 Fix reading request body back pressure in Netty

ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/ConnectionPipeline.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/ConnectErrorsTest.kt, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt, ktor-http/common/src/io/ktor/http/HttpProtocolVersion.kt, ktor-http/ktor-http-cio/api/ktor-http-cio.api, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/backend/ServerPipeline.kt
https://youtrack.jetbrains.com/issue/KTOR-5327
=> KTOR-5327 CIO should use Connection: Close value as default in HTTP/1.0

ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/src/io/ktor/server/websocket/Routing.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/CloseReason.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/DefaultWebSocketSession.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/FrameCommon.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/FrameTooBigException.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/FrameType.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/RawWebSocketCommon.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/WebSocketExtension.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/WebSocketExtensionHeader.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/WebSocketSession.kt
Improved the `WebSocketSession.incoming` description and fixed some grammar issues along the way.
=> KTOR-5480 improve WebSocket API docs grammar

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/JsonContentNegotiationTest.kt, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/test/io/ktor/tests/http/ContentTypeTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3799
=> KTOR-3799 Add charset only for text/* content types

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RegexRouting.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/routing/RegexRoutingTest.kt
[Design](https://youtrack.jetbrains.com/issue/KTOR-5279/Design-for-regex-patterns-support-in-routing)
=> KTOR-5110 Support regex patterns in routing

ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/SessionAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/SessionAuthTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5467
Merging to 2.3.0 because default behaviour changes
=> KTOR-5467 Add default sessions auth challenge behaviour

buildSrc/src/main/kotlin/test/server/tests/Cache.kt, ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheEntry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheLegacy.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/HttpCacheStorage.kt, ktor-client/ktor-client-core/common/test/CacheExpiresTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheLegacyStorageTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5570
=> KTOR-5570 Fixed incorrect handling of private cache directive in HttpCachePlugin

ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/src/io/ktor/server/websocket/WebSocketUpgrade.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestHttpClientEngineBridgeJvm.kt, ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationResponse.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt, ktor-server/ktor-server-test-host/nix/src/io/ktor/server/testing/client/TestHttpClientEngineBridgeNix.kt
https://youtrack.jetbrains.com/issue/KTOR-5525
=> KTOR-5525 Keep external coroutineContext in testApplication

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingResolveContext.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5535
=> KTOR-5535 Use the longest successful routing trait on mismatch

ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/ConnectionPipeline.kt, ktor-client/ktor-client-plugins/ktor-client-logging/api/ktor-client-logging.api, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/LoggingUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt
https://youtrack.jetbrains.com/issue/KTOR-5523
=> KTOR-5523 Add ability to filter sensitive header values in logging

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/BodyProgress.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/DelegatedCall.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/BodyProgressTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5532
=> KTOR-5532 ByteBufferChannel throws exception when HttpCache, ContentEncoding and onDownload are used

ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlClientEngineConfig.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlMultiApiHandler.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlRaw.kt
Adding test is not easy, but the change is self-explanatory.
=> KTOR-5614 Support for CURLOPT_CAINFO and CURLOPT_CAPATH in ktor-client-curl

buildSrc/src/main/kotlin/test/server/tests/Tcp.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-apache5/jvm/src/io/ktor/client/engine/apache5/ApacheRequestProducer.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpRequestBodyPublisher.kt, ktor-http/common/src/io/ktor/http/HttpStatusCode.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/jvm/nio/Writing.kt, ktor-network/jvm/src/io/ktor/network/sockets/CIOWriter.kt, ktor-network/nix/src/io/ktor/network/sockets/CIOWriter.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/internal/EndPointChannels.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/internal/EndPointChannels.kt, ktor-utils/common/src/io/ktor/util/ByteChannels.kt, ktor-utils/jvm/src/io/ktor/util/EncodersJvm.kt
Should fix `testErrorInWritingPropagates` flaky test
=> Fix some error loses in byte channels

ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/DarwinLegacyClientEngine.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngine.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt, ktor-http/common/src/io/ktor/http/HttpStatusCode.kt
https://youtrack.jetbrains.com/issue/KTOR-5502
=> KTOR-5502 Fixed request in Darwin engine deadlocks on macOS since 2.2.2

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4052
=> KTOR-4052 Built-in support for HEAD requests for static files

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/PreCompressed.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/SinglePageApplication.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-jetty-jakarta/jvm/test/io/ktor/tests/server/jetty/jakarta/WebResourcesTest.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/WebResourcesTest.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/callloging/CallLoggingTest.kt, ktor-server/ktor-server-plugins/ktor-server-openapi/jvm/src/io/ktor/server/plugins/openapi/OpenAPI.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
https://youtrack.jetbrains.com/issue/KTOR-818
=> KTOR-818 Static files extensions modifiers

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-plugins/ktor-server-auto-head-response/jvmAndNix/src/io/ktor/server/plugins/autohead/AutoHeadResponse.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/AutoHeadResponseTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5684/AutoHead-should-dispose-response-body
=> KTOR-5684 AutoHead should dispose response body

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCHook.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/callloging/CallLoggingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5665
=> KTOR-5665 CallLogging: logs caused by an exception are suppressed when mdc provider is configured

ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/OAuth2Test.kt
https://youtrack.jetbrains.com/issue/KTOR-5669
=> KTOR-5669 Fix nested objects parsing in OAuth2 token response

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-http/js/src/io/ktor/http/URLBuilderJs.kt, ktor-utils/api/ktor-utils.api, ktor-utils/common/src/io/ktor/util/PlatformUtils.kt, ktor-utils/js/src/io/ktor/util/CryptoJs.kt, ktor-utils/js/src/io/ktor/util/PlatformUtilsJs.kt, ktor-utils/jvm/src/io/ktor/util/PlatformUtilsJvm.kt, ktor-utils/posix/src/io/ktor/util/PlatformUtilsNative.kt, ktor-utils/posix/src/io/ktor/util/ThreadInfo.kt
https://youtrack.jetbrains.com/issue/KTOR-5650
=> KTOR-5650 Prefer Node to browser behaviour

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/Auth.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/DigestProviderTest.kt, ktor-server/ktor-server-plugins/ktor-server-request-validation/jvmAndNix/src/io/ktor/server/plugins/requestvalidation/RequestValidationConfig.kt
https://youtrack.jetbrains.com/issue/KTOR-5681
=> KTOR-5681 Client Auth: Use fresh token if available

README.md, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/JsConfig.kt, buildSrc/src/main/kotlin/Publication.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, gradle.properties, kotlin-js-store/yarn.lock, ktor-io/js/test/io/ktor/utils/io/VerifyingObjectPool.kt, ktor-server/ktor-server-plugins/ktor-server-jte/build.gradle.kts
Fix [KTOR-5543](https://youtrack.jetbrains.com/issue/KTOR-5543)
Fix [KTOR-5544](https://youtrack.jetbrains.com/issue/KTOR-5544)
Fix [KTOR-5698](https://youtrack.jetbrains.com/issue/KTOR-5698)
=> KTOR-5543 KTOR-5544 Update Kotlin to 1.8

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/JsonContentNegotiationTest.kt, ktor-http/js/src/io/ktor/http/URLBuilderJs.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/jvm/test/KotlinxContentNegotiationTest.kt
[KTOR-5687](https://youtrack.jetbrains.com/issue/KTOR-5687)
=> KTOR-5687 Fix serializing with typeInfo Any

ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt
=> Fix flaky testErrorInWritingPropagates test

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RegexRouting.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/routing/RegexRoutingTest.kt
[KTOR-5746](https://youtrack.jetbrains.com/issue/KTOR-5746) 
[KTOR-5748](https://youtrack.jetbrains.com/issue/KTOR-5748)
[KTOR-5750](https://youtrack.jetbrains.com/issue/KTOR-5750)
=> KTOR-5746 & KTOR-5748 & KTOR-5750 Fix processing of slashes and IllegalArgumentException in Regex Routing

gradle.properties, gradle/libs.versions.toml, ktor-server/ktor-server-plugins/ktor-server-sessions/jvmAndNix/src/io/ktor/server/sessions/serialization/MapDecoder.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/test/io/ktor/server/webjars/WebjarsTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/test/JsonSerializationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/jvm/test/JsonClientKotlinxSerializationJsonJvmTest.kt
Combining two PRs from renovate into one
=> Update Kotlin and kotlinx.serialization

THIRDPARTY.md, gradle/libs.versions.toml, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/test/io/ktor/server/auth/jwt/JWTAuthTest.kt
=> Remove mockito from dependencies and replace usages with mockk

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngineJvm.kt, ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationResponse.kt
[KTOR-5815](https://youtrack.jetbrains.com/issue/KTOR-5815)
=> KTOR-5815 Fix NullPointerException when websocket connection failed

CONTRIBUTING.md
Fix [KTOR-5858](https://youtrack.jetbrains.com/issue/KTOR-5858/Contribution-guide-should-be-updated)
=> KTOR-5858 Update CONTRIBUTING.md

ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/CIOMultipartDataBase.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-5864
=> KTOR-5864 Multipart: Support not writing a temporary file for binary data

ktor-server/ktor-server-plugins/ktor-server-sessions/jvmAndNix/src/io/ktor/server/sessions/SessionData.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/sessions/SessionTest.kt
[KTOR-912](https://youtrack.jetbrains.com/issue/KTOR-912) Sessions: Set-Cookie is added on every api request.
=> KTOR-912 Fix adding Set-Cookie on every api request

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/AbstractClientContentNegotiationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/src/GsonConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/src/GsonWebsocketContentConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/test/ClientGsonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/src/JacksonConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/src/JacksonWebsocketContentConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/common/src/io/ktor/serialization/kotlinx/KotlinxSerializationConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/src/io/ktor/serialization/kotlinx/json/KotlinxSerializationJsonExtensions.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-protobuf/jvm/test/ProtoBufClientKotlinxSerializationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/jvm/test/XmlClientKotlinxSerializationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5421
=> KTOR-5421 The Logging plugin doesn't log full deserialization errors

ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/DarwinHttpRequestException.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/DarwinLegacyClientEngine.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/KtorLegacyNSURLSessionDelegate.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/certificates/LegacyCertificatePinner.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyRequestUtils.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyResponseUtils.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacySession.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyTaskHandler.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyUrlUtils.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyUtils.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/TimeoutUtilsLegacy.kt, ktor-client/ktor-client-darwin-legacy/darwin/test/DarwinLegacyEngineTest.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinUtils.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinRequestUtils.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpRequestBodyPublisher.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpRequest.kt
https://youtrack.jetbrains.com/issue/KTOR-5899
=> KTOR-5899 Darwin engine does not support streaming of request body

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MergedApplicationConfig.kt, ktor-server/ktor-server-host-common/jvm/test/io/ktor/tests/hosts/CommandLineTest.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/CommandLine.kt, ktor-server/ktor-server-host-common/jvmAndNix/test-resources/application-additional.conf, ktor-server/ktor-server-host-common/jvmAndNix/test-resources/application-main.conf
https://youtrack.jetbrains.com/issue/KTOR-5895
=> KTOR-5895 HOCON: "No configuration setting found for key" error after merging

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/AuthTokenHolder.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTokenHolderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5879
=> KTOR-5879 Bearer auth token refresh hangs after prior refresh threw an exception

ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/Headers.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/AuthHeadersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5900
=>  KTOR-5900 Ktor throws an exception with full JWT token in a message

ktor-network/ktor-network-quic/api/ktor-network-quic.api, ktor-network/ktor-network-quic/jvm/src/io/ktor/network/quic/tls/CryptoKeys.kt, ktor-network/ktor-network-quic/jvm/src/io/ktor/network/quic/tls/TLSServerComponentJvm.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/bytes/VarInt.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/connections/QUICConnection_v1.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/PacketNumberSpace.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/PacketReader.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/QUICPacket.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/sockets/Builders.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/sockets/QUICSocketBase.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/streams/QUICServer.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/streams/QUICStream.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/streams/QUICStreamChannel.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/streams/ReceiveStreamState.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/tls/ProtocolCommunicationProvider.kt
**Subsystem**
ktor-network
**Solution**
Added basic implementations of stream management for QUIC.
=> [QUIC] Basic Streams

ktor-server/ktor-server-plugins/ktor-server-auth-ldap/api/ktor-server-auth-ldap.api, ktor-server/ktor-server-plugins/ktor-server-auth-ldap/jvm/src/io/ktor/server/auth/ldap/Ldap.kt
[KTOR-793](https://youtrack.jetbrains.com/issue/KTOR-793)
=> KTOR-793 Make LDAP return generic Principal instead of UserIdPrincipal

ktor-client/ktor-client-core/common/src/io/ktor/client/content/ObservableContent.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/utils/ByteChannelUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/BodyProgressTest.kt
[KTOR-1540](https://youtrack.jetbrains.com/issue/KTOR-1540)
=> KTOR-1540 Make ProgressListener.contentLength nullable

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/RequestTests.kt
[KTOR-5971](https://youtrack.jetbrains.com/issue/KTOR-5971)
=> KTOR-5971 Set ContentType for ByteArrayContent body in OkHttp

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MapApplicationConfig.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/config/MapApplicationConfigTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6013
=> KTOR-6013 Fix deeply nested keys in `MapApplicationConfig::toMap`

ktor-http/common/src/io/ktor/http/content/CachingOptions.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/api/ktor-server-webjars.api, ktor-server/ktor-server-plugins/ktor-server-webjars/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/WebjarsUtils.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/test/io/ktor/server/webjars/WebjarsTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6073
=> KTOR-6073 Webjars plugin should include caching headers and ETag by default

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngineJvm.kt, ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt
https://youtrack.jetbrains.com/issue/KTOR-6057
=> KTOR-6057 Fix testApplication when ws connection fails

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6120
=> KTOR-6120 staticFiles responds twice if both index and defaultPath are set

ktor-network/darwin/src/io/ktor/network/selector/SelectUtilsDarwin.kt, ktor-network/linux/src/io/ktor/network/selector/SelectUtilsLinux.kt, ktor-network/nix/interop/network.def, ktor-network/nix/src/io/ktor/network/selector/SelectUtils.kt
Fix [KTOR-5822](https://youtrack.jetbrains.com/issue/KTOR-5822)
=> KTOR-5822 Move fd_set usages to interop

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cookies/CookiesStorage.kt
https://youtrack.jetbrains.com/issue/KTOR-6119
=> KTOR-6119 Persistant Cookie Storage: Make Cookie.matches and Cookie.fillDefaults methods public

gradle/libs.versions.toml, ktor-client/ktor-client-okhttp/build.gradle.kts
Fix [KTOR-6161](https://youtrack.jetbrains.com/issue/KTOR-6161/)
=> KTOR-6161 Bump okio version

ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/DefaultEnginePipeline.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestBaseJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/ExpectedTestException.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/nix/src/io/ktor/server/testing/EngineTestBaseNix.kt, ktor-server/ktor-server-test-suites/jvmAndNix/src/io/ktor/server/testing/suites/HttpServerCommonTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-6150
=> KTOR-6150 Fixed the status code of error response in call.respond(status, body) and error in body

ktor-http/ktor-http-cio/api/ktor-http-cio.api, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt, ktor-io/common/src/io/ktor/utils/io/internal/SequentialCopyTo.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationResponse.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/backend/ServerPipeline.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/NettyHttpResponsePipeline.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationResponse.kt, ktor-server/ktor-server-test-suites/jvmAndNix/src/io/ktor/server/testing/suites/HttpServerCommonTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-3266
=> KTOR-3266 Inconsistent behavior for different engines when exception is thrown in the writer of WriteChannelContent

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt
https://youtrack.jetbrains.com/issue/KTOR-6178
=> KTOR-6178 MicrometerMetricsConfig default registry leaks coroutine

ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/Swagger.kt
**Subsystem**
Server, ktor-server-swagger
- support for swagger `docExpansion` function
=> support for swagger `docExpansion` function

ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinUtils.kt
https://youtrack.jetbrains.com/issue/KTOR-6147
Unfortunately, can't add test for this, because it's reproducible only without network connection
=> KTOR-6147 Darwin: App hangs when streaming request without network connection

buildSrc/src/main/kotlin/test/server/tests/Auth.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt
[KTOR-3391](https://youtrack.jetbrains.com/issue/KTOR-3391)
=> KTOR-3391 Add algorithm field in the Authorization header in Digest Auth

ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt
[KTOR-6064](https://youtrack.jetbrains.com/issue/KTOR-6064)
=> KTOR-6064 Fix documentation and message of NoTransformationFoundException

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlClientEngine.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/DarwinLegacyClientEngine.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyTaskHandler.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngine.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinTaskHandler.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttpClientEngine.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpResponseData.kt
[KTOR-6217](https://youtrack.jetbrains.com/issue/KTOR-6217)
=> KTOR-6217 SSE plugin support in client engines

ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinUtils.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinWebsocketSession.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
Fix [KTOR-5540](https://youtrack.jetbrains.com/issue/KTOR-5540)
=> KTOR-5540 Fix darwin ws pong message

LICENSE
Fix [KTOR-6283](https://youtrack.jetbrains.com/issue/KTOR-6283)
=> KTOR-6283 Fix copyright

ktor-client/ktor-client-core/common/src/io/ktor/client/content/ObservableContent.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/ResponseObserver.kt
https://youtrack.jetbrains.com/issue/KTOR-6252
=> KTOR-6252 Fix client state after network error and ResponseObserver is installed

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cookies/AcceptAllCookiesStorage.kt, ktor-client/ktor-client-core/common/test/AcceptAllCookiesStorageTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2023/AcceptAllCookiesStorage-ignores-cookies-max-age
=> KTOR-2023 AcceptAllCookiesStorage ignores cookie's max-age

ktor-client/ktor-client-android/api/ktor-client-android.api, ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheEngine.kt, ktor-client/ktor-client-apache5/jvm/src/io/ktor/client/engine/apache5/Apache5Engine.kt, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/CIOEngine.kt, ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngineBase.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngineConfig.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/HttpClientEngineBase.js.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/engine/HttpClientEngineBase.jvm.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/engine/HttpClientJvmEngine.kt, ktor-client/ktor-client-core/posix/src/io/ktor/client/engine/HttpClientEngineBase.posix.kt, ktor-client/ktor-client-java/api/ktor-client-java.api, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpEngine.kt, ktor-client/ktor-client-java/jvm/test/io/ktor/client/engine/java/JavaEngineTests.kt, ktor-client/ktor-client-jetty-jakarta/jvm/src/io/ktor/client/engine/jetty/jakarta/JettyHttp2Engine.kt, ktor-client/ktor-client-jetty/jvm/src/io/ktor/client/engine/jetty/JettyHttp2Engine.kt, ktor-client/ktor-client-mock/api/ktor-client-mock.api, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngineConfig.kt, ktor-client/ktor-client-okhttp/api/ktor-client-okhttp.api, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/DelegatingTestClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-utils/api/ktor-utils.api
Fix [KTOR-6292](https://youtrack.jetbrains.com/issue/KTOR-6292)
=> KTOR-6292 Make client use Dispatchers.IO by default

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/builders.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttp.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttpClientEngine.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpRequestProducer.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpResponseData.kt
[KTOR-6312](https://youtrack.jetbrains.com/issue/KTOR-6312)
=> KTOR-6312 Remove http timeout for sse requests

ktor-server/ktor-server-jetty-jakarta/api/ktor-server-jetty-jakarta.api, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/JettyApplicationEngineBase.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/ServerInitializer.kt, ktor-server/ktor-server-jetty/api/ktor-server-jetty.api, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/ServerInitializer.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/MultipleDispatchOnTimeout.kt
[KTOR-6288](https://youtrack.jetbrains.com/issue/KTOR-6288)
=> KTOR-6288 Add idle timeout for Jetty server

ktor-utils/jvm/src/io/ktor/util/date/DateJvm.kt
**Motivation**
Removing unused imports and optimizing imports that can be improved using IntelliJ IDEA "Optimize imports".
=> Optimizing imports for ktor-utils

ktor-server/ktor-server-plugins/ktor-server-compression/jvm/src/io/ktor/server/plugins/compression/Compression.kt, ktor-server/ktor-server-plugins/ktor-server-sse/api/ktor-server-sse.api, ktor-server/ktor-server-plugins/ktor-server-sse/jvmAndNix/src/io/ktor/server/sse/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-sse/jvmAndNix/src/io/ktor/server/sse/SSEServerContent.kt, ktor-server/ktor-server-tests/build.gradle.kts, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CompressionTest.kt
[KTOR-6327](https://youtrack.jetbrains.com/issue/KTOR-6327)
=> KTOR-6327 Disable compression for SSE on server side

ktor-server/ktor-server-config-yaml/jvmAndNix/src/io/ktor/server/config/yaml/YamlConfig.kt, ktor-server/ktor-server-config-yaml/jvmAndNix/test/YamlConfigTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6357
=> KTOR-6357 YAML properties with literal value null cannot be read

ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationResponse.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ResponseHeaders.kt, ktor-server/ktor-server-test-suites/jvmAndNix/src/io/ktor/server/testing/suites/HttpServerCommonTestSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-6352
=> KTOR-6352 CIO: getEngineHeaderValues() returns duplicated values

ktor-utils/js/src/io/ktor/util/logging/KtorSimpleLoggerJs.kt, ktor-utils/js/src/io/ktor/util/logging/LoggerJs.kt, ktor-utils/js/test/io.ktor.util/KtorSimpleLoggerTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6275
=> KTOR-6275 Ktor JS client unconfigurable logging in node

build.gradle.kts
**Subsystem**
Build script
**Motivation**
Remove redundant code which related with JS-both
**Solution**
Just leave only IR code
=> Remove details of JS-both

ktor-shared/ktor-resources/common/test/io/ktor/tests/resources/ResourceUrlBuilderTest.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/test/GsonWebsocketTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/JacksonWebsocketTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ServerJacksonBlockingTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/src/io/ktor/serialization/kotlinx/json/KotlinxSerializationJsonExtensions.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/jvm/test/KotlinxContentNegotiationTest.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/WebSocketSession.kt
**Motivation**
Removing unused imports and optimizing imports that can be improved using IntelliJ IDEA "Optimize imports" for the `ktor-shared` and its sub-libraries.
=> Optimizing imports in ktor-shared library

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/HeadersJvmTest.kt, ktor-server/ktor-server-test-suites/jvmAndNix/src/io/ktor/server/testing/suites/WebSocketEngineSuite.kt
https://youtrack.jetbrains.com/issue/KTOR-6366
=> KTOR-6366 CIO: Unable to perform WebSocket upgrade when Content-Type header is sent in the request

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ClientHeadersTest.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/RequestConverter.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/test/ContentNegotiationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6420
=> KTOR-6420 ContentNegotiation: Adding charset to content type breaks request matching

ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpConnect.kt
=> Fix mingwx64 compilation

ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/EngineConnectorConfig.kt, ktor-server/ktor-server-plugins/ktor-server-hsts/api/ktor-server-hsts.api, ktor-server/ktor-server-plugins/ktor-server-hsts/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-hsts/jvmAndNix/src/io/ktor/server/plugins/hsts/HSTS.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/HSTSTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4168
=> KTOR-4168 HSTS plugin hard codes port 443

ktor-server/ktor-server-plugins/ktor-server-sessions/api/ktor-server-sessions.api, ktor-server/ktor-server-plugins/ktor-server-sessions/jvm/src/io/ktor/server/sessions/SessionTransportTransformerEncrypt.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/sessions/SessionTestJvm.kt
https://youtrack.jetbrains.com/issue/KTOR-6318
=> KTOR-6318 Calculate session encryption mac over encrypted value

build.gradle.kts, gradle.properties, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/core/Buffer.kt, ktor-io/common/src/io/ktor/utils/io/core/BytePacketBuilder.kt, ktor-io/common/src/io/ktor/utils/io/core/ByteReadPacket.kt, ktor-io/common/src/io/ktor/utils/io/core/internal/ChunkBuffer.kt, ktor-io/posix/src/io/ktor/utils/io/pool/DefaultPool.posix.kt, ktor-network/jvmAndNix/test/io/ktor/network/sockets/tests/TCPSocketTest.kt, ktor-network/nix/src/io/ktor/network/sockets/CIOReader.kt, ktor-network/nix/src/io/ktor/network/sockets/CIOWriter.kt
Fix [KTOR-6321](https://youtrack.jetbrains.com/issue/KTOR-6321/High-Native-Server-Memory-Usage)
=> KTOR-6321 Fix ChunkBuffer memory leak in Native ByteChannel

build.gradle.kts
Fix [KTOR-6470](https://youtrack.jetbrains.com/issue/KTOR-6470/Add-security-check-build)
=> KTOR-6470 Introduce security check plugin

buildSrc/src/main/kotlin/test/server/tests/WebSockets.kt, ktor-client/ktor-client-cio/jvmAndNix/test/CIOEngineTest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/WebSockets.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinWebsocketSession.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpWebSocket.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/test/ContentNegotiationTest.kt
[KTOR-6397](https://youtrack.jetbrains.com/issue/KTOR-6397)
=> KTOR-6397 Fix error processing in WebSockets

buildSrc/src/main/kotlin/test/server/tests/Cache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheEntry.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt
[KTOR-6505](https://youtrack.jetbrains.com/issue/KTOR-6505)
=> KTOR-6505 Fix NumberFormatException in HttpCache

ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationRequest.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/plugins/OriginConnectionPoint.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyConnectionPoint.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/Http2LocalConnectionPoint.kt, ktor-server/ktor-server-servlet-jakarta/jvm/src/io/ktor/server/servlet/jakarta/ServletConnectionPoint.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletConnectionPoint.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationRequest.kt
Fix [KTOR-6577](https://youtrack.jetbrains.com/issue/KTOR-6577)
=> KTOR-6577 Add toString for ConnectionPoints

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/builders.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt
Fix [KTOR-6571](https://youtrack.jetbrains.com/issue/KTOR-6571)
=> KTOR-6571 Fix SSEException is thrown instead of JobCancellationException when coroutine's job is cancelled

buildSrc/src/main/kotlin/test/server/tests/ServerSentEvents.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/SSE.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpSSESession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-server/ktor-server-plugins/ktor-server-compression/jvm/src/io/ktor/server/plugins/compression/Compression.kt
Fix [KTOR-6559](https://youtrack.jetbrains.com/issue/KTOR-6559)
=> KTOR-6559 Fix SSE content type issues

buildSrc/src/main/kotlin/test/server/tests/ServerSentEvents.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpSend.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/Url.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/api/ktor-network-tls-certificates.api, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/Certificates.kt
Make the default keystore backward compatible
=> Fix keystore type backward compatibility

ktor-client/ktor-client-cio/build.gradle.kts, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/ConnectErrorsTest.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ClientCertTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-shared/ktor-junit/jvm/src/io/ktor/junit/RetryTest.kt
Added junit extension to retry tests a single time when they hit an exception, hopefully this will improve the random failures 🤞
=> Add retry extension for junit tests to fix flaky tests

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/ClientSSESession.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/DefaultClientSSESession.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/SSE.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpSSESession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt
**Subsystem**
Client, sse
**Motivation**
[KTOR-6660](https://youtrack.jetbrains.com/issue/KTOR-6660)
**Solution**
By analogy with `Websockets`
=> KTOR-6660 Add call property to ClientSSESession

ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/src/io/ktor/server/plugins/csrf/CSRFConfig.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/test/io/ktor/server/plugins/csrf/CSRFTest.kt
**Subsystem**
Server, CSRF
**Motivation**
- KTOR-6687 onFailure without an explicit response would result in a 200 empty body
**Solution**
- Added the default error response when there is no response committed in the onFailure block
=> KTOR-6687 Empty CSRF onFailure option is misleading

ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/JsClientEngine.kt
**Subsystem**
Client, JS (wasm)
**Motivation**
Build broke.
**Solution**
Fix build.
=> Fix for build issue caused by WASM merge

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cookies/AcceptAllCookiesStorage.kt, ktor-client/ktor-client-core/common/test/AcceptAllCookiesStorageTest.kt
**Subsystem**
Client, cookies
**Motivation**
[KTOR-6646](https://youtrack.jetbrains.com/issue/KTOR-6646)
=> KTOR-6646 Fix overflow for cookie with long Max-Age

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCEntryUtils.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/callloging/CallLoggingTest.kt
**Subsystem**
Server, CallLogging
**Motivation**
[KTOR-6642](https://youtrack.jetbrains.com/issue/KTOR-6642)
=> KTOR-6642 Fix overriding MDC context map in CallLogging

ktor-http/common/src/io/ktor/http/auth/AuthScheme.kt
**Subsystem**
ktor/http/auth
**Motivation**
Fix RFC link and reference
**Solution**
Fix
=> [ktor-http/common/src/io/ktor/http/auth/AuthScheme.kt] Make doc to refer to correct RFCs

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/MDCHook.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/callloging/CallLoggingTest.kt
**Subsystem**
Server, CallLogging
**Motivation**
[KTOR-6839](https://youtrack.jetbrains.com/issue/KTOR-6839)
=> KTOR-6839 Fix double logging response in CallLogging

ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-network/ktor-network-tls/jvmAndNix/src/io/ktor/network/tls/CipherSuites.kt
Fix [KTOR-6767](https://youtrack.jetbrains.com/issue/KTOR-6767) io.ktor.network.tls.TLSException has internal visibility
=> KTOR-6767 Make TLSException public

ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/SwaggerConfig.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test/io/ktor/server/plugins/swagger/SwaggerTest.kt
**Subsystem**
Server, swagger
**Motivation**
[KTOR-7019](https://youtrack.jetbrains.com/issue/KTOR-7019)
=> KTOR-7019 Update default version for swagger ui

gradle/libs.versions.toml
**Subsystem**
Server
**Motivation**
[Describe what problem this PR solves and why it is important. Refer to a bug/ticket #.](https://youtrack.jetbrains.com/issue/KTOR-7014/Update-netty-due-to-CVE-2024-29025)
**Solution**
Update Netty version
=> KTOR-7014 Update netty due to CVE-2024-29025

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/SSEClientContent.kt, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/ObservingUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/content/OutgoingContent.kt
**Subsystem**
Client, SSE, Logging
**Motivation**
[KTOR-6912](https://youtrack.jetbrains.com/issue/KTOR-6912)
=> Fix NoTransformationFoundException when SSE with Logging plugin

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/src/io/ktor/http/auth/AuthScheme.kt
**Subsystem**
Shared
**Motivation**
https://www.ietf.org/rfc/rfc3902.txt Ktor does not have the Soap Mime type
**Solution**
Added Soap mime type
=> Add soap+xml content type

ktor-server/ktor-server-core/api/ktor-server-core.api
Missed CI failure during https://github.com/ktorio/ktor/pull/4065
=> KTOR-7043 Fix API snapshot

.github/ISSUE_TEMPLATE/config.yml, CHANGELOG.md, gradle.properties, gradle/libs.versions.toml, ktor-http/common/src/io/ktor/http/FileContentType.kt, ktor-http/common/src/io/ktor/http/Mimes.kt, ktor-io/linux/src/CharsetLinux.kt, ktor-io/mingwX64/src/CharsetMingw.kt, ktor-network/jvmAndNix/src/io/ktor/network/sockets/Sockets.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/SwaggerConfig.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test/io/ktor/server/plugins/swagger/SwaggerTest.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/test/io/ktor/server/webjars/WebjarsTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt, ktor-shared/ktor-events/common/src/io/ktor/events/Events.kt
[KTOR-7054](https://youtrack.jetbrains.com/issue/KTOR-7054) NoSuchMethodError when using coroutines 1.9.0-RC
[KTOR-6655](https://youtrack.jetbrains.com/issue/KTOR-6655) Server: Content-Type header for static js, css and svg resources misses charset
[KTOR-7016](https://youtrack.jetbrains.com/issue/KTOR-7016) Embedded Linux device without iso-8859-1 and UTF-16 cannot use ktor-network
[KTOR-7094](https://youtrack.jetbrains.com/issue/KTOR-7094) Update netty to 4.1.111.Final
[KTOR-7014](https://youtrack.jetbrains.com/issue/KTOR-7014) Update netty due to CVE-2024-29025
[KTOR-7019](https://youtrack.jetbrains.com/issue/KTOR-7019) Update dependency on swagger
=> Release 2.3.12

ktor-network/jvm/src/io/ktor/network/sockets/CIOWriter.kt
This seems to fix the memory problems currently in the CIO engine for kotlinx-io.  There is still an issue with the Netty pipeline after attempting to make the change there.
=> Remove lookahead session from CIO writer

ktor-io/common/src/io/ktor/utils/io/charsets/Encoding.kt, ktor-io/wasmJs/src/io/ktor/utils/io/charsets/CharsetJS.kt
**Subsystem**
ktor-io
**Motivation**
Compilation error after PR https://github.com/ktorio/ktor/pull/4094
=> Fix compilation on Native after PR #4094

ktor-network/jvm/src/io/ktor/network/sockets/DatagramSocketImpl.kt, ktor-network/nix/src/io/ktor/network/sockets/DatagramSocketNative.kt
[KTOR-2914](https://youtrack.jetbrains.com/issue/KTOR-2914) "java.lang.IllegalArgumentException: Failed requirement." in SelectorManagerSupport
=> KTOR-2914 Try to fix crash due to network errors

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClientConfig.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequestPipeline.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpResponsePipeline.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt
Disable SFG in client to avoid cast errors
=> KTOR-6882 Disable SFG in client

ktor-network/nix/interop/network.def, ktor-network/nix/src/io/ktor/network/selector/SelectUtils.kt, ktor-network/nix/test/io/ktor/network/sockets/tests/SelectNixTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4046
=> KTOR-4046 Check file descriptor before executing FD_CLR or FD_SET

ktor-network/nix/src/io/ktor/network/selector/SelectUtilsNix.kt, ktor-network/nix/test/io/ktor/network/sockets/tests/TcpSocketTestNix.kt, ktor-network/nix/test/io/ktor/network/sockets/tests/UdpSocketTestNix.kt, ktor-network/posix/src/io/ktor/network/selector/WorkerSelectorManager.kt, ktor-network/posix/src/io/ktor/network/sockets/TCPServerSocketNative.kt, ktor-network/posix/src/io/ktor/network/sockets/TCPSocketNative.kt, ktor-network/windows/src/io/ktor/network/selector/SelectUtilsWindows.kt
[KTOR-7255](https://youtrack.jetbrains.com/issue/KTOR-7255) Closing socket and selector leaks descriptor on native
=> KTOR-7255 Fix descriptor leak when closing socket and selector

ktor-server/ktor-server-plugins/ktor-server-cors/api/ktor-server-cors.api, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORSConfig.kt
**Subsystem**
ktor-server-plugin/ktor.server.plugins.cors
**Motivation**
[KTOR-3329](https://youtrack.jetbrains.com/issue/KTOR-3329): add the ability to allow all http methods in CORS
**Solution**
Added `anyMethod()` method in CORSConfig
=> KTOR-3329: add anyMethod CORS config method

ktor-network/jvmAndPosix/test/io/ktor/network/sockets/tests/TCPSocketTest.kt, ktor-network/windows/src/io/ktor/network/selector/SelectUtilsWindows.kt, ktor-utils/posix/src/io/ktor/util/collections/ConcurrentMapNative.kt
My PR #4151 unfortunately contained a disconnect issue which was not caught by existing tests. Added a new test and fixed the issue.
=> Fix TCP socket disconnect on mingwX64 & select improvements

CONTRIBUTING.md, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/MultipartTest.kt, ktor-utils/common/src/io/ktor/util/debug/IntellijIdeaDebugDetector.kt
**Subsystem**
**Motivation**
fix some comments
**Solution**
=> chore: fix some comments

ktor-network/nix/test/io/ktor/network/sockets/tests/TcpSocketTestNix.kt
Fix port is already in use for native tests
=> Fix port already in use for flaky tests

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/internal/ByteChannelReplay.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CookiesIntegrationTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CookiesMockTest.kt, ktor-server/ktor-server-jetty-jakarta/jvm/test/io/ktor/tests/server/jetty/jakarta/JettyEngineTest.kt, ktor-server/ktor-server-plugins/ktor-server-body-limit/common/src/io/ktor/server/plugins/bodylimit/RequestBodyLimit.kt, ktor-server/ktor-server-plugins/ktor-server-body-limit/common/test/io/ktor/server/plugins/bodylimit/RequestBodyLimitTest.kt
**Subsystem**
Client + Server
**Motivation**
The formatting check has been failing for a while and I need a win today 😭 
**Solution**
I ran the `formatKotlin` gradle target
=> Fix formatting

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/BodyProgress.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DoubleReceivePlugin.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheEntry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheLegacy.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/HttpCacheStorage.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/DelegatedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/ResponseObserver.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/DefaultHttpResponse.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpResponse.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/Readers.kt, ktor-client/ktor-client-core/common/test/CacheExpiresTest.kt, ktor-client/ktor-client-core/jvm/test/ExceptionsTest.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/src/ContentEncoding.kt, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ClientPipelinesTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PluginsTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheLegacyStorageTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-server/ktor-server-plugins/ktor-server-resources/common/test/io/ktor/tests/resources/Verifiers.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/CompressionTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
Fix [KTOR-6596](https://youtrack.jetbrains.com/issue/KTOR-6596) Misleading function name
=> KTOR-6596 Fix misleading readBytes() function name

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/HostsRoutingBuilder.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/LocalPortRoutingBuilder.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RegexRouting.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingResolveContext.kt, ktor-server/ktor-server-plugins/ktor-server-auth/api/ktor-server-auth.api, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/AuthenticationInterceptors.kt, ktor-server/ktor-server-plugins/ktor-server-rate-limit/api/ktor-server-rate-limit.api, ktor-server/ktor-server-plugins/ktor-server-rate-limit/common/src/io/ktor/server/plugins/ratelimit/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/common/src/io/ktor/server/websocket/Routing.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
**Subsystem**
Server, core
**Motivation**
It's not possible to access the body/call another suspend function in RouteSelector.evaluate
**Solution**
Make evaluate suspending
=> KTOR-7084 Access the body in RouteSelector

ktor-server/ktor-server-plugins/ktor-server-cors/common/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-plugins/ktor-server-cors/common/src/io/ktor/server/plugins/cors/CORSUtils.kt
**Subsystem**
ktor-server-cors
**Motivation**
numberRegex is passed in several methods in CORS.kt, however it is only used in CORSutils.kt and the value does not change. Therefore it can be moved to CORSutils.kt
**Solution**
removed numberRegex from method arguments and moved it to CORSutils.kt
=> Refactor CORS number regex

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Compilations.kt, gradle/libs.versions.toml, kotlin-js-store/yarn.lock, ktor-client/ktor-client-darwin-legacy/api/ktor-client-darwin-legacy.klib.api, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/certificates/LegacyCertificatePinner.kt, ktor-client/ktor-client-darwin/api/ktor-client-darwin.klib.api, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/certificates/CertificatePinner.kt, ktor-http/api/ktor-http.klib.api, ktor-io/api/ktor-io.klib.api, ktor-network/api/ktor-network.klib.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-plugins/ktor-server-auth/api/ktor-server-auth.klib.api, ktor-server/ktor-server-plugins/ktor-server-rate-limit/api/ktor-server-rate-limit.klib.api, ktor-server/ktor-server-plugins/ktor-server-request-validation/api/ktor-server-request-validation.klib.api, ktor-server/ktor-server-test-base/jvm/src/io/ktor/server/test/base/EngineTestBaseJvm.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/routing/RoutingResolveTest.kt, ktor-shared/ktor-websockets/api/ktor-websockets.klib.api, ktor-utils/api/ktor-utils.api, ktor-utils/api/ktor-utils.klib.api, ktor-utils/common/src/io/ktor/util/date/Date.kt
Update kotlin to 2.0.20 and add client retry plugin to fix some flaky tests
=> Update kotlin to 2.0.20; Add client request retry plugin

gradle.properties, ktor-server/ktor-server-cio/jvmAndPosix/src/io/ktor/server/cio/CIOApplicationCall.kt, ktor-server/ktor-server-cio/jvmAndPosix/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/application/PipelineCall.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingNode.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/hosts/ReceiveBlockingPrimitiveTest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationCall.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationCall.kt
Fix missing coroutine context for the ApplicationCall
=> Add missing coroutineScope for the ApplicationCall

ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/Embedded.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/EngineMain.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/Embedded.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/EngineMain.kt
**Subsystem**
Server, Jetty + Tomcat engines
**Motivation**
[KTOR-7315](https://youtrack.jetbrains.com/issue/KTOR-7315) Deprecate old jetty / tomcat / servlet engines
**Solution**
Add deprecation annotations to produce warnings.
=> KTOR-7315 Deprecate old Jetty and Tomcat engines

CONTRIBUTING.md
**Subsystem**
Contributing guide
**Motivation**
Noticed some minor style issues while was preparing my work environment
**Solution**
Fixed indentation in bash commands, replaced one `'` with `
=> Fix minor style issues in contributing guide

buildSrc/src/main/kotlin/JsConfig.kt, buildSrc/src/main/kotlin/NativeUtils.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, ktor-server/gradle.properties, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/api/ktor-serialization-kotlinx-xml.klib.api, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/build.gradle.kts, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/common/src/io/ktor/serialization/kotlinx/xml/XmlSupport.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/common/test/XmlSerializationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/gradle.properties, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/jvm/test/XmlServerKotlinxSerializationTest.kt
**Subsystem**
`ktor-serialization-kotlinx-xml`
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-5085/Add-multiplatform-support-for-XML
**Solution**
Moved sources and some tests from `jvm` to `common` source set.
Docs change: https://github.com/ktorio/ktor-documentation/pull/513
=> KTOR-5085: Add multiplatform support for XML serialization

ktor-server/ktor-server-plugins/ktor-server-sse/common/test/io/ktor/server/sse/ServerSentEventsTest.kt, ktor-shared/ktor-sse/api/ktor-sse.api, ktor-shared/ktor-sse/api/ktor-sse.klib.api, ktor-shared/ktor-sse/common/src/io/ktor/sse/ServerSentEvent.kt
**Subsystem**
Server, SSE
**Motivation**
[KTOR-7391](https://youtrack.jetbrains.com/issue/KTOR-7391/SSE-the-plugin-doesnt-follow-the-spec-when-multiline-data-is-sent)
=> KTOR-7391 Fix `toString()` for ServerSentEvent

ktor-client/ktor-client-curl/build.gradle.kts
**Subsystem**
Client, curl
**Solution**
Reverts a change that causes problems for this build.
=> Revert breaking change to curl client gradle

gradle.properties, ktor-server/ktor-server-core/api/ktor-server-core.klib.api
**Motivation**
CI [is failing](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixCoreAPICheck/277235?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandPull+Request+Details=true&expandBuildProblemsSection=true)
**Solution**
Re-run apiDump
=> Update API dump

.gitignore, docs/develocity.md, gradle-settings-conventions/build.gradle.kts, gradle-settings-conventions/settings.gradle.kts, gradle-settings-conventions/src/main/kotlin/conventions-develocity.settings.gradle.kts, gradle-settings-conventions/src/main/kotlin/customization.kt, gradle-settings-conventions/src/main/kotlin/execute.kt, gradle-settings-conventions/src/main/kotlin/params.kt, gradle.properties, settings.gradle.kts
**Subsystem**
Gradle
**Motivation**
Publish build scans and build cache
**Solution**
Added Develocity configs
=> Added Develocity plugin for build scans and remote build cache

ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/server/engine/EmbeddedServerTest.kt
Fix [KTOR-3031](https://youtrack.jetbrains.com/issue/KTOR-3031) Autoreload not working by default under Windows
=> KTOR-3031 Fix autoreload not working by default under Windows

ktor-server/ktor-server-config-yaml/jvm/src/io/ktor/server/config/yaml/YamlConfigJvm.kt, ktor-server/ktor-server-config-yaml/jvm/test/YamlConfigTestJvm.kt, ktor-server/ktor-server-config-yaml/jvmAndPosix/src/io/ktor/server/config/yaml/YamlConfig.kt, ktor-server/ktor-server-config-yaml/posix/src/io/ktor/server/config/yaml/YamlConfigNix.kt
[KTOR-7492](https://youtrack.jetbrains.com/issue/KTOR-7492) Ktor doesn't read System properties from JVM
=> KTOR-7492 Fix read System properties from jvm

build.gradle.kts, buildSrc/src/main/kotlin/Codestyle.kt, buildSrc/src/main/kotlin/Compilations.kt, buildSrc/src/main/kotlin/JsConfig.kt, buildSrc/src/main/kotlin/JvmConfig.kt, buildSrc/src/main/kotlin/KtorBuildProperties.kt, buildSrc/src/main/kotlin/NamedDomainObjectCollection.kt, buildSrc/src/main/kotlin/Publication.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, buildSrc/src/main/kotlin/Train.kt, buildSrc/src/main/kotlin/WasmConfig.kt, buildSrc/src/main/kotlin/test/server/TestServerPlugin.kt, ktor-client/ktor-client-android/build.gradle.kts, ktor-java-modules-test/build.gradle.kts, ktor-server/build.gradle.kts, ktor-server/ktor-server-core/build.gradle.kts, ktor-server/ktor-server-jetty-jakarta/ktor-server-jetty-test-http2-jakarta/build.gradle.kts, ktor-server/ktor-server-jetty/ktor-server-jetty-test-http2/build.gradle.kts, ktor-server/ktor-server-netty/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-default-headers/build.gradle.kts
**Subsystem**
Infrastructure
**Motivation**
Boost project configuration phase - [KTOR-7499](https://youtrack.jetbrains.com/issue/KTOR-7499/Gradle-Avoid-tasks-configuration-during-the-configuration-phase)
**Solution**
- Use lazy APIs to avoid unnecessary tasks configuration
- ~Enable configuration cache and "configure on demand"~ (Not yet)
| Before | After |
|--------|------|
| <img width="500" alt="image" src="https://github.com/user-attachments/assets/ff9f341b-bbe0-48ef-ae76-6996d8850829"> | <img width="500" alt="image" src="https://github.com/user-attachments/assets/ddaef4f2-d8ac-4a54-83e7-13b9b8ecd218"> |
| [Build Scan](https://ge.jetbrains.com/s/c2jaoyabt76bo/performance/configuration) | [Build Scan](https://ge.jetbrains.com/s/uqrccpehkl3mo/performance/configuration) |
The number of …
=> KTOR-7499 Avoid unnecessary tasks configuration

ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/cache/storage/FileCacheStorage.kt
=> KTOR-6589 Replace MD5 with SHA-3

ktor-server/ktor-server-plugins/ktor-server-resources/jvm/test/io/ktor/tests/resources/ResourcesTestJvm.kt
**Subsystem**
Server, Build
**Motivation**
Build error in main
**Solution**
Add missing import
=> Fix build error

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/AuthProvider.kt
**Subsystem**
**Motivation**
remove redundant backticks
**Solution**
=> chore: remove redundant backticks

ktor-http/common/src/io/ktor/http/Url.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
**Subsystem**
ktor-http
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-7625
**Solution**
Fixed Url.segments parsing
=> KTOR-7625: Url.segments parsing fix

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/calllogging/CallLoggingTest.kt, ktor-utils/common/src/io/ktor/util/pipeline/Pipeline.kt
**Subsystem**
Server
**Motivation**
[KTOR-7326](https://youtrack.jetbrains.com/issue/KTOR-7326) INFO log message with all server interceptors on server startup
**Solution**
Remove debug output of all interceptors on `Pipeline.toString`
=> KTOR-7326 Remove debug implementation of Pipeline.toString

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, buildSrc/src/main/kotlin/Train.kt, gradle-settings-conventions/settings.gradle.kts, gradle-settings-conventions/src/main/kotlin/conventions-dependency-resolution-management.settings.gradle.kts, gradle/libs.versions.toml, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/build.gradle.kts, ktor-client/ktor-client-plugins/ktor-client-tracing/ktor-client-tracing-stetho/build.gradle.kts, ktor-client/ktor-client-tests/build.gradle.kts, ktor-server/ktor-server-jetty-jakarta/build.gradle.kts, ktor-server/ktor-server-test-base/build.gradle.kts, ktor-server/ktor-server-test-host/build.gradle.kts, ktor-server/ktor-server-test-suites/build.gradle.kts, ktor-shared/ktor-junit/build.gradle.kts, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-tests/build.gradle.kts, settings.gradle.kts
**Subsystem**
Infrastructure
**Motivation**
Isolate kotlinx.train configuration better and fix versions substitution
=> Fix configuration for kotlinx.train

ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/ConnectErrorsTest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
**Subsystem**
Client, HttpRequestRetry + CIO
**Motivation**
[KTOR-7618](https://youtrack.jetbrains.com/issue/KTOR-7618) Chunked transfer encoding failure not caught with retry
**Solution**
The issue is caused by the deferred processing of the response body, which also defers the failure to stream the response body.  To trigger the exception within the retry handling block, we simply reference the body to ensure that it can be read.  This can only be leveraged when the body is saved, so there is a check for that as well.
=> KTOR-7618 Fix for chunked transfer disconnect not retried

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/WasmJsClientEngine.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/utils/JsUtils.kt
**Subsystem**
Client, JS
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-6158
**Solution**
* Use `import` global function for ESM
**Related PRs**
* #4422
* #4434
=> KTOR-6158 ESM support for `WebSocket`

ktor-server/ktor-server-core/common/test/io/ktor/server/http/ParametersTest.kt, ktor-server/ktor-server-core/common/test/io/ktor/server/http/PathNormalizationTest.kt, ktor-server/ktor-server-core/common/test/io/ktor/server/routing/RouteTest.kt, ktor-server/ktor-server-core/common/test/io/ktor/server/utils/CopyOnWriteHashMapTest.kt
**Subsystem**
server
**Motivation**
Package directive does not match the file location
**Solution**
Fixed names of test packages according to location
=> Fix names of test packages according to location

ktor-network/api/ktor-network.api, ktor-network/api/ktor-network.klib.api, ktor-network/common/src/io/ktor/network/sockets/UDPSocketBuilder.kt, ktor-network/jvmAndPosix/test/io/ktor/network/sockets/tests/UDPSocketTest.kt
**Motivation**
[KTOR-7663](https://youtrack.jetbrains.com/issue/KTOR-7663)
=> KTOR-7663 Add `bind` overload for UDPSocketBuilder

buildSrc/src/main/kotlin/JsConfig.kt, buildSrc/src/main/kotlin/Publication.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, buildSrc/src/main/kotlin/internal/String.kt
**Subsystem**
Infrastructure
**Motivation**
[KTOR-7738](https://youtrack.jetbrains.com/issue/KTOR-7738) Simplify configuration of publishing for new targets
**Solution**
Add aggregating tasks for publishing a "target family" using a single task.
Next step: https://github.com/ktorio/ktor-build/pull/102
=> KTOR-7738 Add aggregating publish tasks

build.gradle.kts, buildSrc/build.gradle.kts, gradle/libs.versions.toml, ktor-io/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-jte/build.gradle.kts
**Subsystem**
Build Infrastructure
**Motivation**
[KTOR-7795](https://youtrack.jetbrains.com/issue/KTOR-7795) Use version catalogs for all dependencies
**Solution**
Find and replace all places where dependencies were added using string notation.
=> KTOR-7795 Use version catalogs everywhere

ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/CommonClientTestUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-client/ktor-client-tests/js/src/io/ktor/client/tests/utils/ClientLoaderJs.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientLoaderJvm.kt, ktor-client/ktor-client-tests/posix/src/io/ktor/client/tests/utils/ClientLoaderNative.kt, ktor-client/ktor-client-tests/wasmJs/src/io/ktor/client/tests/utils/ClientLoaderWasm.kt, ktor-io/common/src/io/ktor/utils/io/ByteChannel.kt, ktor-server/ktor-server-cio/jvmAndPosix/test/io/ktor/tests/server/cio/CIOEngineTest.kt, ktor-server/ktor-server-test-base/common/src/io/ktor/server/test/base/BaseTest.kt, ktor-server/ktor-server-test-base/jsAndWasmShared/src/io/ktor/server/test/base/BaseTest.jsAndWasmShared.kt, ktor-server/ktor-server-test-base/jvm/src/io/ktor/server/test/base/BaseTestJvm.kt, ktor-server/ktor-server-test-base/posix/src/io/ktor/server/test/base/BaseTestNix.kt, ktor-server/ktor-server-test-suites/common/src/io/ktor/server/testing/suites/HttpServerCommonTestSuite.kt
[KTOR-4534](https://youtrack.jetbrains.com/issue/KTOR-4534) Fix Flaky Tests
=> KTOR-4534 Add retry for flaky tests

.devcontainer/Dockerfile, .devcontainer/cmdline-tools-package.xml, .devcontainer/devcontainer.json
**Subsystem**
Infrastructure
**Motivation**
[KTOR-7823](https://youtrack.jetbrains.com/issue/KTOR-7823) Create a dev container for Ktor
=> KTOR-7823 Add Android build tools to dev container

ktor-server/ktor-server-servlet-jakarta/jvm/src/io/ktor/server/servlet/jakarta/ServletWriter.kt, ktor-server/ktor-server-servlet-jakarta/jvm/test/io/ktor/tests/servlet/jakarta/ServletWriterJakartaTest.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletWriter.kt, ktor-server/ktor-server-servlet/jvm/test/io/ktor/tests/servlet/ServletWriterTest.kt, ktor-server/ktor-server-tests/build.gradle.kts, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CompressionTest.kt
Fix [KTOR-7904 ServletResponseBody is corrupted due to the wrong offset](https://youtrack.jetbrains.com/issue/KTOR-7904)
=> KTOR-7904 Fix Servlet response body is corrupted due to the wrong offset

ktor-server/ktor-server-plugins/ktor-server-swagger/api/ktor-server-swagger.api, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/Swagger.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/SwaggerConfig.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test/io/ktor/server/plugins/swagger/SwaggerTest.kt
**Subsystem**
Server, Swagger
**Motivation**
[KTOR-7893 Swagger UI: Missing Favicon while browsing the UI](https://youtrack.jetbrains.com/issue/KTOR-7893)
=> KTOR-7893 Add favicon to Swagger UI

gradle/libs.versions.toml, kotlin-js-store/yarn.lock, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt
=> KTOR-7921 Bump ws version to 8.18.0

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/CloseHookByteWriteChannel.kt, ktor-utils/jvm/test/io/ktor/tests/utils/FileChannelTest.kt
See https://github.com/ktorio/ktor/pull/4503
Merging this to master so it is picked up in the next patch.
=> KTOR-7845 Merge fix for file byte channel close

ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
**Subsystem**
ktor-http
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-4816
**Solution**
Added `tel` scheme support
=> KTOR-4816: UrlBuilder: support tel scheme

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt, ktor-http/common/src/io/ktor/http/HttpMethod.kt
**Subsystem**
ktor-http
**Motivation**
[KTOR-8011](https://youtrack.jetbrains.com/issue/KTOR-8011)
**Solution**
Overrided HttpMethod toString() method
=> KTOR-8011: fix HTTP method is logged with the class name

ktor-server/ktor-server-cio/api/ktor-server-cio.api, ktor-server/ktor-server-cio/api/ktor-server-cio.klib.api, ktor-server/ktor-server-cio/common/src/io/ktor/server/cio/EngineMain.kt, ktor-server/ktor-server-jetty-jakarta/api/ktor-server-jetty-jakarta.api, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/EngineMain.kt, ktor-server/ktor-server-jetty/api/ktor-server-jetty.api, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/EngineMain.kt, ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/EngineMain.kt, ktor-server/ktor-server-tomcat-jakarta/api/ktor-server-tomcat-jakarta.api, ktor-server/ktor-server-tomcat-jakarta/jvm/src/io/ktor/server/tomcat/jakarta/EngineMain.kt, ktor-server/ktor-server-tomcat/api/ktor-server-tomcat.api, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/EngineMain.kt
**Subsystem**
ktor-server
**Motivation**
[KTOR-8123](https://youtrack.jetbrains.com/issue/KTOR-8123)
**Solution**
added netty EnginMain createServer function
=> KTOR-8123: add EngineMain createServer function

ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-plugins/ktor-client-logging/jvm/test/io/ktor/client/plugins/logging/OkHttpFormatTest.kt
https://youtrack.jetbrains.com/issue/KTOR-8218
=> KTOR-8218 Write request and response logs as single messages

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/ConnectionPipeline.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/ConnectErrorsTest.kt
**Subsystem**
CIO Client
**Motivation**
[KTOR-8205](https://youtrack.jetbrains.com/issue/KTOR-8205) CIO: Exception "Failed to parse HTTP response: the server prematurely closed the connection"
=> KTOR-8205: Wrap EOFException with ClosedReadChannelException

gradle.properties
Update gradle properties version.
=> Version 3.1.3-SNAPSHOT

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
**Subsystem**
ktor-server
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-8416
**Solution**
fixed Accept route selector evaluation
=> KTOR-8416: fix Accept route selector evaluation

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-apache5/jvm/src/io/ktor/client/engine/apache5/ApacheRequestProducer.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/HttpClientTest.kt
**Subsystem**
Client, ktor-client-apache5
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-8318
**Solution**
Fixed entity producer handler
=> KTOR-8318: fix apache entity producer handler

build-logic/src/main/kotlin/ktorbuild/internal/publish/ValidatePublishedArtifactsTask.kt
**Subsystem**
Build infrastructure
**Motivation**
Follow-up for #4791
The task is designed to be used only with a single publlish task
**Solution**
Bring back the check that the task is used with exactly one task, but show warning instead of throwing an exception.
Skip the task and do not configure its dependencies if it is used improperly
=> Show warning if ValidatePublishedArtifactsTask is used improperly

ktor-client/ktor-client-core/api/ktor-client-core.klib.api, ktor-client/ktor-client-core/js/src/io/ktor/client/JsRequestUtils.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/Js.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/JsRequestUtils.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/Js.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/WasmJsClientEngine.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-test-server/src/main/kotlin/test/server/tests/Cookies.kt
Fix [KTOR-539](https://youtrack.jetbrains.com/issue/KTOR-539) Ability to use browser cookie storage
=> KTOR-539 Add ability to set fetch options

CONTRIBUTING.md, gradle.properties, teamcity.default.properties
**Subsystem**
Infrastructure
**Motivation**
[KTOR-8504](https://youtrack.jetbrains.com/issue/KTOR-8504) Gradle throws OOM on IDE sync
**Solution**
Increase `Xmx`, but override its value on CI via `teamcity.default.properties`
=> Fix OOM on IDE sync

ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
Fix [KTOR-5708](https://youtrack.jetbrains.com/issue/KTOR-5708) Url class mangles data URLs
=> KTOR-5708 Add data url support

ktor-server/ktor-server-plugins/ktor-server-di/jvm/src/io/ktor/server/plugins/di/utils/Types.jvm.kt, ktor-server/ktor-server-plugins/ktor-server-di/jvm/test/io/ktor/server/plugins/di/DependencyInjectionJvmTest.kt
**Subsystem**
Server, DI
**Motivation**
[KTOR-8511](https://youtrack.jetbrains.com/issue/KTOR-8511) DI type parameter with bounds not inferred
**Solution**
The problem is from validating type boundaries on type parameters that have type parameters themselves.  Since we know the original type matches the expected type parameter's type parameter, we can assume that its supertypes will also match, so in this case we can just use the star projection of the base type for matching.  Apologies, I don't think I can simplify this description 😅
=> KTOR-8511 Fix type boundary resolution issue

ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/Content.kt
https://youtrack.jetbrains.com/issue/KTOR-8581
=> KTOR-8581 Avoid passing the max parameter of the decode method

ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/AuthenticationInterceptors.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/test/io/ktor/tests/auth/OAuth2Test.kt
https://youtrack.jetbrains.com/issue/KTOR-4420
=> KTOR-4420 OAuth2: Cache body of form requests to make it available in route handler

ktor-client/ktor-client-core/common/src/io/ktor/client/content/ObservableContent.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/BodyProgressTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/Content.kt
https://youtrack.jetbrains.com/issue/KTOR-6790
=> KTOR-6790 Fix ObservableContent by avoid caching the delegate's channel

ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-network/common/test/io/ktor/network/sockets/tests/TCPSocketTest.kt
https://youtrack.jetbrains.com/issue/KTOR-8618
=> KTOR-8618 Fix race condition in ReaderJob.flushAndClose

build-logic/src/main/kotlin/ktorbuild.publish.gradle.kts, build-logic/src/main/kotlin/ktorbuild/internal/publish/PublishTasks.kt, build-logic/src/main/kotlin/ktorbuild/internal/publish/Repositories.kt, gradle/libs.versions.toml
Fixed target repository inference and added more strict validation.
=> Fix publishing (again)

gradle.properties, ktor-client/ktor-client-core/common/src/io/ktor/client/request/builders.kt, ktor-client/ktor-client-core/common/test/BuildMethodsTest.kt
https://youtrack.jetbrains.com/issue/KTOR-8636
=> KTOR-8636 Set HTTP method after executing request builder

ktor-server/ktor-server-plugins/ktor-server-sse/common/test/io/ktor/server/sse/ServerSentEventsTest.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/common/src/io/ktor/server/testing/TestApplicationResponse.kt, ktor-server/ktor-server-test-host/common/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/common/test/TestApplicationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-7910
=> KTOR-7910 Fix WriteChannelContent streaming in testApplication

build-logic/src/main/kotlin/ktorbuild/targets/CiConfig.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt
The task flag should fix [this problem](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixJavaScriptChromeNodeJs/365329?buildTab=log&linesState=512&logView=flowAware&focusLine=46510).
And there seems to be some [flakiness with a couple of tests](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixJavaScriptChromeNodeJs/365329?buildTab=log&linesState=512&logView=flowAware&focusLine=46510).
=> Resolve flaky test issues with JS

build-logic/src/main/kotlin/ktorbuild.compatibility.gradle.kts
After merging https://github.com/ktorio/ktor-build/pull/141 this task is not needed anymore
=> KTOR-8790 Remove apiCheck task

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/builders.kt
**Subsystem**
Client, SSE
**Motivation**
[KTOR-8440](https://youtrack.jetbrains.com/issue/KTOR-8440)
=>  KTOR-8440 Add a note about SSE session lifetime in KDoc
