ktorio/ktor

ktor-core/src/org/jetbrains/ktor/application/ApplicationResponse.kt, ktor-core/src/org/jetbrains/ktor/http/Application.kt, ktor-core/src/org/jetbrains/ktor/testing/TestHost.kt, ktor-core/test/org/jetbrains/ktor/tests/application/HandlerTest.kt, ktor-netty/src/org/jetbrains/ktor/netty/NettyApplicationResponse.kt, ktor-samples/ktor-samples-json/src/org/jetbrains/ktor/samples/json/JsonApplication.kt, ktor-servlet/src/org/jetbrains/ktor/servlet/ServletApplicationResponse.kt
`ResponseHeaders` class encapsulates headers response logic including intercepting, reduces code duplication in host implementations
- Functions `header(name)`, `header(name, value)` and `interceptHeaders` are removed and added property `headers: ReponseHeaders` that contains corresponding functions: `get(name)`, `append(name, value)` and `intercept(handler)`
- Notice `ResponseHeaders.append(name, value)` is self-descriptive so it is clear for user that it appends header rather than set/replace existing value(s)
- Function `contians` function useful to test whether we have header set. For example:
```
if (HttpHeaders.ContentType !in response.headers) {
response.contentType(ContentType.Any)
}
```
- Function `values(name)` provides a list of header values
- Function `allValues()` constructs …
=> Migrate to append-only response headers to support multiple headers

ktor-hosts/ktor-jetty/src/org/jetbrains/ktor/jetty/JettyApplicationHost.kt, ktor-hosts/ktor-jetty/test/MultipleDispatchOnTimeout.kt
Servlet containers with async context will redispatch after a timeout. In Jettys case the default seems to be 30 secs. I think it is part of the three steps discribed here: https://docs.oracle.com/javaee/6/api/javax/servlet/AsyncContext.html
The provided testcase fails without the fix.
This might also be the cause of what we are seeing in #52
=> Fix multiple dispatch problem with async servlet timeouts.

ktor-samples/ktor-samples-websocket/src/org/jetbrains/ktor/samples/chat/ChatApplication.kt, ktor-samples/ktor-samples-websocket/src/org/jetbrains/ktor/samples/chat/ChatServer.kt
Fixes two issues in the Chat (websocket) sample:
1. On startup (browser connecting), the application fails with
```
500 Internal Server Error
IllegalArgumentException: Couldn't instantiate type class org.jetbrains.ktor.samples.chat.Session for parameters [userId]
```
2. The '/who' command displays hash IDs instead of names.
=> Chat sample fix

ktor-features/ktor-freemarker/src/org/jetbrains/ktor/freemarker/FreeMarker.kt, ktor-features/ktor-freemarker/test/org/jetbrains/ktor/tests/fm/FreeMarkerTest.kt
In a typical use case, users don't want to generate ETag for HTML templates.
=> ktor-freemarker: Rendering freemarker template without etag

ktor-core-tests/test/org/jetbrains/ktor/tests/http/CompressionTest.kt, ktor-core/src/org/jetbrains/ktor/features/Compression.kt
Preserve HTTP status of compressed responses by passing the original response status to the new one.
Before this changes, every CompressedResponse and CompressedWriteResponse would return a 200 Ok status because their status was never defined.
A new test case has been added to avoid regressions.
=> Compression: preserve HTTP status

ktor-samples/ktor-samples-ssl-http2/resources/application.conf
without this parameter, I got:
```
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.collections.ArraysKt___ArraysKt.toList, parameter $receiver
at kotlin.collections.ArraysKt___ArraysKt.toList(_Arrays.kt)
at org.jetbrains.ktor.netty.NettyChannelInitializer.<init>(NettyChannelInitializer.kt:27)
at org.jetbrains.ktor.netty.NettyApplicationHost.<init>(NettyApplicationHost.kt:25)
at org.jetbrains.ktor.netty.DevelopmentHost.main(CommandLine.kt:9)
```
=> fix example adding a required paramter

ktor-core-tests/test/org/jetbrains/ktor/tests/session/AutoSerializerTest.kt, ktor-core/src/org/jetbrains/ktor/sessions/SessionSerializerReflection.kt
In my current project, I want to store a `UUID` within a session object, finding that those are not supported during serialization. Instead of fiddling with `String`s, I would rather be very happy to have `UUID`s supported.
So I added support for `UUID`s to `SessionSerializerReflection`, quite along the lines the recently added support for enums.
I hope you like the change and accept it.
Thank you!
=> Add support for UUIDs in session serialization

ktor-features/ktor-freemarker/src/org/jetbrains/ktor/freemarker/RespondTemplate.kt, ktor-features/ktor-freemarker/test/org/jetbrains/ktor/tests/fm/FreeMarkerTest.kt
This PR adds an extension method to the `ApplicationCall` interface which provides a quick and easy way to respond to a request with a Freemarker template.
=> Respond with Freemarker Template

ktor-server/ktor-server-host-common/src/io/ktor/server/engine/ApplicationEngine.kt
Fixed the ApplicationEngine.start() documentation which could create confusion.
=> Fix documentation

README.md
The example on the README no longer works. This commit updates the imports by referring to the example here: http://ktor.io/quickstart/application.html
With this fix, the example on the README should work now!
=> Fixes imports in the example on README

ktor-features/ktor-auth/src/io/ktor/auth/OAuth2.kt, ktor-features/ktor-auth/test/io/ktor/tests/auth/OAuth2.kt
Fixes a bug with double encoding of OAuth2 scope parameter
=> Fix bug with double encoding of OAuth2 scopes

ktor-features/ktor-auth/src/io/ktor/auth/DigestAuth.kt
According to **RFC 2617 (Section 3.2.2.1)**, if `qop` is not present, it should follow the older **RFC 2069** and the response should be in form of:
`MD5(HA1:nonce:HA2)`
instead of:
`MD5(HA1:nonce:nonceCount:cnonce:qop:HA2)`
The current implementation of Digest Authorization does not work in Chrome 65.0.3325.181 due to not following the RFC.
=> Digest Authentication not working in Chrome due to not following RFC 2617

ktor-features/ktor-auth-jwt/src/io/ktor/auth/jwt/JWTAuth.kt, ktor-features/ktor-auth-jwt/test/io/ktor/auth/jwt/JWTAuthTest.kt
This should fix #397 required for supporting realworld with ktor https://github.com/gothinkster/node-express-realworld-example-app/blob/ba04b70c31af81ca7935096740a6e083563b3a4a/routes/auth.js#L5
=> JWT: Support multiple schemes in addition to Bearer

ktor-features/ktor-auth/src/io/ktor/auth/BasicAuth.kt, ktor-features/ktor-auth/test/io/ktor/tests/auth/BasicAuthTest.kt
This change adds validation for the scheme and contents when trying to
parse the HTTP Basic credentials from the Authorization HTTP header.
This prevents the HTTP Basic protected routes from crashing when the
user sends an Authorization header with a scheme other than "Basic" or
when the user sends a malformed Base64 string.
See #414 for the responsible issue.
=> Validate scheme and contents in authorization header

ktor-http/test/io/ktor/tests/http/HeadersTest.kt, ktor-utils/src/io/ktor/util/StringValues.kt
The `fun headersOf(vararg pairs: Pair<String, List<String>>): Headers` signature is not case-insensitve.
=> Fixes headersOf case insensitive issue

ktor-features/ktor-auth-jwt/src/io/ktor/auth/jwt/JWTAuth.kt, ktor-features/ktor-auth-jwt/test/io/ktor/auth/jwt/JWTAuthTest.kt
defines a new verifier that does not need an issuer, to address scenarios where the issuer may vary for a single set of JWKS (like in AzureAD)
=> add verify configuration that does not require an issuer, just the JwkProvider (#437)

ktor-features/ktor-auth-jwt/src/io/ktor/auth/jwt/JWTAuth.kt, ktor-features/ktor-auth-jwt/test/io/ktor/auth/jwt/JWTAuthTest.kt
Per RFC7517, alg should be optional. Spring fixes this by defaulting to RS256 if no alg is given.
=> default to RS256 as algorithm if JWK does not optionally provide one (#434)

ktor-features/ktor-jackson/src/io/ktor/jackson/JacksonConverter.kt, ktor-features/ktor-jackson/test/io/ktor/tests/jackson/JacksonTest.kt
Proposal: for a web server I think it is better to provide consistency by default. So this proposal overrides the Jackson default to use `LF`(`\n`) instead of platform dependant.
=>  Jackson uses `line.separator` by default causing issues in windows

ktor-server/ktor-server-test-host/src/io/ktor/server/testing/TestApplicationRequest.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/http/TestEngineMultipartTest.kt
The problem was that File input streams read as `ISO-8859-1`, but later the whole content was encoded as UTF-8.
This PR tries to handle it as a binary stream so no decoding+encoding is required, and calculates it with a writer and pipes the content, so if the input comes from a large File for testing, no need to read the whole content in memory.
=> Fixes binary data in multipart tests `TestApplicationRequest.setBody`

ktor-server/ktor-server-core/src/io/ktor/content/StaticContentResolution.kt
Fixes #492 
Added range check before calling `substring` to extract the extension
of a file path.
As with #491, not sure if/how this can be unit-tested, if you have any idea how to achieve this I'll gladly add the test case(s).
=> Fix for #492

ktor-server/ktor-server-host-common/src/io/ktor/server/engine/CommandLine.kt, ktor-server/ktor-server-host-common/test-resources/applicationWithEnv.conf, ktor-server/ktor-server-host-common/test/io/ktor/tests/hosts/CommandLineTest.kt
fixes #374
It was hard to test that the resolution actually pulls in env vars. Without the `.resolve()` the test blows up, so I still think it's a worthwhile test, just not the most thorough. Open to suggestions.
=> resovle config file in command line env

ktor-features/ktor-auth-jwt/src/io/ktor/auth/jwt/JWTAuth.kt, ktor-features/ktor-auth-jwt/test/io/ktor/auth/jwt/JWTAuthTest.kt
Found and fixed a little bug when kid not found in jwks and when invalid bearer token used on verification of jwt (throws and causes 500 instead of 401)
=> Handling jwt exceptions for missing keyId and failure to decode token

ktor-client/ktor-client-core/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/src/io/ktor/client/engine/Utils.kt, ktor-http/ktor-http-cio/src/io/ktor/http/cio/HttpHeadersMap.kt, ktor-http/ktor-http-cio/src/io/ktor/http/cio/Pipeline.kt, ktor-http/src/io/ktor/http/HttpHeaders.kt, ktor-http/src/io/ktor/http/HttpMessageProperties.kt, ktor-server/ktor-server-cio/test/io/ktor/tests/server/cio/CIOHttpClientTest.kt, ktor-server/ktor-server-core/src/io/ktor/response/ResponseHeaders.kt, ktor-server/ktor-server-host-common/src/io/ktor/server/engine/BaseApplicationResponse.kt, ktor-server/ktor-server-test-host/src/io/ktor/server/testing/EngineTestSuite.kt, ktor-utils/src/io/ktor/util/StringValues.kt
- fix duplicate `Content-Length` header handling at CIO server
- prohibit setting unsafe headers for client request
- fix `testClosedConnection` to pass faster
- fix Bad Request processing at CIO server
- fix channel write error wrapping for `OutgoingContent.WriteChannelContent`
=> Client and server improvements

ktor-server/ktor-server-core/src/io/ktor/features/OriginConnectionPoint.kt, ktor-server/ktor-server-test-host/src/io/ktor/server/testing/EngineTestSuite.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/HSTSTest.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/HttpsRedirectFeatureTest.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/OriginConnectionPointTest.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/http/URLBuilderTest.kt
To be consistent with `ForwardedHeaderSupport`.
The alternative is to rename `ForwardedHeaderSupport` to `ForwardedHeadersSupport`.
Documentation was wrong because of copy-pasting `ForwardedHeaderSupport` adding an `X`: https://github.com/ktorio/ktorio.github.io/commit/3985523155489d17c8ac623595629e2e1ef5c653
But would be nice if they are consistent.
=> Rename `XForwardedHeaderSupport` to `XForwardedHeadersSupport`

ktor-client/ktor-client-android/test/io/ktor/client/engine/android/CommonTests.kt, ktor-client/ktor-client-apache/test/io/ktor/client/engine/apache/CommonTests.kt, ktor-client/ktor-client-cio/test/io/ktor/client/engine/cio/CommonTests.kt, ktor-client/ktor-client-core/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-okhttp/test/io/ktor/client/engine/okhttp/CommonTests.kt, ktor-client/ktor-client-tests/src/io/ktor/client/tests/HttpClientTest.kt
Copy the existing config in HttpClient#config, as the docs specify.
Prior to this all features and interceptors were lost.
=> ktor-client-core: Copy existing config in HttpClient#config

ktor-client/ktor-client-core/src/io/ktor/client/request/forms/formDsl.kt, ktor-client/ktor-client-tests/src/io/ktor/client/tests/ContentTest.kt
The first commit fixes `Content-Disposition: name="fieldName";filename="filename.jpg";form-data` to `Content-Disposition: form-data;name="fieldName";filename="filename.jpg"`. The rationale is [this MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_header_for_a_multipart_body).
About the second commit, I think it's not bad to treat filename header specially.
=> Add append method for form-data filename

ktor-server/ktor-server-core/src/io/ktor/sessions/Sessions.kt, ktor-server/ktor-server-test-host/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/testing/TestApplicationEngineTest.kt
* Added `TestApplicationEngine.cookiesSession` feature to keep cookie
* Added a `TestApplicationEngine.hookRequests` mechanism to hook requests in a scope
* Added a CurrentSession.getOrSet convenience method.
=>  Added `TestApplicationEngine.cookiesSession` to keep cookies between test requests

ktor-http/src/io/ktor/http/ContentTypes.kt
This Content Type is part of this RFC:
https://tools.ietf.org/html/rfc4180
=> RFC4180: Add ContentType for text/csv

ktor-client/ktor-client-core/src/io/ktor/client/call/HttpClientCall.kt, ktor-client/ktor-client-core/src/io/ktor/client/engine/HttpClientEngineConfig.kt, ktor-client/ktor-client-core/src/io/ktor/client/response/HttpResponse.kt, ktor-client/ktor-client-core/src/io/ktor/client/response/HttpResponseConfig.kt
Some HTTP servers maybe send a Content-Type header with MIME-type only( i.e. without charset), e.g. `text/plain`, `application/json`, etc. And if the real encoding of the response content is ISO-8859-1, the HTTP client now can handle the text/JSON correctly. But if the content is other encoding (e.g. UTF-8), the result of `HttpClient.get<String>` or `HttpClient.get<AComplexObject>` may contains messy code.
This change is for solving the above problem manually. Added a `HttpResponseConfig` property to the `HttpClientEngineConfig` and this enabled to set a custom default charset of response content rather than the hard coded ISO-8859-1.
e.g. To request a server URL which respond a json contains **UTF-8** strings with the Content-Type `application/json`, we can configure the HTTP client as …
=> Introduce HttpResponseConfig for client & enable to set custom default response charset rather than ISO-8859-1

ktor-http/ktor-http-jvm/test/io/ktor/tests/http/URLBuilderJvmTest.kt, ktor-http/src/io/ktor/http/URLBuilder.kt, ktor-http/src/io/ktor/http/URLProtocol.kt, ktor-http/test/io/ktor/tests/http/URLBuilderTest.kt, ktor-http/test/io/ktor/tests/http/UrlTest.kt
See #561 for the original issue discussion
This modification removes the behavior on the [URLBuilder] to no longer set the `port` when explicitly specifying a `protocol`.
```kotlin
val url = URLBuilder().apply {
port = 8080
protocol = URLProtocol.HTTPS
}.build()
println(url.port) // 443
```
```kotlin
val url = URLBuilder().apply {
port = 8080
protocol = URLProtocol.HTTPS
}.build()
println(url.port) // 8080
```
```kotlin
val url = URLBuilder().apply {
protocol = URLProtocol.HTTPS
println(port) // 443, changed by `protocol =`
}.build()
println(url.port) // 443
```
```kotlin
val url = URLBuilder().apply {
protocol = URLProtocol.HTTPS
println(port) // -1, no longer changed by `protocol =`
}.build()
println(url.port) // 443
```
```kotlin
val url = URLBuilder().apply { …
```
=> ktor-http: URLBuilder isolate port and the protocol's defaultPort

ktor-server/ktor-server-core/src/io/ktor/features/StatusPages.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/StatusPageTest.kt
Run a nested `coroutineScope { }` block to gather all children's job completions and re-throw if failed. Otherwise job failure are propagated to an engine so status page feature has no chance to handle it
=> Fix StatusPages to handle child job failures (#646)

ktor-client/ktor-client-android/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-android/src/io/ktor/client/engine/android/AndroidEngineConfig.kt, ktor-client/ktor-client-android/test/io/ktor/client/engine/android/AndroidHttpsTest.kt, ktor-client/ktor-client-android/test/io/ktor/client/engine/android/AndroidProxyTest.kt
First commit adds proxy configuration to `AndroidEngineConfig`. On Android platform `AndroidClientEngine` is the only choice and proxy feature is quite useful to inspect http traffic. So I request this feature.
Second commit permits `HttpsURLConnection` manipulation. Although I don't need it right now, I thought someone can need it. But it can be dangerous when an user calls inherited methods from `HttpConnection` etc. I have no refutation even if this commit is rejected.
=> Add some entries to AndroidEngineConfig

ktor-client/ktor-client-core/ktor-client-core-js/src/io/ktor/client/engine/js/JsUtils.kt
Requests do not currently send content headers.
=> Properly construct request headers in JS engine

gradle.properties, ktor-server/ktor-server-core/src/io/ktor/features/Compression.kt, ktor-server/ktor-server-servlet/src/io/ktor/server/servlet/BlockingServlet.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/CompressionTest.kt, ktor-utils/ktor-utils-jvm/src/io/ktor/util/Deflater.kt
- Upgrade Kotlin (1.3.0-rc-146) and kotlinx.io (to get migration fixes as well)
- Modify `CompressionEncoder` interface (breaking change), mark it as experimental
=> Migrate to kotlinx.coroutines 1.0.0-RC1

ktor-features/ktor-gson/build.gradle
The version here is hardcoded and does not correspond to the version defined in the global `gradle.properties` [here](https://github.com/ktorio/ktor/blob/99aaf42a9210dbf25c500a980490d94ba3667435/gradle.properties#L38).
I suggest the feature should use the global version of gson, the same way [another client feature](https://github.com/ktorio/ktor/blob/99aaf42a9210dbf25c500a980490d94ba3667435/ktor-client/ktor-client-features/ktor-client-json/ktor-client-gson/build.gradle#L4) does.
Also, in the current state dependency resolution strategy `failOnVersionConflict` actually fails if the two features are used together.
=> Gson version should be consistent

ktor-server/ktor-server-host-common/src/io/ktor/server/engine/ApplicationEngine.kt
Fix error in documentation which wrongly claims that the gradePeriod is in millis. In reality both the gradeperiod and the timeout is applied to the timeUnit specified as the third argument.
If one specifies `stop(1_000, 20, TimeUnit.SECONDS)`an `java.lang.IllegalArgumentException: timeout: 20 (expected >= quietPeriod (1000))` is thrown.
=> Fix documentation inaccuracy in stop()

ktor-server/ktor-server-core/src/io/ktor/features/CallLogging.kt, ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/CallLoggingTest.kt
This will make is possible to use `CallLogging` feature with a customized logger, e.g.
```kotlin
install(CallLogging) {
logger = LoggerFactory.getLogger("access.log")
}
```
Edit force-push: realised test was in error, updated with fix
=> Allow configuring Logger instance for CallLogging

ktor-client/ktor-client-features/ktor-client-logging/ktor-client-logging-jvm/build.gradle.kts
Simple change to swap the slf4j implementation with the API.  I used the same slf4j-api version from jvm.gradle.
=> Update slf4j dependency in JVM HTTP Client Logging Feature

ktor-client/ktor-client-features/ktor-client-websocket/jvm/src/io/ktor/client/features/websocket/ClientSessions.kt
The bug is caused by the use of overriding to set the masking property to true, which has no effect on the actual session delegate. 
An init {} block should be used to initialise the "masking" property to true. This also preserves the delegation mechanism to work properly. Changing the masking value of the wrapper class will also be propagated to the underlying delegate.
=> Fixed issue #827: WebSocket masking cannot be enabled

ktor-http/common/src/io/ktor/http/HttpUrlEncoded.kt, ktor-http/common/src/io/ktor/http/Query.kt, ktor-http/common/test/io/ktor/tests/http/QueryParametersTest.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
I noticed that you could add a key with an empty list to the `StringValues` class. I used this to convey that the key has no value and should not append the =. This means you can still get the = by setting the value to the empty string. An alternative solution would be to allow null values, and use that to convey no value. But that would require a major refactoring of the `StringValues` class and its  dependencies.
Fixes #818
=> http-client UrlBuilder adds = to query parameters without value

ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngineExtended.kt, ktor-client/ktor-client-mock/jvm/test/io/ktor/client/tests/mock/MockEngineExtendedTests.kt
Related issue - https://github.com/ktorio/ktor/issues/913
=> MockEngine version which favors execution order and returns processed requests

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/ContentTest.kt
Fixes #766 
IMO it's enough to add `ContentType`, that covers like 99% of upload scenarios now. For all other scenarios we can use `append(key, headers,, bodyBuilder)`
=> Add optional contentType to formDsl

ktor-features/ktor-jackson/build.gradle
Security update for `jackson-databind`:
https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=+jackson-databind&search_type=all
Closes #952
=> [SECURITY-FIX] Update to jackson version 2.9.8

ktor-utils/jvm/src/io/ktor/util/date/DateJvm.kt, ktor-utils/jvm/test/io/ktor/tests/utils/DateJvmTest.kt
Solves https://github.com/ktorio/ktor/issues/984
=> Fix: [GMTDate] .toJvmDate() uses current date instead of given date.

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt
I encountered an issue with the Netty pipeline where it's possible to keep a connection open indefinitely when sending a request with a JSON body (parsed by Jackson) that doesn't complete, for example by using Telnet to send a request but never closing it (I have hit this issue in real world use too though).
When using ktor in an environment where it will only handle a single connection at a time, this causes it to entirely stop responding to new requests because the stream is kept open waiting for the partial request to complete. 
This PR adds a `ReadTimeoutHandler` to Netty which terminates the connection after a configurable timeout, as the pipeline already does for writes. I'm happy to make changes to the PR if I've done anything nasty  :)
Thanks!
=> Added ReadTimeoutHandler to Netty pipeline.

ktor-features/ktor-auth/jvm/src/io/ktor/auth/DigestAuth.kt
Added provider´s algorithm name to the HttpAuthHeader.digestAuthChallenge method so it requests the algorithm user sets instead of the default MD5 all the time.
=> Pass providers algorithm name to the auth challenge

ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransportTransformer.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/sessions/SessionTransportTransformerKtTest.kt
I've found that if you add 2 different transformers, session reading breaks because of incorrect transformations order. Here is simple fix with tests.
=> Fix SessionTransportTransformers application order

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/EngineMain.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/EngineMain.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/EngineMain.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/EngineMain.kt
Remove 'development' word in comments of EngineMain so not to confuse.
=> Remove 'development' word in comments of EngineMain

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/features/websocket/JsWebSocketSession.kt
I'm encountered with error `CloseEvent is undefined` in nodejs environment, so just omit types here.
Also delay connection until event handlers are installed, otherwise it may drop first incoming message without a shame.
=> Fix client ws in nodejs

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/Routing.kt
Move all inner logic of Routing to separated class to allow user use routing feature in detached mode.
Also make interceptor function public to use it independently of `install(Routing)`
Main motivation of that pull request is to allow user use dynamic routing
=> Remove private modifier from Routing.interceptor

ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/ServerInitializer.kt
**Subsystem**
Server
**Motivation**
Enable Jetty server to use arbitrary customized HTTP connectors. #1182 .
**Solution**
exchange the order of `configuration.configureServer(this)` and `initializeServer(environment)`.
=> Enable Jetty server to use arbitrary customized HTTP connectors.

ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CORSTest.kt
**Subsystem**
Server, CORS feature
**Motivation**
Accidentally we have wrong headers accepted by default by the CORS feature. The other problem is that it is not providing `Vary` header when no `Origin` header specified that is not exactly correct since providing `Origin` header affects response headers so caches should also consider the header value as well (unless all origins are allowed using `*`).
**Solution**
- Provide `Vary` header in more cases.
- Separate default request and response headers (called _simple_ in the spec)
=> CORS improvements

ktor-client/ktor-client-features/ktor-client-json/ktor-client-jackson/jvm/src/io/ktor/client/features/json/JacksonSerializer.kt
**Subsystem**
ktor-client:ktor-client-features:ktor-client-json:ktor-client-jackson
**Motivation**
Pr adds custom jackson mapper, now people can do
```kotlin
val client = HttpClient(HttpClientEngine) {
install(JsonFeature) {
serializer = JacksonSerializer(ObjectMapper())
}
}
```
refs #1208 
Link for docs pr https://github.com/ktorio/ktorio.github.io/pull/204
**Solution**
I deleted one primary constructor and added to constructor in body of class with argument of previous constructor and constructor with objectMapper parameter to init backend value.
=> Add constructor for custom mapping with Jackson

CONTRIBUTING.md
**Motivation**
Typo in the Contribution Guideline. See [issue](https://github.com/ktorio/ktor/issues/1269)
**Solution**
Fixed the typo
=> Fix star typo in Contributing.md

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/FormDataContent.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt
**Subsystem**
Client multipart forms
**Motivation**
The entities in headers for multipart form parts should be separated by a semicolon and a space (`form-data; name=...`) not just a semicolon (`form-data;name=...`). Certain webservers (Rails in my case) can't correctly parse the headers otherwise. See: 
* https://tools.ietf.org/html/rfc7578#section-4.2 
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_header_for_a_multipart_body
**Solution**
Added a space after the semicolon when building form multipart headers
=> Fix multipart form header entity separator

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosClientEngine.kt
**Subsystem**
iOS engine client
**Motivation**
Fixes #1341
**Solution**
Since a new session is used for each request, we can safely allow the session to be invalidated after the request has completed.
=> finishTasksAndInvalidate after executing a request (#1341).

binary-compatibility-validator/reference-public-api/ktor-http.txt, ktor-http/common/src/io/ktor/http/HttpHeaders.kt
De-facto header used in many REST APIs to indicate the amount of items returned in list response (i.e. plain GET on a REST resources). Most useful in conjunction with paginated results where the number of returned item might be different than what was requested.
**Subsystem**
Server, related modules
**Motivation**
It's a fairly common header that is used in several popular REST APIs (a few can easily be found with a [Google search](google.com/search?q=x-total-count+header))
**Solution**
Adding that header to the framework's enum avoids custom solutions.
=> Add X-Total-Count HTTP header

ktor-server/ktor-server-core/jvm/src/io/ktor/features/PartialContent.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/PartialContentTest.kt
**Subsystem**
Server Core
**Motivation**
Partial content without the passed range doesn't have content length. But it should
**Solution**
override ContentLength in PartialContent.Bypass
=> Problem: partial content without the passed range doesn't have content length

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/testing/TestApplicationEngineTest.kt
**Subsystem**
Server, ktor-server/ktor-server-test-host
**Motivation**
There is a clash in names between this.processRequest and function's argument processRequest and it resolved to function's argument (bug #1300)
**Solution**
`hookRequest` will restore the original set of processors
Kudos to @LoneEngineer
=> referencing private processors when storing old state

ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpEngineTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpClientCallTest.kt
**Subsystem**
Client, OkHttp and HttpClientCall.
**Motivation**
Bugs, tests in this PR demonstrates issues.
**Solution**
Wrap receive into try-catch and close it in case of exception. Launch OkHttp close functionality on `GlobalScope`.
=> Fix client call hanging in case of exception and OkHttp close method.

binary-compatibility-validator/README.md
**Subsystem**
Binary compatibility validator, docs.
**Motivation**
The wrong command mentioned in docs.
**Solution**
Correct command, `s/test/check`.
=> Fix wrong command in README.md of binary-compatibility-validator module.

binary-compatibility-validator/reference-public-api/ktor-client-mock.txt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngineConfig.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockUtils.kt
**Subsystem**
Mock client
**Motivation**
Call context is not handled correctly in the Mock engine and as a result, we get hanging tests.
**Solution**
Pass call context to the `HttpResponseData`.
=> Handle callContext correctly in Mock client engine.

ktor-http/common/src/io/ktor/http/FileContentType.kt, ktor-http/common/src/io/ktor/http/Mimes.kt
**Subsystem**
Client
**Motivation**
It was doing a lot of unnecessary work when JS module were imported:
**Solution**
Just make those properties lazy-initialized.
=> Optimize JS module import time

gradle/darwin.gradle
**Subsystem**
Client
**Motivation**
As metioned in #1378 targets for both platforms were added to `posix.gradle` which makes artifacts like `ktor-client-core` already available for them. To actually use ktor on these platforms you need the platform specific artifacts like `ktor-client-ios` as well. However `darwin.gradle` which is used in the ios client was not updated.
**Solution**
This adds tvos and watchos targets to `darwin.gradle` which makes all artiacts that currently target only macOS and iOS available for them.
=> add tvos and watchos targets to darwin.gradle

ktor-client/ktor-client-features/ktor-client-json/ktor-client-jackson/jvm/src/io/ktor/client/features/json/JacksonSerializer.kt
**Subsystem**
Client Jackson
**Motivation**
I have my own ObjectMapper instance which I would like to use as JsonSerializer.
**Solution**
Just allow passing it as argument with current implementation as default. This is also more in line with content converters for ktor server.
=> Allow passing ObjectMapper to serializer

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/LocalPortRoutingBuilder.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
**Subsystem**
ktor-server
**Motivation**
I'm building an application that has some functions that should be exposed on a separate port (e.g. metrics). The existing (experimental) [`HostRouteSelector`](https://api.ktor.io/1.2.4/io.ktor.routing/-host-route-selector/index.html) (introduced in #835) is geared towards multi-tenant/VirtualHost-style configurations, allowing a client to send a `Host` header to get information that perhaps shouldn't be exposed to them.
**Solution**
I suggest a simple `RouteSelector` based on the `local: RequestConnectionPoint` port, whose documentation says (emphasis mine):
> Contains http request and connection details such as a host name used to connect, port, scheme and so on. ***No proxy headers could affect it.***
Sadly, some implementations don't abide by …
=> Introduce Local Port Routing Builder

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngine.kt
**Subsystem**
Server Testing
**Motivation**
Cookies in `cookiesSession { ... }` only persist for one request before being overwritten. In my case I needed to run multiple requests after storing a session cookie.
**Solution**
Instead of replacing the `trackedCookies` list, I instead append new cookies from responses. Perhaps this should be a `Set<Cookie>` instead?
=> Accumulate cookies instead of replacing in cookiesSession

ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/src/io/ktor/http/CookieUtils.kt, ktor-http/common/src/io/ktor/http/DateUtils.kt, ktor-http/common/test/io/ktor/tests/http/CookieDateParserTest.kt
**Subsystem**
ktor-http
**Motivation**
Attempts to fix #1382 by implementing the algorithm described in RFC6265 for cookie Expires dates.
**Solution**
Adds a new function to DateUtils for parsing cookie-specific dates using the new RFC6265-conformant CookieDateParser. Should this fail it falls back on the current implementation.
=> Fix cookie expires-date parsing (implements RFC6265)

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt
**Subsystem**
Client Digest Authentication
**Motivation**
#1385 describes a problem with ktor client's digest authentication. This PR proposes an implementation that makes ktor client's digest authentication compatible with [RFC 2617](https://tools.ietf.org/html/rfc2617#section-3.2.2.1)
**Solution**
Adjusts the computation of the digest response and the fields in the authentication header:
* adds the qop and the A2 hash to the digest response 
* adds the qop and the nonce count to the authentication header
=> Fix for ktor-client digest authentication

ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/Curl.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt, ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/Ios.kt, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRedirectTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpStatementTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PostTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ProxyTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/CacheTest.kt, ktor-client/ktor-client-tests/js/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/posix/src/io/ktor/client/tests/utils/ClientLoader.kt
**Subsystem**
Client Tests
**Motivation**
We need to add an ability to exclude engines by names, not platforms.
=> Add exclude engine functionality into ClientLoader.kt.

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpHeadersMap.kt
**Subsystem**
CIO client
**Motivation**
Trello authentication api is returning more than that, so we clearly need this lifted. Also that's a cheap change, and does not prompt for a refactoring.
**Solution**
I just bumped header buffer size to 64k.
=> Update HttpHeadersMap.kt header buffer limit

ktor-network/jvm/src/io/ktor/network/selector/InterestSuspensionsMap.kt
**Subsystem**
ktor-network
**Motivation**
Fix #1491
**Solution**
My solution removes the locale-dependent call to `toLowerCase()` and introduces compile-time safe code to determine the name of the field associated with each `SelectInterest` to replace it. Jvm tests pass on my computer.
=> Replace locale-dependent code fixes #1491

ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultResponseValidation.kt
Add @SharedImmutable over a readonly private var to avoid exceptions when used in multithreading
**Subsystem**
Client core.
**Motivation**
Encountered when making a request on iOS from another thread.
**Solution**
SharedImmutable should prevent the exception thrown by Kotlin when this var gets accessed on another thread.
=> Add @SharedImmutable over a readonly private var to avoid exceptions

binary-compatibility-validator/reference-public-api/ktor-client-cio.txt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/CIOEngineConfig.kt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/ConnectionPipeline.kt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/MultiPartFormDataTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientTestServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestServer.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/MultiPartFormData.kt
**Subsystem**
Client, CIO
**Motivation**
In the case of using `WriteChannelContent` CIO client closes the output channel and so triggers TCP connection half-close. Although this behavior is correct from the protocol perspective it's not encouraged in some cases and is not supported by all servers (Netty for example).
There are several issues caused by current implementation: #1456 and #1462.
**Solution**
This change makes TCP half-close optional and disabled by default.
=> Make CIO TCP half close behavior optional and disabled by default.

binary-compatibility-validator/reference-public-api/ktor-client-core.txt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequestPipeline.kt, ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/Logging.kt
**Subsystem**
Client, Pipeline and Logging
**Motivation**
Some client features like Logging need access to the final request that will be sent using engine (see https://github.com/ktorio/ktor/issues/1506). So far we have only `State` phase that modifies the request and `Engine` phase that actually sends the request.
**Solution**
To support Logging we need to add the correspondent `Logging` phase that has access to request but don't modify it.
=> Add Monitoring phase to HttpSendPipeline

ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/src/io/ktor/http/DateUtils.kt, ktor-http/common/src/io/ktor/http/FileContentType.kt, ktor-http/common/src/io/ktor/http/IpParser.kt, ktor-http/common/src/io/ktor/http/Mimes.kt, ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/internals/Chars.kt, ktor-io/common/test/io/ktor/utils/io/tests/ReadBufferTest.kt, ktor-io/posix/src/io/ktor/utils/io/errors/PosixErrors.kt, ktor-utils/common/src/io/ktor/util/Base64.kt, ktor-utils/common/src/io/ktor/util/Crypto.kt
**Subsystem**
Client
**Motivation**
We have native crashes in non-main thread due to top-level vals.
**Solution**
We need to find and mark all top-level vals with `@SharedImmutable` or `@ThreadLocal`.
=> Mark top-level vals SharedImmutable or thread local

ktor-network/jvm/src/io/ktor/network/selector/ActorSelectorManager.kt
**Subsystem**
ktor-client-cio, ktor-server-cio
**Description**
If there were cancelled keys encountered but no pending keys (other keys) then the selection loop may do spin too many times because only `handleSelectedKeys` clears the cancelled counter. The spinning causes high CPU load when it happens with low activity.
This is important since this is proven to happen in Circlet production from time to time and therefore should be included in 1.3.0.
**Solution**
The solution is to always zero the counter.
=> Fix CIO ActorSelectorManager to not spin due to cancelled keys

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpEngineTests.kt, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/CommonClientTestUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CommonHttpClientTest.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationEngine.kt
**Subsystem**
`HttpClient`, `OkHttp` client infrastructure.
**Motivation**
The problem mentioned in https://github.com/ktorio/ktor/issues/1340.
**Solution**
The problem could be fixed by using a shared `OkHttp` client (aka prototype). Such an approach leads to the inability to clear resources fully closing all internal objects of the prototype. To allow it there is also separated `HttpClient` and `HttpClientEngine` closing.
=> Fix OkHttp leaking threads.

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt
**Subsystem**
Client, OkHttp.
**Motivation**
As a result of unsafe publication, we're getting NPEs in `WebSocketTest.testEcho[OkHttp]`.
**Solution**
Await for object construction using `CompletableDeferred`.
=> Fix unsafe publication in OkHttpWebsocketSession.kt.

ktor-io/jvm/src/io/ktor/utils/io/charsets/UTF.kt, ktor-io/jvm/test/io/ktor/utils/io/charsets/UTFTest.kt
**Subsystem**
`ktor-io`
**Motivation**
The problem was mentioned in #1323. In case when `ByteBuffer` has an offset (particularly on Android when we call `ByteBuffer.allocateDirect(SIZE)`) function `decodeUTF8Line()` works incorrectly.
**Solution**
Fix position movements in `decodeUTF8Line()` function.
=> Fix UTF#decodeUTF8Line() wrong behavior in case ByteBuffer has an offset.

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/WebSockets.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/RawWebSocket.kt
**Subsystem**
OkHttp client.
**Motivation**
The initial problem is mentioned in https://github.com/ktorio/ktor/issues/1262.
**Solution**
Add `onClosing()` handler to `OkHttpWebsocketSession.kt`.
=> Fix onClosing() web socket handler in OKHttp client (#1262).

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosClientEngine.kt
**Subsystem**
iOS client engine
**Motivation**
#1420 describes a memory leak in the iOS client. I have posted more details in that issue, but the gist of it is that when opening an `NSUrlSession` using `sessionWithConfiguration()`, the `delegate` is leaked until the app exits unless we call `invalidateAndCancel()` or `finishTasksAndInvalidate()` at some point. See the documentation for the `delegate` parameter [on developer.apple.com](https://developer.apple.com/documentation/foundation/nsurlsession/1411597-sessionwithconfiguration?language=objc) for more information.
In effect, this meant that the engine, the session, and the coroutine used for executing the request are all leaked until the app dies.
**Solution**
After adding the data task to `NSUrlSession`, we immediate call …
=> Fix NSUrlSession memory leak by finishing session

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt
**Subsystem**
Server, Netty, WebSockets
**Motivation**
#1427, https://tools.ietf.org/html/rfc6455#section-5.5.1
According to RFC WebSockets TCP connection closing should be initialized from a server.
=> Fix behavior of Netty WebSocket closing, server initiates closing in accordance with RFC

ktor-client/ktor-client-features/ktor-client-auth/build.gradle.kts, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/Auth.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Auth.kt
**Subsystem**
ktor-client:ktor-client-features:ktor-client-auth
**Motivation**
Solves Issue #1051 
**Solution**
The while loop on the returned status code (Unauthorized) was not the only problem for the potential infinite request-response loop: The interceptor is triggering itself infinitely. Solution was to introduce a circuit breaker in the form of an attribute on the HTTP request. My hypothesis here was that these attributes are kind of a meta-data on the client side only and are not sent to the server as a payload. If this is not correct, please let me know.
The first commit enables JVM tests for the unit tests already present (they did not run before). Also, I added a test which provokes the SendCountExceedException as described in the issue. The second commit is the actual fix. The …
=> Prevent infinite request-response loop for client authentication (#1051)

ktor-features/ktor-websockets/jvm/test/io/ktor/tests/websocket/WriterTest.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Frame.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/RawWebSocket.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketWriter.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt
**Subsystem**
**Motivation**
Too early channel close caused Windows to mark the connection as aborted so test client is unable to read close frame.
**Solution**
Wait for all jobs completion before closing channel.
=> Fix Netty upgrade to wait for all jobs completion

ktor-utils/jvm/src/io/ktor/util/EncodersJvm.kt
**Subsystem**
ktor-utils
**Motivation**
Fix httpclient gzip decoding failed #1189
**Solution**
Changing the gzip header check to conform [specification](http://www.zlib.org/rfc-gzip.html)
=> Fix httpclient gzip decoding failed #1189 - gzip header check fix

ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
**Subsystem**
Module `ktor-http`. 
**Motivation**
The bug described in #1614. URL scheme parser does not handle URLs that are correct from the RFC perspective.
=> Fix URL scheme parser (#1614).

binary-compatibility-validator/reference-public-api/ktor-client-json.txt, binary-compatibility-validator/reference-public-api/ktor-http.txt, ktor-client/ktor-client-features/ktor-client-json/common/src/io/ktor/client/features/json/JsonFeature.kt, ktor-client/ktor-client-features/ktor-client-json/common/test/JsonFeatureTest.kt, ktor-http/common/src/io/ktor/http/ContentTypes.kt
**Subsystem**
Ktor Client, `JsonFeature`.
**Motivation**
Lack of a good DSL described in #1472.
=> Improve JsonFeature configuration DSL (#1472).

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpEngineTests.kt
**Subsystem**
Client, OkHttp.
**Motivation**
The bug described in https://github.com/ktorio/ktor/issues/1646. Currently, we ignore preconfigured OkHttpClinet.
=> Fix missed preconfigured OkHttpClient in OkHttpEngine (#1646).

binary-compatibility-validator/reference-public-api/ktor-client-core.txt, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngine.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/Auth.kt
**Subsystem**
Client, `HttpRequestBuilder`
**Motivation**
When we deprecated `takeFrom` we lost the support of important use case described in https://github.com/ktorio/ktor/issues/1626.
**Solution**
Make a separate `takeFromWithExecutionContext` method for internal usage and leave `takeFrom` to be used in client code.
=> Recover HttpRequestBuilder.takeFrom function (#1626).

binary-compatibility-validator/reference-public-api/ktor-client-core.txt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheHttpRequest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpCallValidator.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/utils/ExceptionUtils.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/utils/ExceptionUtils.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/utils/ExceptionUtils.kt, ktor-client/ktor-client-core/posix/src/io/ktor/client/utils/ExceptionUtils.kt, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/Assertions.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-client/ktor-client-tests/js/src/io/ktor/client/tests/utils/Assertions.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/Assertions.kt, ktor-client/ktor-client-tests/posix/src/io/ktor/client/tests/utils/Assertions.kt, ktor-io/common/test/io/ktor/utils/io/ByteChannelSmokeTest.kt, ktor-io/js/src/io/ktor/utils/io/ByteChannelJS.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialJVM.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelTest.kt
**Subsystem**
Client, `ktor-io`.
**Motivation**
The client throws `CancellationException` with the actual exception put into the cause. It is not convenient in many cases.
=> Unwrap cancellation exception in client code (#1482).

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt
**Subsystem**
Js-Client
**Motivation**
Fixes #1674 .
**Solution**
`Response#body` returns `ReadableStream`. But, it does not have `on` method.
So I replaced `Response#arrayBuffer` method instead of `ReadableStream` methods on `CoroutineScope.readBodyNode`.
And I use `jsRequire`, always throws `"Error loading module 'node-fetch': Error: Cannot find module 'node-fetch'"`. So, I deleted the method.
The operation has been confirmed in my sample repository.
=> Switch conditional branch PlatformUtils.IS_NODE and PlatformUtils.IS_BROWSER

ktor-http/common/src/io/ktor/http/Mimes.kt
**Subsystem**
Server/http
**Motivation**
Some mime type mapping were incorrect/had typo's (I bet there are more in the file). The mime type for .mp4 files was incorrectly set to application/mp4 instead of video/mp4 due to ordering within the file.
**Solution**
Corrected typo's and ordering
=> Mime types

gradle.properties, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-features/ktor-client-json/common/test/KotlinxSerializerTest.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/PlatformDetection.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpBinTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/MockedTests.kt, ktor-client/ktor-client-tests/js/src/io/ktor/client/tests/utils/PlatformDetection.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/PlatformDetection.kt, ktor-client/ktor-client-tests/posix/src/io/ktor/client/tests/utils/PlatformDetection.kt, ktor-io/js/test/io/ktor/utils/io/tests/VerifyingObjectPool.kt, ktor-utils/js/src/io/ktor/util/CryptoJs.kt
**Subsystem**
Client
**Motivation**
Publish JS IR klibs in 1.4.0
**Solution**
Updated build script to build, test and publish with both legacy and IR Kotlin/JS backends.
Locally worked around known issues. Muted 6 JS IR tests.
=> Enable JS IR backend

ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRedirectTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Redirect.kt
When a requested url responds with multiple redirects and the last redirect uses a relative path the relative path is resolved with the path of the initial request.
Example: 
initial request https://test.com/login/ location[/user/ ] -> https://test.com/user/ location[acccount/details] -> https://test.com/login/account/details
Expected:
initial request https://test.com/login/ location[/user/ ] -> https://test.com/user/ location[acccount/details] -> https://test.com/user/account/details
=> Client: Redirect URL resolution bug with relative paths

CONTRIBUTING.md, README.md
**Subsystem**
README and CONTRIBUTING files only 
**Motivation**
Minor updates to the English grammar.
**Solution**
Please note that I am not a native English speaker either and that some of my fixes might be incorrect. Some sentences were missing articles though, and there is at least one definite typo :).
=> Fix minor grammar mistakes in the README.

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpWebsocketSessionTest.kt
**Subsystem**
Client, OkHttp
**Motivation**
https://github.com/ktorio/ktor/issues/1363
OkHttp does not complete close reason in case of failure.
=> Fix OkHttp WebSocket close reason completion (#1363).

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/Auth.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/AuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/BasicAuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/oauth/OAuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/oauth/TokenProvider.kt
**Subsystem**
client, auth-feature
**Motivation**
There is no `AuthProvider` for OAuth. This is needed in many cases.
refs #1595 (and hopefully closes it as well)
**Solution**
I've modified `Auth` to let the `AuthProvider` decide, if the request should be retried or not. This is indicated by `AuthProvider.addRequestHeaders()` now *returning* a request or not. This is just like OkHttp handles this and many people might be used to. This is why, this was also renamed to `authenticate()`.
To let the `AuthProvider` get original request as a `HttpRequestBuilder`, I needed to use `HttpRequestBuilder().takeFrom(call.request)` because `takeFromWithExecutionContext()` does not add a header which was just added by the `AuthProvider` (not sure why).
I'm not sure how to add this provider to the test …
=> add OAuthProvider

gradle.properties, ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/CertificatePinner.kt, ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosUtils.kt, ktor-client/ktor-client-ios/darwin/test/io/ktor/client/engine/ios/CertificatePinnerTest.kt
**Subsystem**
Client, iOS
**Motivation**
Pinning certificates defends against attacks on certificate authorities. It also prevents connections through man-in-the-middle certificate authorities either known or unknown to the application's user.
#1431
**Solution**
Added class `CertificatePinner` which confirms to `ChallengeHandler`. In doing so it can override:
```
fun invoke(
session: NSURLSession,
task: NSURLSessionTask,
challenge: NSURLAuthenticationChallenge,
completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Unit
)
```
and therefore ensure that the certificates in the serverTrust match those that are pinned.
=> iOS Certificate Pinning

ktor-client/ktor-client-core/jvm/src/io/ktor/client/request/HttpRequestJvm.kt, ktor-http/jvm/src/io/ktor/http/URLUtilsJvm.kt
**Subsystem**
JVM/Http
**Motivation**
closes #1751 
**Solution**
change URLBuilder.takeFrom(uri: URI) and made return URLBuilder to be able to chain calls
Added a static extension to concisely create a Url object from a java.net.URI object
=> #1751 uri support

ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/HttpCookies.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CookiesTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Cookies.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/features/CookiesTest.kt
Subsystem
Client, HttpCookies feature.
Motivation
HttpCookies encodes all cookies with DQUOTES rather than respecting their own encoding
Solution
HttpCookies uses the cookies respective encoding
Continues work on #1393
Fixes #1222
=> HttpClient should render cookies with their respective encoding

ktor-client/ktor-client-core/common/src/io/ktor/client/engine/Utils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HeadersTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/engine/UtilsTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Headers.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Proxy.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestSuite.kt
**Subsystem**
Client Utils
**Motivation**
The issue described in https://github.com/ktorio/ktor/issues/1765 and [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).
=> Use comma to divide headers (Fix #1765).

ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/ObservingUtils.kt, ktor-client/ktor-client-features/ktor-client-logging/common/test/io/ktor/client/features/logging/CommonLoggingTest.kt, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannel.kt
fix log channel is not closed for ByteArrayContent and
add tests for OutgoingContent types handled in ObservingUtils.kt
replace deprecated call to `writeStringUtf8` with `writeText` in `ByteWriteChannel.kt`
**Subsystem**
Client
**Motivation**
Solving the problem stated in https://github.com/ktorio/ktor/issues/1729
**Solution**
The log channel was not closed for ByteArrayContent. Added closing and added tests for all the types of OutgoingContent that are used in ObservingUtils.kt
=> fix log channel is not closed for ByteArrayContent

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt
**Subsystem**
Client/Android Engine
**Motivation**
This pull request should solve the following issue: https://github.com/ktorio/ktor/issues/1812
**Solution**
The underlying http client of AndroidEngine can't extract the reasonPhrase when the server is not sending it. The reason phrase is actually optional, so it could be that some servers are sending and some dont. The http specification has also mentioned that it is optional:
> The reason-phrase element exists for the sole purpose of providing a
textual description associated with the numeric status code, mostly
out of deference to earlier Internet application protocols that were
more frequently used with interactive text clients. A client SHOULD
ignore the reason-phrase content.
See here for more information: …
=> bug-fix: enhanced handling of statusCode for AndroidEngine

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HeadersTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Headers.kt
=> Fix doubling host

ktor-features/ktor-auth/api/ktor-auth.api, ktor-features/ktor-auth/jvm/src/io/ktor/auth/OAuth.kt, ktor-features/ktor-auth/jvm/src/io/ktor/auth/OAuth2.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/OAuth2.kt
This allows to use GitLab OAuth2 provider.
Fixes #1846 
**Subsystem**
:ktor-features:ktor-auth
**Motivation**
This allows to use GitLab OAuth2 provider.
**Solution**
Added option to pass token retrieval params in URL instead of body in POST requests.
=> OAuth2: Added option to pass params in URL

ktor-server/ktor-server-core/jvm/src/io/ktor/features/ConditionalHeaders.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/ConditionalHeadersTests.kt
**Subsystem**
Ktor server, `ConditionalHeaders` feature.
**Motivation**
The issue described in #1849.
=> Fix conditional headers behaviour (Fix #1849).

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidEngineConfig.kt
**Subsystem**
ktor-client-android
**Solution**
Fixed typo in AndroidEngineConfig docs. 100_000 ms == 100 seconds (not 10)
=> Fixed typo in AndroidEngineConfig docs

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/RequestProducerTest.kt
**Subsystem**
Ktor client - Apache engine
**Motivation**
We should use existing approach when merging content-related headers and common ones, it will make engines safely replaceable.
**Solution**
Content-Type and Content-Length of OutgoingContent will be preferred now.
=> Apache should use existing approach when merging headers

ktor-io/posix/src/io/ktor/utils/io/bits/PrimitiveArraysNative.kt, ktor-io/posix/test/io/ktor/utils/io/tests/MemoryTest.kt
**Subsystem**
ktor-io (posix)
**Motivation**
i am fairly certain that the alignment checks are just a little typo, if not I'm sorry
**Solution**
Fixed to binary representation to check if the pointer is dividable by 2,4 or 8
=> fix memory alignment check

ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt
**Subsystem**
Client
**Motivation**
See https://github.com/ktorio/ktor/issues/1944
Using the ktor-client on Android with the OkHttp engine I noticed that using the `maxAge()` function to set the `Cache-Control` header had no effect on the caching strategy.
It was caused because using that function the `max-age` directive key and value are separated with ':' and the OkHttp client expected '=' as a separator.
According to the HTTP standard, the `max-age` directive of the `Cache-Control` header must use the '=' symbol instead of ':' to separate the directive key with the value.
**Solution**
The ':' separator has been replaced by '=' on the `max-age` directive key-value pair
=> Fix max-age directive on the Cache-Control header to use '=' instead of ':'.

ktor-client/ktor-client-features/ktor-client-json/common/src/io/ktor/client/features/json/JsonFeature.kt, ktor-client/ktor-client-features/ktor-client-json/common/test/KotlinxSerializerTest.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-gson/jvm/src/io/ktor/client/features/json/GsonSerializer.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-jackson/jvm/src/io/ktor/client/features/json/JacksonSerializer.kt, ktor-client/ktor-client-features/ktor-client-json/ktor-client-json-tests/jvm/src/io/ktor/client/features/json/tests/JsonTest.kt
**Subsystem**
Client: JsonFeature/JsonSerializer
**Motivation**
When using `JsonFeature` the empty body (e.g. a `get()` request without a body) gets serialized to `{}` instead of an empty string. This causes problems with some backends which expect the body to be empty.
For more context, let's assume we define an HttpClient with JsonFeature and a default `Content-Type` header like this:
```
val client = HttpClient(...) {
defaultRequest {
contentType(ContentType.Application.Json)
}
install(JsonFeature) {
// ...
}
}
```
This gives us some more convenience because we don't need to add the Content-Type header to each `post()`/`put()` call. However, now every request where we don't assign a body (e.g. a simple `get("https://...")`) gets turned into a request containing `{}` in the body and …
=> Fixed serialization of empty body

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt
**Subsystem**
Client
**Motivation**
The problem is described in issue #1974. When using digest auth, the qop field is never included in the authentication header. This breaks digest authentication.
**Solution**
Add missing `= it` so that the qop field is assigned to the correct value.
=> Fix missing qop in DigestAuthProvider (Issue #1974)

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt
**Subsystem**
ktor-client-core
**Motivation**
Solve webpack warning about a critical depencency (using require with an expression as a parameter).
```
WARNING in /Users/tiz/src/sandbox/ktor-client-test/build/js/packages_imported/ktor-ktor-client-core/1.3.2/ktor-ktor-client-core.js 16801:13-32
Critical dependency: the request of a dependency is an expression
@ ./kotlin/ktor-client-test.js
@ multi ./kotlin/ktor-client-test.js
```
**Solution**
Changed the require call to use the fixed 'node-fetch' string instead of a passed parameter.
This will cause builds to fail because of the missing 'node-fetch' dependency.
However, builds already fail because of missing dependencies. Users have to declare them in gradle build or add them to Webpack's externals so the build. See  #961 and #57
As of now …
=> fix webpack warning about ktor-client-core critical dependency

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/Auth.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/BearerAuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Auth.kt, ktor-http/common/src/io/ktor/http/auth/AuthScheme.kt
**Subsystem**
Http-Client
**Motivation**
Add support of Bearer tokens to the client-side. (Issue #1967 )
**Solution**
Added a BearerAuthProvider with an ability to load and refresh tokens.
=> Add a bearer auth feature for http-client

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/DigestProviderTest.kt
Subsystem
Client
Motivation
The problem is described in issue #1990 . When using digest auth, the uri field does not include the request parameters included in the original request. This breaks digest authentication.
Solution
Changing all places in DigestAuthProvider.addRequestHeaders which currently use url.encodedPath to use url.fullPath so that the uri field and token include the request parameters.
=> Fix uri field in digest auth header to include query params

ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/charsets/Encoding.kt, ktor-io/js/src/io/ktor/utils/io/charsets/CharsetJS.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/charsets/CharsetJVM.kt, ktor-io/jvm/test/io/ktor/utils/io/charsets/ByteChannelTextTest.kt, ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt
Change the exception type in `readLine` when a limit occurs, to distinguish the limit case from `MalformedInputException`
related: https://youtrack.jetbrains.com/issue/KTLIB-49
=> Change exception type for long strings in readUtf8Line

ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/HttpCookies.kt
**Subsystem**
Client.
**Motivation**
Some systems may behave differently if an empty cookie is sent, rather than omitting the Cookie header.
**Solution**
The header is only added if the Cookies list is not empty.
=> Prevent Empty Cookie addition

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/CIOEngineConfig.kt
**Subsystem**
Client 
**Motivation**
I assume this is a typo. 
**Solution**
Make configuration option writable.
=> socketTimeout in EndpointConfig was read only

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
**Subsystem**
Server
**Motivation**
[Routing: get matcher has higher priority than param matcher on the same level
](https://youtrack.jetbrains.com/issue/KTOR-792)
**Solution**
Original problem happens because `ParameterRouteSelector` uses the same priority (quality) as `PathSegmentParameterRouteSelector`, but they should not be the same
Example:
1. path: `/users/admin`
selectors:
* `/users/admin` - `qualityConstant` (1.0)
* `/users/{username}` - `qualityParameter` (0.8)
in this case chosen selector is `/users/admin` because it's more specific - everything works as expected
2. path: `/users?username=admin`
selectors:
* `users?[username]` - `qualityParameter` (0.8)
* `users:get` - `qualityConstant` (1.0)
Here selector `users:get` wins, but is should be the opposite. Route with parameter is …
=> KTOR-792 - Fix priority of routing with query parameter selector

ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/Logging.kt, ktor-client/ktor-client-features/ktor-client-logging/jvm/test/io/ktor/client/features/logging/LoggingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTests.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Logging.kt
**Subsystem**
Client/Server
**Motivation**
[KTOR-391](https://youtrack.jetbrains.com/issue/KTOR-391)
[KTOR-425](https://youtrack.jetbrains.com/issue/KTOR-425)
**Solution**
Avoid throwing of exception when parsing the malformed body
=> KTOR-391 KTOR-425 omit logging of malformed body

ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpResponse.kt
Added note that this property is not touched by any interceptors from HttpResponsePipeline
**Subsystem**
Server
**Motivation**
Property `content` of `HttpResponse` is a raw response from the server, that is not modified by `HttpResponsePipeline`. It created confusions and questions, like [KTOR-307](https://youtrack.jetbrains.com/issue/KTOR-307)
**Solution**
Added note that this property is not touched by any interceptors from HttpResponsePipeline
=> KTOR-307 update documentation of HttpResponse::content property

ktor-utils/common/src/io/ktor/util/collections/ConcurrentList.kt, ktor-utils/common/test/io/ktor/util/ConcurrentListTest.kt
Finish KTOR-1034 with fix of `clear` method
=> KTOR-1034 Fix ConcurrentList clear

ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/RequestTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ExceptionsTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestWithKtor.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Download.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelTest.kt
**Subsystem**
Client
**Motivation**
[OkHttp Can't reuse same HttpRequestBuilder for different network clients](https://youtrack.jetbrains.com/issue/KTOR-949)
**Solution**
When first client respond with timeout, it also cancels `executionContext` of a builder. Second client doesn't receive request because job is cancelled. `SupervisorJob` fix this issue.
=> KTOR-949 fix reusing HttpRequestBuilder for different network clients

ktor-utils/common/src/io/ktor/util/Annotations.kt
Reminder for those struggling:
Possessive adjective: her, his, its (one word, see)
Being: she's, he's, it's (two words contracted)
=> Fix typo: it's -> its

ktor-server/ktor-server-benchmarks/src/jmh/kotlin/io/ktor/server/benchmarks/HttpBenchmarkClient.kt
**Subsystem**
HTTP Benchmark Client
**Motivation**
When checking out the current master branch and running `gradlew build`, the project fails with a compilation error: "Using 'body(): ResponseBody?' is an error. moved to val".
**Solution**
This changes the function invocation to a property access, which fixes the deprecation compilation error.
=> HttpBenchmarkClient: Fix deprecated response.body() - moved to val

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt
**Subsystem**
Server
**Motivation**
Cleanup #2041 with better naming but API change
**Solution**
Separate quality constants for different route selectors. Since this change adds new constants to public API, it can't go to patch release.
=> KTOR-792 - Follow up on #2041 with cleanup and API change

ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/test/io/ktor/tests/http/CodecTest.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
**Subsystem**
common URL parser
**Motivation**
[Emoji in URL leads to an infinite loop](https://youtrack.jetbrains.com/issue/KTOR-1059)
**Solution**
Read surrogate symbols in pairs when encoding path
=> KTOR-1059 handle surrogate symbols in url path

ktor-network/ktor-network-tls/build.gradle.kts, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/CertificateInfo.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSClientHandshake.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/tests/ConnectionTests.kt
Subsystem
Client, ktor-network-tls
Motivation
Fix for [KTOR-366](https://youtrack.jetbrains.com/issue/KTOR-366)
Solution
Corrected the search of a Principal in the collection of principals. I.e. comparing X500Principal against other implementation of Principal interface always returns false. And since io.ktor.network.tls.CertificateInfo is an internal class I believe it is ok to make sure authorities are always X500Principals and then convert any other principal to X500Principal before comparison. That way the comparison will always be correct.
=> Closes #KTOR-366

ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/test/io/ktor/tests/http/HeadersTest.kt
**Subsystem**
Client/Server
**Motivation**
[Content-Disposition additional parameters should be inside quotes](https://youtrack.jetbrains.com/issue/KTOR-455)
**Solution**
Handle all separator symbols listed in [RFC](https://tools.ietf.org/html/rfc2616#section-2.2)
=> KTOR-455 quote separator fields in header values

ktor-client/ktor-client-cio/api/ktor-client-cio.api, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/CIOEngineConfig.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOConfigTest.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOHttpsTest.kt
**Subsystem**
**Motivation**
[CIO: client throws ConnectTimeoutException when endpoint.connectRetryAttempts = 0](https://youtrack.jetbrains.com/issue/KTOR-1125)
**Solution**
Deprecate misleading property. Add new property and delegate the old one to the new one.
=> KTOR-1125 - Rename misleading CIO config property

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/certificates/CertificatePinner.kt
**Subsystem**
Client iOS
**Motivation**
This PR fixes a wrong error message output when the iOS certificate pinning check fails.
https://youtrack.jetbrains.com/issue/KTOR-1139
**Solution**
Instead of outputting a reference value to the CertificatesInfo object, it now outputs "sha256/" as expected.
=> KTOR-1139 Fix CertificatePinner buildErrorMessage outputs CertificatesInfo reference

ktor-features/ktor-auth/jvm/src/io/ktor/auth/Authentication.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/AuthBuildersTest.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
**Subsystem**
server routing
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-613
**Solution**
Introduce `RouteSelectorEvaluation.qualityTransparent` constant for route items that don't have their own quality and should delegate evaluation to their children
=> KTOR-613 - Add transparent quality for route evaluation result

ktor-features/ktor-locations/jvm/test/io/ktor/tests/locations/LocationsTest.kt, ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt, ktor-features/ktor-webjars/jvm/test/io/ktor/webjars/WebjarsTest.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultEnginePipeline.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationResponse.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CallLoggingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CompressionTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/HeadTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/HttpsRedirectFeatureTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/StatusPageTest.kt
**Subsystem**
Server, Status pages, tests
**Motivation**
[StatusPages: TestEngine doesn't handle requests when no route selector matches](https://youtrack.jetbrains.com/issue/KTOR-842)
**Solution**
Move replying with 404 status on unhandled response from `defaultEnginePipeline` to `BaseApplicationEngine`, because `TestApplicationEngine` do not use `defaultEnginePipeline` 
This unifies behaviour in tests and real life
=> KTOR-842 Fix 404 StatusPages in tests

ktor-client/ktor-client-core/common/src/io/ktor/client/features/cache/HttpCache.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/CacheTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Cache.kt
**Subsystem**
Client cache
**Motivation**
[Client: InvalidCacheStateException when Vary header differs for 200 and 304 responses](https://youtrack.jetbrains.com/issue/KTOR-1103)
**Solution**
According to [Calculating Secondary Keys with Vary](https://tools.ietf.org/html/rfc7234#section-4.1), if 304 response doesn't have `Vary` headers, the client should compare headers listed in Vary from cached responses with new request to find a match.
=> KTOR-1103 handle 304 response without Vary header

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosClientEngine.kt, ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/ProxySupportCommon.kt
**Subsystem**
`io.ktor:ktor-client-ios`
**Motivation**
This PR makes it possible to make network requests from `Dispatchers.Default` without getting `IncorrectDereferenceException`. See: https://kotlinlang.slack.com/archives/C0A974TJ9/p1600972836014600
**Solution**
Add some freeze calls to the iOS engine.
=>  Add freeze calls to iOS engine

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheEngine.kt
`setMaxConnPerRoute` and `setMaxConnPerRoute` configure the client, not the IO reactor.
Moving the two lines to the outer scope doesn't change what they do but make their intent clearer.
**Subsystem**
Apache Client Engine
**Motivation**
Code was confusing to read because it looked like that the two lines configure the IO reactor instead of the client.
**Solution**
Move calls to correct scope.
=> Fixed incorrect placement of setMaxConnPerRoute and setMaxConnTotal ApacheEngine

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpTimeout.kt, ktor-client/ktor-client-jetty/build.gradle.kts, ktor-client/ktor-client-jetty/jvm/src/io/ktor/client/engine/jetty/JettyHttp2Engine.kt, ktor-client/ktor-client-jetty/jvm/test/io/ktor/client/engine/jetty/JettyHttp2EngineTest.kt
**Subsystem**
Client, Jetty
**Motivation**
[KTOR-1120](https://youtrack.jetbrains.com/issue/KTOR-1120) Jetty client engine with high concurrency randomly freezes, throws NPEs, ISEs or EofExceptions
**Solution**
Timeout config was used as a key for HTTP clients cache, but it didn't have an implementation for `equals`/`hashcode`. That caused LRU cache overflow and closing of clients that were in use
=> KTOR-1120 Fix caching of jetty client

ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/testing/TestApplicationEngineTest.kt
**Subsystem**
Test Ktor Client
ktor-server-test-host
**Motivation**
Fixing NPE #1891 
We should never throw NPE
**Solution**
We should emulate real client behavor with test client engine. So, if request not handled we should return 404 like real ktor.
=> Ktor test client returns 404 if request not handled. Fixing NPE #1891

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/features/CallLogging.kt, ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultEnginePipeline.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyKtorHandler.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/JettyServletApplicationEngine.kt, ktor-server/ktor-server-jetty/ktor-server-jetty-test-http2/jvm/test/io/ktor/tests/server/jetty/http2/JettyHttp2ServletContainer.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt, ktor-server/ktor-server-servlet/api/ktor-server-servlet.api, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/KtorServlet.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletApplicationEngine.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestBase.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
Server
**Motivation**
[Implement proper unhandled exception handling strategy](https://youtrack.jetbrains.com/issue/KTOR-835)
**Solution**
Every engine now handles exception in the pipeline with a simple `try/catch` block. In case of failure, they log the error and respond with 500 status code.
=> KTOR-835 Respond 500 in engines on not caught errors

ktor-features/ktor-jackson/jvm/src/io/ktor/jackson/JacksonConverter.kt, ktor-features/ktor-jackson/jvm/test/io/ktor/tests/jackson/JacksonTest.kt
**Subsystem**
ktor-jackson
**Motivation**
The existing implementation of the JacksonConverter used a TextContent, which meant that the ObjectMapper had to serialize the entire output value to a String before responding.
For large output objects, this causes significant allocation pressure. It can avoid by instead streaming the output. This change does that.
**Solution**
The change is fairly small, simply using different existing streaming methods on the ObjectMapper in combination with a OutputStreamContent.
There is an added test to verify that it got UTF-16 conversion right.
=> Jackson: Do not convert to String before converting to JSON

ktor-client/ktor-client-core/common/src/io/ktor/client/features/cache/HttpCacheEntry.kt, ktor-client/ktor-client-core/common/test/CacheExpiresTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/features/CacheTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Cache.kt
**Subsystem**
ktor-client-core
**Motivation**
[KTOR-364](https://youtrack.jetbrains.com/issue/KTOR-364)  Ktor Client HTTP Cache for invalid or blank Expires header 
This is based on user's PR #2102
=> Fix illegal expires header behaviour

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/features/HttpsRedirect.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/HttpsRedirectFeatureTest.kt
Add excludeSuffix() as a compliment to the existing excludePrefix() function
**Subsystem**
HttpsRedirect feature
**Motivation**
There is already a excludePrefix(). excludeSuffix() is a complimentary function.
**Solution**
Restrict inclusion by suffix.
=> Add excludeSuffix()

ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/JsonSupport.kt, ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/SerializationConverter.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Frame.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/http/HttpDate.kt
Instead of suppressing errors, which doesn't work with JVM IR.
=> Use JvmName for deprecated-hidden conflicting overloads

ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/LoggedContent.kt, ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/ObservingUtils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTests.kt
**Subsystem**
Client, Logging
**Motivation**
[Ktor 1.4.1 fails to upload file (submit form) when logging level = LogLevel.BODY](https://youtrack.jetbrains.com/issue/KTOR-1129)
**Solution**
Logging creates a new instance for the content of the request and drops its properties. This PR keeps them by delegating from new content to the old one.
=> KTOR-1129 Delegate to original OutgoingContent when logging body

buildScripts/cleanupKeysWindows.ps1, buildScripts/prepareKeysWindows.ps1
Add prepare and clean-up Powershell files for keys for Windows machines. Currently TeamCity doesn't allow this information [to be stored in its own repository](https://youtrack.jetbrains.com/issue/TW-68479)
=> KTOR-1241 Add PS files for key prep and clean-up

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/NettyResponsePipeline.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationResponse.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt
**Subsystem**
**Motivation**
[KTOR-1298](https://youtrack.jetbrains.com/issue/KTOR-1298)
HttpServerTestSuite.testHeadResponse fails with Netty HTTP/2 because a response message has no actual body but headers have the concrete content length so it leads to the pipeline failure.
**Solution**
- Send head and empty (without body) responses in a single HTTP/2 frame marked as EOS.
- Enable the corresponding test back for HTTP/2
=> KTOR-1298 Fix hanging HEAD response with Netty HTTP/2

ktor-client/ktor-client-tests/posix/test/io/ktor/client/tests/HttpClientFreezingTest.kt, ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt
**Subsystem**
Client, native
**Motivation**
This PR fixes an `IncorrectDereferenceException` when using the HttpClient on `Dispatchers.Default`. The bug was caused by https://github.com/ktorio/ktor/pull/2110 that added a top level value not marked as `@SharedImmutable`. 
HttpClient on `Dispatchers.Default` was supposed to be fixed in Ktor 1.4.2 with https://github.com/ktorio/ktor/pull/2092 but as explained above unfortunately another issue was introduced. That is why I also added a test to prevent issues like this in the future.
https://kotlinlang.slack.com/archives/C0A974TJ9/p1605058326000100
**Solution**
Mark the top level value with `@SharedImmutable` and add a test.
=> Fix IncorrectDereferenceException when using HttpClient on Dispatchers.Default

ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheEngine.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheHttpRequest.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheResponseConsumer.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/InterestControllerHolder.kt, ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/RequestProducerTest.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannelSequentialJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/RingBufferCapacity.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteChannelSequentialTest.kt
**Subsystem**
Client, Apache
**Motivation**
[Apache client engine sometimes hits an unrecoverable socket timeout when using ChannelWriterContent](https://youtrack.jetbrains.com/issue/KTOR-1149)
**Solution**
There was a race condition in `ApacheRequestProducer`. Fixed by rewriting it to a better approach.
=> Rewrite ApacheRequestProducer

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidURLConnectionUtils.kt, ktor-client/ktor-client-android/jvm/test/io/ktor/client/engine/android/UrlConnectionUtilsTest.kt
**Subsystem**
Client, Android
**Motivation** 
[Timeout﻿ feature: android engine throws Java's SocketTimeoutException instead of ConnectTimeoutException](https://youtrack.jetbrains.com/issue/KTOR-1229)
**Solution**
Not only `connect()`, but also `statusCode` and other methods on `HttpURLConnection` can throw an exception that we need to map. This PR wraps all of them in a block.
Note: Not sure how to write a proper test for it, since only some versions of Android has this behavior.
=> KTOR-1229 Fix mapping of SocketTimeoutException in Android engine

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
**Subsystem**
Server, routing
**Motivation**
["Wrong HEX escape": gracefully handle invalid URLs](https://youtrack.jetbrains.com/issue/KTOR-1308)
=> KTOR-1308 throw BadRequestException on malformed path

ktor-io/common/test/io/ktor/utils/io/tests/AbstractInputTest.kt, ktor-io/js/src/io/ktor/utils/io/charsets/CharsetJS.kt, ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt
**Subsystem**
Client/Server, IO
**Motivation**
[Input.readTextExactBytes(n) on empty input different behavior per platform](https://youtrack.jetbrains.com/issue/KTOR-1235)
=> KTOR-1235 throw EOFException when trying to read empty input on all platforms

ktor-http/common/src/io/ktor/http/CacheControl.kt, ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/src/io/ktor/http/CookieUtils.kt, ktor-http/common/src/io/ktor/http/FileContentType.kt, ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/src/io/ktor/http/Headers.kt, ktor-http/common/src/io/ktor/http/HttpHeaderValueParser.kt, ktor-http/common/src/io/ktor/http/HttpHeaders.kt, ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt, ktor-http/common/src/io/ktor/http/HttpProtocolVersion.kt, ktor-http/common/src/io/ktor/http/HttpUrlEncoded.kt, ktor-http/common/src/io/ktor/http/LinkHeader.kt, ktor-http/common/src/io/ktor/http/Parameters.kt, ktor-http/common/src/io/ktor/http/Query.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/src/io/ktor/http/URLProtocol.kt, ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt, ktor-http/common/src/io/ktor/http/content/CachingOptions.kt, ktor-http/common/src/io/ktor/http/content/Multipart.kt, ktor-http/common/src/io/ktor/http/content/OutgoingContent.kt, ktor-http/common/src/io/ktor/http/parsing/GrammarBuilder.kt, ktor-http/common/src/io/ktor/http/websocket/Utils.kt
**Subsystem**
ktor-http (all)
**Motivation**
This is an attempt to make `ktor-http` module conform to [ktlint](https://github.com/pinterest/ktlint). This is under question if we want such changes. Please look at whet I was forced to do.
The only disabled rule is "no-wildcard-imports" to make start imports work.
=> Reformat ktor-http to conform to ktlint

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationRequest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationResponse.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationRequest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/Utils.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
**Motivation**
[KTOR-905](https://youtrack.jetbrains.com/issue/KTOR-905) Request headers exceeding expected threshold are not handled correctly
Before this fix, we didn't send content-length so clients were simply hanging when waiting for response content since neither content-length nor connection nor chunked specified.
**Solution**
Supply both `Connection: close` and `Content-Length` in this case. Add a test to ensure the same on all servers.
=> KTOR-905 Fix Netty HTTP 400 BadRequest response

ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/WriteSessionImpl.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelTest.kt
**Subsystem**
Client/Server, ByteBufferChannel
**Motivation**
[KTOR-1247](https://youtrack.jetbrains.com/issue/KTOR-1247)
Race condition:
1. writer calls `channel.writeByte` 
2. writer goes inside `setupStateForWrite` 
3. no bytes available for write -> `buffer.limit() == buffer.position()`
4. reader reads content, creates space for the writer
5. writer checks capacity in state -> success, tries to write to a preconfigured buffer that has no available space
6. crash
**Solution**
* Move setting up buffer position and limit after checking of capacity to avoid race. 
* Unified behavior of `writeByte/Short/Int/Long`
* Cleaned up some unused methods and parameters
=> KTOR-1247 - Fix writing race condition in ByteBufferChannel

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-network/jvm/src/io/ktor/network/sockets/CIOReader.kt, ktor-network/jvm/src/io/ktor/network/sockets/CIOWriter.kt, ktor-network/jvm/src/io/ktor/network/util/Utils.kt, ktor-network/jvm/test/io/ktor/network/util/StartTimeoutTest.kt, ktor-utils/common/src/io/ktor/util/date/Date.kt, ktor-utils/js/src/io/ktor/util/date/DateJs.kt, ktor-utils/jvm/src/io/ktor/util/date/DateJvm.kt, ktor-utils/posix/src/io/ktor/util/date/DateNative.kt
**Motivation**
[KTOR-1127 CIO: client engine exceptions are both logged and thrown](https://youtrack.jetbrains.com/issue/KTOR-1127)
**Solution**
The previous implementation of socket timeout was very ineffective and allocated a lot of unnecessary objects. Rewrote it to a more low level one.
=> KTOR-1127 Rewrite timeout impl for CIO

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/KtorServlet.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerTestSuite.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt
**Subsystem**
Server
**Motivation**
[Netty engine doesn't keep coroutine elements in coroutine context](https://youtrack.jetbrains.com/issue/KTOR-1358)
**Solution**
Use `parentCoroutineContext` as base context for handlers coroutines
=> KTOR-1358 Propagate parentCoroutineContext to handlers

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/FormDataContent.kt
**Subsystem**
Client
**Motivation**
[Client: NPE in FormDataContentKt -> Input.copyTo](https://youtrack.jetbrains.com/issue/KTOR-1349)
**Solution**
TBH I am not sure how to reproduce it, but the crash is happening [here](https://github.com/ktorio/ktor/pull/2221/files#diff-6667837f9857b90b173abc24a146f7cbfaf384d6181180c32d40384363099a12L151)
I rewrote this block to the newer approach to remove the possibility of NPE
=> KTOR-1349 rewrite Input.copyTo from writeSuspendSession to write

ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpRequestBodyPublisher.kt, ktor-client/ktor-client-java/jvm/test/io/ktor/client/engine/java/RequestTests.kt
**Subsystem**
ktor-client-java
**Motivation**
Test testErrorInWritingPropagates is failing in master
**Solution**
If the body channel is closed too quickly, a publisher quits with no signalling error so the whole engine freezes. The solution is to propagate the cause in this case instead of just quitting.
=> KTOR-348 Fix testErrorInWritingPropagates

ktor-utils/api/ktor-utils.api, ktor-utils/common/src/io/ktor/util/date/Date.kt, ktor-utils/common/test/io/ktor/util/GMTDateTest.kt
**Subsystem**
Utils, GMTDate
**Motivation**
As Ktor already has some overloads for kotlin.time.Duration in ktor-server-core/features/KotlinTimeJvm.kt, this overload would be nice too, [KTOR-1403](https://youtrack.jetbrains.com/issue/KTOR-1403)
**Solution**
Added plus/minus fun for GMTDate
=> KTOR-1403 Add plus/minus Duration Support for GMTDate

ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSConfigBuilder.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/tests/TLSConfigBuilderTest.kt
**Subsystem**
CIO - JVM
Fixing [KTOR-941](https://youtrack.jetbrains.com/issue/KTOR-941)
**Motivation**
This fix adds the option to use only a specific alias instead all alias for a given JVM Keystore.
This change is addictive only, no breaking change.
**Solution**
Added null-able default null alias which will be use if present. Otherwise, all aliases from a Keystore will be used as known behavior. 
https://youtrack.jetbrains.com/issue/KTOR-941
Please reopen the issue on youtrack, it was closed after 30 days...
=> KTOR-941 CIO TLSConfigBuilder JVM - Use only specific alias

ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelTest.kt
**Subsystem**
Client/Server
**Motivation**
[testWriteXRaceCondition sometimes hangs on CI](https://youtrack.jetbrains.com/issue/KTOR-1449)
**Solution**
This is not a proper fix but will unblock CI and we can see logs on where the block is.
=> KTOR-1449 Add timeout rule

settings.gradle
**Subsystem**
Gradle
**Motivation**
The native targets are always include, ignoring the variable. https://youtrack.jetbrains.com/issue/KTOR-1434
=> KTOR-1434 Remove always included native targets

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt, ktor-client/ktor-client-core/common/test/FormDslTest.kt
**Subsystem**
Client
**Motivation**
[Content-Disposition additional parameters should be inside quotes](https://youtrack.jetbrains.com/issue/KTOR-455)
**Solution**
This bug was fixed before, but I forgot to escape values here as well
=> KTOR-455 escape file and filename in formData builder

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt
Simple comment fix. Makes a comment gender neutral.
=> Use gender neutral word in HttpClient comment

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClientConfig.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultResponseValidation.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpCallValidator.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CallValidatorTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/testing/TestApplicationEngineTest.kt
**Subsystem**
**Motivation**
[KTOR-1412](https://youtrack.jetbrains.com/issue/KTOR-1412) Response validation happens only on call to `receive<T>()`
**Solution**
Move validation from `HttpResponsePipeline` to `HttpReceivePipeline`
=> KTOR-1412 Move response validation to the receive pipeline

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/http/Push.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/response/ApplicationResponse.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/response/DefaultResponsePushBuilder.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/response/ResponsePushBuilder.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/response/UseHttp2Push.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationResponse.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationResponse.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationResponse.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2Handler.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/AsyncServlet.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/v4/Push.kt
**Subsystem**
ktor-server-core
**Motivation**
[KTOR-1329 Deprecate HTTP/2 push support](https://youtrack.jetbrains.com/issue/KTOR-1329)
=> KTOR-1329 Add warning annotation for HTTP/2 push

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/request/utils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CookiesTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Cookies.kt
**Subsystem**
Client, HttpRequestBuilder
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-926
**Solution**
Wrapper over `headers { ... }` extension that allows adding cookies via `Cookie` header that can be accessed on server.
=> KTOR-926 Introduce wrapper for sending cookies via HTTPRequestBuilder

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultResponseValidation.kt, ktor-client/ktor-client-core/posix/test/ExceptionsTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ExceptionsTest.kt
**Subsystem**
Client (ktor-client-core), exceptions in validation
**Motivation**
This PR solves https://youtrack.jetbrains.com/issue/KTOR-844 issue.
**Solution**
- Read  `responseText` in `HttpResponseValidator` and provide the constructor of `ResponseException` and it's descendants (`ServerResponseException`, `ClientRequestException`, `RedirectResponseException`) with the cached response text.
- Put the text to the message.
=> KTOR-844 add responseText field to ResponseException and SavedCall

ktor-features/ktor-metrics-micrometer/api/ktor-metrics-micrometer.api, ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt, ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt
**Subsystem**
Server, MicrometerMetrics
**Motivation**
[Micrometer metrics: scan of random URLs of a server exhausts available values per tag in influx](https://youtrack.jetbrains.com/issue/KTOR-1312)
**Solution**
To not change existing behavior, I added the flag to opt-in for the new one.
=> KTOR-1312 Add config flag to MicrometerMetrics to log all 404 request with n/a route

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/websocket/FrameType.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/websocket/FrameCloseTest.kt
**Solution**
WA for [KT-43901](https://youtrack.jetbrains.com/issue/KT-43901) to pass `FrameCloseTest` in JS IR compiler backend in Node.JS.
=> KT-43901 Use WA for Enum.values in companion object

ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt
**Subsystem**
**Motivation**
[KTOR-368 ktor not closing user connections](https://youtrack.jetbrains.com/issue/KTOR-368) 
Unlike other backends, the netty backend doesn't have either read timeout, IDLE timeout or TCP keep alive option. So dead clients that don't close TCP connections properly, may get stuck forever. We only have read timeout that is disabled by default and still doesn't solve the problem because it's difficult to find the best time value for it as it may break WebSockets, SSE and long polling, including old techniques like "comet".
**Solution**
Introduce a way to enable TCP keep alive for Netty via option. It is disabled by default.
**Problems**
I see no way to write a reliable and fast enough test for this. So I decided to enable that flag for one of …
=> KTOR-368 Introduce Netty tcpKeepAlive flag

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionIdProvider.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionsBuilder.kt
**Subsystem**
ktor-server-core
**Motivation and solution**
[KTOR-878 Possibility of birthday attach for SessionStorage key](https://youtrack.jetbrains.com/issue/KTOR-878)
Currently, the session-id strength is not that high. In spite of that, we have no particular evidence of that it's really unsafe, our competitors usually have longer identifiers. So I decided to twice the id in ktor as well.
Also, the default session-id generation function is now public.
=> KTOR-878 Strengthen session ID generation

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpConfig.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpWebsocketSessionTest.kt
**Subsystem**
Client, OkHttp, WebSockets
**Motivation**
[KTOR-951](https://youtrack.jetbrains.com/issue/KTOR-951)  Allow OkHttpConfig to configure WebSocket.Factory 
Previously, OkHttpWebsocketSession used OkHttpClient directly to create WebSocket instances. This meant there was no way to provide a custom implementation of WebSocket interface.
**Solution**
This change allows users to provide their own WebSocket.Factory instance on OkHttpConfig.
=> Add OkHttpConfig#webSocketFactory

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionSerializerReflection.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionsBuilder.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/sessions/AutoSerializerTest.kt
**Subsystem**
ktor-server-core
**Motivation**
[KTOR-826 Support Sealed Classes inside Session-Objects](https://youtrack.jetbrains.com/issue/KTOR-826)
Currently, server sessions feature only supports plain classes with primitive properties + the particular list of supported types.
**Solution**
- Provide the ability to serialize class instances including:
- sealed classes with subclasses
- objects
- Pass proper `KType` instead/with `KClass` from DSL to session serializer
=> KTOR-826 Support sealed classes in server sessions

ktor-client/ktor-client-android/jvm/test/io/ktor/client/engine/android/CommonTests.kt, ktor-client/ktor-client-apache/jvm/test/io/ktor/client/engine/apache/CommonTests.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/CIOEngine.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/ConnectionPipelineCommon.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/ConnectionPipeline.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CommonTests.kt, ktor-client/ktor-client-cio/posix/src/io/ktor/client/engine/cio/ConnectionPipelineNative.kt, ktor-client/ktor-client-java/jvm/test/io/ktor/client/engine/java/CommonTests.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/CommonTests.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/SslOverProxyTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Proxy.kt, ktor-network/api/ktor-network.api, ktor-network/common/src/io/ktor/network/sockets/Sockets.kt, ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-network/ktor-network-tls/common/src/io/ktor/network/tls/TLSCommon.kt
**Subsystem**
Client
**Motivation**
[KTOR-1458](https://youtrack.jetbrains.com/issue/KTOR-1458) Support SSL over HTTP proxy for CIO
Since we need to use raw input of Socket before starting TLS handshake, we can't open it for reading inside TLS methods. That's why the new class `Connection` was introduced. It holds the socket and its input and output.
=> KTOR-1458 Add tunneling functionality to CIO

ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultResponseValidation.kt, ktor-client/ktor-client-core/jvm/test/ExceptionsTest.kt
**Subsystem**
ktor-client-core, JVM
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-1552
https://github.com/ktorio/ktor/issues/1256
**Solution**
Mark _response transient in ResponseException.
Note: accessing the response field of the deserialized exception will throw a NullPointerException. That is the same behaviour as it was before. This cannot be improved unless the response field is made nullable.
=> KTOR-1552 Mark _response transient in ResponseException

ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/CurlProcessor.kt
**Subsystem**
ktor-client-curl
**Motivation**
[KTOR-1220 "Unfinished workers detected" using client on native](https://youtrack.jetbrains.com/issue/KTOR-1220)
**Solution**
Terminate worker on client close
**Known issues**
We can't force memory checker to run in tests, so no tests provided
=> KTOR-1220 Fix terminating curl processor worker on close

ktor-client/ktor-client-jetty/jvm/src/io/ktor/client/engine/jetty/JettyHttp2Engine.kt, ktor-client/ktor-client-jetty/jvm/src/io/ktor/client/engine/jetty/JettyHttpRequest.kt, ktor-client/ktor-client-jetty/jvm/src/io/ktor/client/engine/jetty/JettyResponseListener.kt, ktor-client/ktor-client-jetty/jvm/test/io/ktor/client/engine/jetty/JettyHttp2EngineTest.kt
**Subsystem**
ktor-client-jetty
**Motivation**
[KTOR-874 Jetty: requests to resources, that doesn't respond with HTTP/2, lead to unexpected behaviour](https://youtrack.jetbrains.com/issue/KTOR-874)
**Solution**
Add error handler and fail requests with more detailed errors rather than EOF at writing.
=> KTOR-874 Fix jetty client error handling

ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/ClassCastExceptionTest.kt
**Subsystem**
ktor-server-cio/tests
**Motivation**
From time to time the test is failing because of the address already in use error.
**Solution**
Use server tests infrastructure that is almost tolerant for such kind of problems.
=> KTOR-1572 Fix flaky ClassCastExceptionTest

ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpResponseBodyHandler.kt
**Subsystem**
ktor-client-java
**Motivation**
[KTOR-1567 Java client freeze](https://youtrack.jetbrains.com/issue/KTOR-1567)
**Solution**
Stop doing runBlocking in a reactive handler. Launch a separate coroutine to push bytes from reactive stream to byte channel
=> KTOR-1567 Fix freezing Java client

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkUtils.kt, ktor-network/jvm/src/io/ktor/network/util/Utils.kt, ktor-network/jvm/test/io/ktor/network/util/StartTimeoutTest.kt
**Subsystem**
ktor-client-okhttp
**Motivation**
[KTOR-1583 HttpTimeoutTest.testConnect are flaky](https://youtrack.jetbrains.com/issue/KTOR-1583)
Sometimes, a timeout exception is not get mapped to the correct exception type because the platform exception text may be different. In particular, on Mac it may contain "Connect" so the contains check may fail
**Solution**
- Split and simplify code
- use case-insensitive contains check instead
=> KTOR-1583 Fix wrong connect timeout exception with OkHttp

ktor-network/jvm/src/io/ktor/network/util/Utils.kt, ktor-network/jvm/test/io/ktor/network/util/StartTimeoutTest.kt
[KTOR-1585 testTimeoutCancelsWhenParentScopeCancels is flaky](https://youtrack.jetbrains.com/issue/KTOR-1585)
=> KTOR-1585 Fix flaky testTimeoutCancelsWhenParentScopeCancels

ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt
KTOR-1543
Fixes #1293
**Subsystem**
`URLBuilder`
**Motivation**
The `URLBuilder` was using the wrong url encoding method for the path, which wasn't encoding some characters as they should have been.
**Solution**
Switch the encoder function call from `path.encodeURLQueryComponent()` to `path.encodeURLPath()`.
=> KTOR-1543 Fix URL path encoding using incorrect encoding function

ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Timeout.kt
**Subsystem**
ktor-client-tests, ktor-client-apache
**Motivation**
[KTOR-1584 HttpTimeout.testSocketTimeoutWriteFail is flaky](https://youtrack.jetbrains.com/issue/KTOR-1584)
The possible reason is that sleep duration is only one second while timeouts are checked by Apache every selection (that is also 1sec by default). So if the test server is too fast or selection is a little bit slower, we may get a response too early so no timeout happens in this case so the tests do fail because timeouts were expected.
This is a test bug.
**Solution**
Increase server delay to ensure that Apache detects timeout in time.
=> KTOR-1584 Increase test server delay to fix missing timeouts

ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultTransform.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTests.kt
**Subsystem**
ktor-client-core
**Motivation**
[KTOR-1598 Response channel is always cancelled with Logging feature](https://youtrack.jetbrains.com/issue/KTOR-1598)
**Solution**
Launch coroutine under the client's job instead of the request one.
=> KTOR-1598 Fix receving client channel with Logging feature

ktor-client/ktor-client-core/common/src/io/ktor/client/features/DefaultTransform.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRequestLifecycle.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpEngine.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpResponseBodyHandler.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTests.kt
**Subsystem**
ktor-client-java
**Motivation**
[KTOR-1599 Java client logging tests are fluky](https://youtrack.jetbrains.com/issue/KTOR-1599)
**Solution**
- Remove unnecessary client jobs and make it work similar to other engines
- Fix using the wrong job instance when creating a `ResponseData` instance
- Add call job cancellation in the case when there was no `ResponseData` produced
Should be only merged after #2282 ([KTOR-1598](https://youtrack.jetbrains.com/issue/KTOR-1598))
=> KTOR-1599 Fix Java client job structure

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Proxy.kt
**Subsystem**
CIO client
**Motivation**
Fixes wrong http `CONNECT` request when tunneling https through a http proxy.
The request line should be `CONNECT $host:$port HTTP/1.1` (e.g. `CONNECT example.com:443 HTTP/1.1`)
Not `CONNECT $url HTTP/1.1` (e.g. `CONNECT https://example.com/ HTTP/1.1`)
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT)
**Related PR**
#2256
=> Fix CIO client tunneling https through http proxy

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt
**Subsystem**
ktor-http
**Motivation**
#1868 
**Solution**
Check if the header name is valid before parsing.
=> KTOR - 378 Fix request/response accepting empty header name (#1868)

ktor-client/ktor-client-java/api/ktor-client-java.api, ktor-io/api/ktor-io.api
**Subsystem**
ktor-io, ktor-client-java
**Description**
[KTOR-1637 Upgrade kotlin to 1.4.21](https://youtrack.jetbrains.com/issue/KTOR-1637)
Upgrade to Kotlin 1.4.21 introduced binary changes.
The changes:
- The added method with suffix "default" was added by the new API dumper (wasn't dumped before due to the bug + this is inline function so nobody actually call it)
- note that the function actually was always there
- The removed methods are safe changes because we don't override the methods and there are such functions in the base class so method resolution will work anyway
- they seems to be not checked because the build configuration on TC uses the wrong JDK so java client is not checked (will open a PR on this)
=> KTOR-1615 Fix apidump

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt
**Subsystem**
ktor-cio-http
**Motivation**
After applying fix #2288 we are reporting the wrong error message.
**Solution**
Detect empty header name case more precisely and report the proper error.
=> KTOR-378 Fix empty header name diagnostic

ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CORSTest.kt
**Subsystem**
ktor-server-core
**Motivation**
[KTOR-1662 CORS doesn't reject bad headers](https://youtrack.jetbrains.com/issue/KTOR-1662)
Caused by #2034 
**Solution**
Fix accidental early return
=> KTOR-1662 Fix CORS headers processing

ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/common/src/io/ktor/utils/io/bits/MemoryFactory.kt, ktor-io/common/test/io/ktor/utils/io/ByteChannelTest.kt, ktor-io/js/src/io/ktor/utils/io/ByteReadChannelJs.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/ByteBufferChannelInternals.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/RingBufferCapacity.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/Utils.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/WriteSessionImpl.kt
**Subsystem**
Client/Server, ktor-io
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-1449
https://youtrack.jetbrains.com/issue/KTOR-1557
**Solution**
* Cleanup code, remove unused code, add early returns, simplify expressions
* Migrate from tailrec to loops
* Remove duplication in `readByte`/`Int`/`Short`/`etc` and `writeByte`/`Int`/`Short`/`etc`
* Add tests for `peekTo` method and fix failures
* Fix race condition in `ByteBufferChannel`
=> Cleanup ByteBufferChannel

ktor-network/posix/src/io/ktor/network/selector/SelectUtils.kt, ktor-network/posix/src/io/ktor/network/selector/SignalPoint.kt, ktor-network/posix/src/io/ktor/network/selector/WorkerSelectorManager.kt
**Subsystem**
ktor-client-cio
**Motivation**
Currently, CIO selector does blocking select. Closing it or adding interests don't wakeup so no new interests will be selected and close operation may hang forever.
**Solution**
Use a signal pipe and do selection on it. When a new interest is configured or close request arrived, we do signal to force abort blocking selection.
=> ~ Make CIO selector do wakeup on close/suspend

ktor-client/ktor-client-core/common/test/FormDslTest.kt, ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/test/io/ktor/tests/http/HeadersTest.kt
**Subsystem**
Client/Server
**Motivation**
[KTOR-1797](https://youtrack.jetbrains.com/issue/KTOR-1797) Do not quote already quoted parameters
=> KTOR-1797 Prevent double quotes on header params

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/utils/Logging.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt
**Subsystem**
ktor-server-cio
**Motivation**
Sometimes 400 Bad Request response is not actually sent to clients because of coroutines hierarchy cancellation so this is why `testChunkedIsNotFinal` is flaky. This small bug is not that serious and doesn't provide a breach, just undesired behaviour.
**Solution**
There are several places when we respond with 400. In the case of wrong transfer encodings, we rethrow an exception after writing 400 response bytes. However, rethrowing exceptions leads to the whole coroutines structure cancellation so sometimes actual bytes don't get passed to the underlying socket in time, so the client sees unexpected EOF instead of 400.
=> KTOR-1590 Fix CIO server 400 response handling

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/utils/Logging.kt
**Subsystem**
ktor-client-tests
**Motivation**
Test `testLogResponseWithException` is flaky because there is a floating log entry that appears in different places.
**Solution**
Provide the ability to specify a log entry that is required but could appear later in the log
=> ~ fix floating log entry

ktor-client/ktor-client-core/jvm/test/HttpClientEngineTest.kt
**Subsystem**
ktor-client-core
**Motivation**
`testEarlyCancellation` is flaky. Example:
```
java.lang.AssertionError: Expected value to be true.
...
at kotlin.test.AssertionsKt.assertTrue$default(Unknown Source)
at HttpClientEngineTest$testEarlyCancellation$1.invokeSuspend(HttpClientEngineTest.kt:36)
...
```
**Solution**
Wait for different job completion before checking the dispatcher close flag.
=> KTOR-1661 Fix testEarlyCancellation

ktor-features/ktor-locations/api/ktor-locations.api, ktor-features/ktor-locations/jvm/src/io/ktor/locations/Location.kt, ktor-features/ktor-locations/jvm/test/io/ktor/tests/locations/LocationsTest.kt
**Subsystem**
Ktor-locations
**Motivation**
[KTOR-1684 ApplicationCall.locationOrNull raises error](https://youtrack.jetbrains.com/issue/KTOR-1684)
**Solution**
At the first step in 1.6.0 we will simply add `location` function and deprecate `locationOrNull` pointing to the new function. This will help us to fix this in 2.0.0 when we can make `locationOrNull` return the nullable `T`
=> KTOR-1684 Deprecate locationOrNull

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSessionImpl.kt
**Subsystem**
Web socket
**Motivation**
[Support explicit WebSocket session close](https://youtrack.jetbrains.com/issue/KTOR-340)
**Solution**
Calling `close` on `WebSocketSession` closes `outgoing` channel. When `incoming` receives `Frame.Close` it sends close to the outgoing channel, resulting in the crash. To fix just check that the outgoing channel is open.
=> KTOR-340 Prevent sending close to already closed outgoing ws channel

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/HttpUrlEncoded.kt, ktor-http/common/src/io/ktor/http/Parameters.kt, ktor-http/common/test/io/ktor/tests/http/ParametersBuilderTest.kt
**Subsystem**
ktor-http/common
**Motivation**
ktor-client cannot be used for URLs which are not supported by the URL Encoding format. It's because ktor-client always uses `URLBuidler` and there's no way to bypass the query encoding.
This PR adds an option to disable URL Encoding via `ParametersBuilder` (which can be passed to `URLBuidler`) without breaking changes.
(I mentioned in [this issue](https://github.com/ktorio/ktor/issues/1351) that `/api?k1=v1;k1=v1` (non-encoded `;`) is preventing us to use ktor-client. We needed to switch to another library just because of one character in the URL.)
**Solution**
`formUrlEncodeTo()` method is doing actual encoding. Added an option to bypass the encoding to `ParametersBuilder` and passed it to the method.
- Created `UrlEncodingOption` enum which …
=> Add an option to disable URL Encoding

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/certificates/CertificatePinner.kt
If you check okhttp implementation, the pinning require only one valid certificate https://github.com/1184893257/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/CertificatePinner.java
```
for (int i = 0, size = peerCertificates.size(); i < size; i++) {
X509Certificate x509Certificate = (X509Certificate) peerCertificates.get(i);
if (pins.contains(sha1(x509Certificate))) return; // Success!
}
```
**Subsystem**
HttpClient ios CertificatePinner
**Motivation**
Pinning should allow to pin only the leaf certificate public key
**Solution**
Replace all by any
=> Allow to pin only the leaf certificate

ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/FormDataContent.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/MultipartTest.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationRequest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/testing/TestApplicationEngineTest.kt
**Subsystem**
Client/Server, multipart
**Motivation**
[Test a POST with MultiPart using TestApplicationEngine does not succeed or fail](https://youtrack.jetbrains.com/issue/KTOR-345)
**Solution**
1. Send one CRLF instead of two after the last boundary (https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html)
2. Skip one CRLF after the last boundary when parsing multipart
=> KTOR-345 Do no send extra new line in multipart requests

ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/TestConnectorInterfaceUsed.kt
**Subsystem**
ktor-server-cio
**Motivation**
- CIO server startup doesn't fail-fast if connectors are not properly configured or the port is already in use.
- [KTOR-334 Connector host configuration (listen interface) is ignored](https://youtrack.jetbrains.com/issue/KTOR-334)
**Solution**
- Fix startup to crash if any connector is failed to start, block start function before the startup sequence complete
- pass host configuration and add test
=> Fix CIO connectors startup

ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngine.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HeadersTest.kt, ktor-http/common/src/io/ktor/http/HttpHeaders.kt
**Subsystem**
ktor-client
**Motivation**
If a user adds multiple unsafe headers to a request, then an UnsafeHeadersException will only be thrown on the first unsafe header it finds. The user will then remove that header from their request, try again, and then see another error with the other unsafe header that it finds.
**Solution**
All of the unsafe headers in a request should be identified and then returned to the user, rather than just the first one.
=> Check if there are multiple unsafe headers in request

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/routing/RouteSelectorTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
**Subsystem**
Server, routing
**Motivation**
[Mandatory Path Segment parameter can be empty, if no explicit route with trailing / is defined](https://youtrack.jetbrains.com/issue/KTOR-2054)
=> KTOR-2054 Fix routing with non optional trailing path parameter

ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOHttpsTest.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/CipherSuitesJvm.kt
**Subsystem**
Client, ktor-network-tls
**Motivation**
Issue : [1914](https://youtrack.jetbrains.com/issue/KTOR-1914)
The list contains TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 here :
https://github.com/ktorio/ktor/blob/master/ktor-network/ktor-network-tls/common/src/io/ktor/network/tls/CipherSuites.kt#L144-L152
but it is ignored by isSupported method here :
https://github.com/ktorio/ktor/blob/master/ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/CipherSuitesJvm.kt#L9-L12
which makes these cipher suites unavailable to be used because of :
https://github.com/ktorio/ktor/blob/master/ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSHandshakeType.kt#L70
**Solution**
This PR increases this limit from 128 bits to 256 bits, adds a test to verify it.
=> KTOR-1914 : Allow 256 bits Cipher Suites to be used

ktor-features/ktor-locations/api/ktor-locations.api, ktor-features/ktor-metrics-micrometer/api/ktor-metrics-micrometer.api, ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt, ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt
**Subsystem**
Server, Features/Micrometer
**Motivation**
When Ktor service is running in the environment with services written in other frameworks like Spring Boot, having standardized metric names is important for monitoring. Static, non-configurable "ktor.http.server" base name is inconvenient and breaks existing monitoring setup or at least requires special handling for Ktor services.
**Solution**
Make it configurable
=> KTOR-2210 Make base name of micrometer metrics configurable

ktor-features/ktor-jackson/jvm/src/io/ktor/jackson/JacksonConverter.kt, ktor-features/ktor-jackson/jvm/test/io/ktor/tests/jackson/JacksonTest.kt
**Subsystem**
Server, jackson
**Motivation**
[Can't override Kotlin module configuration using jackson dsl function](https://youtrack.jetbrains.com/issue/KTOR-1692)
**Solution**
Move default kotlin module registration after user-specified one. Jackson will ignore registering module that already exists.
=> KTOR-1692 Support custom kotlin modules in jackson {} DSL

ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
Just add more debug info for testEmbeddedServerCancellation to see why it's still running
=> KTOR-2264 Add debug info for testEmbeddedServerCancellation

ktor-network/common/src/io/ktor/network/sockets/SocketOptions.kt, ktor-network/jvm/src/io/ktor/network/sockets/ConnectUtilsJvm.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
ktor-network, ktor-server-cio
**Motivation**
[KTOR-2265 Fix flaky CIOSustainabilityTest.testBlockingConcurrency](https://youtrack.jetbrains.com/issue/KTOR-2265)
There are two issues around the test. The original issue is that client connections get reset in the test. The other issue is that it wasn't easy to reproduce it on local machines. 
The reason why it was so difficult was a small bug in the test that could reduce the workload accidentally. Fixing it makes it 100% reproducible. 
The reason why connections get reset is that when there is a requests burst, all requests overflows so-called TCP backlog because we use the default backlog size that may vary on different machines and operating systems. Requests that don't fit into the backlog, get replied with an RST frame …
=> Fix flaky CIOSustainabilityTest.testBlockingConcurrency[jvm]

ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingBuilder.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
**Subsystem**
Server - Routing
**Motivation**
Currently, only `post` has a typed overload. [KTOR-1344](https://youtrack.jetbrains.com/issue/KTOR-1344)
**Solution**
Added a typed overload to `put` and `patch` as well
=> KTOR 1344 - Unified pre-typed routes

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/CommandLine.kt
**Subsystem**
Server
**Motivation**
The assertion that the TLS key exists in the key store will trigger properly. Otherwise it fails with NPE somewhere in Netty pipepline during startup
**Solution**
Proper null check for absence of the key
=> KTOR-2311 Fix the assertion that the key exists in the key store

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/features/ContentNegotiation.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/ContentNegotiationTest.kt
**Subsystem**
Server, ContentNegotiation
**Motivation**
[call.respond() will not check or apply ContentNegotiation for some types](https://youtrack.jetbrains.com/issue/KTOR-2194)
**Solution**
Add a flag to `ContentNegotiation` feature that will check accept header of response and content-type header of the request
=> KTOR-2194 Force ContentNegotiation to verify Accept and ContentType header compliance

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultEnginePipeline.kt
**Subsystem**
Server
**Motivation**
Logging pipeline i/o errors stacktraces was too verbose (since they can often be due to client errors), and they have been filtered so that a single line error message is logged. But this line only states "io failed" whereas it should at least log the exception error message.
In my case, it was a permission problem on the server side (on the persistent sessions directory). It took me a painful debugging session to figure it out, whereas it's a trivial error that should be logged.
**Solution**
Have the engine log the i/o exception message.
=> Io error message logging

ktor-features/ktor-auth-jwt/api/ktor-auth-jwt.api, ktor-features/ktor-auth-jwt/jvm/src/io/ktor/auth/jwt/JWTAuth.kt, ktor-features/ktor-auth-jwt/jvm/test/io/ktor/auth/jwt/JWTAuthTest.kt
**Subsystem**
JWT Auth
**Motivation**
When interacting with `JWTCredential` & `JWTPrincipal`, to access the decoded JWT token, it's a bit clunky to need to do `credential.payload.<foo>` (or its variable based workarounds) - the classes are just wrappers to apply the Ktor interfaces
**Solution**
This PR simply adds an implementation of auth0-jwt's `Payload` interface by delegation.
It doesn't provide _much_ benefit, but the more fields accessed the more evident it becomes.
Before (snippet from the docs)
```
validate { credential ->
if (credential.payload.audience.contains(jwtAudience)) JWTPrincipal(credential.payload) else null
}
```
After
```
validate { credential ->
if (credential.audience.contains(jwtAudience)) JWTPrincipal(credential.payload) else null
}
```
=> add direct access to payload in JWTCredential & JWTPrincipal

ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSConfigBuilder.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/tests/TLSConfigBuilderTest.kt
**Subsystem**
CIO JVM TLSConfigBuilder
Fixing [KTOR-940](https://youtrack.jetbrains.com/issue/KTOR-940)
**Motivation**
It is legal (and possible with Apache HttpClientEngine) to use a keystore without a password. One valid and secure use-case is using a pki/smartcard middleware which is loaded as a keystore, and enforces itself the password/the smartcard pin.
**Solution**
Made password nullable
=> [KTOR-940] CIO TLSConfigBuilder JVM allow null as password

ktor-client/ktor-client-features/ktor-client-json/api/ktor-client-json.api, ktor-client/ktor-client-features/ktor-client-json/common/src/io/ktor/client/features/json/JsonSerializer.kt
One of the commits added a new method to the interface which broke source compatibility. Add circular delegations between old and new methods to fix it.
Side effect: new implementations of the interface will need to manually peek the method to override.
=> KTOR-1780 fix source compatibility

ktor-network/api/ktor-network.api, ktor-network/common/src/io/ktor/network/sockets/SocketOptions.kt, ktor-network/jvm/src/io/ktor/network/sockets/JavaSocketOptions.kt, ktor-network/jvm/test/io/ktor/network/sockets/tests/UDPSocketTest.kt
**Subsystem**
ktor-network
**Motivation**
ktor-network provides a coroutine-compatible implementation of Sockets and Channels but is pretty bare-bones at the moment. Broadcast UDP sockets are useful when advertising or discovering services on a network. Without setting `SO_BROADCAST` on the socket, broadcast messages are not properly sent.
**Solution**
Add a `broadcast` option to `UDPSocketOptions` to configure a UDP socket in broadcast mode.
See the following pull request by @ObsidianX for more details:
Closes https://github.com/ktorio/ktor/pull/1258
=> Add SO_BROADCAST option to UDP sockets

ktor-utils/common/src/io/ktor/util/collections/ConcurrentMap.kt, ktor-utils/common/src/io/ktor/util/collections/internal/ForwardListNode.kt, ktor-utils/common/test/io/ktor/util/collections/ConcurrentMapTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2482
`insertAfter` was not updating `previous` for current `next`, resulting in all `previous` pointing to `head`. That's why `previous.removeNext()` always removed first element after `head`
=> KTOR-2482 Fixed remove on ConcurrentMap

ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
`appendLn` was changed to `appendLine` in tracing, which always uses `\n` instead of platform line separators
=> KTOR-2505 fix testRoutingWithTracing on windows

ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRedirectTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Redirect.kt, ktor-features/ktor-auth/jvm/src/io/ktor/auth/OAuth2.kt, ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/Parameters.kt, ktor-http/common/src/io/ktor/http/Query.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/src/io/ktor/http/URLUtils.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt, ktor-http/jvm/src/io/ktor/http/URLUtilsJvm.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/http/UrlEncodedTest.kt
Disable query encoding/decoding when creating url from string
Proper fix is comming in 2.0.0 here #2367
=> KTOR-2057 fix http redirect with encoded URL

ktor-io/common/test/io/ktor/utils/io/ByteChannelSmokeTest.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
Fix [KTOR-2519](https://youtrack.jetbrains.com/issue/KTOR-2519)
=> KTOR-2519 fix ByteBufferChannel.readRemaining suspend when should not

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/fetch/LibDom.kt, ktor-utils/js/src/io/ktor/util/CryptoJs.kt
**Subsystem**
Client
**Motivation**
Even when it under `if` condition and standard Node.JS module, in webpack 4, it polyfill it into final bundle.
Since webpack 5, webpack not longer polyfill standard Node.JS modules, and report error.
So for WA this problem, need to use `eval('require')` instead of `require`
https://youtrack.jetbrains.com/issue/KT-46082
**Solution**
Webpack will not resolve `eval('require')('crypto')`, and it will be false branch of `if`
=> KTOR-2512 Require forces webpack to resolve dependency

ktor-features/ktor-metrics/api/ktor-metrics.api, ktor-features/ktor-metrics/jvm/src/io/ktor/metrics/dropwizard/DropwizardMetrics.kt, ktor-features/ktor-metrics/jvm/test/io/ktor/metrics/dropwizard/DropwizardMetricsTests.kt
**Subsystem**
ktor-metrics
**Motivation**
I was unpleasantly surprised to see that the `DropwizardMetrics` feature registered various MetricSets from `metrics-jvm`. Having them added for me in the Ktor feature means I cannot control the naming or configuration of those metrics, nor can I opt out entirely. It is easy to add those MetricSets outside of Ktor, so it's not like it's saving the user some huge burden by bundling that here. Ultimately, I don't think it's appropriate for Ktor to register metrics that aren't at all related to the core problem of measuring _Ktor specific_ things. 
**Solution**
Add a boolean to the feature's config that makes it possible to opt out. The default setting preserves the old behavior.
=> Make JVM MetricSet registration optional

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/Auth.kt, ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/DigestProviderTest.kt
Fix client digest auth realm handling to use the realm provided by the server if the realm is not configured in the client feature
**Subsystem**
ktor-client-auth
**Motivation**
[Digest authentition: using the realm of the 401 response to an initial incomplete request for an immediate second complete request including realm.](https://youtrack.jetbrains.com/issue/KTOR-1464)
This replaces PR #2236
=> KTOR-1464 Fix client Digest auth realm handling

ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/ByteBufferChannelInternals.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelLookAheadTest.kt
There were two issues:
* Channel closed with error didn't propagate it on reading through LookAheadSession
* Successfully closed channel that still has available to read bytes wasn't returning them when reading through LookAheadSession
=> KTOR-2278 Fix LookAheadSession on closed channel

ktor-io/posix/test/io/ktor/utils/io/VerifyingObjectPool.kt
**Subsystem**
ktor-io
**Motivation**
[KTOR-2685 Avoid using Kotlin_Any_hashCode ](https://youtrack.jetbrains.com/issue/KTOR-2685)
**Solution**
Since there is already `Any.identityHashCode()` in K/N, we no longer need to invoke `Kotlin_Any_hashCode` directly.
=> KTOR-2685 Migrate to Any.identityHashCode

ktor-server/ktor-server-core/jvm/src/io/ktor/application/ApplicationFeature.kt
**Subsystem**
Server
**Motivation**
This method is misleading. It only closes open resources, but doesn't remove feature interceptors.
Right now, there is no way to properly uninstall features, but also no clear use case for that.
=> KTOR-367 Deprecate uninstallFeature method

ktor-features/ktor-auth/jvm/src/io/ktor/auth/Authentication.kt, ktor-features/ktor-websockets/jvm/src/io/ktor/websocket/Routing.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/HostsRoutingBuilder.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/LocalPortRoutingBuilder.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolveTrace.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/StaticContentTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
Clean up and make routing resolving algorithm smarter. Compare not only direct children's priorities, but the whole successful path.
Ex: 
Route 1:  path, q=1 -> missing parameter, q=0.2
Route 2: path, q=1 -> parameter, q=0.8
If both of these routes match, the old algorithm would choose route 1, even though it has lower quality overall. It happens because it compares only siblings' quality, and when they are similar, it will choose the first one based on order. The new algorithm will compare the whole paths.
=> KTOR-2468 New routing resolve algorithm

ktor-features/ktor-auth-jwt/jvm/test/io/ktor/auth/jwt/JWTAuthTest.kt, ktor-features/ktor-auth-ldap/jvm/test/io/ktor/tests/auth/ldap/LdapAuthTest.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/AuthBuildersTest.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/BasicAuthTest.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/DigestTest.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/OAuth1a.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/OAuth2.kt, ktor-features/ktor-auth/jvm/test/io/ktor/tests/auth/UserHashedTableAuthTest.kt, ktor-features/ktor-locations/jvm/test/io/ktor/tests/locations/Verifiers.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/WebResourcesTest.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationCall.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationResponse.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/Utils.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/application/HandlerTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CachingHeadersTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CallIdTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CallLoggingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/CompressionTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/ConditionalHeadersTests.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/HeadTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/PartialContentTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/features/StaticContentTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/testing/TestApplicationEngineTest.kt
And replace all usages in tests
https://youtrack.jetbrains.com/issue/KTOR-2712
=> KTOR-2712 deprecate TestApplicationCall::requestHandled property

ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosClientEngine.kt
**Subsystem**
ktor-client-ios
**Motivation**
When executing the Http request test in the iOS unit test. You need to use runBlocking to block the current thread, but the IosEngine response uses the main thread to return the result, which will cause deadlock.
In fact, IosEngine does **NOT NEED** to consider using the main thread to return data. **This part of the logic should be guaranteed by Ktor users.**
**Solution**
Use the current thread to return the result
=> KTOR-2683 fixed iOS engine deadlock

ktor-io/common/src/io/ktor/utils/io/core/internal/ChunkBuffer.kt
Fix [KTOR-2442](https://youtrack.jetbrains.com/issue/KTOR-2442)
=> Make ChunkBuffer constructor public to allow leak tests

ktor-features/ktor-auth/jvm/src/io/ktor/auth/Authentication.kt, ktor-features/ktor-locations/jvm/test/io/ktor/tests/locations/LocationsTest.kt, ktor-features/ktor-websockets/jvm/src/io/ktor/websocket/Routing.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/HostsRoutingBuilder.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/LocalPortRoutingBuilder.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/Routing.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/routing/RouteSelectorTest.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationCall.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/TestApplicationResponse.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
[Should return 405 when route exists but not for given method instead of 404](https://youtrack.jetbrains.com/issue/KTOR-737)
* Make `RouteSelectorEvaluation` a sealed class with two children: `Success` and `Failure`
* `Failure` has `errorStatusCode` property to reply if the route doesn't match. For example, the `HttpMethodSelector` status code is 405
* The routing resolve algorithm keeps track of the best failed route and uses it to respond if no matches are found.
=> KTOR-737 Reply with proper status code on routing mismatch

ktor-client/ktor-client-core/common/src/io/ktor/client/features/observer/ResponseObserver.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt
**Subsystem**
Client, Logging
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-2711
**Solution**
Completing the response's context is redundant and even harmful since migrating to `HttpStatement`
=> KTOR-2711 Remove redundant completion of response coroutine

gradle.properties
**Subsystem**
Server, auth with JWT.
**Motivation**
The immediate goal is adding support for Elliptic Curve public keys. See https://youtrack.jetbrains.com/issue/KTOR-2387.
**Solution**
The dependency already supports EC but in the newest version. Starting from 0.16.0, but 0.17.0 I'd the first version in Maven Central so I propose to use it.
Looking at the release notes for behavior changes between 0.9.0 and 0.17.0, I didn't find anything worth attention, but it would be good if Ktor team member cloud double-check it.
**Testing**
`./gradlew jvmTest` locally succeeds. Replacing the dependency in my project that uses Ktor brings desired results - EC algo is supported.
=> KTOR-2387: Bump com.auth0:jwks-rsa to 0.17.0

MIGRATION_GUIDE.md
Added `https://` to Youtrack links since GitHub adds `https://github.com/ktorio/ktor/blob/main/` before the address and links lead to 404.
=> fix youtrack links

CONTRIBUTING.md
**Subsystem**
No related modules
**Motivation**
The default branch changed and try to fix it. https://youtrack.jetbrains.com/issue/KTOR-2742
**Solution**
Change the word `master` to `main` in CONTRIBUTING.md
=> Fix CONTRIBUTING.md PR default branch name

ktor-utils/jvm/src/io/ktor/util/reflect/TypeInfoJvm.kt
**Subsystem**
JVM Utils
**Motivation**
Fix https://youtrack.jetbrains.com/issue/KTOR-2709
Using kotlin.reflect.javaType doesn't produce an anonymous class for each call site. Also, this prevents Ktor from being affected by this compiler bug: https://youtrack.jetbrains.com/issue/KT-46797.
**Solution**
Use kotlin.reflect.javaType instead of type token pattern.
=> KTOR-2709 Use kotlin.reflect.javaType instead of type token

ktor-server/ktor-server-core/jvm/src/io/ktor/application/ApplicationEvents.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/application/DefaultApplicationEvents.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/routing/Routing.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt
Kotlin doesn't like having mixed usages
=> KTOR-2472 Replace deprecated EventDefinition usages

ktor-features/ktor-freemarker/jvm/src/io/ktor/freemarker/FreeMarker.kt, ktor-features/ktor-freemarker/jvm/test/io/ktor/tests/freemarker/FreeMarkerTest.kt, ktor-features/ktor-mustache/jvm/src/io/ktor/mustache/Mustache.kt, ktor-features/ktor-mustache/jvm/test/io/ktor/mustache/MustacheTest.kt, ktor-features/ktor-pebble/jvm/src/io/ktor/pebble/Pebble.kt, ktor-features/ktor-pebble/jvm/test/io/ktor/pebble/PebbleTest.kt, ktor-features/ktor-thymeleaf/jvm/src/io/ktor/thymeleaf/Thymeleaf.kt, ktor-features/ktor-thymeleaf/jvm/test/io/ktor/thymeleaf/ThymeleafTest.kt, ktor-features/ktor-velocity/jvm/src/io/ktor/velocity/Velocity.kt, ktor-features/ktor-velocity/jvm/src/io/ktor/velocity/VelocityTools.kt, ktor-features/ktor-velocity/jvm/test/io/ktor/tests/velocity/VelocityTest.kt
`StatusPages` can't handle errors that happen in writing bodies, because response was already sent at this point. To fix this, move all the templates rendering before responding.
=> KTOR-343 Fix exception in template can't be handled in StatusPages

ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyCustomChannelPipelineConfigurationTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
**Subsystem**
Server, ktor-server, ktor-server-netty
**Motivation**
I'm working on project where we need to add few organization cross cutting channel handler. Current implementation doesn't expose any ways to add our channel handler.
https://github.com/ktorio/ktor/issues/1909
Fix for [KTOR-356](https://youtrack.jetbrains.com/issue/KTOR-356).
**Solution**
provide a way to configure netty pipeline with user provided custom `channelHandler`.  The user provided channel handler will be added in the channel pipeline along with the default channelHandler added [here].(https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt#L94).
```
embeddedServer(Netty, port = configuration.server.port, configure = {
channelPipelineConfig …
```
=> KTOR-356 fix to provide a way to configure netty pipeline with user provided custom channel handler

ktor-network/js/src/io/ktor/network/sockets/SocketTimeoutException.kt, ktor-network/posix/src/io/ktor/network/sockets/SocketTimeoutException.kt
Fix https://youtrack.jetbrains.com/issue/KTOR-2276
The `SocketTimeoutException` class is duplicated in the Ktor source code in `ktor-network` and `ktor-client-core` modules, which is causing issues for native targets. See the expect classes in the same packages here:
https://github.com/ktorio/ktor/blob/082156982d894297fa2408829845b71683dc54bf/ktor-network/common/src/io/ktor/network/sockets/Sockets.kt#L128
https://github.com/ktorio/ktor/blob/082156982d894297fa2408829845b71683dc54bf/ktor-client/ktor-client-core/common/src/io/ktor/network/sockets/TimeoutExceptionsCommon.kt#L22
On the JVM, one of the actuals is a typealias to `java.net.SocketTimeoutException` so there are no duplicate classes.
However, in the posix and js source sets, they are both declared as `public actual class`. On native …
=> KTOR-2276 Fix unbound public symbol error for SocketTimeoutException

ktor-io/common/test/io/ktor/utils/io/StringsTest.kt, ktor-io/jvm/src/io/ktor/utils/io/internal/Strings.kt
https://youtrack.jetbrains.com/issue/KTOR-2868
=> ByteReadChannel.readUTF8Line() indefinitely returns empty lines when `\r` is not followed by `\n`

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/BodyProgress.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/DelegatedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/ResponseObserver.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpResponsePipeline.kt, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ClientPipelinesTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PluginsTest.kt
Otherwise, it's impossible to modify response, since context has its own instance of response.
=> KTOR-2822 Change `HttpReceivePipeline` context to Unit

buildSrc/build.gradle.kts
**Subsystem**
Build configuration
**Motivation**
We need the ability to customize the kotlin_version in the train/user projects
=> Allow override kotlin_version via -P for buildSrc

CHANGELOG.md
As it's not released in 1.6.1
**Subsystem**
**Motivation**
**Solution**
=> Remove watchosx64 from the changelog

CHANGELOG.md
**Subsystem**
Documentation
**Motivation**
Updating Kotlin / coroutines / serialization dependencies is a breaking change. It's hard to find the compatible version of ktor with the corresponding Kotlin version as is, because of the disparate versioning. Including them in the changelog along with any other behavior change is the minimum, because updating ktor might pull any project's Kotlin version over to a new major version.
Version 1.2.3 and 1.4.1 gave the right significance to these updates, it would be nice if that convention was kept.
**Solution**
Updated version history based on Git Blame of gradle.properties.
Also included the suggested change by https://youtrack.jetbrains.com/issue/KTOR-372#focus=Comments-27-4951326.0-0
=> Update changelog with some missing breaking changes

gradle.properties, ktor-client/ktor-client-cio/posix/src/io/ktor/client/engine/cio/LoaderNative.kt, ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/Curl.kt, ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/Ios.kt
**Subsystem**
Client
**Motivation**
Prepare for lazy top-level property initialization strategy in Kotlin/Native.
We consider enabling this strategy by default with new memory manager.
**Solution**
`@EagerInitialization` annotation forces a property to be initialized eagerly on program startup, like it happens for any top-level property in current non-lazy init strategy.
If lazy init strategy is not enabled, this annotation doesn't have any effect, so it is safe to merge it to `main` branch. But the annotation is available since Kotlin 1.5.30-RC, so the version update would be required.
=> Force eager initialization for initHook on Native

ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSConfigBuilder.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/tests/TLSConfigBuilderTest.kt
**Subsystem**
Server - Core - TLSConfigBuilder
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-3047
**Solution**
Add check for null
=> KTOR-3047 Fail when cert chain does not exist for alias

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationRequest.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerTestSuite.kt
This fix unifies behavior with other engines
=> KTOR-2991 Do not treat semicolon as separator in Netty engine.

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/AuthTokenHolder.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt
**Subsystem**
Client
**Motivation**
After clearing the tokens, we could not start loading the tokens again because the initialized flag was not reset
e.g., log out of one account and log in to another was impossible
**Solution**
just set initialized to null when clearing tokens
=> KTOR-3008 Fixed Client Bearer Feature 

ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/Auth.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt, ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt
**Subsystem**
Ktor Client, Auth Feature
**Motivation**
Auth feature uses global constants during token refresh process which are not marked with @ThreadLocal annotation. This makes it impossible to perform refresh from non-main thread in Kotlin/Native targets.
I attached a stack trace to [the YouTrack issue](https://youtrack.jetbrains.com/issue/KTOR-3055).
**Solution**
In order to make it work on iOS I annotated 2 constants as ThreadLocal.
=> KTOR-3055 Add @ThreadLocal annotation to top level constants

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/observer/ResponseObserver.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ResponseObserverTest.kt
**Subsystem**
Ktor Client ResponseObserver interceptor.
**Motivation**
The Ktor Client ResponseObserver interceptor is heavy, therefore it becomes tricky to avoid the overhead when one needs the interceptor just for a subset of requests. Since the interceptor is attached on the Client and not a single call, the only option one has currently is to use two different clients.
**Solution**
The filtering support for the client response interceptor would provide the possibility to enable the interceptor for certain requests only based on a request header or parameter or any other flag.
Example usage:
```
val responseObserver = ResponseObserver(observer) {
feature.level(it.callContext()).debug
}
```
=> KTOR-2992 Add filtering support in Ktor client response interceptor

ktor-client/ktor-client-curl/posix/test/io/ktor/client/engine/curl/test/CurlNativeTests.kt, ktor-client/ktor-client-features/ktor-client-auth/common/test/io/ktor/client/features/auth/AuthTest.kt, ktor-client/ktor-client-features/ktor-client-websockets/common/test/io/ktor/client/tests/features/WebSocketRemoteTest.kt, ktor-client/ktor-client-tests/build.gradle.kts
Native engines were not registered for tests outside of `ktor-client-tests` modules.
=> KTOR-3069 Register native engines in tests

ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-network/ktor-network-tls/common/src/io/ktor/network/tls/OID.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/api/ktor-network-tls-certificates.api, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/Certificates.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOClientCertTest.kt, ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/EmbeddedServer.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/EngineConnectorConfig.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/ServerInitializer.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/JettyClientCertTest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestBase.kt, ktor-server/ktor-server-test-suites/build.gradle.kts, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ClientCertTestSuite.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt, ktor-server/ktor-server-tomcat/jvm/test/io/ktor/tests/server/tomcat/TomcatEngineTest.kt
**Subsystem**
Netty, Jetty and Tomcat Server
**Motivation**
Some TLS connections are secured by client certificate authentication. This feature is implemented in Netty, Jetty and Tomcat, but it is currently not possible to use it in Ktor.
**Fixing**
[KTOR-742](https://youtrack.jetbrains.com/issue/KTOR-742) (Netty)
[KTOR-1122](https://youtrack.jetbrains.com/issue/KTOR-1122) (Jetty)
**Solution**
@andrey-vasilyev and I implemented the client certificate authentication for the server engines Netty, Jetty and Tomcat.
Note: Smaller PR of #2028
=> KTOR-742, KTOR-1122 - Add Jetty, Netty and Tomcat Client Certificate Authentication

ktor-utils/jvm/src/io/ktor/util/converters/ConversionServiceJvm.kt, ktor-utils/jvm/test/io/ktor/tests/utils/converters/DataConversionTest.kt
**Subsystem**
Server-Core, JVM, DefaultConversionService
**Motivation**
Add UUID to DefaultConversionService  - https://youtrack.jetbrains.com/issue/KTOR-1264
```
val id: UUID by call.parameters
```
**Solution**
Added UUID
=> KTOR-1264 - Add UUID to DefaultConversionService

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultResponseValidation.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ExceptionsTest.kt
**Subsystem**
Client core
**Motivation**
KTOR-3128 https://youtrack.jetbrains.com/issue/KTOR-3128
Currently, the exception contains only the URL, but the used method is helpful too to understand and find the cause.
**Solution**
Add the method to the exception
=> KTOR-3128 Add method to ResponseException

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CommonHttpClientTest.kt
**Subsystem**
Client
**Motivation**
KTOR-3116
It seems that the original intention of closing installed `Closeable` features are not working properly due to an added layer of indirection of `FEATURE_INSTALLED_LIST` key at https://github.com/ktorio/ktor/blob/92f4e96b6f863ffbfc3f6afae52a8ac584a2be3b/ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClientConfig.kt#L75
The demo test fails because the only key in `attributes` is this `FEATURE_INSTALLED_LIST`, and all features are under the `Attributes` value of this key.
**Solution**
This PR retrieves the correct "map" for installed features to invoke the `close()` function on them as originally intended.
=> KTOR-3116 Fix closing installed features

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ShutdownHook.kt
**Subsystem**
Server
**Motivation**
Logging in shutdown thread looks not informative:
```
14:02:10  INFO Thread-1 link.kotlin.server.ApplicationFactory Going to shutdown X
```
**Solution**
Set thread name to ShutdownHook thread
=> Add name to ShutdownHook thread, for better logging experience

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/ContentNegotiation.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/test/io/ktor/client/plugins/ContentNegotiationTests.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/test/io/ktor/client/plugins/TestContentConverter.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvm/src/io/ktor/server/plugins/ContentNegotiation.kt
**Subsystem**
Client
**Motivation**
The `ContentConverter` documentation as well as the server implementation of `ContentNegotiation` both specify that `ContentConverter::(de)serialize` should return null when the converter is not suitable for the current content-type/body. This is to allow other registrations / converters to (de)serialize the content.
The client implementation of `ContentNegotiation` only tried (de)serialization with the first matching registration.
**Solution**
Instead of only (de)serializing with the first matching registration, this PR changes the behaviour to filter out matching registrations and try (de)serialization on each until one succeeds.
=> KTOR-3346 ContentNegotiation plugins don't accept null-responses from ContentConverts

ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/EngineHeaderFlushingTest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/NettyResponsePipeline.kt
**Subsystem**
Server
**Motivation**
Headers are only flushed after first byte is written [KTOR-3364](https://youtrack.jetbrains.com/issue/KTOR-3364). We need the same behavior for `Jetty`, `Netty` and other engines, but `Netty` is different now.
**Solution**
Flush respond headers right after writing them to the channel.
=> KTOR-3364 Flush Header With Netty

gradle.properties
Fix [KTOR-3422](https://youtrack.jetbrains.com/issue/KTOR-3422)
=> KTOR-3422 Upgrade kotlin to 1.6.0

ktor-server/ktor-server-plugins/ktor-server-cors/jvm/src/io/ktor/server/plugins/CORS.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/plugins/CORSTest.kt
**Subsystem**
Server
**Motivation**
CORS plugin respond with `4xx` code with empty `Access-Control-Request-Headers` 
[KTOR-445](https://youtrack.jetbrains.com/issue/KTOR-445)
**Solution**
Filter empty elements in `requestHeaders` for preflight requests
=> KTOR-445 corsCheckRequestHeaders false

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/EngineMain.kt
**Subsystem**
Server
**Motivation**
Ability to configure all of the simple Netty engine properties via `application.conf`.
I was surprised to discover after reading the docs that `runningLimit` was not set in `EngineMain`.
**Solution**
Like with the other simple properties, read from application configuration and assign to `NettyApplicationEngine` if present and valid.
=> KTOR-3464 Set missing simple properties in Netty EngineMain

ktor-client/ktor-client-plugins/ktor-client-websockets/common/test/io/ktor/client/tests/plugins/WebSocketRemoteTest.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/backend/HttpServer.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/backend/ServerPipeline.kt
[KTOR-3461](https://youtrack.jetbrains.com/issue/KTOR-3461)
=> KTOR-3461 Exceptions are Swallowed in `HttpClient.wss` block

build.gradle.kts, buildSrc/src/main/kotlin/IdeUtils.kt, buildSrc/src/main/kotlin/JvmConfig.kt, buildSrc/src/main/kotlin/NativeUtils.kt, ktor-client/ktor-client-core/build.gradle.kts, ktor-client/ktor-client-curl/build.gradle.kts, ktor-client/ktor-client-curl/desktop/interop/libcurl.def, ktor-client/ktor-client-curl/macosArm64/src/io/ktor/client/engine/curl/CurlMac.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-server/ktor-server-test-host/build.gradle.kts, ktor-server/ktor-server-test-suites/build.gradle.kts
**Subsystem**
Infrastructure 
**Motivation**
It is not possible to build Ktor on Apple Silicon Mac.
https://youtrack.jetbrains.com/issue/KTOR-3248
**Solution**
Adopt Gradle targets
=> KTOR-3248 Build Ktor on Apple Silicon

build.gradle.kts
**Subsystem**
Infrastructure
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-3561
Current outdated nodeJS version exists build on Apple Arm: `'Resolving NPM dependencies using yarn' returns 139`
**Solution**
Bump nodeJS to 16.13.1
=> KTOR-3561 Bump nodeJS to 16.13.1

ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt
```
internal suspend fun awaitAtLeastNBytesAvailableForRead(count: Int) {
while (availableForRead < count && !closed) {
// !!! writer can flush here !!!
slot.sleep()
}
}
```
Usually it's ok, because the next writer will wake up reader. But if it was the last writing, only `close` will try to do it. Internally, it checks that if there is nothing to flush, then no need to resume the `slot`, which is wrong. Reader should be woken up anyway.
=> KTOR-2776 Fix race condition in closing ByteChannelSequential

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/CallLogging.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/plugins/CallLoggingTest.kt
Call `withMdcBlock` multiple times, to add new MDC entries to the context.
Also, migrate test to the new API
=> KTOR-536 Support for adding values to the MDC later on in the pipeline.

ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/plugins/CookiesTest.kt
Ticket: [KTOR-3497](https://youtrack.jetbrains.com/issue/KTOR-3497)
**Motivation**
Current cookie implementation supports [rfc6265](https://datatracker.ietf.org/doc/html/rfc6265#page-13), but browsers support old [netscape spec](https://curl.se/rfc/cookie_spec.html) in cookie names
**Solution**
Support netscape spec: allow characters ()<>@:/\"[]? in cookie names. 
Also browsers support comma and white space as [stackowerflow question](https://stackoverflow.com/questions/1969232/what-are-allowed-characters-in-cookies) says, so this changes allow them too.
=> KTOR-3497 HttpCookies: parse / in the name of a cookie

ktor-server/ktor-server-plugins/ktor-server-cors/jvm/src/io/ktor/server/plugins/CORS.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvm/test/io/ktor/tests/CORSTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/plugins/CORSTest.kt
**Subsystem**
Server CORS plugin
**Motivation**
Regression caused by https://youtrack.jetbrains.com/issue/KTOR-2872
well-intentioned check changed behavior of `Access-Control-Allow-Origin`.
**Solution**
Revert KTOR-2872
- No revert commit due to changed package name and new testApplication api
@rsinukov Do you plan to release `1.6.8` or similar? If so, I would also patch this change into `1.6` branch.
=> Revert KTOR-2872 due regression

ktor-client/ktor-client-plugins/ktor-client-json/ktor-client-serialization/js/src/SerializerInitializer.kt
**Subsystem**
Client
**Motivation**
Since 1.6.20 there is lazy initialization of properties. So now using of properties as side effect is not possible.
For compatibility annotation `@EagerInitialization` can be used.
**Solution**
Using of `@EagerInitialization` on side-effect property
=> Initializer should be initialized eagerly

build.gradle.kts
This PR updates dokka to 1.6.10 and removes a workaround for the [ZipException](https://youtrack.jetbrains.com/issue/KTOR-1032#focus=Comments-27-4865014.0-0) as it has been [fixed](https://github.com/Kotlin/dokka/pull/2258).
I've built docs via `./gradlew clean dokkaHtmlMultiModule` - everything seems OK
=> Update Dokka to 1.6.10 and remove ZipException workaround for JS files

ktor-network/jvm/src/io/ktor/network/sockets/CIOReader.kt, ktor-network/jvm/src/io/ktor/network/sockets/CIOWriter.kt, ktor-network/jvm/src/io/ktor/network/sockets/ConnectUtilsJvm.kt, ktor-network/jvm/src/io/ktor/network/sockets/DatagramSocketImpl.kt, ktor-network/jvm/src/io/ktor/network/sockets/JavaSocketOptions.kt, ktor-network/jvm/src/io/ktor/network/sockets/ServerSocketImpl.kt, ktor-network/jvm/src/io/ktor/network/sockets/SocketImpl.kt, ktor-network/jvm/src/io/ktor/network/sockets/UDPSocketBuilderJvm.kt
https://youtrack.jetbrains.com/issue/KTOR-3659
Since https://github.com/ktorio/ktor/pull/2603 was merged the sockets no longer work on Android API level < 24.
This PR fixes the issue by only calling Java 1.7 APIs if they are available, and fall back to older APIs otherwise. 
I have not tested this PR yet on Android, will do that soon.
=> KTOR-3659 Fix sockets on Android

ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/DefaultTransform.kt
According to  https://www.rfc-editor.org/rfc/rfc2046.html#section-4.1.2 the default charset to `Text/*` is ASCII, so using `Charsets.ISO_8859_1` doesn't make sense here. `Application/json` and other popular types have `UTF-8` as default charset.
=> KTOR-789 Use UTF-8 as default charset for text and forms

ktor-client/ktor-client-plugins/ktor-client-encoding/common/src/ContentEncoding.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/test/ContentEncodingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Encoding.kt
**Subsystem**
- Client
- ContentEncoding plugin
**Motivation**
Client should not decode empty body: https://youtrack.jetbrains.com/issue/KTOR-3781
```
Unexpected exception occurred during switching: kotlinx.coroutines.channels.ClosedReceiveChannelException: Unexpected EOF: expected 10 more bytes
at io.ktor.utils.io.ByteBufferChannel.readFullySuspend(ByteBufferChannel.kt:594)
at io.ktor.utils.io.ByteBufferChannel.readFully(ByteBufferChannel.kt:586)
at io.ktor.utils.io.ByteBufferChannel.readPacketSuspend(ByteBufferChannel.kt:802)
at io.ktor.utils.io.ByteBufferChannel.readPacket$suspendImpl(ByteBufferChannel.kt:788)
at io.ktor.utils.io.ByteBufferChannel.readPacket(ByteBufferChannel.kt)
at io.ktor.utils.io.ByteReadChannelKt.readPacket(ByteReadChannel.kt:207)
at …
```
=> Ktor client content encoding: do not decode empty body

ktor-server/ktor-server-plugins/ktor-server-conditional-headers/api/ktor-server-conditional-headers.api, ktor-server/ktor-server-plugins/ktor-server-conditional-headers/jvmAndNix/src/io/ktor/server/plugins/conditionalheaders/ConditionalHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-partial-content/jvmAndNix/src/io/ktor/server/plugins/partialcontent/PartialContent.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/ConditionalHeadersTests.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/ConditionalHeadersTests.kt
When replying with data class, there is no way to set headers on `OutgoingContent` and headers set on response are ignored
https://youtrack.jetbrains.com/issue/KTOR-728
=> KTOR-728 Use conditional headers from response too

ktor-client/ktor-client-plugins/ktor-client-auth/api/ktor-client-auth.api, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/Auth.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BearerAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Auth.kt
https://youtrack.jetbrains.com/issue/KTOR-3795
When refresh token request fails with 401 it tries to refresh token again, resulting in an infinite cycle. Since token refreshing in a client's code, they need to mark such requests, so we can have a special case for them.  
Marking function is only available inside `refreshToken {}` block.
=> KTOR-3795 Break infinite refresh token cycle on 401

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/HttpClientJs.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/HttpClientJvm.kt, ktor-client/ktor-client-core/posix/src/io/ktor/client/HttpClient.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/src/io/ktor/client/plugins/json/JsonPlugin.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/src/io/ktor/client/plugins/json/JsonSerializer.kt, ktor-client/ktor-client-plugins/ktor-client-json/ktor-client-gson/jvm/src/io/ktor/client/plugins/gson/GsonSerializer.kt, ktor-client/ktor-client-plugins/ktor-client-json/ktor-client-jackson/jvm/src/io/ktor/client/plugins/jackson/JacksonSerializer.kt, ktor-client/ktor-client-plugins/ktor-client-json/ktor-client-serialization/common/src/io/ktor/client/plugins/kotlinx/serializer/KotlinxSerializer.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-hsts/jvmAndNix/src/io/ktor/server/plugins/hsts/HSTS.kt, ktor-server/ktor-server-plugins/ktor-server-metrics/jvm/src/io/ktor/server/metrics/dropwizard/DropwizardMetrics.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestEngine.kt
Added links to a migration guide for some deprecated members.
Note that these links will work AFTER releasing v2.0.0 as currently a migration guide is only available under https://ktor.io/docs/eap.
=> KTOR-3966 add links to a migration guide

ktor-shared/ktor-serialization/ktor-serialization-kotlinx/common/src/io/ktor/serialization/kotlinx/SerializerLookup.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/test/JsonSerializationTest.kt, ktor-utils/jvm/src/io/ktor/util/debug/IntellijIdeaDebugDetectorJvm.kt
https://youtrack.jetbrains.com/issue/KTOR-3782
=> KTOR-3782 Fix contextual serializer with kotlinx

ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/OAuth2Test.kt
**Subsystem**
Server, OAuth2 module.
**Motivation**
See KTOR-3945
**Solution**
Separate scopes with space. These are encoded to "+" by the URL encoder. (Generally encoding to "%20" is also acceptable, so I'm not going to test that here.)
Also fix the tests that were failing to catch this due to accidental double-decoding of query string.
Question: Can we catch these double-decoding errors systematically? IDE inspections? Type-level guards?
=> KTOR-3945 Fix OAuth scopes encoded to %2B

ktor-utils/jvm/src/io/ktor/util/Deflater.kt, ktor-utils/jvm/test/io/ktor/tests/utils/DeflaterReadChannelTest.kt
**Subsystem**
Utils
**Motivation**
The Deflater implementation is causing memory leaks when the response channel gets closed (for example when a peer resets the connection) and the gzipped content is larger than the ByteBufferChannel backing buffer (4088). More details in the YT ticket: https://youtrack.jetbrains.com/issue/KTOR-4028
**Solution**
Refactored the `ByteWriteChannel.deflated` method to not use an intermediary channel, but instead to write the compressed body directly into the response channel. This will fix the memory leak and maybe at the same time bring also a small performance improvement by not needing to spawn an extra coroutine and an extra copy across buffers.
Another solution could have been to pass the coroutineContext of the first coroutine to the second one, instead …
=> KTOR-4028 Fix Compression plugin memory leak

ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt
https://youtrack.jetbrains.com/issue/KTOR-4130
I am not sure how to add a test for it, since there is no side effect of loading a config, unless it's invalid and fails on crashing. But then we lose the ability to test proper default config, which is more important.
=> KTOR-4130 Only load default config if custom is not set in tests

ktor-utils/common/test/io/ktor/util/HashFunctionTest.kt, ktor-utils/posix/src/io/ktor/util/CryptoNative.kt
Fix [KTOR-4217](https://youtrack.jetbrains.com/issue/KTOR-4217/%60io.ktor.util.sha1()%60-always-returns-da39a3ee5e6b4b0d3255bfef956)
=> KTOR-4217 Fix sha1 argument

ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlProcessor.kt, ktor-server/ktor-server-test-host/build.gradle.kts, ktor-server/ktor-server-test-host/nix/src/io/ktor/server/testing/BaseTestNix.kt, ktor-test-dispatcher/build.gradle.kts, ktor-test-dispatcher/darwin/src/TestDarwin.kt, ktor-test-dispatcher/linuxX64/src/TestLinuxX64.kt, ktor-test-dispatcher/mingwX64/src/TestMingwX64.kt, ktor-test-dispatcher/posix/src/TestWorker.kt, ktor-utils/build.gradle.kts, ktor-utils/darwin/src/io/ktor/util/ThreadInfoDarwin.kt, ktor-utils/linuxX64/src/io/ktor/util/ThreadInfoLinux.kt, ktor-utils/mingwX64/src/io/ktor/util/ThreadInfoMingw.kt, ktor-utils/nix/interop/threadUtils.def, ktor-utils/posix/src/io/ktor/util/CoroutineUtils.kt, ktor-utils/posix/src/io/ktor/util/ThreadInfo.kt
Fix [KTOR-4198](https://youtrack.jetbrains.com/issue/KTOR-4198/Print-Native-Stacktrace-on-Timeout)
=> KTOR-4198 Add native stacktrace on timeout

ktor-server/ktor-server-plugins/ktor-server-locations/jvm/src/io/ktor/server/locations/BackwardCompatibleImpl.kt, ktor-server/ktor-server-plugins/ktor-server-locations/jvm/test/io/ktor/tests/locations/LocationsTest.kt
**Subsystem**
Locations feature/plugin
**Motivation**
Fixes KTOR-836
**Solution**
Restore trailing slash if it was present prior to all the `.split("/")` calls. It is kind of similar to how it always prefixes a "/" except that is always required.
=> KTOR-836 Fix Location href stripping trailing slash.

ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/test/io/ktor/tests/resources/ResourcesTest.kt
**Subsystem**
Server (`ktor-server-resources`)
**Motivation**
This PR aims to solve KTOR-4239, see that ticket for more information.
**Solution**
Simply retrieve the result of the `method()` call and return it. There may be a more idiomatic way to do this, but I could not figure out a simpler solution.
=> Return correct route in Resources (KTOR-4239)

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingResolveContext.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4267
=> KTOR-4267 Fixed routing returns 405 even for not completely matched paths

ktor-server/ktor-server-plugins/ktor-server-auto-head-response/jvmAndNix/src/io/ktor/server/plugins/autohead/AutoHeadResponse.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORSConfig.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/routing/CORS.kt
For CORS, I've referenced a new route scoped plugin and changed a port in a snippet because `5000` can be in use on macOS by the Airplay receiver.
=> Update API docs for AutoHead and CORS

ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/AuthenticationContext.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/AuthBuildersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4250
This part of the app should be redesigned to remove circular reference between `ApplicationCall` and `AuthenticationContext`. But for now, to keep binary compatibility, we can only update reference every time context is accessed.
=> KTOR-4250 Fix missing routing params in auth interceptors

ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORS.kt
**Subsystem**
Server Plugin CORS
**Motivation**
ReplaceWith didn't work because the new import was not fully qualified.
**Solution**
Fixed ReplacedWith.
=> CORS: Fix deprecation ReplaceWith

ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlProcessor.kt
Fix warning: CurlProcessor.kt: (62, 43): Parameter 'api' is never used
**Subsystem**
Client Curl
**Motivation**
The Parameter 'api' is never used, because it is overridden in the next line.
**Solution**
Remove the overridden variable, because the value of the parameter is the same (line 54).
=> Curl: Use parameter api

ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/test/io/ktor/tests/http/ContentTypeTest.kt
Fix [KTOR-4105](https://youtrack.jetbrains.com/issue/KTOR-4105/Darwin-and-Kotlin-JS-List-has-more-than-one-element-error-when-h)
=> KTOR-4105 Consider only last content-type header

ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngine.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientTestServer.kt
Fix [KTOR-3900](https://youtrack.jetbrains.com/issue/KTOR-3900/A-native-application-with-the-Darwin-engine-doesn-t-make-a-reque)
=> KTOR-3900 Make Darwin engine work in runBlocking

ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngine.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinUrlUtils.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientTestServer.kt, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/test/io/ktor/tests/http/ContentTypeTest.kt
Fix [KTOR-1858](https://youtrack.jetbrains.com/issue/KTOR-1858/Ios-NullPointerException-when-query-parameters-contain-cyrillic-)
=> KTOR-1858 Sanitize url in Darwin engine

build.gradle.kts
Fix [KTOR-4290](https://youtrack.jetbrains.com/issue/KTOR-4290/Revert-Dokka-to-1-6-10-due-to-Publication-Freeze)
=> KTOR-4290 Revert dokka to the latest working version

ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/src/io/ktor/serialization/kotlinx/json/JsonSupport.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/test/JsonSerializationTest.kt
**Subsystem**
Client
**Motivation**
The documentation says that the JSON configuration is "mode is not strict so extra json fields are ignored" but is not what is actually doing.
**Solution**
Add `ignoreUnknownKeys = true` to make the JSON configuration work as expected.
=> Fix DefaultJson documentation

.github/images/ktor-logo-for-dark.svg, .github/images/ktor-logo-for-light.svg, README.md
Add the light logo as well and update the logo position to be centered.
GitHub recently made it possible to [Specify theme context for images in Markdown](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/).
The images were taken from [Ktor documentation repository](https://github.com/ktorio/ktor-documentation/blob/main/images/ktor_logo.svg).
| Before | After |
| ------- | ------ |
| ![before](https://user-images.githubusercontent.com/29678011/170962810-b268be02-cf48-4736-84ca-523991fee3cc.png) | ![after](https://user-images.githubusercontent.com/29678011/170962848-6078729e-af5a-4c59-8791-b966cf4b88dc.png) |
=> Add dark logo to be used in README

ktor-server/ktor-server-plugins/ktor-server-cors/api/ktor-server-cors.api, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORSConfig.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CORSTest.kt
**Subsystem**
`ktor-server-cors` plugin
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-316
Ktor Server has been lacking proper CORS support for years.
In our specific case, we validate CORS origins using a regex defined externally and injected into various API projects by the CI/CD. Note that these projects are developed using various languages and frameworks, hence why a single, simple regex was chosen to implement CORS check globally.
Until now, our way to implement this in our Ktor backends was using an altered copy of the CORS plugin made like 2 or 3 years ago, largely unmaintained. I'm in the process of upgrading a very old (more than 4 years) important Kotlin API project to the latest and greatest, including Ktor 2. During this process I checked on the linked issue above …
=> KTOR-316 Add custom validation support for origin in CORS plugin

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/test/server/ClientTestServer.kt, buildSrc/src/main/kotlin/test/server/TestServer.kt, buildSrc/src/main/kotlin/test/server/tests/Auth.kt, buildSrc/src/main/kotlin/test/server/tests/Builders.kt, buildSrc/src/main/kotlin/test/server/tests/Cache.kt, buildSrc/src/main/kotlin/test/server/tests/CloseableGroup.kt, buildSrc/src/main/kotlin/test/server/tests/Content.kt, buildSrc/src/main/kotlin/test/server/tests/Cookies.kt, buildSrc/src/main/kotlin/test/server/tests/Download.kt, buildSrc/src/main/kotlin/test/server/tests/Encoding.kt, buildSrc/src/main/kotlin/test/server/tests/Events.kt, buildSrc/src/main/kotlin/test/server/tests/Features.kt, buildSrc/src/main/kotlin/test/server/tests/Forms.kt, buildSrc/src/main/kotlin/test/server/tests/Headers.kt, buildSrc/src/main/kotlin/test/server/tests/Json.kt, buildSrc/src/main/kotlin/test/server/tests/Logging.kt, buildSrc/src/main/kotlin/test/server/tests/MultiPartFormData.kt, buildSrc/src/main/kotlin/test/server/tests/Multithreaded.kt, buildSrc/src/main/kotlin/test/server/tests/Redirect.kt, buildSrc/src/main/kotlin/test/server/tests/Serialization.kt, buildSrc/src/main/kotlin/test/server/tests/Tcp.kt, buildSrc/src/main/kotlin/test/server/tests/Timeout.kt, buildSrc/src/main/kotlin/test/server/tests/Upload.kt, buildSrc/src/main/kotlin/test/server/tests/WebSockets.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-http/common/src/io/ktor/http/Url.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/ServerURLBuilderTest.kt, ktor-shared/ktor-resources/common/test/io/ktor/tests/resources/ResourceUrlBuilderTest.kt
Fix [KTOR-4390](https://youtrack.jetbrains.com/issue/KTOR-4390/CIO-Websockets-request-doesnt-include-query-parameters)
=>  KTOR-4390 Fix Query Parameters for UrlBuilder.set method

ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsUtils.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/ReadableStream.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/browser/BrowserFetch.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/node/NodeFetch.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/fetch/LibDom.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRedirectTest.kt
Fix [KTOR-326](https://youtrack.jetbrains.com/issue/KTOR-326/JS-client-Cannot-change-redirect-policy-by-followRedirectsfalse)
=> KTOR-326 Allow to set followRedirect property for js client engine

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCall.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/RequestBodyHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1Handler.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletReader.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/EngineTestBaseJvm.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-utils/common/src/io/ktor/util/cio/Channels.kt
Fix [KTOR-4379](https://youtrack.jetbrains.com/issue/KTOR-4379/Validate-that-the-body-incoming-server-request-was-received-completely)
=> KTOR-4379 Validate body size equals Content-Length

CHANGELOG.md, gradle.properties
https://youtrack.jetbrains.com/issue/KTOR-4428
=> Release 2.0.3

ktor-server/ktor-server-plugins/ktor-server-pebble/api/ktor-server-pebble.api, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/test-resources/i18n_test.properties, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/test-resources/i18n_test_es.properties, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/test/io/ktor/server/pebble/PebbleTest.kt
**Subsystem**
Ktor-Server-Pebble
**Motivation**
This PR adds support for improving the ergonomics of using pebbles built in I18N support. It essentially makes it so you do not need to match Accept Headers to Locales in every route.
**Solution**
This uses a similar approach as the #1632 using `call.request.acceptLanguages` and validating it against a list of supported translations to either set the Locale or keep it `null` which is the default state.
=> KTOR-4593 Add support to automatically use the correct translation file for Pebble based on Accept Language header

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/OverridingClassLoader.kt, ktor-server/ktor-server-host-common/jvm/test-resources/resource.txt, ktor-server/ktor-server-host-common/jvm/test/io/ktor/server/engine/OverridingClassLoaderTest.kt
Previously it was (presumably) only able to find resources on its own classpath.
KTOR-4004
**Subsystem**
Server
**Motivation**
Classes were unable to load resources from the classpath when loaded in OverridingClassLoader
**Solution**
A breaking test demonstrates the problem and I have submitted a fix.
=> OverridingClassLoader now delegates to parent for resources also.

ktor-utils/jvm/src/io/ktor/util/cio/FileChannels.kt, ktor-utils/jvm/test/io/ktor/tests/utils/FileChannelTest.kt
**Subsystem**
utils
**Motivation**
[KTOR-4607](https://youtrack.jetbrains.com/issue/KTOR-4607/FilereadChannel-might-leak-open-file-handle-outside-scope)
**Solution**
Dont use RandomAccessFile outside of `.use {}`
=> KTOR-4607 Only use file resource with .use in File.readChannel().

ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/EngineMain.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/EngineMainTest.kt
**Subsystem**
Server configuration
**Motivation**
In our company we had to increase netty limits slightly. We a using EngineMain and application.conf.
Unfortionally, this configuration approach does not support netty configuration.
We should create an embeded version . . . It is not conviniant . . .
**Solution**
This pull request allow to configure common netty limits via application.conf
I will also push these changes to the documentation (after merge)
=> KTOR-4636: Unable to configure netty codec limits via application.config

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpBody.kt, ktor-network/ios/test/io/ktor/network/sockets/tests/TestUtilsIos.kt, ktor-network/linuxX64/test/io/ktor/network/sockets/tests/TestUtilsLinux.kt, ktor-network/macos/test/io/ktor/network/sockets/tests/TestUtilsMacos.kt, ktor-network/nix/test/io/ktor/network/sockets/tests/TestUtilsNix.kt, ktor-network/tvos/test/io/ktor/network/sockets/tests/TestUtilsTvos.kt, ktor-network/watchos/test/io/ktor/network/sockets/tests/TestUtilsWatchos.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/hooks/CommonHooks.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/RequestBodyHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1Handler.kt, ktor-server/ktor-server-plugins/ktor-server-request-validation/api/ktor-server-request-validation.api, ktor-server/ktor-server-plugins/ktor-server-request-validation/jvmAndNix/src/io/ktor/server/plugins/requestvalidation/RequestValidation.kt, ktor-server/ktor-server-plugins/ktor-server-request-validation/jvmAndNix/src/io/ktor/server/plugins/requestvalidation/RequestValidationConfig.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletReader.kt, ktor-server/ktor-server-test-suites/build.gradle.kts, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-utils/posix/test/io/ktor/util/MultiWorkerDispatcherTest.kt
Fix [KTOR-4655](https://youtrack.jetbrains.com/issue/KTOR-4655/Validate-ContentLength-Header-with-flag-only)
=> KTOR-4655 Fix ContentLength validation by default

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/src/io/ktor/http/ContentDisposition.kt, ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/src/io/ktor/http/CookieUtils.kt, ktor-http/common/src/io/ktor/http/FileContentType.kt, ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt, ktor-http/common/src/io/ktor/http/HttpHeaderValueParser.kt, ktor-http/common/src/io/ktor/http/HttpHeaders.kt, ktor-http/common/test/io/ktor/tests/http/ContentDispositionTest.kt
Fix [KTOR-4669](https://youtrack.jetbrains.com/issue/KTOR-4669)
=> KTOR-4669 Encode Content-Disposition filename* parameter

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationResponseJvm.kt, ktor-server/ktor-server-host-common/nix/src/io/ktor/server/engine/BaseApplicationResponseNative.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CookiesTest.kt
**Subsystem**
`ktor-server-host-common`
**Motivation**
It solves https://youtrack.jetbrains.com/issue/KTOR-4697 
**Solution**
The application now considers `wss` secure context and allows setting `Secure` cookies even  `wss` is used as a request scheme (for example in case when reverse proxy uses `X-Forwarded-Proto: wss` as described in  KTOR-4697)
=> KTOR-4697 Consider wss to be a secure context

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/logging/Logging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/CallLoggingTest.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt
**Subsystem**
Server Call Logging & Server Status Pages
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-4193/CallLogging-configured-MDC-entries-are-not-passed-to-StatusPages-exception-handlers
**Solution**
Fix `mdcProvider`, and use it to wrap the exception handlers in the mdc block.
I'm open to other solutions, may be possible to change CallLogging to not remove MDC entries once the try/finally has finished, but instead to remove them in a dedicated phase after fallback, but that feels more brittle.
Perhaps KtorMDCProvider should use a AttributeKey accessible in core, instead of the current "Look through all the plugins for the one we want" method.
=> KTOR-4193 Log CallLogging MDC values in StatusPages exception handlers.

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultResponseValidation.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/CallValidatorTest.kt
**Subsystem**
Client
**Motivation**
Resolves [KTOR-1619](https://youtrack.jetbrains.com/issue/KTOR-1619)
HTTP responses with non-2XX status codes and non-text bodies cause an unexpected exception in default response validation. This is because the validator attempts to decode the body as text to generate the exception message. This causes issues with endpoints that respond with a generic error image when requesting a non-existent record.
**Solution**
Attempt to decode the body in a `try` block, then on `MalformedInputException`, use a placeholder string to represent the non-decodable body in the resulting exception message. Also includes unit test written by original issue creator Takahiro Menju.
=> KTOR-1619 Use placeholder text if response body decoding fails in default validator

ktor-http/js/src/io/ktor/http/URLBuilderJs.kt
**Subsystem**
Clients
**Motivation**
In web workers `window` will be undefined, and `window === undefined` will crash because `window` is not dynamic.
**Solution**
I'm sure there is a more elegant way to accomplish this, but it seems like the best solution for now might be to just execute raw JS to check for `undefined`.
=> KTOR-4715  Fix crash in browser web workers where window is undefined

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/URLUtils.kt, ktor-http/common/test/io/ktor/tests/http/URLBuilderTest.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
Fix [KTOR-621](https://youtrack.jetbrains.com/issue/KTOR-621/The-beginning-character-of-endodedPath-fieldUrl-class-is-wrong-when-relative-path)
=> KTOR-621 Add extensions to check if the Url is absolute or relative

ktor-network/jvm/src/io/ktor/network/sockets/SocketAddressJvm.kt
**Subsystem**
ktor-network
**Motivation**
Fixes a regression in the JVM version of UnixSocketAddress (cf [KTOR-4695](https://youtrack.jetbrains.com/issue/KTOR-4695/Regression-UnixSocketAddresspath-fails-on-JVM))
**Solution**
Simply give the right object to the call to `getPath.invoke()`.
=> KTOR-4695 Fix UnixSocketAddress.path

ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/EngineConnectorConfigJvm.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/ServerInitializer.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt
**Subsystem**
Server
**Motivation**
Addresses https://youtrack.jetbrains.com/issue/KTOR-4587, providing mechanism to enable use of particular TLS versions 
**Solution**
Added new `enabledProtocols` property to engine connector config which is then applied in Netty, Jetty and Tomcat engines.
Some additional context in https://kotlinlang.slack.com/archives/C0A974TJ9/p1656335256667499
=> add enabledProtocols to ssl connector config

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt
**Subsystem**
Server - Netty
**Motivation**
See [KTOR4712](https://youtrack.jetbrains.com/issue/KTOR-4712): "sun.security.ssl.A**LPN**Extension" is only available if jetty-alpn is on the boot classpath, the class included in the jdk since 8u251 is called "sun.security.ssl.A**lpn**Extension". This leads to ktor refusing to use alpn with the jdk's implementation.
**Solution**
I've reused the same check provided by netty that was already in use for checking for openssl. Additionally I moved openssl to the top since `netty-tcnative` is an optional dependency, so if it is on the classpath it's probably the user's intention to use it in preference over the default jdk implementation.
=> KTOR-4712 Use Netty's alpn check instead of attempting to load jetty-alpn class

ktor-network/jvm/src/io/ktor/network/sockets/JavaSocketAddressUtils.kt, ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/backend/SocketAddressUtilsJvm.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/backend/SocketAddressUtils.kt, ktor-server/ktor-server-cio/nix/src/io/ktor/server/cio/backend/SocketAddressUtilsNative.kt
https://youtrack.jetbrains.com/issue/KTOR-4827
=> KTOR-4827 Fix CIO response delay

ktor-server/ktor-server-plugins/ktor-server-auth/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/AuthWithPlugins.kt
Fix [KTOR-678](https://youtrack.jetbrains.com/issue/KTOR-678/Json-request-failure-with-configured-form-authentication)
=> KTOR-678 Add test for Auth with Jackson

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/internals/CharArrayPool.kt, ktor-http/ktor-http-cio/js/src/io/ktor/http/cio/internals/CharArrayPoolJs.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/internals/CharArrayPoolJvm.kt, ktor-http/ktor-http-cio/posix/src/io/ktor/http/cio/internals/CharArrayPoolPosix.kt, ktor-io/jvm/src/io/ktor/utils/io/pool/DefaultPool.kt
Fix [KTOR-4809](https://youtrack.jetbrains.com/issue/KTOR-4809/Sparse-arrays)
=> KTOR-4809 Add Flag to disable CharArray pooling

ktor-client/ktor-client-core/common/test/CookiesTest.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/test/io/ktor/client/plugins/ContentNegotiationTests.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/internal/EngineUtilsJvm.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/BaseApplicationEngine.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/internal/EngineUtils.kt, ktor-server/ktor-server-host-common/nix/src/io/ktor/server/engine/internal/EngineUtilsNix.kt
Fix [KTOR-4834](https://youtrack.jetbrains.com/issue/KTOR-4834/Default-host-address-0000-isnt-reachable-on-Windows)
=> KTOR-4834 Fix startup message on Windows

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingBuilder.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4849
=> KTOR-4849 Routing: Wrong content-type should result in 415

buildSrc/src/main/kotlin/test/server/ClientTestServer.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlMultiApiHandler.kt, ktor-client/ktor-client-curl/desktop/test/io/ktor/client/engine/curl/test/CurlNativeTests.kt
https://youtrack.jetbrains.com/issue/KTOR-3566
=> KTOR-3566 Fixed sending DELETE with body in Curl engine

ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4875
=> KTOR-4875 Fixed respecting connectors port in testApplication

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentReloading.kt, ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestEngine.kt
Using empty `watchPaths` disables creating special class loader. In the future, we may add a new property to enable the development mode, but disable auto reload explicitly. But it needs design on how `developmentMode`, `autoReload` and `watchPaths` properties should work together
https://youtrack.jetbrains.com/issue/KTOR-4729
https://youtrack.jetbrains.com/issue/KTOR-4926
=> KTOR-4729 KTOR-4926 Disable auto reload in tests

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationResponse.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyHttp2ApplicationResponseTest.kt
https://youtrack.jetbrains.com/issue/KTOR-4943
=> KTOR-4943 NettyHttp2ApplicationResponse should not expose pseudo headers

ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/WebSocketDeflateExtension.kt, ktor-shared/ktor-websockets/jvm/test/WebSocketDeflateTest.kt
Fix [KTOR-4916](https://youtrack.jetbrains.com/issue/KTOR-4916/WebSocketDeflateExtension-configureProtocols-always-failed-with-stackOverflow)
=> KTOR-4916 Fix recursion in deflate config

ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/test/io/ktor/utils/io/charsets/ByteChannelTextTest.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/backend/ServerPipeline.kt
Fix [KTOR-2588](https://youtrack.jetbrains.com/issue/KTOR-2588/ByteReadChannel-is-unable-to-read-files-with-long-lines)
=> KTOR-2588 Fix long line reading

ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/test/io/ktor/tests/websocket/DefaultWebSocketTest.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/DefaultWebSocketSession.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/PingPong.kt
Timeout should send close frame and not wait for close acknowledge from the other side. Instead, directly close channels and provide close reason.
https://youtrack.jetbrains.com/issue/KTOR-2430
https://youtrack.jetbrains.com/issue/KTOR-3504
=> KTOR-3504 KTOR-2430 Fix WS timeout

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MergedApplicationConfig.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/config/MergedApplicationConfigTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5000
=> KTOR-5000 Fix merging nested configs

ktor-network/ktor-network-tls/jvmAndNix/src/io/ktor/network/tls/OID.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/api/ktor-network-tls-certificates.api, ktor-network/ktor-network-tls/ktor-network-tls-certificates/build.gradle.kts, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/Certificates.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/builders.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/test/io/ktor/network/tls/certificates/CertificatesTest.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/test/io/ktor/network/tls/certificates/KeyStoreBuilderTest.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/test/io/ktor/network/tls/certificates/TestUtils.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/test/io/ktor/network/tls/certificates/TimeMocks.kt
⚠️ Note: I'm making this PR against the `2.2.0-eap` branch because of a discussion with @e5l , but given the size of the changes, I can also change it to `main` instead if you prefer.
**Subsystem**
The subsystem is only the `ktor-network-tls-certificates` helper library to generate certificates (usually for tests).
**Motivation**
The initial issue I have with the current state of this library is that the allowed domains are hardcoded (`localhost` and `127.0.0.1`), thus preventing me from allowing hosts like `host.docker.internal` or `0.0.0.0` or potentially others when generating test certificates for a docker registry mock.
Also, plenty of things are hardcoded in these certificate generation helpers, and there is a lot of code duplication. So I figured I could also polish a bit the API …
=> Make certificate generation helpers more flexible

ktor-network/jvm/src/io/ktor/network/selector/SelectorManagerSupport.kt, ktor-network/jvm/test/io/ktor/network/selector/ActorSelectorManagerTest.kt
Fix [KTOR-2914](https://youtrack.jetbrains.com/issue/KTOR-2914/javalangIllegalArgumentException-Failed-requirement-in-SelectorManagerSupport)
=> KTOR-2914 Change exception type and clarify message

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/internal/AutoReloadUtils.kt
Fix [KTOR-1647](https://youtrack.jetbrains.com/issue/KTOR-1647/comsunniofileSensitivityWatchEventModifier-Move-the-reflection-call-of-this-modifier-out-from-the-Ktor-Core)
=> KTOR-1647 Avoid reflection access for SensitivityWatchEventModifier on Android

ktor-network/jvmAndNix/test/io/ktor/network/sockets/tests/UDPSocketTest.kt, ktor-network/nix/src/io/ktor/network/sockets/DatagramSendChannel.kt, ktor-network/nix/src/io/ktor/network/sockets/DatagramSocketNative.kt, ktor-network/nix/src/io/ktor/network/sockets/UDPSocketBuilderNative.kt
Fix [KTOR-4877](https://youtrack.jetbrains.com/issue/KTOR-4877/POSIX-error-56-Socket-is-already-connected-error-when-a-socket-is-connection-mode-on-Darwin-targets)
=> KTOR-4877 Fix UDP already connected

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/src/io/ktor/server/auth/jwt/JWTAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/api/ktor-server-auth.api, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/BearerAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/SimpleAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/BearerAuthTest.kt
**Subsystem**
ktor-server-auth
**Motivation**
[KTOR-5118](https://youtrack.jetbrains.com/issue/KTOR-5118/Add-Server-BearerAuthenticationProvider)
While Ktor provides mechanisms for authorizing JWTs and OAuth tokens, sometimes the developer needs to authorize bearer tokens with a custom lookup. I propose a new BearerAuthenticationProvider that extracts the bearer token from the Authorization header, and delegates the Principal lookup to the provided AuthenticationFunction<String>.
**Solution**
Added `BearerAuthenticationProvider` that authenticates a `BearerTokenCredential` via the provided `AuthenticateFunction`.
=> KTOR-5118 Add BearerAuthenticationProvider

buildSrc/src/main/kotlin/KotlinExtensions.kt, buildSrc/src/main/kotlin/NativeUtils.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, gradle/compatibility.gradle, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ClientHeadersTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PostTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CookiesTest.kt, ktor-client/ktor-client-winhttp/build.gradle.kts, ktor-client/ktor-client-winhttp/windows/interop/winhttp.def, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttp.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttpClientEngine.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttpClientEngineConfig.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttpSecurityProtocol.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpCallback.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpChunkedMode.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpConnect.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpCoroutine.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpExceptions.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpRequest.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpRequestProducer.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpResponseConsumer.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpResponseData.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpSession.kt, ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpWebSocket.kt, ktor-client/ktor-client-winhttp/windows/test/io/ktor/client/engine/winhttp/WinHttpProxyTest.kt, ktor-client/ktor-client-winhttp/windows/test/io/ktor/client/engine/winhttp/WinHttpTests.kt, ktor-client/ktor-client-winhttp/windows/test/io/ktor/client/engine/winhttp/WinHttpWebSocketTests.kt, ktor-client/ktor-client-winhttp/windows/test/io/ktor/client/engine/winhttp/internal/WinHttpExceptionsTest.kt, settings.gradle.kts
This change brings support of new Windows engine built on top of WinHTTP library. It supports HTTP 1.x/2 and WebSocket protocols.
**Subsystem**
Client, native windows engine.
**Motivation**
Fixes #671 WinHTTP API allows using native HTTP client without need to include additional DLLs. Also, it allows using certificate stored in Windows Certificates store.
**Solution**
We’re using WinHTTP in asynchronous working mode. In such mode notifications about operation results are delivered via status callback. The library supports both HTTP request processing as well as WebSockets protocol.
In HTTP engine we are using the following abstractions:
* `WinHttpSession` - create once per HTTP engine and allows configuring common settings like timeouts.
* `WinHttpConnect` - represents connection to HTTP …
=> KTOR-735 Support WinHTTP engine

ktor-network/nix/src/io/ktor/network/selector/WorkerSelectorManager.kt
**Subsystem**
Network - CIO Native
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-5035/Remove-check-for-internal-class-in-Select
**Solution**
Remove internal class check
**Current workaround**
I copied this code in postgresql driver: https://github.com/hfhbd/postgres-native-sqldelight/blob/main/postgres-native-sqldelight-driver/src/commonMain/kotlin/app/softwork/sqldelight/postgresdriver/Ktor_select.kt but would like to switch to ktor.
=> KTOR-5035 - Remove internal class check

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
Fix [KTOR-4535](https://youtrack.jetbrains.com/issue/KTOR-4535/Fix-WebSocketTest.testQueryParametersmacosX64)
=> KTOR-4535 Remove flaky WebSocketTest.testQueryParameters

ktor-utils/jvm/src/io/ktor/util/Nonce.kt
https://youtrack.jetbrains.com/issue/KTOR-668
=> NativePRNGNonBlocking is not found, fallback to SHA1PRNG

ktor-server/ktor-server-plugins/ktor-server-auth/api/ktor-server-auth.api, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/OAuthProcedure.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/OAuth2Test.kt
https://youtrack.jetbrains.com/issue/KTOR-5225
=> KTOR-5225 Add callbacks to save application state for OAuth2

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Route.kt, ktor-server/ktor-server-core/jvmAndNix/test/io/ktor/server/routing/RouteTest.kt
**Subsystem**
Server
**Motivation**
[KTOR-581](https://youtrack.jetbrains.com/issue/KTOR-581/List-of-all-routes)
**Solution**
dfs with adding all routes that have handlers
=> KTOR-581 Implement getAllRoutes method

ktor-server/ktor-server-config-yaml/jvmAndNix/src/io/ktor/server/config/yaml/YamlConfig.kt, ktor-server/ktor-server-config-yaml/jvmAndNix/test/YamlConfigTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5283
=> KTOR-5283 Support Default Value for missing Env Variables in YAML

ktor-shared/ktor-websockets/api/ktor-websockets.api, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/ProtocolViolationException.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/RawWebSocketCommon.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/FrameParser.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/RawWebSocketJvm.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/WebSocketReader.kt, ktor-shared/ktor-websockets/jvm/test/WebSocketReaderTest.kt
Fragmented control frames are explicitly disallowed by the websocket spec.
**Subsystem**
Server, Websockets
**Motivation**
Ktor's websocket implementation is currently pretty non-compliant. We see a lot of "unknown opcode" errors in our logs, so I'm going on an endevaour to start fixing all the protocol violations. This one specifically fixes https://youtrack.jetbrains.com/issue/KTOR-5006/Websockets-Connection-should-failed-immediately-1002-Protocol-Error-when-control-frame-has-a-payload-with-more-than-125-octets.
**Solution**
For this initial PR we just need to add some Frame validation before forwarding the Frame to the queues. In an earlier version I had the validation directly in the frame, however this'd prevent testing this solution within ktor since invalid frames could not be …
=> KTOR-5006: Close WS when reading fragmented control frames

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt
Some browsers do not expose `Content-Encoding` header 
https://youtrack.jetbrains.com/issue/KTOR-5300
=> KTOR-5300 Disable body length check for JS Browser target

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/CacheControl.kt, ktor-server/ktor-server-plugins/ktor-server-caching-headers/jvmAndNix/src/io/ktor/server/plugins/cachingheaders/CacheControlMerge.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CachingHeadersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-3757/Allow-specifying-immutable-in-CacheControl
=> KTOR-3757 Allow specifying custom CacheControl directives

ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CachingHeadersTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5342
=> KTOR-5342 Fix freezing of readUTF8Line

build.gradle.kts, buildSrc/src/main/kotlin/Train.kt
Reason: build_snapshot_train type had Boolean  for the root project ktor, while in the rest of projects it is String? (:ktor-bom, :ktor-client, :ktor-http). That led to the java.lang.ClassCastException.
=> Chore(infra): fix reading of build_snapshot_train gradlew property.

ktor-client/ktor-client-plugins/ktor-client-resources/common/src/io/ktor/client/plugins/resources/Resources.kt, ktor-client/ktor-client-plugins/ktor-client-resources/common/test/ResourcesTest.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvm/test/io/ktor/tests/resources/ResourcesTestJvm.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Resources.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/test/io/ktor/tests/resources/ResourcesTest.kt, ktor-shared/ktor-resources/common/src/io/ktor/resources/Resource.kt, ktor-shared/ktor-resources/common/test/io/ktor/tests/resources/PathPatternSerializationTest.kt, ktor-shared/ktor-resources/common/test/io/ktor/tests/resources/ResourceUrlBuilderTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5397
=> KTOR-5397 Make @Resource annotation @MetaSerializable

ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/jvm/nio/Writing.kt, ktor-io/jvm/test/io/ktor/utils/io/ByteBufferChannelTest.kt
https://youtrack.jetbrains.com/issue/KTOR-5372
=> KTOR-5372 Fix EOF in ByteBufferChannel when min is 0

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt, ktor-client/ktor-client-core/common/test/MultiPartFormDataContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt
**Subsystem**
Client multipart/form-data enhancement
**Motivation**
As per [KTOR-5405](https://youtrack.jetbrains.com/issue/KTOR-5405) there is desire to encode `Boolean` values the same way as `Number` values are encoded.
**Solution**
Wrapping `Boolean`s in `PartData.FormItem` which effectively puts quotes around string representation of the value.
=> KTOR-5405 allow booleans as multipart values

ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/CIOEngine.kt
**Subsystem**
CIO Client
**Motivation**
Both lazy implementations are immediately called on line 37, so making these properties lazy is useless and adds synchronization overhead: 
https://github.com/hfhbd/ktor/blob/248fca49fbdf63003d731dfc58ef7062b52b4435/ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/CIOEngine.kt#L34
**Solution**
Remove the laziness
=> CIO Client: Useless lazy

ktor-shared/ktor-websockets/common/src/io/ktor/websocket/PingPong.kt
**Subsystem**
Server
**Motivation**
The TRACE logs prints typo with WebSocket PingPong. Original message:
```
2023-01-16 15:13:00.799 [eventLoopGroupProxy-3-1] TRACE io.ktor.websocket.WebSocket - Starting WebSocket pinger coroutine with perioud 5000 ms and timeout 5000 ms
```
**Solution**
Fix the typo from `perioud` to `period`
=> Fix perioud typo to period

ktor-server/ktor-server-plugins/ktor-server-metrics/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-metrics/jvm/src/io/ktor/server/metrics/dropwizard/DropwizardMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics/jvm/src/io/ktor/server/metrics/dropwizard/DropwizardMetricsUtils.kt, ktor-server/ktor-server-plugins/ktor-server-metrics/jvm/test/io/ktor/server/metrics/dropwizard/DropwizardMetricsTests.kt
**Subsystem**
Server
**Motivation**
[KTOR-5420](https://youtrack.jetbrains.com/issue/KTOR-5420/DropwizardMetricsPlugin-logs-status-code-incorrectly-when-is-used-together-with-StatusPages-plugin)
**Solution**
Invoke phases for DropwizardMetricsPlugin after phase `CallFalled`
=> KTOR-5420 Fix DropwizardMetricsPlugin when using with StatusPages plugin

ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/cache/storage/FileCacheStorage.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/FileCacheTest.kt
**Subsystem**
Client
**Motivation**
Any exceptions thrown while accessing the cache are expected not to fail the request but instead continue the request as if there was a cache miss.
**Solution**
Add try-catch for FileCacheStorage
=> KTOR-5444 Fix FileNotFoundException thrown by FileCacheStorage

ktor-http/common/src/io/ktor/http/Mimes.kt
[KTOR-5533](https://youtrack.jetbrains.com/issue/KTOR-5533/Wrong-ContentType-for-.mjs-files)
=> KTOR-5533 Add MIME type for .mjs extension

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/api/ktor-server-call-logging.api, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/callloging/CallLoggingConfig.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/callloging/CallLoggingTest.kt
**Subsystem**
Server
**Motivation**
[KTOR-5474](https://youtrack.jetbrains.com/issue/KTOR-5474/CallLogging-plugin-add-config-to-avoid-logging-static-file-request)
**Solution**
Add property `ignoreStaticContent` to `CallLoggingConfig` (by default false)
=> KTOR-5474 Add property to avoid logging static file request

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkUtils.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/StreamRequestBody.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/RequestTests.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/StreamRequestBodyTest.kt
Fix [KTOR-5518](https://youtrack.jetbrains.com/issue/KTOR-5518/OkHttp-Cancelling-while-writing-to-ByteWriteChannel-when-overriding-WriteChannelContent-causes-propagation-of)
=> KTOR-5518 Fix Exception type for OkHttp channel adapter

ktor-client/ktor-client-plugins/ktor-client-resources/common/src/io/ktor/client/plugins/resources/Resources.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Resources.kt
**Subsystem**
- Client Resources Plugin
- Server Resources Plugin
**Motivation**
The JavaDoc in its current form does not compile as the `Users` data class must have at least one primary constructor parameter, which it doesn't. See [KTOR-5492](https://youtrack.jetbrains.com/issue/KTOR-5492/Javadoc-for-Resources.kt-cannot-be-compiled) for more details.
**Solution**
Replaces the data classes in the example with normal classes analogue to the examples in the documentation.
=> KTOR-5492 Javadoc for Resources.kt cannot be compiled

ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/BaseApplicationResponse.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CompressionTest.kt
**Motivation**
[KTOR-5510](https://youtrack.jetbrains.com/issue/KTOR-5510/Compressing-the-response-will-result-in-unexpected-ERROR-log-output-after-processing-in-the-StatusPages) 
**Solution**
Flag `isSent` wasn't set because of an accident `return` call
=> KTOR-5510 Fix isSent when content is ReadChannelContent

ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/src/io/ktor/server/resources/Routing.kt, ktor-server/ktor-server-plugins/ktor-server-resources/jvmAndNix/test/io/ktor/tests/resources/ResourcesTest.kt
**Subsystem**
Server, Routing, Resources
**Motivation**
This PR adds resource route builders accepting typed body as second parameter.
They are very convenient and are in pair with classic routing builders.
**Solution**
```kotlin
// classic routing builder (already in framework)
post<LoginCredentials>("/login") { credentials ->
// ...
}
// compatible resource builder (this PR)
post<LoginRoute, LoginCredentials> { route, credentials ->
// ...
}
```
=> KTOR-5589 Add resource route builders accepting typed body as second parameter

ktor-http/jvm/src/io/ktor/http/URLUtilsJvm.kt, ktor-http/jvm/test/io/ktor/tests/http/URLBuilderTest.kt
java `URI` does not support `_` in host, so it becomes `null`
https://youtrack.jetbrains.com/issue/KTOR-5591
=> KTOR-5591 Fix takeFrom(URL) method with underscore in host

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/utils/ExceptionUtilsJs.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingResolveContext.kt
https://youtrack.jetbrains.com/issue/KTOR-5466
=> KTOR-5466 Connect timeout is not respected when using the HttpRequestRetry plugin

ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/EngineMain.kt, ktor-server/ktor-server-host-common/api/ktor-server-host-common.api, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/ApplicationEngine.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/CommandLine.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/EngineContextCancellationHelper.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/EngineMain.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/JettyApplicationEngineBase.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/EngineMain.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/EngineMain.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-tomcat-jakarta/jvm/src/io/ktor/server/tomcat/jakarta/EngineMain.kt, ktor-server/ktor-server-tomcat-jakarta/jvm/src/io/ktor/server/tomcat/jakarta/TomcatApplicationEngine.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/EngineMain.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt
**Subsystem**
Server
**Motivation**
[KTOR-5560](https://youtrack.jetbrains.com/issue/KTOR-5560/Add-shutdown-configuration-for-engine-in-stop-method)
=> KTOR-5560 Add shutdown configuration for engine

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContentResolution.kt
**Subsystem**
Server, Static Resources
**Motivation**
It is needed to enable serving static files inside GraalVM native image.
**Solution**
Added "resource" protocol to supported protocols.
=> KTOR-5580 Add "resource" to supported protocols for classpath resource resolution

ktor-client/ktor-client-apache5/jvm/src/io/ktor/client/engine/apache5/Apache5Engine.kt
It's safe to close it with `CloseMode.IMMEDIATE`, because all requests are finished when `coroutineContext[Job]` is completed
=> Fix closing of Apache5 client engine

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt, ktor-server/ktor-server-plugins/ktor-server-metrics/jvm/src/io/ktor/server/metrics/dropwizard/DropwizardMetricsUtils.kt
**Motivation**
[KTOR-5595](https://youtrack.jetbrains.com/issue/KTOR-5595/Metrics-ClassCastException-when-the-DropwizardMetrics-plugin-is-installed-after-the-MicrometerMetrics-plugin)
**Solution**
The problem was that both plugins used the same name "metrics" for their `measureKey`
=> KTOR-5595 Fix ClassCastException when DropwizardMetrics is used together with MicrometerMetrics

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/WebSockets.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpWebSocket.kt
**Subsystem**
Client, Web Sockets
**Motivation**
The web socket client throws `WebSocketException` without cause in `onError` in the Java engine.
See https://youtrack.jetbrains.com/issue/KTOR-5652/Missing-cause-for-WebSocketException-in-JavaHttpWebSocket
**Solution**
Add the cause to the exception, so the stacktraces can show the underlying problem when the message is not sufficient (or absent).
=> KTOR-5652 Add proper cause to WebSocketException in Java engine

ktor-shared/ktor-websockets/common/src/io/ktor/websocket/PingPong.kt
**Subsystem**
Server, websocket
**Motivation**
[KTOR-5672](https://youtrack.jetbrains.com/issue/KTOR-5672) The trace log was written even when the `PONG` frame was received in time after the `PING` one.
**Solution**
Shouldn't we put the log in the condition body? Currently, this is confusing.
=> KTOR-5672 Fix erroneous trace log about expired websocket pings

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/DigestProviderTest.kt, ktor-http/common/src/io/ktor/http/HttpStatusCode.kt
**Subsystem**
ktor-client-auth 
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-4514/DigestAuthProvider-realm-sent-from-the-server-doesnt-participate-in-the-computation-of-response
Connecting to Axis cameras fails without this fix
**Solution**
Prior to this change, the realm used in the `credential` was always the class property. If the realm is unknown, it should be read from the headers. This was happening, but after the `credential` was created.
This change uses the constructed `realm` in the `credential` instead of the class property.
=> KTOR-4515 set realm before it's used to create credential

ktor-utils/js/src/io/ktor/util/logging/KtorSimpleLoggerJs.kt
**Subsystem**
Client, all modules
**Motivation**
The Ktor JS client is currently very noisy, displays lots of TRACE logs at the "info" level which is typically visible by default (in Chrome).
**Solution**
By using `console.debug()` these TRACE logs will be hidden unless you enable Verbose logging in the JS console.
=> KTOR-5456 Fix log level for JS Client DEBUG & TRACE logging

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/DefaultTransformTest.kt
A lot of code has the same implementation for handling all HTTP requests, and this includes reading the body of a response. In the case of a HEAD request, this can break when the Content-Length header has a non-zero
value
Original PR https://github.com/ktorio/ktor/pull/3438
=> KTOR-5699 Fix reading response of HEAD request

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/ClientSessions.kt, ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/JsonContentNegotiationTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/api/ktor-server-websockets.api, ktor-server/ktor-server-plugins/ktor-server-websockets/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/src/io/ktor/server/websocket/WebSocketServerSession.kt, ktor-shared/ktor-websocket-serialization/api/ktor-websocket-serialization.api, ktor-shared/ktor-websocket-serialization/common/src/io/ktor/websocket/serialization/WebsocketChannelSerialization.kt
**Subsystem**
Client, Websockets
**Motivation**
Sometimes it is not possible to use reified parameters when creating websockets and use deserialization of result
**Solution**
In that case it is reasonable to extract type info into parameters and provide API to use websockets with the prepared type info
=> KTOR-5740 Add opportunity to pass type info into receiveDeserializedBase and other

ktor-server/ktor-server-cio/build.gradle.kts, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-cio/jvmAndNix/test/io/ktor/tests/server/cio/CIOEngineTest.kt
Server
[KTOR-829](https://youtrack.jetbrains.com/issue/KTOR-829/Support-100-Continue)
[rfc7231](https://www.rfc-editor.org/rfc/rfc7231#section-5.1.1)
=> KTOR-829 Support `100 Continue` on server side

ktor-http/common/src/io/ktor/http/Codecs.kt, ktor-http/common/test/io/ktor/tests/http/ContentDispositionTest.kt
**Subsystem**
ktor-http
**Motivation**
The Content-Disposition header filename* content does not handle multi byte characters properly.
This is because `percentEncode` function used within `encodeContentDispositionAttribute`, does not encode the string to UTF-8.
**Solution**
Encode the string using UTF-8 representation, and add a test that handles multi byte characters.
=> Fix percentEncode to use UTF-8

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/HttpStatusCode.kt, ktor-http/common/test/io/ktor/tests/http/HttpStatusCodeTest.kt
[KTOR-4673](https://youtrack.jetbrains.com/issue/KTOR-4673) The '425 Too Early' status code is missing in the HttpStatusCode
=> KTOR-4673 Add '425 Too Early' http status code

ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-cio/jvmAndNix/test/CIOEngineTest.kt
Client
[KTOR-829](https://youtrack.jetbrains.com/issue/KTOR-829/Support-100-Continue)
[rfc7231 section-5.1.1](https://www.rfc-editor.org/rfc/rfc7231#section-5.1.1)
=> KTOR-829 Support `100 Continue` on client side

ktor-server/ktor-server-config-yaml/jvm/src/io/ktor/server/config/yaml/YamlConfigJvm.kt, ktor-server/ktor-server-config-yaml/jvmAndNix/src/io/ktor/server/config/yaml/YamlConfig.kt, ktor-server/ktor-server-config-yaml/jvmAndNix/test/YamlConfigTest.kt, ktor-server/ktor-server-config-yaml/nix/src/io/ktor/server/config/yaml/YamlConfigNix.kt
KTOR-5797 YAML config does not support reading variables from itself 
KTOR-5796 Support optional properties in YAML
=> Yaml config improvement

ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOWebSocketTestJvm.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationResponse.kt
Not sure how to add a test for this, since the bug is observed only as a side effect of a lot of requests
=> KTOR-5829 WebSockets: requests to a non-existing route cause server to lock up

ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt
**Subsystem**
Client, Logging plugin
**Motivation**
Original doc comment for `logLevel` property in `Logging.Config` is `Specifies the log the logging level.`
**Solution**
Change the doc comment to `Specifies the logging level.`
=> Fix log level doc comment typo

ktor-client/ktor-client-core/js/src/io/ktor/client/plugins/websocket/JsWebSocketSession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
**Subsystem**
Client, JS, Websockets
**Motivation**
Currently, websockets opened by the JS implementation in the browser do not get properly closed in case of cancellation or failure.
This is caused by browser `websocket.close()` throwing `InvalidAccessError` with codes that are not 1000 or 3000-4999 (see documentation [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#exceptions)), the implementation used 1011.
This is also mentioned in KTOR-2932. This PR does not change the meaning of cancellations which is the main focus of KTOR-2932, it only addresses the major bug.
The websockets staying open can cause critical performance issues (and has caused them for us, exhausting websockets in nginx).
**Solution**
Use 1000 as the closing reason code in the JS …
=> KTOR-2932 Fix cancelled and failed JS websockets not closing

gradle/libs.versions.toml
**Subsystem**
Client and Server
**Motivation**
This gets all the bug fixes in https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.5.1, and https://github.com/Kotlin/kotlinx.serialization/pull/2274 can heavily affect ktor users.
=> upgrade kotlinx-serialization to 1.5.1

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/config/MergedApplicationConfig.kt
**Subsystem**
Server module
- Config
**Motivation**
A bug that was fixed my Rustam introduced a new property, that doesn't fit the pattern and makes the code a bit less readable and unefficient.
**Solution**
By also caching the keys of the second ApplicationConfig this consistency is restored
=> Improve consistency of MergedApplicationConfig.kt

buildSrc/src/main/kotlin/NativeUtils.kt, buildSrc/src/main/kotlin/Publication.kt
`iosArm32` and `watchosX86` were deprecated in Kotlin 1.8.20 and will be removed in Kotlin 1.9.20.
See https://kotl.in/native-targets-tiers for details.
=> Remove deprecated Kotlin/Native targets.

gradle.properties, gradle/libs.versions.toml, ktor-client/ktor-client-cio/jvm/src/io/ktor/client/plugins/websocket/cio/buildersCio.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/builders.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlProcessor.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpWebSocket.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/MultipartTest.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/TrySkipDelimiterTest.kt, ktor-network/jvm/src/io/ktor/network/sockets/DatagramSendChannel.kt, ktor-network/jvmAndNix/test/io/ktor/network/sockets/tests/UDPSocketTest.kt, ktor-network/nix/src/io/ktor/network/sockets/DatagramSendChannel.kt, ktor-server/ktor-server-host-common/jvmAndNix/src/io/ktor/server/engine/EngineContextCancellationHelper.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/RequestBodyHandler.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WriterTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/test/io/ktor/tests/websocket/DefaultWebSocketTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvmAndNix/test/io/ktor/tests/websocket/RawWebSocketTest.kt, ktor-server/ktor-server-servlet-jakarta/jvm/src/io/ktor/server/servlet/jakarta/BlockingServlet.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/BlockingServlet.kt, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletUpgrade.kt, ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/client/TestEngineWebsocketSession.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/DefaultWebSocketSession.kt
**Subsystem**
Client and Server
**Motivation**
This upgrades `kotlinx-coroutines` to 1.7, which is besides many things a blocker to https://youtrack.jetbrains.com/issue/KTOR-5753
Seems to also be a fix to https://youtrack.jetbrains.com/issue/KTOR-5728, I cannot reproduce the error anymore on my machine after this patch.
**Solution**
Upgrade library and make necessary adjustments.
=> Upgrade kotlinx-coroutines to 1.7.1

buildSrc/src/main/kotlin/test/server/tests/Cache.kt, ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/UnlimitedCacheStorage.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/cache/storage/FileCacheStorage.kt, ktor-client/ktor-client-core/jvm/test/CachingCacheStorageTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-client/ktor-client-tests/jvm/test/io/ktor/client/tests/FileCacheTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6001
=> KTOR-6001 Cache returns null when vary header has more fields in the cached response

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultRequest.kt, ktor-client/ktor-client-core/common/test/DefaultRequestTest.kt
Fix [KTOR-5619](https://youtrack.jetbrains.com/issue/KTOR-5619/DefaultRequest-a-cookie-appears-twice-in-the-request-header-when-sending-a-request-with-another-cookie)
=> KTOR-5619 Fix cookie appears twice with DefaultRequest cookie

ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ShutdownHookJvm.kt
Fix [KTOR-6070](https://youtrack.jetbrains.com/issue/KTOR-6070/Add-system-property-to-disable-automatic-installation-of-runtime-shutdown-hook)
=> KTOR-6070 Add SystemProperty to disable shutdown hook

ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt
**Subsystem**
Client
**Motivation**
[HttpMessage.vary()](https://github.com/ktorio/ktor/blob/15a0cc73fe2ad9cb1f664d9495f480524cdbb62f/ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt#L89) returns `listOf("Origin")` if vary header is configured twice like below.
```
vary: Origin
vary: Accept
```
On the other hand, [HttpMessage.vary()](https://github.com/ktorio/ktor/blob/15a0cc73fe2ad9cb1f664d9495f480524cdbb62f/ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt#L89) returns `listOf("Origin", "Accept")` if vary header is configured once with comma separated values.
```
vary: Origin,Accept
```
Those are same vary keys, but HttpCache plugin doesn't regard as same vary keys in [this line](https://github.com/ktorio/ktor/blob/15a0cc73fe2ad9cb1f664d9495f480524cdbb62f/ktor-client/k …
=> KTOR-6081  Cache returns null when vary header set different ways whatever it has same values

ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationRequest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationRequest.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationRequest.kt
These methods aren't used anywhere, and weren't part of the public API.
Also, `DefaultHttpHeaders(false)` is an indicator of a potential vulnerability,
due to disabling HTTP header validation.
Removing this code removes the potential for this vulnerability being present.
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
**Subsystem**
Server: `ktor-server-netty`
**Motivation**
Potential risk of HTTP request/reponse splitting through the use of `DefaultHttpHeaders(false)`.
**Solution**
Completely remove the unused method.
=> Remove unused `NettyApplicationRequest#newDecoder`

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/HttpCacheStorage.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt
**Subsystem**
Client
**Motivation**
[KTOR-6087](https://youtrack.jetbrains.com/issue/KTOR-6087/s-maxage-is-not-used-even-if-HttpCache.Config.isShared-is-true.)
max-age is used unexpectedly instead of s-maxage, even if `HttpCache.Config.isShared` is true.
I've reproduce this issue in Unit Test that requests to server even if s-maxage is not expired. e8d2148ad494a83133b77ed0f916f6c2746bed92
**Solution**
To resolve this issue, passing `isShared` member to a parameter of cache storing function. ec614b4dec94a8b377d418f263b616203fbe22d5
=> KTOR-6087 s-maxage is not used, even if `HttpCache.Config.isShared` is true

ktor-server/ktor-server-netty/api/ktor-server-netty.api, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/EngineMain.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6098
=> KTOR-6098 Netty: Allow listening only for HTTP/1.1 protocol SSL connections

buildSrc/src/main/kotlin/NativeUtils.kt, buildSrc/src/main/kotlin/Publication.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, ktor-io/common/src/io/ktor/utils/io/charsets/Encoding.kt, ktor-io/common/test/io/ktor/utils/io/BytePacketReadTest.kt, ktor-io/common/test/io/ktor/utils/io/BytePacketStringTest.kt, ktor-io/common/test/io/ktor/utils/io/ReadTextCommonTest.kt, ktor-io/darwin/src/CharsetDarwin.kt, ktor-io/js/src/io/ktor/utils/io/charsets/CharsetJS.kt, ktor-io/jvm/src/io/ktor/utils/io/charsets/CharsetJVM.kt, ktor-io/linux/src/CharsetLinux.kt, ktor-io/mingwX64/src/CharsetMingw.kt, ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt
Fix [KTOR-5980](https://youtrack.jetbrains.com/issue/KTOR-5980/Uncaught-Kotlin-exception-kotlin.IllegalArgumentException-Failed-to-open-iconv-for-charset-UTF-8-with-error-code-22)
=> KTOR-5980 Replace iconv with platform converter on darwin

ktor-shared/ktor-serialization/ktor-serialization-kotlinx/common/src/io/ktor/serialization/kotlinx/KotlinxSerializationConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-protobuf/common/test/ProtoBufSerializationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6125
=> KTOR-6125 ContentNegotiation with protobuf fails on empty body

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ApplicationResponseFunctions.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/RespondFunctionsTest.kt
https://youtrack.jetbrains.com/issue/KTOR-6183
=> KTOR-6183 The "charset=UTF-8" part is automatically added to the `application/json` Content-Type

ktor-utils/api/ktor-utils.api, ktor-utils/common/src/io/ktor/util/Attributes.kt, ktor-utils/common/test/io/ktor/util/AttributesTest.kt
Fix [KTOR-6122](https://youtrack.jetbrains.com/issue/KTOR-6122/AttributeKey-equality-comparison-breaks-type-safety)
=> KTOR-6122 Add type to AttributeKey equals

ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpEngine.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpResponse.kt, ktor-client/ktor-client-java/jvm/test/io/ktor/client/engine/java/JavaEngineTests.kt
Fix [KTOR-6190](https://youtrack.jetbrains.com/issue/KTOR-6190/Unknown-error.-Try-to-repeat-your-request.-If-the-issue-persists-contact-us)
=> KTOR-6190 Handle NPE in JavaClientEngine body() call

ktor-network/ktor-network-quic/jvm/src/io/ktor/network/quic/tls/CryptoKeys.kt, ktor-network/ktor-network-quic/jvm/test/io/ktor/network/quic/integration/TestKwikClient.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/bytes/PayloadSize.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/connections/PacketSendHandler.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/connections/QUICConnection.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/errors/QUICTransportError.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/frames/FrameProcessor.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/frames/FrameReader.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/frames/FrameWriter.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/Consts.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/PacketNumberSpace.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/PacketReader.kt, ktor-network/ktor-network-quic/jvmAndNix/src/io/ktor/network/quic/packets/PacketWriter.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/frames/FrameExpectedSizeTest.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/frames/FrameReadWriteTest.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/frames/base/TestFrameProcessor.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/frames/base/TestFrameWriter.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/other/VarIntCodingTest.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/packets/PacketNumberSpaceTest.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/packets/PacketSendHandlerTest.kt, ktor-network/ktor-network-quic/jvmAndNix/test/io/ktor/network/quic/util/TestUtils.kt
**Subsystem**
ktor-network
**Motivation**
QUIC packet retransmission requires caching individual frames, which in current solution is hard
**Solution**
Refactor frames and packets writing operations to allow to introduce recovery module
=> [QUIC] Packets retransmission 1

ktor-client/ktor-client-apache5/jvm/src/io/ktor/client/engine/apache5/Apache5Engine.kt
**Subsystem**
Client, Apache5 engine
**Motivation**
When using the Apache5 engine, total concurrent requests to a single route were limited to 5 requests. This causes an unexpected bottleneck when switching engines.
Issue link is https://youtrack.jetbrains.com/issue/KTOR-6221/Apache5-engine-limits-concurrent-requests-to-individual-route-to-5.
**Solution**
This just fixes the type/missing call to `setMaxConnPerRoute` which was intended all along.
=> KTOR-6221: Fix reduced concurrent reqs in Apache5

ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSClientSessionJvm.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/tests/ConnectionTest.kt
**Subsystem**
Client, TLS over TCP
**Motivation**
When using a plain TCP socket with TLS, two worker jobs are spawned:
- cio-tls-input-loop
- cio-tls-output-loop
These worker jobs live in their own scope, and exceptions they throw can't easily be caught by the caller: the only option is to install a `CoroutineExceptionHandler` for the whole TLS socket, which is quite hacky and may hide bugs.
When the TCP socket is closed, this is only caught when trying to write on the output channel, which throws a `ClosedSendChannelException`.
See the following tickets for that issue:
- https://youtrack.jetbrains.com/issue/KTOR-5178/TLSSocket-cannot-catch-the-exception-thrown-by-appDataOutputLoop
- https://youtrack.jetbrains.com/issue/KTOR-4360/Android-Impossible-to-catch-the-ClosedSendChannelException-w …
=> Avoid crashing when TLS TCP socket is closed

gradle/libs.versions.toml
[KTOR-6286](https://youtrack.jetbrains.com/issue/KTOR-6286) We need to update `xmlutil` because in the previous version it was vulnerable to XXE attack
=> KTOR-6286 Update xmlutil to 0.86.2

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt
[KTOR-6344](https://youtrack.jetbrains.com/issue/KTOR-6344) 
Invoke `setFixedLengthStreamingMode(long contentLength)` instead of `setFixedLengthStreamingMode(int contentLength)` because `contentLength` is `Long?`
=> KTOR-6344 Fix content length range in AndroidClientEngine

buildSrc/src/main/kotlin/test/server/tests/WebSockets.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpWebSocket.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
**Subsystem**
JS Engines Websockets
Java Engine Websockets
**Motivation**
Fixes KTOR-4001
There needs to be a way to set the subprotocols the websocket supports/requires (See [KTOR-4001](https://youtrack.jetbrains.com/issue/KTOR-4001/Server-sent-a-subprotocol-but-none-was-requested-when-using-Node-WebSockets#focus=Comments-27-5866649.0-0)) because certain server implementations will reject connections that do not specify the correct subprotocols, or [being important for handler resolution](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket#parameters). Currently, [apollographql/apollo-kotlin](https://github.com/apollographql/apollo-kotlin) (a downstream consumer of KTOR) has implemented a work around because the `createWebSocket` method provided by KTOR does not allow …
=> Support  Websocket Subprotocols For JS Clients (KTOR-4001)

.gitignore, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinSession.kt
Fix [KTOR-6243](https://youtrack.jetbrains.com/issue/KTOR-6243/Darwin-Even-a-coroutine-Job-is-canceled-network-load-keeps-high)
=> KTOR-6243 Fix darwin task leak

ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpWebSocket.kt, ktor-client/ktor-client-winhttp/windows/test/io/ktor/client/engine/winhttp/WinHttpWebSocketTests.kt
Fix [KTOR-6394](https://youtrack.jetbrains.com/issue/KTOR-6394/WinHttp-ArrayIndexOutOfBoundsException-when-sending-WS-frame-with-empty-body)
=> KTOR-6394 Fix WinHttp websocket empty frame

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/WebSocketContent.kt
**Subsystem**
Client
**Motivation**
[KTOR-6388 WebSocket Connection Failure Due to Lowercase 'upgrade' in 'Connection: upgrade' Header](https://youtrack.jetbrains.com/issue/KTOR-6388)
Here are some references that discuss the importance of capitalizing 'Upgrade':
- [GitHub discussion on kubectl port-forward issue](https://github.com/kubernetes/kubernetes/issues/43962)
- [MDN Web Docs - HTTP Upgrade Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade)
- [WebSocket example in HAProxy documentation](https://www.haproxy.com/blog/websockets-load-balancing-with-haproxy/)
=> KTOR-6388 WebSocket Connection Failure Due to Lowercase 'upgrade' in 'Connection: upgrade' Header

ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt
**Subsystem**
Server, related modules: ktor-server-test-host
**Motivation**
Test engine does not complete job launched during init (which logs resolved connectors) which makes it hard to detect if all the launch jobs in test are already finished.
Details: https://youtrack.jetbrains.com/issue/KTOR-6411
**Solution**
Complete pending job during the test engine start (like in Netty implementation).
=> KTOR-6411 resolve connectors in the test engine

build.gradle.kts, gradle.properties
**Subsystem**
Infrastructure
**Motivation**
Dokka stopped working after #3662 was merged into `main`. If you run Dokka's tasks now, it will lead to build failures related to the resolution of platform dependencies, likely caused by the combination of Gradle 8 + `kotlin.mpp.enableCInteropCommonization=true`
**Solution**
Update Dokka to 1.9.0 and use the proposed workaround flag, which changes the underlying dependency resolution algorithm.
For more details, see https://github.com/Kotlin/dokka/issues/3153.
=> Update Dokka to 1.9.0 and add a workaround for build errors

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Compilations.kt, buildSrc/src/main/kotlin/Versions.kt, gradle.properties, ktor-client/ktor-client-core/jvm/src/io/ktor/client/HttpClientJvm.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlAdapters.kt, ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/KtorLegacyNSURLSessionDelegate.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/KtorNSURLSessionDelegate.kt, ktor-io/jvm/src/io/ktor/utils/io/charsets/CharsetJVM.kt, ktor-io/posix/src/io/ktor/utils/io/locks/Synchronized.kt, ktor-network/jvm/src/io/ktor/network/sockets/SocketAddressJvm.kt, ktor-network/jvmAndNix/src/io/ktor/network/sockets/SocketAddress.kt, ktor-network/nix/src/io/ktor/network/sockets/SocketAddressNative.kt, ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/ApplicationEngineEnvironmentJvm.kt, ktor-server/ktor-server-host-common/nix/src/io/ktor/server/engine/ApplicationEngineEnvironmentNix.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/AuthenticationInterceptors.kt, ktor-utils/darwin/src/io/ktor/util/ThreadInfoDarwin.kt, ktor-utils/linux/src/io/ktor/util/ThreadInfoLinux.kt
Fix [KTOR-6447](https://youtrack.jetbrains.com/issue/KTOR-6447/Update-Kotlin-to-1.9.20)
=> KTOR-6447 Update Kotlin to 1.9.20

gradle/libs.versions.toml
**Subsystem**
**Motivation**
We're getting security warnings from dependabot in a project that uses `ktor` that versions of `netty-codec-http2 < 4.1.100.Final` are affected by [CVE-2023-44487](https://www.cve.org/CVERecord?id=CVE-2023-44487).
**Solution**
Just bumped the version to the latest patch.
=> Bump http-version to 4.1.101.Final

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/PreCompressed.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/test/io/ktor/server/webjars/WebjarsTest.kt
**Subsystem**
StaticContent, Webjars
**Motivation**
[KTOR-6400](https://youtrack.jetbrains.com/issue/KTOR-6400) Marking files provided by Webjars plugin as static files
**Solution**
Introduced a public attribute for any static file response producer to add the path to the call.  This allows plugins like `Webjars` (or any other) to return true for the `ApplicationCall.isStaticContent()` extension function.  Previously, this function only checked if a path parameter was present from the routing.
=> KTOR-6400 Add attribute for extending isStaticContent() functionality in Webjars

ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/src/io/ktor/server/plugins/contentnegotiation/RequestConverter.kt, ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvmAndNix/test/ContentNegotiationTest.kt
Fix [KTOR-5410](https://youtrack.jetbrains.com/issue/KTOR-5410/Server-ContentNegotiation-no-longer-allows-multiple-decoders-for-one-Content-Type)
=> KTOR-5410 Fix multiple converters for content negotiation

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/RequestBodyHandler.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1Handler.kt, ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyReadRequestTimeoutTest.kt
Before in the case of `ReadTimeoutException`:
1. The client gets an empty response
2. Only `Netty` knows about exception 
3. The request is still executed
Now in the case of `ReadTimeoutException`:
1. The client gets a `408 Request Timeout` response
2. Ktor server will get a `CancellationException` and response will contain status `500`
3. Connection with a client is closed
=> Fix ReadTimeoutException on Netty

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
**Subsystem**
Routing
**Motivation**
[KTOR-2121](https://youtrack.jetbrains.com/issue/KTOR-2121) {...} (tailcard) does not match URLs ending with '/'
**Solution**
Made it so the tailcard selector treats empty segments the same as others, and allowed failures for when there is no segment.
This is a pretty significant change to the routing logic, and could break some people if they rely on routes like `/foo/{...}` to match on `/foo`.  I was thinking maybe we ought to include some flag to opt in or out of this behaviour, wdyt?
There were also some intentional tests for the opposite behaviour than described in the bug, although the logic there is inconsistent:
1. Routes like `/foo/{...}/` should be considered invalid because the wildcard here is described as "the rest of the URL path" in the …
=> KTOR-2121 Update trailcard logic for handling trailing slashes

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContentResolution.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/tests/http/content/StaticContentResolutionTest.kt
After playing around with the allocation benchmarks a bit, I found that the `ClassLoader.getResources()` call was the most expensive operation and can be avoided most of the time - resulting in 20-30% improvement by removing ~90 strings allocated from looking through the classpath on each request (which could potentially be much larger on big projects).
The caveat here is that introducing a cache for the resource URLs could create problems for projects that rely on swapping jars at runtime, so I'm thinking it might make sense to introduce this in 3.0.0 with an opt-out option.
I also have a few improvements in `ktor-benchmarks` but I lack the ability to push there atm 🥺
=> Add resource URL cache

ktor-server/ktor-server-plugins/ktor-server-content-negotiation/jvm/test/ContentNegotiationJvmTest.kt, ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORSConfig.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CORSTest.kt
**Subsystem**
CORS (Server)
**Motivation**
[KTOR-6494](https://youtrack.jetbrains.com/issue/KTOR-6494) CORS: `allowHost` without the second argument doesn't allow the secure host
^ This seems like a pretty valid concern, only allowing http by default is quite strange and will inevitably lead to friction when deploying to production.
**Solution**
Simply add https to the default schemas.
=> KTOR-6494 Add https to default allowed schemas for CORS

ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOSpecificHttpsTest.kt, ktor-http/common/src/io/ktor/http/IpParser.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/HostnameUtils.kt
Fix [KTOR-6396](https://youtrack.jetbrains.com/issue/KTOR-6396) CIO: "getSubjectAlternativeNames(...) must not be null" error on Android when using CA without SAN since 2.3.5
=> KTOR-6396 Skip certificate hostname check if no hostnames provided

ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/Certificates.kt, ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/builders.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EnvironmentUtilsJvm.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt
On some platforms (e.g. Android) Java KeyStore (JKS) support is not available. Using the default platform keystore ensures that keys can still be stored on those platforms.
**Subsystem**
Server and Network
**Motivation**
Attempting to use the keystore related code results in an error on Android, switching the assumption that "JKS" is always available to using the platform provided default resolves this.
**Solution**
Change hard coded "JKS" to use of `getDefaultType()` which provides the keystore format available on the system. On Android this is "BKS" (ref: https://cs.android.com/android/platform/superproject/main/+/main:libcore/luni/src/main/java/java/security/security.properties;l=50)
=> Remove assumption "JKS" is always available.

ktor-server/ktor-server-plugins/ktor-server-auth/api/ktor-server-auth.api, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuth2.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuthCommon.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/OAuthProcedure.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/test/io/ktor/tests/auth/OAuth2Test.kt
**Subsystem**
Ktor-server-auth (oauth2)
**Motivation**
See https://youtrack.jetbrains.com/issue/KTOR-6605 - currently there is no way for user code to see the original error code & description returned from an identity provider. This contains useful information like the fact that the user intentionally cancelled the auth flow etc.
**Solution**
This PR extends the callback response handling to include unhappy path handling. 
It does change the exception type that populates `call.authentication.allFailures` to be a typed descendent of `AuthenticationFailedCause.Error` rather than the `object AuthenticationFailedCause.NoCredentials` that would have (confusingly) been mapped before. This is unlikely to break any userland code, but it could be possible if user code is explicitly checking for …
=> Add handling to propagate error from oauth server to caller

ktor-utils/common/src/io/ktor/util/pipeline/StackTraceRecover.kt
**Subsystem**
None.
**Motivation**
The Kotlin team checks ktor with the new versions of the K2 compiler. Found problems are investigated and if the problem is not planned to be fixed, migration is added. Branch: kotlin-community/k2/dev. To make maintaining the branch easier, we suggest moving migrations to the main branch.
[KT-57776](https://youtrack.jetbrains.com/issue/KT-57776)
Since we don't have `INVISIBLE_MEMBER` in FIR, libraries should migrate to `@Suppress("INVISIBLE_REFERENCE")`
**Solution**
Added `INVISIBLE_REFERENCE`, kept `INVISIBLE_MEMBER` for compatibility with K1.
=> Kotlin K2 Migration: Add INVISIBLE_REFERENCE KT-57776

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultRequest.kt, ktor-client/ktor-client-core/common/test/DefaultRequestTest.kt, ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLUtils.kt, ktor-http/common/src/io/ktor/http/Url.kt
Fix for [KTOR-5586](https://youtrack.jetbrains.com/issue/KTOR-5586).
The solution is to move the source of truth for the protocol into a nullable property (`protocolOrNull`) while delegating the original (`protocol`) to it, defaulting to `URLProtocol.HTTP` as before. This way the original behavior remains unchanged, but if necessary it's now possible to tell whether or not http came about as the default, or if it was provided explicitly: In the first case `protocolOrNull == null` while in the latter `protocolOrNull == URLProtocol.HTTP`.
I believe the only change to the public api brought about by this (aside from the new `protocolOrNull` property) is that `protocol` is now nullable in the `URLBuilder` constructor, which shouldn't be a problem i believe?
=> KTOR-5586 Fix DefaultRequest overwriting explicitly provided http protocol

.github/workflows/gradle-wrapper-validation.yml
**Subsystem**
build
**Motivation**
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or …
=> GitHub Workflows security hardening

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpCallValidator.kt
Fix [KTOR-6625](https://youtrack.jetbrains.com/issue/KTOR-6625) HttpCalValidatorConfig class name is misspelled
=> KTOR-6625 Fix HttpCallValidatorConfig name

ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
Test suite
**Motivation**
Fix for a test that fails sometimes due to a timeout on waiting for server to shut down.
**Solution**
Simply increase the timeout - since the server startup time can take quite long on the TC server due to competing threads, this ought to resolve the periodic timeouts.
=> Increase timeout for testEmbeddedServerCancellation and update failure

ktor-server/ktor-server-plugins/ktor-server-thymeleaf/api/ktor-server-thymeleaf.api, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/src/io/ktor/server/thymeleaf/RespondTemplate.kt
**Subsystem**
Server, Thymeleaf plugin
**Motivation**
The default HTTP status in `io.ktor.server.engine.BaseApplicationResponse#commitHeaders` is `HttpStatusCode.OK` (200). This is almost always applicable when responding with a template. However, in the case of templates being used along with the `StatusPages` plugin or for response entities for HTTP methods, it is necessary to respond with an appropriate HTTP status code.
**Solution**
This change allows for an optional parameter for the caller to set the status code along with responding with a template. IIUC, it should be binary compatible.
It does not address other templating library plugins. With a little effort all the template plugins could be harmonized under an interface for the `xContent` type and an abstract implementation for …
=> Allow `respondTemplate` set HTTP status

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-server/ktor-server-cio/api/ktor-server-cio.api, ktor-server/ktor-server-servlet-jakarta/api/ktor-server-servlet-jakarta.api, ktor-server/ktor-server-servlet-jakarta/jvm/src/io/ktor/server/servlet/jakarta/ServletApplicationEngine.kt, ktor-server/ktor-server-servlet-jakarta/jvm/test/io/ktor/tests/servlet/jakarta/ConfigTest.kt, ktor-server/ktor-server-servlet/api/ktor-server-servlet.api, ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletApplicationEngine.kt, ktor-server/ktor-server-servlet/jvm/test/io/ktor/tests/servlet/ConfigTest.kt
**Subsystem**
Server: ktor-server-servlet, ktor-server-servlet-jakarta
**Motivation**
[KTOR-6574](https://youtrack.jetbrains.com/issue/KTOR-6574/Double-Transfer-Encoding-header-while-using-respondOutputStream-on-Tomcat)
If Ktor project is running as a [WAR](https://ktor.io/docs/war.html) application under the Tomcat application server, a user has duplicate headers `Transfer-Encoding` and `Connection` in response.
**Solution**
The problem is on the `Tomcat` side or `Gretty` + `Tomcat` side because the user doesn't use `Tomcat` from Ktor, only `ServletApplicationEngine` is used. The solution is to configure the `managedByEngineHeaders` property in `ServletApplicationEngine`
Also, I gave in to write test since it's reproducible with gretty and it was hard to run test as WAR under the Tomcat …
=> KTOR-6574 Fix duplicate headers in ServletApplicationEngine with Tomcat

ktor-server/ktor-server-plugins/ktor-server-sse/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-sse/jvmAndNix/test/io/ktor/server/sse/ServerSentEventsTest.kt, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/src/io/ktor/server/thymeleaf/RespondTemplate.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/DelegatingTestClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-shared/ktor-junit/jvm/src/io/ktor/junit/RetrySupport.kt
**Subsystem**
Server sse
**Motivation**
We have an old ticket [KTOR-3290](https://youtrack.jetbrains.com/issue/KTOR-3290) with [PR](https://github.com/ktorio/ktor/pull/2659). However, it became outdated because we have SSE support now, so we can just add a support for test to engine to have simple way to test
=> KTOR-3290 Add SSE support for test engine

gradle/libs.versions.toml
I noticed the allocation tests have been broken for the last few days due to a compilation issue in :ktor-client:ktor-client-mock:compileCommonMainKotlinMetadata.  After a bit of digging I narrowed it down to this commit 8891c452403530123b484a76a242344baff03ebd for upgrading the serialization version.  Reverting this for now until we can figure out why upgrading the serialization version is causing the common compilation to fail with missing stdlib references.
=> Fix for publications build

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/builders.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientLoaderJvm.kt
[KTOR-6664](https://youtrack.jetbrains.com/issue/KTOR-6664) WebSocket doesn't get terminated when runBlocking is used
=> KTOR-6664 Cancel pending incoming messages if the session is closing

ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/jvm/resources/META-INF/services/io.ktor.serialization.kotlinx.KotlinxSerializationExtensionProvider
Fix failed shadowJar ServiceFileTransformer relocation.
**Subsystem**
Client and Server, `kotlinx-serialization-json-jvm`.
Issue from 2.2.4 to 2.3.0 or later migration.
**Motivation**
When using [shadow](https://github.com/johnrengelman/shadow) to shade and relocate Ktor, a runtime `java.util.ServiceConfigurationError` is thrown.
> java.util.ServiceConfigurationError: shaded.io.ktor.serialization.kotlinx.KotlinxSerializationExtensionProvider: Provider io.ktor.serialization.kotlinx.json.KotlinxSerializationJsonExtensionProvider not found
**Solution**
Remove the leading whitespace in the service configuration `io.ktor.serialization.kotlinx.KotlinxSerializationExtensionProvider`. Whitespace causes shadow's [ServiceFileTransformer](https://github.com/johnrengelman/shadow/blob/9c5182d2d9c5f7141 …
=> Remove leading whitespace in service configuration

ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLS.kt
**Subsystem**
Client/Server, network-tls
**Motivation**
Update docs based on discussion in Slack: https://kotlinlang.slack.com/archives/C0A974TJ9/p1705535602239209.
**Solution**
Add docs explaining that the `coroutineContext` parameter to `tls()` should generally not be a child of the enclosing scope.
=> Update TLS.kt with docs about coroutineContext parameter

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/URLUtils.kt
like `buildString` but for URL's
**Subsystem**
http
**Motivation**
I dislike calling 
```kotlin
UrlBuilder().apply {
// ...
}.build()
```
and yet seem to do it every-time I construct a URL.
**Solution**
```kotlin
public fun buildUrl(block: URLBuilder.() -> Unit): Url = URLBuilder().apply(block).build()
```
**Some examples**
with no `url`
```kotlin
fun issuer(region: String, userPoolId: String) = buildUrl {
protocol = URLProtocol.HTTPS
host = "cognito-idp.$region.amazonaws.com"
appendPathSegments(userPoolId)
}
```
with `url`
```kotlin 
fun domain(region: String, userPoolId: String): Url = buildUrl {
takeFrom(issuer(region, userPoolId))
appendPathSegments(".well-known", ".jwks.json")
}
```
=> add buildUrl

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/engine/BaseApplicationResponse.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/response/ResponseCookies.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CookiesTest.kt
**Subsystem**
Server, Cookies, Security
**Motivation**
- [KTOR-3159](https://youtrack.jetbrains.com/issue/KTOR-3159) Allow to set secure cookie even with http scheme
- [KTOR-6593](https://youtrack.jetbrains.com/issue/KTOR-6593) Allow setting "Secure" flag for cookies on localhost
The general complaint is that we're preventing developers from setting secure cookies when their application is behind a secure proxy.  We assumed that we could still enforce the protocol by relying on the "X-Forwarded-Proto" for this configuration but it doesn't seem to be true for all cases.
**Solution**
This removes the protocol check for responding with the "Secure" flag on the "Set-Cookie" header.  Instead of enforcing the protocol adheres to the "Secure" rule, we rely on the application developer and client …
=> KTOR-3159 Allow secure cookie with unencrypted response

ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/src/io/ktor/server/plugins/csrf/CSRF.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/test/io/ktor/server/plugins/csrf/CSRFTest.kt
**Subsystem**
Server, CSRF
**Motivation**
- [KTOR-6701](https://youtrack.jetbrains.com/issue/KTOR-6701) CSRF: false positive originMatchesHost validation when default port is explicitly defined
**Solution**
Always check origin with port in case it's explicitly specified.
=> KTOR-6701 CSRF match origin on host when default port is included

ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/src/io/ktor/server/plugins/csrf/CSRF.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/test/io/ktor/server/plugins/csrf/CSRFTest.kt
**Subsystem**
Server, CSRF
**Motivation**
- [KTOR-6698](https://youtrack.jetbrains.com/issue/KTOR-6698) CSRF: validations probably shouldn't be applied to GET/HEAD/OPTIONS requests
**Solution**
Skips validation for GET, HEAD, and OPTIONS requests.
=> KTOR-6698 Skip safe HTTP methods for CSRF

gradle/libs.versions.toml
**Subsystem**
Server, build
**Motivation**
- [KTOR-6666](https://youtrack.jetbrains.com/issue/KTOR-6666)
**Solution**
Looks like the serialization lib got updated again, this will fix the maven publishing / allocation tests.  I'll try to find a solution that allows us to upgrade this.
=> KTOR-6666 Fix Ktor build problem; cannot compile native targets

build.gradle.kts
On CI environment, it is a common situation to have different versions for kotlin-native and Kotlin plugin because we don't push all the Kotlin verisons to the dev repo.
**Subsystem**
build script
**Motivation**
This PR solves problem with different versions for "org.jetbrains.kotlin" dependencies and "org.jetbrains.kotlin:kotlin-native-prebuilt" on CI.
**Solution**
Turned off version alignment
=> Turned of forcing version update for kotlin native dependencies.

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/SSE.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/builders.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt
**Subsystem**
Client, SSE
**Motivation**
- [KTOR-6614](https://youtrack.jetbrains.com/issue/KTOR-6614) Installing SSE breaks GET/POST functionality
**Solution**
Added an attribute flag to enable SSE transform; previously it would apply to all requests.
=> KTOR-6614 Fix SSE client breaking non-SSE requests

ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIOSpecificHttpsTest.kt
This test just recently started failing because the server started responding with 401's.
I don't know what exactly it's testing, or why were making calls to npay.eu in our test... I'm thinking maybe we should just delete it?
=> Disable failing https test

ktor-network/ktor-network-tls/build.gradle.kts, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/HostnameUtils.kt, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/HostnameUtilsTest.kt
Fix [KTOR-6746](https://youtrack.jetbrains.com/issue/KTOR-6746) CIO: "getSubjectAlternativeNames(...) must not be null" when IP-addresses are verified and no SAN in the certificate
=> KTOR-6746 Add nullability check for certificates

ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/JsUtils.kt
Two requests were merged next to each other:
- [Wasm support](https://github.com/ktorio/ktor/pull/3575)
- [SSE Updates](https://github.com/ktorio/ktor/pull/3951)
And on the build server, there were no WasmJs builds configured (see https://github.com/ktorio/ktor-build/pull/84)
This led to Wasm code being broken in master, and errors were unnoticed. 
This PR provides fixes to the build.
=> Fix WasmJs build

ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/src/io/ktor/server/plugins/csrf/CSRF.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/test/io/ktor/server/plugins/csrf/CSRFTest.kt
**Subsystem**
Server, CSRF
**Motivation**
- [KTOR-6697](https://youtrack.jetbrains.com/issue/KTOR-6697) CSRF: confusing error message when Host has no port and the hosts match
**Solution**
Error message origin includes port when specified.
=> KTOR-6697 CSRF: confusing error message when Host has no port and hosts match

ktor-server/ktor-server-test-host/jvm/test/TestApplicationTestJvm.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplicationResponse.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/Utils.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-host/jvmAndNix/test/TestApplicationTest.kt
**Subsystem**
Test Client
**Motivation**
[KTOR-6909](https://youtrack.jetbrains.com/issue/KTOR-6909)
=> KTOR-6909 Add SocketTimeout for Test Engine

gradle.properties, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlCallbacks.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/EventsTest.kt, ktor-io/common/src/io/ktor/utils/io/ByteChannelSequential.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt, ktor-network/jvmAndNix/test/io/ktor/network/sockets/tests/UDPSocketTest.kt, ktor-server/ktor-server-cio/jvmAndNix/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-plugins/ktor-server-default-headers/jvmAndNix/src/io/ktor/server/plugins/defaultheaders/DefaultHeaders.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/TestApplication.kt, ktor-utils/posix/src/io/ktor/util/network/NetworkAddressNative.kt
**Motivation**
`kotlinx-atomicfu` is on the way to stabilization, as the next step I'm going to enable compiler transformations by default with the following getting rid of legacy transformations. For that it would be great to enable compiler plugin transformations in ktor. This PR enables JVM and Kotlin Native IR transformations performed by atomicfu-compiler-plugin. 
I've disabled JS IR transformations, for now there is a discussion regarding removal of the JS part of the compiler plugin.
**Solution**
Minor changes were made in the code: 
- replaced `minusAssign`/`plusAssign` operators with `addAndGet` call, because the operators are not supported by the compiler plugin.
- introduced atomic extension function to avoid passing atomic reference as a parameter …
=> Apply kotlinx-atomicfu compiler plugin

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BearerAuthProvider.kt
**Subsystem**
Client-Auth
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-6928/Auth-Make-refreshToken-of-BearerTokens-class-nullable
**Solution**
Make refreshToken nullable. This change is ABI compatible, but not API. On the other hand this parameter isn't used by Ktor, only by users.
Alternative: wait for v3.
=> KTOR-6928 Make refresh_token optional according to RFC 6749

buildSrc/src/main/kotlin/TargetsConfig.kt
KotlinHierarchyTemplate allows writing KMP source set structures with less code and without explicit dependsOn relations.
There is one downside is that all source sets are created now if at least one of the target is declared. i.e. for example if JS target is declared but wasm is not. Then jsAndWasmSharedMain source set will be created anyway.
=> Use KotlinHierarchyTemplate for structuring source sets

gradle/libs.versions.toml
This reverts commit d96f14697c9371f0efe07e1349b9b65f7d53e646.
All of our common compilation targets have been broken for the last week after this dependency update.  I just noticed today that the allocation tests target on all PRs are failing because of this.
=> Revert "fix(deps): update coroutines.version to v1.8.1 (#4028)"

ktor-server/ktor-server-cio/build.gradle.kts
CIOHttpServerTest extends from the base class
HttpServerCommonTestSuite. It in turn extends EngineTestBase declared in :ktor-server:ktor-server-test-base. Dependency on this module is declared for jvmTest instead of the shared jvmAndNixTest that contains CIOHttpServerTest. The missing dependency on a transitive module with the grandparent class results in a MISSING_DEPENDENCY_SUPERCLASS in K2 IDE.
KTIJ-28250
**Subsystem**
Build configuration
**Motivation**
KTOR is one of the quality gate projects for K2 IDE.
Relates to https://youtrack.jetbrains.com/issue/KTIJ-28250.
We think that this particular problem might be a misconfiguration in KTOR itself rather then a resolution issue.
**Solution**
Update the build config.
=> Lift test dependency to the source set that uses it

ktor-client/ktor-client-core/common/src/io/ktor/client/network.sockets/TimeoutExceptionsCommon.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt, ktor-http/common/src/io/ktor/http/auth/AuthScheme.kt, ktor-http/jvm/src/io/ktor/http/content/MultipartJvm.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/RequestResponseBuilder.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteChannelCtor.kt, ktor-io/common/src/io/ktor/utils/io/ByteChannelUtils.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/core/Copy.kt, ktor-io/common/src/io/ktor/utils/io/core/internal/ChunkBuffer.kt, ktor-io/common/src/io/ktor/utils/io/internal/AwaitingSlot.kt, ktor-io/js/src/io/ktor/utils/io/core/ByteOrderJS.kt, ktor-io/jsAndWasmShared/src/io/ktor/utils/io/pool/DefaultPool.kt, ktor-io/jvm/src/io/ktor/utils/io/core/ByteOrderJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/jvm/nio/WriteSuspendSession.kt, ktor-io/mingwX64/src/CharsetMingw.kt, ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt, ktor-io/posix/src/io/ktor/utils/io/core/ByteOrderNative.kt, ktor-io/wasmJs/src/io/ktor/utils/io/core/ByteOrder.wasmJs.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/Render.kt, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOWebSocketTestJvm.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt, ktor-server/ktor-server-test-host/jvmAndNix/src/io/ktor/server/testing/client/TestHttpClientEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt, ktor-utils/jvm/src/io/ktor/util/cio/FileChannels.kt
Addressing comments and CI problems in https://github.com/ktorio/ktor/pull/4032
=> Fixes for kotlinx-io byte channel handling

ktor-http/api/ktor-http.api, ktor-http/common/src/io/ktor/http/URLUtils.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
**Subsystem**
ktor-http
**Motivation**
issue https://github.com/ktorio/ktor/issues/1903. 
Currently URL parsing returns a valid URL when an invalid URL is passed in (for "bogus" it returns "http://localhost/bogus"). Also there is no method that would return null instead of an exception if url parsing fails.
**Solution**
added `parseUrl` function to the `URLUtils.kt`, it tries to parse the URL using the passed string and, if unsuccessful, returns null
=> KTOR-360: add parseUrl function

ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-http/common/src/io/ktor/http/content/OutgoingContent.kt
**Subsystem**
Client, CIO, SSE
**Solution**
Extract check of needing processing content from `launch`. Because otherwise, we have the following situation:
``` kotlin
fun makeDedicatedRequest(...) {
try {
writeRequest(...)
readResponse(...)
} catch (cause: Throwable) {
// error must be caught here
throw cause.mapToKtor(request)
}
}
fun writeRequest(...) = withContext(callContext) {
writeBody(...)
}
fun writeBody(...) {
val scope = CoroutineScope(callContext + CoroutineName("Request body writer"))
scope.launch {
try {
processOutgoingContent(...) // error is throwing here
}
}
}
```
So where is a race and a case when because of `launch` in `writeBody`, `readResponse` starts and finishes earlier than the error is throwing in `launch`, and the error isn't caught 
Proposed solution: Extract …
=> Fix flaky testErrorForProtocolUpgradeRequestBody 

ktor-io/linux/src/CharsetLinux.kt, ktor-io/mingwX64/src/CharsetMingw.kt
Fix [KTOR-7016](https://youtrack.jetbrains.com/issue/KTOR-7016) Embedded Linux device without iso-8859-1 and UTF-16 cannot use ktor-network
=> KTOR-7016 Lazy initialize iconv charsets

ktor-http/common/src/io/ktor/http/FileContentType.kt, ktor-http/common/src/io/ktor/http/Mimes.kt, ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/test/io/ktor/server/webjars/WebjarsTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
**Subsystem**
Server, Static
**Motivation**
[KTOR-6655](https://youtrack.jetbrains.com/issue/KTOR-6655)
1) `application/javascript` obsoleted in favor of `text/javascript` (https://www.iana.org/assignments/media-types/application/javascript)
2) Add charset for `svg`, it's optional parameter (https://www.w3.org/TR/SVG/mimereg.html)
=> Fix missing charset for static js, css and svg resources

ktor-test-dispatcher/build.gradle.kts
**Subsystem**
N/A
**Motivation**
K2 IDE quality gates for multiplatform project
**Solution**
The `TestResult` class from `kotlinx-coroutines-test` is used as the return type in the `testSuspend` function from the `ktor-test-dispatcher:commonMain`. So the library is an API dependency for the module. Changing `implementation`
dependency to `api` fixes the K2 `MISSING_DEPENDENCY_CLASS` diagnostics in common tests, which were false negatives in the K1. Example: `io.ktor.utils.io.ByteChannelTest`.
CLI compilations don't report the error: there are no compilations for common test source sets that would've missed the dependency. Platform test compilations use the `actual` versions, which are type aliases with RHS types from stdlib. Stdlib is an implicit dependency, so there's no error either. …
=> Change kotlinx-coroutines-test dependency to API

ktor-server/ktor-server-plugins/ktor-server-call-id/api/ktor-server-call-id.api, ktor-server/ktor-server-plugins/ktor-server-call-id/jvm/src/io/ktor/server/plugins/callid/CallIdJvm.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/api/ktor-server-call-logging.api, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/calllogging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/calllogging/CallLoggingConfig.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/calllogging/MDCEntryUtils.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/calllogging/MDCHook.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/calllogging/MDCProvider.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/calllogging/CallLoggingTest.kt, ktor-server/ktor-server-test-base/jvm/src/io/ktor/server/test/base/EngineTestBaseJvm.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/testing/TestApplicationEngineTest.kt
**Subsystem**
Server
**Motivation**
- [KTOR-4273](https://youtrack.jetbrains.com/issue/KTOR-4273) CallLogging: package is misspelled
**Solution**
Add g.
=> KTOR-4273 Fix typo in CallLogging plugin package

ktor-io/js/src/io/ktor/utils/io/charsets/CharsetJS.kt, ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt
**Subsystem**
io utils
**Motivation**
Since the class is called Exception, it should be an ✨ Exception ✨
**Solution**
I decided to make it an `IOException` as the JVM version also extends from IOException
=> Make MalformedInputException actually inherit from exception

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, gradle/libs.versions.toml, ktor-server/ktor-server-plugins/build.gradle.kts
**Subsystem**
Build
**Motivation**
- [KTOR-7123](https://youtrack.jetbrains.com/issue/KTOR-7123) Some dependency versions not tracked
I noticed today we had an older version of slf4j floating around, which is replaced by the one imported by logback, but I figure it would be best if all our versions are tracked in one place.
**Solution**
Read versions from `libs.versions.toml` rather than using constants.
=> KTOR-7123 Replace Versions values with catalog

ktor-utils/nix/interop/threadUtils.def
ktor-utils/nix/interop/threadUtils.def has some C code which is internally compiled by Clang from the LLVM bundled with K/N.
This C code uses `printf` and includes `printf.h` to get the declaration. Apparently, `printf.h` doesn't declare `printf` function, `stdio.h` does. So, this causes an implicit declaration warning (`-Wimplicit-function-declaration`) with Clang 11 (currently used in K/N).
With updating to Clang 16, this warning becomes an error, so the code no longer compiles.
This commit replaces `printf.h` by `stdio.h` and thus fixes the problem.
KT-49279
**Subsystem**
ktor-utils
**Motivation**
This PR prepares ktor compilation for Kotlin 2.1.0 where we intend to merge the update to LLVM 16.
https://youtrack.jetbrains.com/issue/KT-49279/Kotlin-Native-update-LLVM-from-11.1.0-to-16.0.0 …
=> [kc/dev] Fix compatibility with Clang 16 for C code in nix threadUtils.def

buildSrc/src/main/kotlin/test/server/tests/ServerSentEvents.kt, ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/SSE.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/builders.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpSSESession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-shared/ktor-sse/api/ktor-sse.api, ktor-shared/ktor-sse/common/src/io/ktor/sse/ServerSentEvent.kt
**Subsystem**
Client, SSE
**Motivation**
[KTOR-6808](https://youtrack.jetbrains.com/issue/KTOR-6808)
=> KTOR-6808 Fix exception handling in SSE

ktor-utils/nix/interop/threadUtils.def
ktor-utils/nix/interop/threadUtils.def has some C code which is internally compiled by Clang from the LLVM bundled with K/N.
This C code uses `printf` and includes `printf.h` to get the declaration. Apparently, `printf.h` doesn't declare `printf` function, `stdio.h` does. So, this causes an implicit declaration warning (`-Wimplicit-function-declaration`) with Clang 11 (currently used in K/N).
With updating to Clang 16, this warning becomes an error, so the code no longer compiles.
This commit replaces `printf.h` by `stdio.h` and thus fixes the problem.
KT-49279
**Subsystem**
ktor-utils
**Motivation**
This PR prepares ktor compilation for Kotlin 2.1.0 where we intend to merge the update to LLVM 16.
https://youtrack.jetbrains.com/issue/KT-49279/Kotlin-Native-update-LLVM-from-11.1.0-to-16.0.0 …
=> Fix compatibility with Clang 16 for C code in nix threadUtils.def

ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/RoutingRoot.kt
**Subsystem**
Server Core
**Motivation**
The check prevented users from changing the log level of the `LOGGER` at a later point as the interceptor responsible isn't added.
See [KTOR-7193](https://youtrack.jetbrains.com/issue/KTOR-7193/Tracing-allow-changing-log-level-at-runtime) for an extensive rationale.
**Solution**
Remove the check. The SLF4j implementation will do it prior to every log anyway. The performance impact should be absolutely neglectable.
=> KTOR-7193 RoutingRoot: remove preemptive tracing check

ktor-utils/common/src/io/ktor/util/Text.kt
**Subsystem**
ktor-utils
**Motivation**
issue: [KTOR-7209](https://youtrack.jetbrains.com/issue/KTOR-7209/io.ktor.util.TextKt.chomp-doesnt-work-on-strings-with-more-than-one-character)
`chomp` assumes the input string is exactly one character, however it is expected to work with any non-empty separator
**Solution**
Fixed offset in substring from `1` to `separator.length`
=> KTOR-7209: fix Text.chomp values separator

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngineBase.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngineConfig.kt, ktor-client/ktor-client-mock/api/ktor-client-mock.api, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngineConfig.kt
Fix [KTOR-6417](https://youtrack.jetbrains.com/issue/KTOR-6417) Ktor Client MockEngine dispatcher handle removed
[KTOR-6462](https://youtrack.jetbrains.com/issue/KTOR-6462) Ktor clients and servers should use Dispatchers.IO.limitedParallelism(...) wherever possible
We need the possibility to set custom dispatchers to enable users to reuse dispatchers and configure test-specific dispatchers in tests.
=> KTOR-6417 Allow changing dispatcher in the client

ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/src/io/ktor/server/plugins/csrf/CSRF.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/test/io/ktor/server/plugins/csrf/CSRFTest.kt
**Subsystem**
Server, CSRF
**Motivation**
- [KTOR-6695](https://youtrack.jetbrains.com/issue/KTOR-6695) CSRF: The allowOrigin method enables the Origin Header validation
**Solution**
After thinking about how to provide some default behaviour for the CSRF plugin, I am of the opinion that it would be unwise to select one of the mitigations automatically for the user.  Instead, we ought to report an error for when it is an empty configuration.  Personally, I'd rather throw an exception, but logging a warning should be enough.
=> KTOR-6695 Add configuration warning when nothing is provided for CSRF

ktor-server/ktor-server-plugins/ktor-server-csrf/jvmAndNix/test/io/ktor/server/plugins/csrf/CSRFTest.kt
Slf4j no longer available for the jvmAndNix target.
=> KTOR-6695 Fix for logger reference after main branch changes

ktor-network/jvmAndNix/test/io/ktor/network/sockets/tests/TCPSocketTest.kt, ktor-network/nix/src/io/ktor/network/selector/SelectUtils.kt, ktor-network/nix/src/io/ktor/network/sockets/ConnectUtilsNative.kt, ktor-network/nix/src/io/ktor/network/sockets/TCPServerSocketNative.kt, ktor-network/nix/src/io/ktor/network/sockets/TCPSocketNative.kt
[KTOR-5289](https://youtrack.jetbrains.com/issue/KTOR-5289) withTimeout doesn't cancel socket connection on native
This PR changes the connect call to not block. That means connect is now cancellable and works with timeouts. Furthermore, I noticed that in some conditions connect can block for very long (on iOS), which is now also resolved as it can be cancelled.
On JVM the connect call is already non-blocking, so no changes needed there.
My second commit changes the exception type from `IllegalStateException` to `IOException`, as I think this is better . You can revert it if needed as it is a separate commit.
=> KTOR-5289 Change TCP connect on native to non-blocking and cancellable

gradle/libs.versions.toml, ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt, ktor-http/ktor-http-cio/api/ktor-http-cio.api, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/CIOMultipartDataBase.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-io/api/ktor-io.api, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/CountedByteReadChannel.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/TestEngineMultipartTest.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/build.gradle.kts, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/src/io/ktor/serialization/kotlinx/json/JsonSupport.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/jvm/src/io/ktor/serialization/kotlinx/json/JsonExtensionsJvm.kt
Fix [KTOR-7201](https://youtrack.jetbrains.com/issue/KTOR-7201) Data truncated in receiveParameters and receiveMultipart
=> KTOR-7201 Fix data truncated in receiveParameters and receiveMultipart

ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelOperations.jvm.kt, ktor-io/jvm/test/ByteReadChannelReadTest.jvm.kt
[KTOR-7220](https://youtrack.jetbrains.com/issue/KTOR-7220) ByteReadChannel.copyTo sometimes throws "IllegalArgumentException: Buffer is empty"
=> KTOR-7220 Fix reading from empty Buffer

ktor-network/nix/src/io/ktor/network/sockets/ConnectUtilsNative.kt, ktor-network/nix/src/io/ktor/network/sockets/DatagramSocketNative.kt, ktor-network/nix/src/io/ktor/network/sockets/TCPServerSocketNative.kt, ktor-network/nix/src/io/ktor/network/sockets/UDPSocketBuilderNative.kt
[KTOR-6977](https://youtrack.jetbrains.com/issue/KTOR-6977) ConnectionUtilsNative leaks descriptors on error
=> KTOR-6977 Fix descriptor leak on bind/connect error

ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/src/io/ktor/server/plugins/cors/CORSUtils.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/plugins/CORSTest.kt
**Subsystem**
ktor-server-plugin/ktor.server.plugins.cors
**Motivation**
[KTOR-5936](https://youtrack.jetbrains.com/issue/KTOR-5936): every origin with a trailing slash at the end is considered valid and the request passes successfully, even if this origin was not added to the CORS config
**Solution**
Corrected origin validation and origin normalization
=> KTOR-5936: add support for CORS origin with trailing slash

buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/WasmConfig.kt, gradle/libs.versions.toml
**Subsystem**
All WasmJs target modules
**Motivation**
The browser declarations are [going to be moved](https://youtrack.jetbrains.com/issue/KT-54299/Extract-org.w3c-declarations-to-separate-library-from-K-Wasm-Stdlib) from the wasmJs stdlib to a separate [artifact](https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kotlinx-browser).
**Solution**
Add a new dependency to wasmJs target.
=> Add kotlinx.browser dependency to WasmJs target

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/application/ApplicationEnvironment.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/ApplicationEnvironmentJvm.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt, ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/application/CommonApplicationEnvironment.kt, ktor-server/ktor-server-core/nix/src/io/ktor/server/application/NixApplicationEnvironment.kt, ktor-server/ktor-server-core/nix/src/io/ktor/server/engine/ApplicationEngineEnvironmentNix.kt, ktor-server/ktor-server-core/nix/src/io/ktor/server/engine/EmbeddedServerNix.kt
**Subsystem**
Server
**Motivation**
[KTOR-7264](https://youtrack.jetbrains.com/issue/KTOR-7264) Backwards compatibility for monitor
This change breaks the Koin plugin, and anything else that would have relied on the monitor property. 
**Solution**
Moved monitor back to `ApplicationEnvironment` with a deprecation warning for direct access.
=> KTOR-7264 Revert migration of monitor property to fix backwards compatibility

buildSrc/src/main/kotlin/NativeUtils.kt, buildSrc/src/main/kotlin/Publication.kt, ktor-server/ktor-server-core/build.gradle.kts, ktor-server/ktor-server-test-base/build.gradle.kts, ktor-server/ktor-server-test-host/build.gradle.kts
fixes [KTOR-6368](https://youtrack.jetbrains.com/issue/KTOR-6368/Add-watchosDeviceArm64-target) by adding workaround for `yaml` module and removing unnecessary dependencies on that module in tests.
[yamlkt](https://github.com/Him188/yamlkt/issues/67) doesn't support the target yet. There is an open [PR](https://github.com/Him188/yamlkt/pull/72), but there are some problems with integration.
After that PR will be merged, dependency could be updated and hack in `NativeUtils` could be removed.
=> Add `watchosDeviceArm64` target with yaml workaround

ktor-network/windows/src/io/ktor/network/selector/SelectUtilsWindows.kt
Found an issue in the mingw selector code.
When a single descriptor would suspend for both reading and writing, it would cause an `IndexOutOfBoundsException`.
Not really sure how to make a test that suspends on both reading and writing.
=> Fix IndexOutOfBoundsException in mingwX64 selector code

ktor-network/api/ktor-network.api, ktor-network/jvmAndPosix/src/io/ktor/network/sockets/Datagram.kt, ktor-network/jvmAndPosix/src/io/ktor/network/sockets/Sockets.kt, ktor-network/posix/src/io/ktor/network/sockets/DatagramSocketNative.kt
[KTOR-7303](https://youtrack.jetbrains.com/issue/KTOR-7303) Remove read/write channels for UDP sockets
I didn't remove the `attachForReading`/`attachForWriting` functions from the internal NIOSocketImpl. Is that alright or should they be moved to `SocketImpl`?
=> KTOR-7303 Remove read/write channels for UDP sockets

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/PreCompressed.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
**Subsystem**
Server, StaticContent
**Motivation**
[KTOR-7243](https://youtrack.jetbrains.com/issue/KTOR-7243)
**Solution**
Add a flag `reloadOnRequest`, and if it is set to true, then reload the zip every time a request comes
I was also thinking about [`WatchService`](https://docs.oracle.com/javase%2F8%2Fdocs%2Fapi%2F%2F/java/nio/file/WatchService.html) for `FileSystem`, but it's not really obvious for me, because on request we can try to get and go through incoming `WatchEvents`, we can keep map of  modified/deleted/created `WatchEvents` and reload `file` or entire `zip` if it was changed. But maybe a variant with reloading zip on request is okay to go. It's much simpler and more obvious
=> KTOR-7243 Support reloading of zip files in StaticContent

buildSrc/src/main/kotlin/test/server/tests/Content.kt, buildSrc/src/main/kotlin/test/server/tests/Encoding.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/internal/ByteChannelReplay.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/src/ContentEncoding.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/test/ContentEncodingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt
**Subsystem**
Client, ContentEncoding, SaveBody
**Motivation**
- [KTOR-7265](https://youtrack.jetbrains.com/issue/KTOR-7265) ContentEncoding: request hangs when using 3.0.0-beta-2
**Solution**
The problem would arise when the `SaveBody` plugin's `ByteChannelReplay` would be called by two consumers and the first wouldn't read the full response.  This would cause the 
deferred result to never complete, which would make subsequent calls hang indefinitely.
The simplest solution here is to just cancel the writer on the first caller when the second tries to read.  This allows the stream to finish copying without relying on being read by the first caller.
This solution has the caveat that you can run into problems when you try accessing the response with multiple threads.  I attempted to do a …
=> KTOR-7265 Fix for ContentEncoding deadlock

.github/workflows/gradle-wrapper-validation.yml
**Subsystem**
CI
**Motivation**
The coordinate changed to gradle/actions/wrapper-validation, that's why renovatebot was unable to bump this dependency.
**Solution**
Use new coordinates.
=> CI: Update gradle-wrapper-validation action to v4

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt
**Subsystem**
Http Client, retries with exponential backoff
**Motivation**
The exponential backoff has two issues
- The "base delay" multiplier is fixed to 1 second
- The initial delay is already `base^1 * 1 second`, resulting in 2 seconds for the first delay with the default base of 2.0
While you could set a non-default base of e.g. 1.1, this flattens mainly the exponential increase, and still does not allow a initial delay < 1 second. Setting the base to `0 < delay < 1` would even lead to decreasing delays. This is at least counter-intutive. 
**Solution**
- Allow the delay multiplier to be set to arbitrary millisecond values
- Fix the initial delay to not be `base ^ retry`, but `base ^(retry - 1)`
Examples: 
`base = 2, baseDelay = 1000` produces delays of 1000, 2000, 4000, 8000 ... ms …
=> KTOR-7294: allow for exp. retry delays of below 2 seconds

ktor-server/ktor-server-jetty-jakarta/ktor-server-jetty-test-http2-jakarta/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/src/io/ktor/server/auth/jwt/JWTAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/src/io/ktor/server/auth/jwt/JWTUtils.kt, ktor-server/ktor-server-plugins/ktor-server-auth-jwt/jvm/test/io/ktor/server/auth/jwt/JWTAuthTest.kt, ktor-server/ktor-server-plugins/ktor-server-auth-ldap/jvm/src/io/ktor/server/auth/ldap/Ldap.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/Authentication.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/AuthenticationContext.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/AuthenticationInterceptors.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/AuthenticationProvider.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/BasicAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/BearerAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/FormAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/OAuthCommon.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/Principal.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/SessionAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/src/io/ktor/server/auth/SimpleAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/test/io/ktor/tests/auth/AuthBuildersTest.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/test/io/ktor/tests/auth/BasicAuthTest.kt, ktor-server/ktor-server-plugins/ktor-server-auth/common/test/io/ktor/tests/auth/SessionAuthTest.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/src/io/ktor/server/auth/DigestAuth.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/DigestTest.kt
**Subsystem**
Server, Authentication
**Motivation**
[KTOR-7323](https://youtrack.jetbrains.com/issue/KTOR-7323) Drop marker interface requirements in Ktor auth
These interfaces don't do anything and they prevent users from using decoupled domain objects for their principal and credential types.
**Solution**
Removed the type boundaries and deprecated the interfaces.
=> KTOR-7323 Drop marker interface requirements in Ktor auth

ktor-server/ktor-server-plugins/ktor-server-swagger/api/ktor-server-swagger.api, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/Swagger.kt
Fix [KTOR-6491](https://youtrack.jetbrains.com/issue/KTOR-6491) Make the internal Route.swaggerUI method public
=> KTOR-6491 Make the internal Route.swaggerUI method public

ktor-http/api/ktor-http.api, ktor-http/api/ktor-http.klib.api, ktor-http/build.gradle.kts, ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-utils/api/ktor-utils.api, ktor-utils/api/ktor-utils.klib.api, ktor-utils/build.gradle.kts, ktor-utils/common/src/io/ktor/util/date/Date.kt
**Subsystem**
`ktor-http`, `ktor-utils`
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-6258/Make-Cookie-class-Serializable
**Solution**
Added kotlinx.serialization as a dependency to these modules and added `@Serializable` annotation to `Cookie` and `GMTDate` classes.
I wasn't able to use `compileOnly` configuration for kotlinx.serialization dependency as it is supported only on JVM targets. More context: https://youtrack.jetbrains.com/issue/KT-64109/Using-compileOnly-runtimeOnly-dependencies-in-K-N-related-configurations-leads-to-odd-behaviour
Moreover, some tests were failing on JVM target with `NoClassDefFoundError` exception:
```
java.lang.NoClassDefFoundError: kotlinx/serialization/KSerializer
at io.ktor.util.date.GMTDate.<clinit>(Date.kt:106)
at …
```
=> KTOR-6258 Make Cookie class Serializable

ktor-network/posix/src/io/ktor/network/sockets/CIOReader.kt, ktor-network/posix/src/io/ktor/network/sockets/DatagramSocketNative.kt
**Subsystem**
ktor-network on mingwX64
**Motivation**
The recvfrom call can fail with `-1L`, which means there is an error. On Windows, the `WSAGetLastError()` function is called to retrieve the error, but for some reason this can return `0` (which means NO error). This does not happen that often, but when receiving UDP messages continually, this does occur about once per minute for me.
**Solution**
Solution is to just ignore the error as `0` means no error. Why this happens, no idea. UDP receive still works after this strange error and packets can be received. Not sure how to reproduce this in a test.
=> Fix UDP/TCP receive on Windows

gradle.properties, ktor-server/ktor-server-plugins/ktor-server-double-receive/common/test/DoubleReceiveTest.kt, ktor-server/ktor-server-plugins/ktor-server-double-receive/jvm/test/DoubleReceiveTestJvm.kt
**Subsystem**
Tests / CI
**Motivation**
Gradle daemon is exhausting it's memory in TC.
**Solution**
Disable the double receive test.
=> Fix gradle memory issue for running tests

ktor-server/ktor-server-plugins/ktor-server-cors/common/src/io/ktor/server/plugins/cors/CORS.kt, ktor-server/ktor-server-plugins/ktor-server-csrf/common/src/io/ktor/server/plugins/csrf/CSRF.kt, ktor-server/ktor-server-plugins/ktor-server-http-redirect/common/src/io/ktor/server/plugins/httpsredirect/HttpsRedirect.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/plugins/CORSTest.kt
**Subsystem**
Server, Netty
**Motivation**
- [KTOR-4433](https://youtrack.jetbrains.com/issue/KTOR-4433) Netty: UnsupportedOperationException is thrown when responding in CallSetup and CORS plugin is installed
**Solution**
Ignore headers after the response is committed.  This aligns the behaviour with the other engines.
Ideally we'd have some mechanism for skipping other interceptors / phases in the application pipeline when you want to respond during the `CallSetup` phase and the like, though from what I can tell there is nothing in the platform for achieving this.
=> KTOR-4433 Fix Netty error on CORS trying to set header on committed requests

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/ktor-client-content-negotiation-tests/jvm/src/io/ktor/client/plugins/contentnegotiation/tests/JsonContentNegotiationTest.kt, ktor-shared/ktor-serialization/ktor-serialization-gson/jvm/test/ServerGsonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ServerJacksonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-tests/jvm/src/AbstractServerSerializationTest.kt
**Subsystem**
Client/Server, `ktor-serialization-*` modules
**Motivation**
[KTOR-7396](https://youtrack.jetbrains.com/issue/KTOR-7396/) Remove usage of deprecated `withTestApplication` DSL.
**Solution**
Migrated to `testApplication` DSL
=> KTOR-7396 Migrate ktor-serialization tests to testApplication DSL

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt, ktor-server/ktor-server-plugins/ktor-server-metrics/jvm/test/io/ktor/server/metrics/dropwizard/DropwizardMetricsTests.kt
**Subsystem**
Server, `ktor-server-metrics-*` modules
**Motivation**
[KTOR-7398](https://youtrack.jetbrains.com/issue/KTOR-7398/) Remove usage of deprecated withTestApplication DSL.
**Solution**
Migrated to testApplication DSL.
=> KTOR-7398 Migrate ktor-server-metrics tests to testApplication DSL

ktor-server/ktor-server-plugins/ktor-server-auth-ldap/jvm/test/io/ktor/tests/auth/ldap/LDAPServerExtension.kt, ktor-server/ktor-server-plugins/ktor-server-auth-ldap/jvm/test/io/ktor/tests/auth/ldap/LdapAuthTest.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/DigestTest.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/OAuth1aTest.kt
**Subsystem**
Server, `ktor-server-auth-*`
**Motivation**
[KTOR-7397](https://youtrack.jetbrains.com/issue/KTOR-7397/) Remove usage of deprecated `withTestApplication` DSL.
**Solution**
Migrated to `testApplication` DSL
=> KTOR-7397 Migrate ktor-server-auth tests to testApplication DSL

ktor-server/ktor-server-plugins/ktor-server-mustache/jvm/test/io/ktor/server/mustache/MustacheTest.kt, ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/test/io/ktor/server/pebble/PebbleTest.kt, ktor-server/ktor-server-plugins/ktor-server-velocity/jvm/test/io/ktor/tests/velocity/VelocityTest.kt, ktor-server/ktor-server-plugins/ktor-server-velocity/jvm/test/io/ktor/tests/velocity/VelocityToolsTest.kt
**Subsystem**
Server, `ktor-server-mustache`, `ktor-server-pebble`, `ktor-server-velocity`
**Motivation**
[KTOR-7406](https://youtrack.jetbrains.com/issue/KTOR-7406/) Remove usage of deprecated `withTestApplication` DSL.
**Solution**
Migrated to `testApplication` DSL
=> KTOR-7406 Migrate ktor-server-plugins tests to testApplication DSL

build.gradle.kts, buildSrc/src/main/kotlin/Publication.kt
**Subsystem**
Build System
**Motivation**
- [KTOR-6826](https://youtrack.jetbrains.com/issue/KTOR-6826) Include relocation notes for old Ktor modules
- [KTOR-7393](https://youtrack.jetbrains.com/issue/KTOR-7393) Redirect dependencies from ktor-server-test-base
**Solution**
I added a map for projects that have been moved, so that they can automatically be resolved by maven, and should include a note in the central listing.
I also noticed we have several artifacts that shouldn't have been included in the publications, so I added a couple to the `skipPublish` extension property, and included a clause in the publish condition to skip parent projects (projects without sub-projects, like `ktor-server`).
=> KTOR-6826 Include relocation notes for old ktor modules

ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOEngineTestJvm.kt, ktor-server/ktor-server-cio/jvmAndPosix/src/io/ktor/server/cio/CIOApplicationEngine.kt
**Subsystem**
Server, CIO
**Motivation**
[KTOR-7360](https://youtrack.jetbrains.com/issue/KTOR-7360)
=> KTOR-7360 Fix `EmbeddedServer.stop()` on CIO always blocks for shutdownGracePeriod

renovate.json
**Subsystem**
Renovate
**Motivation**
Enabled automerge setting [requires](https://docs.renovatebot.com/updating-rebasing/) all renovate branches to be always updated. It results in a lot of rebases and extra CI runs. Our CI is not prepared for that.
**Solution**
Disable automerge for now.
=> Disable automerge in Renovate

renovate.json
**Subsystem**
Renovate
**Motivation**
Renovate is still rebasing its PRs, producing noise
**Solution**
Explicitly specify that rebase is allowed only on conflicts
=> Allow renovate to rebase only on conflicts

ktor-server/ktor-server-tests/jvm/test/io/ktor/server/http/ApplicationRequestContentTestJvm.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/http/RespondFunctionsJvmTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/http/RespondWriteTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/AutoHeadResponseJvmTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CompressionTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CookiesTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/DataConversionTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/PartialContentTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/sessions/SessionTestJvm.kt
**Subsystem**
Server, `ktor-server-tests`
**Motivation**
[KTOR-7407](https://youtrack.jetbrains.com/issue/KTOR-7407/) Remove usage of deprecated `withTestApplication` DSL.
**Solution**
Migrated to `testApplication` DSL
=> KTOR-7407 Migrate ktor-server-tests to testApplication DSL

buildSrc/build.gradle.kts, renovate.json
Use [`embeddedKotlinVersion`](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.kotlin.dsl/embedded-kotlin-version.html) utility (provided by Gradle) to automatically align `kotlin("plugin.serialization")`
=> Align Kotlin Serialization plugin version in buildSrc

build.gradle.kts, buildSrc/src/main/kotlin/Publication.kt
This reverts commit 3da1214e1f66a45be57b1ff9e00f1db233fbd7c5.
**Subsystem**
Published artifacts
**Motivation**
Links to old artifacts actually goes the other way, so now maven will always try to use the old artifacts.
- [KTOR-7425](https://youtrack.jetbrains.com/issue/KTOR-7425) Maven builds not working
**Solution**
Reverts changes linking to old artifacts.
=> Revert "KTOR-6826 Include relocation notes for old ktor modules (#4276)"

build.gradle.kts, buildSrc/src/main/kotlin/Publication.kt
**Subsystem**
Build system
**Motivation**
- [KTOR-7393](https://youtrack.jetbrains.com/issue/KTOR-7393) Redirect dependencies from ktor-server-test-base
**Solution**
Redirect only the test-base artifact, because it was present in our generator for a long time and will cause issues if used instead of test-host when people upgrade.
I'll avoid trying to add the relocation notes for the 1.* artifacts that were moved, because it would involve creating new publications for each of them, which is very complicated and would be better done with a one-time script.
=> Test host redirect

ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WebSocketWithContentNegotiationTest.kt, ktor-shared/ktor-websockets/jvm/test/ParserTest.kt, ktor-shared/ktor-websockets/jvm/test/WriterTest.kt
**Subsystem**
Server, `ktor-server-websockets` tests
**Motivation**
[KTOR-7405](https://youtrack.jetbrains.com/issue/KTOR-7405) Remove usage of deprecated `withTestApplication` DSL.
**Solution**
Migrate to `testApplication` DSL.
It wasn't as simple as for other modules. Actually, I had to rewrite most of the tests to make them work.
It is better to review test-by-test in an IDE.
=> Migrate ktor-server-websockets tests to testApplication

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/JarFileContent.kt, ktor-utils/jvm/src/io/ktor/util/cio/InputStreamAdapters.kt
**Subsystem**
Server, `ktor-core`
**Motivation**
[KTOR-7012](https://youtrack.jetbrains.com/issue/KTOR-7012/) `InputStream.toByteReadChannel` creates an unattached job
**Solution**
Deprecate this extension in favor of the variant from `ktor-io` which doesn't suffer from this problem.
=> KTOR-7012 Deprecate `InputStream.toByteReadChannel` with fallback to ktor-io module

gradle/wrapper/gradle-wrapper.properties
**Motivation**
Gradle 8.10.1 makes builds unstable. For example, it randomly fails to apply `TestServerPlugin`:
```
Failed to apply plugin class 'test.server.TestServerPlugin'.
> Could not create task ':ktor-client:ktor-client-android:checkKotlinGradlePluginConfigurationErrors'.
> DefaultTaskCollection#configureEach(Action) on task set cannot be executed in the current context.
```
Issue: https://github.com/gradle/gradle/issues/30497
**Solution**
Downgrade to 8.10 and wait for the next version.
=> Downgrade to Gradle 8.10

gradle.properties
- Enabling `org.gradle.vfs.watch` is the default from Gradle 7.
- Parallel tasks executing.
=> Tweak Gradle flags

ktor-network/nix/src/io/ktor/network/selector/SelectUtilsNix.kt
**Subsystem**
ktor-network
**Motivation**
Received the following crash report on iOS:
```
Non-fatal Exception: ConcurrentModificationException
0  RemoteGamepad                  0x141330 kfun:kotlin.collections.HashMap.Itr#checkForComodification(){} + 593 (HashMap.kt:593)
1  RemoteGamepad                  0x141398 kfun:kotlin.collections.HashMap.KeysItr#next(){}1:0 + 600 (HashMap.kt:600)
2  RemoteGamepad                  0xdbb904 kfun:kotlin.collections.Iterator#next(){}1:0-trampoline + 18 (Iterator.kt:18)
3  RemoteGamepad                  0xaef308 kfun:io.ktor.network.selector.SelectorHelper.selectionLoop#internal + 1863 (_Collections.kt:1863)
4  RemoteGamepad                  0xaf0b1c kfun:io.ktor.network.selector.SelectorHelper.$start$lambda$0$FUNCTION_REFERENCE$0.invoke#internal + 53 …
```
=> Fix ConcurrentModificationException in SelectorHelper

ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinClientEngineConfig.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
**Subsystem**
Client, `ktor-client-darwin`
**Motivation**
[KTOR-7355](https://youtrack.jetbrains.com/issue/KTOR-7355/) Preconfigured NSURLSession causes requests to hang
**Solution**
It is a valid behavior because the session was created without the delegate.
Nevertheless, it is quite unobvious behavior, so I added check that delegate was specified and example of usage to KDoc.
=> KTOR-7355 Check in usePreconfiguredSession that delegate is set

ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/CIOMultipartDataBase.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/MultipartTest.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/http/TestEngineMultipartTest.kt
**Subsystem**
Server, I/O
**Motivation**
[KTOR-7356](https://youtrack.jetbrains.com/issue/KTOR-7356) Multipart/form-data: Form limit applied for binary and file items
Users having difficulty with the low limit getting triggered during file upload posting in slack recently when trying out the latest build.  The limit here is generally used to avoid DDoS attacks with endless streams, so most other frameworks set this in the megabytes.
**Solution**
Bumped the default limit to 50MB and added some actionable details to the thrown exception.
=> KTOR-7356 Increase multi-part formdata limit

ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt
**Subsystem**
Tests
**Motivation**
[Test history](https://ktor.teamcity.com/test/8431731462014885548?currentProjectId=Ktor_ProjectKtorCore)
**Solution**
Await for server finish before assertions
=> Fix flaky test WebSocketTest.testFragmentationMaxSize

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt
**Subsystem**
Server, plugins, ktor-server-metrics-micrometer
**Motivation**
The PR fixes annoying warning as described in https://youtrack.jetbrains.com/issue/KTOR-7035/
**Solution**
Registration of the MeterFilter is moved up, so that the filter is registered before the gauge meter. Warning message disappears.
=> KTOR-7035: Register MeterFilters before the very first Meter is registered.

ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingNode.kt, ktor-server/ktor-server-core/common/test/io/ktor/server/routing/RouteTest.kt
**Subsystem**
Server, Routing
**Motivation**
[KTOR-7449](https://youtrack.jetbrains.com/issue/KTOR-7449) UninitializedPropertyAccessException for `request` property when using MonitoringEvent(RoutingCallStarted)
**Solution**
Use lazy delegate over lateinit var.  The previous approach seemed a bit crazy to me.
=> KTOR-7449 Fix for uninitialized request

ktor-io/jvm/src/io/ktor/utils/io/jvm/javaio/Blocking.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt
**Subsystem**
Server, I/O
**Motivation**
[KTOR-7461](https://youtrack.jetbrains.com/issue/KTOR-7461) respondOutputStream reads entire contents into memory before returning response
**Solution**
The `OutputStream` adapter for `ByteChannel` was writing directly to the `writeBuffer` without ever flushing, which would cause the entire contents to be put into memory before being written to the socket.
=> KTOR-7461 Fix for OutputStream response writing full contents to memory

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/test/ReadUtf8LineTest.kt
**Subsystem**
Client/Server, I/O
**Motivation**
[KTOR-7474](https://youtrack.jetbrains.com/issue/KTOR-7474) ByteChannel.readUtf8Line() backwards compatibility
**Solution**
Re-introduced this function to prevent breaking consumers.  I also noticed that the behaviour changed so that the result is truncated after reaching the max rather than throwing the TooLongLineException, which seems like it could cause some problems, so I restored its use.
=> KTOR-7474 ByteChannel.readUtf8Line() backwards compatibility

ktor-server/ktor-server-plugins/ktor-server-sessions/common/src/io/ktor/server/sessions/SessionsBuilder.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/sessions/SessionTest.kt
**Subsystem**
**Motivation**
[KTOR-7442](https://youtrack.jetbrains.com/issue/KTOR-7442) Sessions: custom SessionSerializer is no longer supported
**Solution**
Removed the implicit call to initialize the kotlinx serializer when constructing the cookie session builder.
=> KTOR-7442 Sessions: custom SessionSerializer is no longer supported

gradle-settings-conventions/build.gradle.kts, renovate.json
**Subsystem**
Gradle
**Motivation**
Develocity auto-update broke scans publication.
Our develocity server does not support versions other than 3.17
**Solution**
Disable auto update
=> Fixed develocity version

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/atomicfu-conventions.gradle.kts
This change fixes this [train failure](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_KotlinxTrainKtorK2/565822720). 
```
e: KLIB resolver: The same 'unique_name=io.ktor:ktor-io' found in more than one library: /mnt/agent/work/1edc2f021dd239f7/project.ktor/ktor-io/build/classes/atomicfu/js/main, /mnt/agent/work/1edc2f021dd239f7/project.ktor/ktor-io/build/classes/kotlin/js/main
Please file an issue to https://kotl.in/issue and meanwhile use CLI flag `-Xklib-duplicated-unique-name-strategy` with one of the following values:
allow-all-with-warning: Use all KLIB dependencies, even when they have same `unique_name` property.
allow-first-with-warning: Use the first KLIB dependency with clashing `unique_name` property. No order guarantees are given though.
deny: Fail a …
```
=> WA: Disable JS legacy transformation manually until it is completely removed from the atomicfu plugin.

ktor-http/common/src/io/ktor/http/content/Multipart.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/CIOMultipartDataBase.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-io/common/src/io/ktor/utils/io/SourceByteReadChannel.kt, ktor-server/ktor-server-config-yaml/jvm/test/YamlConfigTestJvm.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ContentTestSuite.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/http/TestEngineMultipartTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/http/MultipartServerTest.kt, ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/http/MultipartServerTest.kt
**Subsystem**
Server, I/O
**Motivation**
[KTOR-7500](https://youtrack.jetbrains.com/issue/KTOR-7500) MultiPartData.readPart does not return null when stream ends
**Solution**
Introduce a reference to the previous part to automatically dispose.  This is necessary because of a change in 3.0 to use `ByteReadChannel` for file data, which is required for streaming the body properly.
Note: this will make it so you can't read the parts out of order, though I don't think that makes sense or was officially supported in any way before.
=> KTOR-7500 Fix multi-part read lock issue when part is skipped

ktor-client/ktor-client-cio/jvmAndPosix/src/io/ktor/client/engine/cio/ConnectionFactory.kt, ktor-network/api/ktor-network.api, ktor-network/api/ktor-network.klib.api, ktor-network/jvm/src/io/ktor/network/sockets/UDPSocketBuilderJvm.kt, ktor-network/jvmAndPosix/src/io/ktor/network/sockets/Builders.kt, ktor-network/jvmAndPosix/src/io/ktor/network/sockets/SocketOptions.kt, ktor-network/jvmAndPosix/src/io/ktor/network/sockets/TcpSocketBuilder.kt, ktor-network/jvmAndPosix/src/io/ktor/network/sockets/UDPSocketBuilder.kt, ktor-network/posix/src/io/ktor/network/sockets/UDPSocketBuilderNative.kt, ktor-server/ktor-server-cio/api/ktor-server-cio.api, ktor-server/ktor-server-cio/api/ktor-server-cio.klib.api, ktor-server/ktor-server-cio/jvmAndPosix/src/io/ktor/server/cio/CIOApplicationEngine.kt, ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/engine/ApplicationEngine.kt, ktor-server/ktor-server-test-base/posix/src/io/ktor/server/test/base/EngineTestBaseNix.kt
Note: this is a part of ongoing implementation of client/server support for CIO on JS/WasmJS (https://github.com/ktorio/ktor/compare/main...whyoleg:ktor:common-cio)
NodeJS APIs are asynchronous by default but server-related functions in `ktor` are non-suspend.
This PR has breaking changes which will be needed to allow to implement CIO server via NodeJS for JS/WasmJS in 3.1.
=> Preparation for NodeJS CIO server

ktor-server/ktor-server-tests/jvm/test/io/ktor/server/http/MultipartServerTest.kt
**Subsystem**
Server
**Motivation**
[KTOR-7505](https://youtrack.jetbrains.com/issue/KTOR-7505) Multi-part form data body does not work in native targets
**Solution**
No solution yet, hence the disabling.
=> KTOR-7505 Disable test broken on native

buildSrc/src/main/kotlin/test/server/tests/Auth.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinWebsocketSession.kt, ktor-client/ktor-client-java/jvm/src/io/ktor/client/engine/java/JavaHttpWebSocket.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
**Subsystem**
Websockets
**Motivation**
[KTOR-7363](https://youtrack.jetbrains.com/issue/KTOR-7363)
=> KTOR-7363 Fix ProtocolException when Websockets is used with Auth

ktor-io/api/ktor-io.api, ktor-io/jvm/src/io/ktor/utils/io/jvm/javaio/Reading.kt, ktor-io/jvm/src/io/ktor/utils/io/jvm/nio/Reading.kt, ktor-io/jvm/test/io/ktor/utils/io/jvm/nio/ReadingTest.kt
**Subsystem**
Shared, I/O
**Motivation**
[KTOR-7518](https://youtrack.jetbrains.com/issue/KTOR-7518) ReadableByteChannel to ByteReadChannel JVM interop is missing
I found this was missing during migration work for Space as a large sample project.  There are places where `ReadableByteChannel` is used for Ktor inputs.
**Solution**
Introduced a utility extension function for converting `ReadableByteChannel` to a `RawSource` and `ByteReadChannel` for async I/O.
=> KTOR-7518 Add ReadableByteChannel to ByteReadChannel interop util

ktor-client/ktor-client-core/api/ktor-client-core.api, ktor-client/ktor-client-core/api/ktor-client-core.klib.api, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/jvm/test/HttpCacheTest.kt
Fix [KTOR-7483](https://youtrack.jetbrains.com/issue/KTOR-7483) HttpCache: Cache collision in the plugin when Authorization header is used [ZD-6809850]
=> KTOR-7483 Allow auth header when client is not shared

ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt
Improve the ordering of the Jetty server initization so the configureServer step can configure the connections added by the server initializer
**Subsystem**
Ktor Server, Jetty Engine
**Motivation**
There is currently only limited means to customise the server created by the ktor server initializer.
Any logic in the `configuration.configureServer` block will always see 0 connections on the server. Whilst this is fine for adding custom connections it does not give any capacity to refine the configuration of the Jetty server connections created by Ktor.
It is possible to get the configured connections on the Jetty server, if the configure server block is executed after `initializeServer()`.
**Solution**
Switch the ordering of the `configuration.configureServer` invocation so the ktor created …
=> Improve Jetty server initializing for customization

ktor-client/ktor-client-plugins/ktor-client-json/ktor-client-gson/jvm/src/io/ktor/client/plugins/gson/GsonSerializer.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/util/Parameters.kt, ktor-utils/api/ktor-utils.api, ktor-utils/api/ktor-utils.klib.api, ktor-utils/common/src/io/ktor/util/reflect/Type.kt, ktor-utils/jsAndWasmShared/src/io/ktor/util/reflect/TypeInfoJs.kt, ktor-utils/jvm/src/io/ktor/util/reflect/TypeInfoJvm.kt, ktor-utils/posix/src/io/ktor/util/reflect/TypeInfoNative.kt
**Subsystem**
`ktor-utils`
**Motivation**
[KTOR-7540](https://youtrack.jetbrains.com/issue/KTOR-7540/Remove-reflection-utils-used-only-on-JVM-target-from-common-source-set) - JVM-specific field `reifiedType` has leaked into the common source set
**Solution**
Remove the field from `TypeInfo` and provide an extension property only for the JVM target.
=> KTOR-7540 Turn TypeInfo.reifiedType into an extension-property

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/application/PipelineCall.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingNode.kt
**Subsystem**
Server, Routing
**Motivation**
[KTOR-7543](https://youtrack.jetbrains.com/issue/KTOR-7543) Common backwards compatibility problems for 3.0
These are a couple of items that are tough to solve with structural replacement, and I've found are very common in projects.
**Solution**
- Added coroutine scope to RoutingContext so that `launch` references don't break.
- Added property alias through an extension for `call`, which is generally always used for interceptors - this only applies to pipeline contexts where the context extends `ApplicationCall`
=> KTOR-7543 Fix a couple backwards compatibility issues in 3.0

ktor-http/api/ktor-http.api, ktor-http/api/ktor-http.klib.api, ktor-http/common/src/io/ktor/http/content/Multipart.kt
**Subsystem**
Server, I/O
**Motivation**
[KTOR-7548](https://youtrack.jetbrains.com/issue/KTOR-7548) Introduce Flow API for multi-part
I realized during the Space migration exercise how difficult our current API is to work with.
**Solution**
This simply introduces `multipart.asFlow()` for reading in parts.
=> KTOR-7548 Introduce Flow API for multi-part

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/WebSockets.kt
Fix [KTOR-6963](https://youtrack.jetbrains.com/issue/KTOR-6963) Darwin: The `maxFrameSize` option has no effect
=> KTOR-6963 Fix darwin maxFrameSize option

ktor-client/ktor-client-cio/build.gradle.kts, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIORequestTest.kt, ktor-client/ktor-client-cio/jvmAndPosix/src/io/ktor/client/engine/cio/CIOEngine.kt, ktor-client/ktor-client-cio/jvmAndPosix/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/HttpClientEngine.kt
**Subsystem**
**Motivation**
[KTOR-6803](https://youtrack.jetbrains.com/issue/KTOR-6803) CIO: Requests face connection timeouts when executed on the Android main dispatcher
**Solution**
The problem was caused by a second address resolution performed in `releaseConnection()`. If something happens during this resolution (an exception is thrown or the resolved address differs from the first one), we never release a connection.
=> KTOR-6803 Use last resolved address to release connection

ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/jvm/test/ByteReadChannelOperationsJvmTest.kt
**Subsystem**
ktor-io
**Motivation**
See [KTOR-7571](https://youtrack.jetbrains.com/issue/KTOR-7571)
**Solution**
This attempts to solve a cpu-bound endless loop by both passing the number of expected bytes to `awaitContent()` and (in case `awaitContent()` doesn't actually suspend like [`SourceByteReadChannel`](https://github.com/ktorio/ktor/blob/c99356f5ea8a202bfaf022a57ab8de0643354e66/ktor-io/common/src/io/ktor/utils/io/SourceByteReadChannel.kt#L28)) to `yield()` to other coroutines between iterations.
=> KTOR-7571 byte read channel cpu lock

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/CI.kt, buildSrc/src/main/kotlin/KtorBuildProperties.kt, buildSrc/src/main/kotlin/TargetsConfig.kt, gradle-settings-conventions/build.gradle.kts, gradle-settings-conventions/settings.gradle.kts, gradle/libs.versions.toml
**Subsystem**
Test infrastructure
**Motivation**
[KTOR-7552](https://youtrack.jetbrains.com/issue/KTOR-7552/CI-Rerun-failed-tests-to-detect-flaky-tests) Detect flaky tests
**Solution**
Enable [testRetry feature](https://docs.gradle.com/develocity/gradle-plugin/current/#test_retry) of Develocity to rerun failed tests one time.
This feature works only for JVM tests, and flaky tests will be marked as "muted" in TC. However, we will be able to see flaky tests in Develocity reports.
See also: https://github.com/ktorio/ktor-build/pull/98
=> KTOR-7552 Rerun failed tests one more time

buildSrc/src/main/kotlin/NativeUtils.kt, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/api/ktor-serialization-kotlinx-xml.klib.api, ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-xml/gradle.properties
**Subsystem**
Client/Server, `ktor-serialization-kotlinx-xml`
**Motivation**
[KTOR-7583](https://youtrack.jetbrains.com/issue/KTOR-7583) Support missing native targets in ktor-serialization-kotlinx-xml
**Solution**
Enable native targets as we’ve updated xmlutil (https://github.com/ktorio/ktor/pull/4402)
=> KTOR-7583 Enable missing native targets in ktor-serialization-kotlinx-xml

ktor-http/common/src/io/ktor/http/URLBuilder.kt, ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
**Subsystem**
ktor-http
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-7410
**Solution**
Added processing of `about:blank` and other `about:` urls
=> KTOR-7410: add about URL parsing

ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt
[KTOR-6501](https://youtrack.jetbrains.com/issue/KTOR-6501) Add Actionalable KDocs for the HttpClient public API
=> KTOR-6501 Update API Docs for HttpClient

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/DigestProviderTest.kt, ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt, ktor-server/ktor-server-plugins/ktor-server-auth/jvm/test/io/ktor/tests/auth/DigestTest.kt
**Subsystem**
Client/Server, 
**Motivation**
- [KTOR-4318](https://youtrack.jetbrains.com/issue/KTOR-4318) Digest Auth does not implement nc parameter correctly according to RFC 7616
- [KTOR-7561](https://youtrack.jetbrains.com/issue/KTOR-7561) Digest auth: `username` and `cnonce` parameters aren't surrounded with quotes
**Solution**
Update parameters’ implementation to follow RFC 7616 guidelines.
This PR fixes only these two bugs, while we have more implementation inconsistencies with the RFC. I've created a separate issue to update Digest Auth implementation according to the RFC - [KTOR-7578](https://youtrack.jetbrains.com/issue/KTOR-7578/Update-Digest-authentication-implementation-according-to-RFC-7616)
It's better to review commit-by-commit
=> KTOR-4318, KTOR-7561: Fix digest auth parameters

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/contentnegotiation/JsonContentTypeMatcher.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/src/io/ktor/client/plugins/json/JsonContentTypeMatcher.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/MultipartTest.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/JettyKtorHandler.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyKtorHandler.kt
**Subsystem**
Server, `ktor-http-cio`
**Motivation**
[KTOR-7596](https://youtrack.jetbrains.com/issue/KTOR-7596) receiveMultipart fails with "IOException: Failed to parse multipart" when content-type is capitalized
**Solution**
Use case-insensitive check for multipart content-type
=> KTOR-7596 Make multipart Content-Type check case-insensitive

ktor-client/ktor-client-core/common/src/io/ktor/client/engine/Utils.kt
**Subsystem**
Client
**Motivation**
The product identifier in a user agent should not contain spaces.
https://httpwg.org/specs/rfc9110.html#field.user-agent
**Solution**
Make it kebab-case.
=> Remove space from default user agent

buildSrc/src/main/kotlin/test/server/TestServerPlugin.kt
**Subsystem**
Test infrastructure
**Motivation**
[KTOR-7645](https://youtrack.jetbrains.com/issue/KTOR-7645) Use BuildService API to start the test server
**Solution**
Refactor `TestServerPlugin` to use `BuildService` API and run the test server only before test tasks.
=> KTOR-7645 Use BuildService API to start the test server

ktor-utils/jsAndWasmShared/src/io/ktor/util/CryptoJs.kt
**Subsystem**
Client, JS
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-6158
**Solution**
* Use common global `crypto`
* Available since [Node 15](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto). Current LTS - Node 22 ;)
**Related PRs**
* #4422
=> KTOR-6158 JS. Remove redundant `require` call for `crypto`

ktor-http/common/test/io/ktor/tests/http/MimesTest.kt
The problem was introduced with #4410
Build fails with an error because of spaces in test names
```
e: file:///mnt/agent/work/8d547b974a7be21f/ktor-http/common/test/io/ktor/tests/http/MimesTest.kt:12:5 Name contains illegal chars that cannot appear in JavaScript identifier.
e: file:///mnt/agent/work/8d547b974a7be21f/ktor-http/common/test/io/ktor/tests/http/MimesTest.kt:21:5 Name contains illegal chars that cannot appear in JavaScript identifier.
e: file:///mnt/agent/work/8d547b974a7be21f/ktor-http/common/test/io/ktor/tests/http/MimesTest.kt:28:5 Name contains illegal chars that cannot appear in JavaScript identifier.
```
=> KTOR-7586 Fix MimesTest doesn't compile on JS target

ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/test/io/ktor/tests/http/RenderSetCookieTest.kt
**Subsystem**
Client, HttpCookies plugin
**Motivation**
[KTOR-7469](https://youtrack.jetbrains.com/issue/KTOR-7469)
**Solution**
The exception is thrown if a cookie with Raw encoding contains an invalid character such as:
```kotlin
isWhitespace() || this < ' ' || this in setOf(';', ',', '"')
```
Some servers send cookies to clients that contain these characters, however, the documentation does not support it. The solution is to remove this check because it doesn't break [Security Considerations](https://datatracker.ietf.org/doc/html/rfc6265#section-8)
=> KTOR-7469 Fix IllegalArgumentException in HttpCookies when server returns a raw cookie with not allowed characters

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/DigestAuthProvider.kt
**Subsystem**
Client Auth Plugin
**Motivation**
Fixes https://youtrack.jetbrains.com/issue/KTOR-7681
**Solution**
The "response" token was being generated with "nc" encoded as a decimal string, when in Ktor 3.0.1, it was changes to be an 8 digit hex string. Passing the properly encoded "nc" into the token fixes the breakage.
=> use encoded nonceCount to create response token

ktor-server/ktor-server-core/common/src/io/ktor/server/config/MergedApplicationConfig.kt, ktor-server/ktor-server-core/common/test/io/ktor/server/config/MergedApplicationConfigTest.kt
**Subsystem**
Server
**Motivation**
YouTrack issue link here - [KTOR-7008](https://youtrack.jetbrains.com/issue/KTOR-7008)
**Solution**
Instead of using the default "+" operator on the 2 source maps, deep merge them.
=> KTOR-7008 Fix toMap() to correctly handle nested values in MergedApplicationConfig

ktor-client/ktor-client-core/build.gradle.kts, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/jvm/test/HttpCacheTest.kt
**Subsystem**
Client
**Motivation**
[KTOR-7727](https://youtrack.jetbrains.com/issue/KTOR-7727) Backport fix for CVE-2024-49580 to Ktor 2
**Solution**
Cherry-pick solution from #4337 and #4368
=> KTOR-7727 Backport fix for CVE-2024-49580 to Ktor 2

ktor-http/jvm/src/io/ktor/http/content/MultipartJvm.kt, ktor-http/jvm/test/io/ktor/tests/http/content/MultipartJvmTest.kt
Fix [KTOR-7731](https://youtrack.jetbrains.com/issue/KTOR-7731) `FileItem.streamProvider` is deprecated and doesn't have implementation
=> KTOR-7731 Add implementation for the deprecated FileItem.streamProvider

ktor-http/api/ktor-http.api, ktor-http/api/ktor-http.klib.api, ktor-http/build.gradle.kts, ktor-http/common/src/io/ktor/http/Cookie.kt, ktor-http/common/src/io/ktor/http/URLProtocol.kt, ktor-http/common/src/io/ktor/http/Url.kt, ktor-http/jvm/test/io/ktor/tests/http/SerializableTest.kt, ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/JvmSerializable.kt, ktor-io/jsAndWasmShared/src/io/ktor/utils/io/JvmSerializable.jsAndWasmShared.kt, ktor-io/jvm/src/io/ktor/utils/io/JvmSerializable.jvm.kt, ktor-io/posix/src/io/ktor/utils/io/JvmSerializable.posix.kt, ktor-shared/ktor-junit/jvm/src/io/ktor/junit/Assertions.kt
In our project we had to define our own UrlSerializer. It would be much nicer to have this in the Ktor library itself, so it works out of the box (similar to how Cookie was recently extended).
Also, types like Url and Cookie should be java.io.Serializable. Otherwise Android crashes when using those types as e.g. screen arguments. This happens very quickly when Url is used indirectly as part of a data class where we wanted type safety.
=> KTOR-7620 Make Url class @Serializable and JVM Serializable

ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RouteSelector.kt, ktor-server/ktor-server-tests/common/test/io/ktor/tests/server/routing/RoutingProcessingTest.kt
**Subsystem**
Server, ktor-server-core
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-7278
**Solution**
fixed `Content-Type` header evaluation
=> KTOR-7278: fix accept header evaluation

buildSrc/src/main/kotlin/CI.kt
Fixes flaky failure on running kover tasks
=> Restore targetName value as other plugins might rely on it

ktor-server/ktor-server-cio/posix/src/io/ktor/server/cio/internal/CoroutineUtilsNix.kt, ktor-server/ktor-server-core/posix/src/io/ktor/server/engine/internal/ApplicationUtilsNix.kt, ktor-server/ktor-server-test-host/posix/src/io/ktor/server/testing/internal/CoroutineUtilsNix.kt
**Subsystem**
Server
**Motivation**
Fixes https://youtrack.jetbrains.com/issue/KTOR-7761/Use-Dispatchers.IO-for-native-in-server-IOBridge
=> KTOR-7761 Use Dispatchers.IO for IOBridge

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteChannel.kt, ktor-io/jvm/src/io/ktor/utils/io/ByteChannel.jvm.kt, ktor-io/posix/src/io/ktor/utils/io/ByteChannel.posix.kt, ktor-io/src/jsAndWasmSharedMain/kotlin/io/ktor/utils/io/ByteChannel.jsAndWasmShared.kt
Will help with the investigation of [KTOR-7729](https://youtrack.jetbrains.com/issue/KTOR-7729) Kotlinx-io `Check failed` from `ByteChannel`
=> KTOR-7729 Add logging for tracking concurrent access in the dev mode

ktor-server/ktor-server-cio/posix/src/io/ktor/server/cio/internal/CoroutineUtilsNix.kt, ktor-server/ktor-server-core/posix/src/io/ktor/server/engine/internal/ApplicationUtilsNix.kt, ktor-server/ktor-server-test-host/posix/src/io/ktor/server/testing/internal/CoroutineUtilsNix.kt
**Subsystem**
Server
**Motivation**
Fixes https://youtrack.jetbrains.com/issue/KTOR-7761/Use-Dispatchers.IO-for-native-in-server-IOBridge
**Original PR:** https://github.com/ktorio/ktor/pull/4478
=> KTOR-7761 Use Dispatchers.IO for IOBridge (cherry-pick to main branch)

gradle/libs.versions.toml, ktor-shared/ktor-serialization/ktor-serialization-jackson/build.gradle.kts, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/src/JacksonConverter.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ClientJacksonTest.kt, ktor-shared/ktor-serialization/ktor-serialization-jackson/jvm/test/ServerJacksonTest.kt
**Subsystem**
ContentNegociation: Server, Client: `JacksonConverter`.
**Motivation**
Allows usage of non-textual Smile JSON factory with Jackson, which is used for binary encoding of JSON.
Fixes https://youtrack.jetbrains.com/issue/KTOR-7726
**Solution**
When reading input, `JacksonConverter` creates a character stream, using the request `Charset` (default `UTF-8`). This approach is not compatible with the binary format, the [Smile encoding](https://github.com/FasterXML/smile-format-specification).
When attempting to read the binary encoded JSON structure with `JacksonConverter`, Jackson fails with an initialization error (or sometimes `JsonParseException`):
```Can not create parser for character-based (not byte-based) source
java.lang.UnsupportedOperationException: Can not create parser …
```
=> KTOR-7726 Support binary (Smile) encoding in JacksonConverter

ktor-client/ktor-client-cio/jvmAndPosix/src/io/ktor/client/engine/cio/Endpoint.kt
**Subsystem**
Client
**Motivation**
We encountered a lot of crashes after updating to the Ktor v3 with the root causes:
```Caused by: java.lang.IllegalStateException: The number of released permits cannot be greater than 100```
The problem is that we request 4 calls to the same endpoint asynchronously. However, InetSocketAddress(host, port) could have different results (IP address could change) - the current solution stores only the last address.
**Solution**
Store InetSocketAddress separately per connect request.
=> KTOR-7777 Release proper InetSocketAddress

ktor-io/common/src/io/ktor/utils/io/ByteChannel.kt, ktor-io/common/test/ByteReadChannelOperationsTest.kt
**Subsystem**
Core
**Motivation**
[KTOR-7746](https://youtrack.jetbrains.com/issue/KTOR-7746) ByteReadChannel.{readShort/readInt/readLong} leads to infinite loop when required bytes distributed in flush and read buffers
**Solution**
This fixes the condition where we have partial content in the read buffer and the flush buffer is never transferred because it is waiting for the condition of `_readBuffer.exhausted` in the accessor, and it is skipped in `awaitContent`.
Now, when flushBuffer + readBuffer size is greater than min, then `sleepWhile` will exit immediately without any synchronization then the flush will happen.
=> KTOR-7746 Fix infinite loop issue with eager buffer shifting

.editorconfig, .gitignore, .idea/externalDependencies.xml, CONTRIBUTING.md, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt, ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/RequestResponseBuilder.kt
**Subsystem**
Code Style
**Motivation**
We need wildcard imports to be used only for packages with DSLs, for third-party libraries it is better to use regular imports.
**Solution**
Use `ij_kotlin_packages_to_use_import_on_demand` option instead of `ij_kotlin_name_count_to_use_star_import` in `.editorconfig`.
=> Use "import on demand" only for Ktor modules

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/engine/EmbeddedServer.kt, ktor-server/ktor-server-core/jsAndWasmShared/src/io/ktor/server/engine/EmbeddedServer.jsAndWasmShared.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt, ktor-server/ktor-server-core/posix/src/io/ktor/server/engine/EmbeddedServerNix.kt, ktor-server/ktor-server-test-base/jsAndWasmShared/src/io/ktor/server/test/base/EngineTestBase.jsAndWasmShared.kt
**Subsystem**
Server
**Motivation**
* fixes https://youtrack.jetbrains.com/issue/KTOR-7459
* alternative to https://youtrack.jetbrains.com/issue/KTOR-2939
* prerequisite for https://github.com/ktorio/ktor/pull/4466
**Solution**
Only `startSuspend` and `stopSuspend` functions were added with minimal bridge for JVM and Native implementations.
That was done like this, because in most cases users will anyway call `start` and `stop`, and it's not clear, which engines could support `suspend` start/stop (e.g CIO can, for sure, but for others it's not that clear).
That's why minimally invasive changes were implemented to support wasm-js and js case, where `runBlocking` is not available.
PR also contains changes to `EngineTestBase` for js and wasm-js as this is the main consumer for those new …
=> KTOR-7359 Implement a suspending version of EmbeddedServer.start and EmbeddedServer.stop

.editorconfig, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/conventions.gradleDoctor.gradle.kts, gradle.properties, gradle/libs.versions.toml
**Subsystem**
Build Infrastructure
**Motivation**
It is hard to build the project on machines with less than 16 GB RAM because of high memory consumption.
We have problems on CI when Kotlin Daemon or Gradle Daemon are killed because of high memory pressure.
[KTOR-7825](https://youtrack.jetbrains.com/issue/KTOR-7825) Reduce Gradle memory consumption
**Solution**
- Decrease `Xmx` for Kotlin Daemon (including the one used by Gradle to compile `buildSrc`)
- Decrease `Xmx` for Gradle Daemon
- Add a workaround for Gradle Doctor - https://github.com/runningcode/gradle-doctor/issues/348
It would be great to specify `-XX:MaxMetaspaceSize` to prevent Gradle from being silently killed by OS due to unlimited metaspace consumption (see https://github.com/gradle/gradle/issues/19750) and make memory …
=> KTOR-7825 Decrease Gradle memory consumption

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/CloseHookByteWriteChannel.kt, ktor-utils/jvm/test/io/ktor/tests/utils/FileChannelTest.kt
**Subsystem**
Core, I/O
**Motivation**
[KTOR-7845](https://youtrack.jetbrains.com/issue/KTOR-7845) File is not commited after closing writeChannel() of the file
**Solution**
The problem here is that `flushAndClose()` doesn't wait for the `ReaderJob` to finish so it has no effect on the final destination of the data.  By adding a hook to wait for the job to complete, we can daisy chain these jobs with some trust that `flushAndClose()` will work properly from the perspective of the caller.
For reference, here is the `writeChannel` utility function:
```kotlin
@OptIn(DelicateCoroutinesApi::class)
public fun File.writeChannel(
coroutineContext: CoroutineContext = Dispatchers.IO
): ByteWriteChannel = GlobalScope.reader(CoroutineName("file-writer") + coroutineContext, autoFlush = true) { …
```
=> KTOR-7845 Fix for threading issue in flushAndClose for reader job channels

ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/utils.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlClientEngine.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/ResponseUtils.kt, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/src/ContentEncoding.kt, ktor-client/ktor-client-plugins/ktor-client-encoding/common/test/ContentEncodingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/DefaultTransformTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/MockedTests.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/PluginsTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CookiesIntegrationTests.kt
[KTOR-7828](https://youtrack.jetbrains.com/issue/KTOR-7828) CIO: Response body truncated because read amount of bytes isn't compared against Content-Length
=> KTOR-7828 Revert removed content-length check

ktor-server/ktor-server-test-base/jvm/src/io/ktor/server/test/base/HighLoadHttpGenerator.kt, ktor-utils/jvm/test/io/ktor/tests/utils/CacheTest.kt
Since 2.1.0-Beta1 Atomic types are introduced in `kotlin.concurrent` package, `AtomicLong` and `AtomicBoolean` types have the same names in both `kotlin.concurrent` and `java.util.concurrent.atomic` packages, which causes resolution ambiguity in case when both packages are star imported.
=> Removed star imports of java.util.concurrent.atomic.* package.

build.gradle.kts, buildSrc/src/main/kotlin/JvmConfig.kt, buildSrc/src/main/kotlin/KtorBuildProperties.kt, gradle-settings-conventions/src/main/kotlin/conventions-dependency-resolution-management.settings.gradle.kts, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/CIORequestTest.kt, ktor-client/ktor-client-cio/jvm/test/io/ktor/client/engine/cio/ConnectErrorsTest.kt, ktor-client/ktor-client-tests/build.gradle.kts, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/ClientLoaderJvm.kt, ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/TestWithKtor.kt, ktor-network/jvm/test/io/ktor/network/sockets/tests/ClientSocketTest.kt, ktor-network/jvm/test/io/ktor/network/sockets/tests/ServerSocketTest.kt, ktor-network/ktor-network-tls/build.gradle.kts, ktor-network/ktor-network-tls/jvm/test/io/ktor/network/tls/ConnectionTest.kt, ktor-server/ktor-server-cio/build.gradle.kts, ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/ServerPipelineTest.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-plugins/ktor-server-i18n/jvm/test/io/ktor/tests/i18n/TranslationTest.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-websockets/jvm/test/io/ktor/tests/websocket/WebSocketTest.kt, ktor-server/ktor-server-test-base/build.gradle.kts, ktor-server/ktor-server-test-base/jvm/src/io/ktor/server/test/base/BaseTestJvm.kt, ktor-server/ktor-server-test-suites/build.gradle.kts, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/ClientCertTestSuite.kt, ktor-shared/ktor-junit/build.gradle.kts, ktor-shared/ktor-junit/jvm/src/io/ktor/junit/coroutines/CoroutinesTimeoutExtension.kt, ktor-utils/jvm/src/io/ktor/util/NioPath.kt, ktor-utils/jvm/src/io/ktor/util/reflect/ServiceLoader.kt, ktor-utils/jvm/test/io/ktor/tests/utils/DeflaterReadChannelTest.kt
**Subsystem**
Test Infrastructure
**Motivation**
[KTOR-7846](https://youtrack.jetbrains.com/issue/KTOR-7846) Fix running tests against Java 8 on CI
**Solution**
Fix problems making tests incompatible with Java 8 and remove `testJdk.coerceAtLeast(11)` from tests toolchain configuration.
_It is better to review commit-by-commit_
=> KTOR-7846 Fix running tests against JDK 8

ktor-server/ktor-server-core/common/src/io/ktor/server/engine/EngineContextCancellationHelper.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/JettyApplicationEngineBase.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-test-host/common/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-test-host/common/src/io/ktor/server/testing/TestApplicationEngine.kt, ktor-server/ktor-server-test-host/common/test/TestApplicationTest.kt, ktor-server/ktor-server-tomcat-jakarta/jvm/src/io/ktor/server/tomcat/jakarta/TomcatApplicationEngine.kt, ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt
**Subsystem**
Test Infrastructure
**Motivation**
[KTOR-7682 TestApplication.stop() doesn't stop the application anymore](https://youtrack.jetbrains.com/issue/KTOR-7682)
**Solution**
The problem occurs because `TestApplication.client` uses an instance of an application different from the returned by `TestApplication` constructor-like function and calls `start()` on it. `TestApplication.start()` calls `TestApplicationEngine.start()` under the hood which rewrites `cancellationJob`, so coroutine waiting for cancellation never ends.
To fix this problem:
- make `TestApplication` return `application` from builder – the same as used in a client
- remove builder from `TestApplication` constructor to make builder the only way to get `TestApplication` and break circular dependency: `TestApplication` …
=> KTOR-7682 Fix TestApplication.stop() doesn't stop the application anymore

ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/core/Buffers.kt, ktor-io/jvm/test/ByteReadChannelOperationsJvmTest.kt
**Subsystem**
Core, I/O
**Motivation**
[KTOR-7941](https://youtrack.jetbrains.com/issue/KTOR-7941) A Performance issue reading with ByteReadChannel.readUTF8LineTo request body
**Solution**
When reading input that is missing either CR or LF characters, the current implementation will read the full buffer for every line, which leads to a `O(n^2)` performance, which is very bad for this kind of operation when there are many newlines with only `\n` for example.
=> KTOR-7941 Fix performance on readUtfLineTo

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/internal/ByteChannelReplay.kt, ktor-client/ktor-client-core/common/test/ByteChannelReplayTest.kt
**Subsystem**
Client, SaveBody
**Motivation**
[KTOR-7952](https://youtrack.jetbrains.com/issue/KTOR-7952) SaveBodyPlugin: UninitializedPropertyAccessException when reading response body within receivePipeline
**Solution**
Using a lazy delegate instead of a lateinit variable will make it so it will always get initialized - either from `copyTask.start()` or from `awaitImpatiently()`.
=> KTOR-7952 Fix for uninitialized writerJob property

ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOEngineTestJvm.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt
**Subsystem**
Server
**Motivation**
[KTOR-7963](https://youtrack.jetbrains.com/issue/KTOR-7963) Uncaught ClosedWatchServiceException exception thrown by finalizer when closing the server
**Solution**
Catch exceptions from polling.  I was unable to reproduce this reliably in a unit test, it seems to be pretty random with timing.
=> KTOR-7963 Handle ClosedWatchServiceException

ktor-client/ktor-client-tests/common/src/io/ktor/client/tests/utils/ClientLoader.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentEncodingIntegrationTest.kt
**Subsystem**
Test Infrastructure
**Motivation**
This test is always failing on non-JVM targets as `GZipEncoder` is implemented only on JVM.
**Solution**
Make `clientTests(only(...))` use `EnginePattern` and specify pattern `jvm:*` for this test.
Alternatively, we could move this test into the JVM source-set, but I decided to keep it here since it doesn't use any JVM-specific API.
=> Disable testGzipWithContentLengthWithoutPlugin for non-JVM clients

ktor-client/ktor-client-curl/gradle.properties
**Subsystem**
ktor-client-curl
**Motivation**
During curl static setup there was an issue with K/N caches (https://github.com/ktorio/ktor/pull/4445#issuecomment-2462084904) for linuxX64 target, but with Kotlin 2.1.0 and LLVM 16 (instead of 11 previously) it should work fine. 
**Solution**
drop flag, To be tested by linux CI agent, as the issue reproduces only on linux machine
=> Enable linuxX64 caches back after update to Kotlin 2.1.0 with llvm 16

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt
**Subsystem**
server, metrics-micrometer
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-7658
**Solution**
Excluded metrics for unknown http methods
=> KTOR-7658: do not write unknown HTTP method names to metrics

ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt
**Subsystem**
Server - Plugin Micrometer
**Motivation**
Lots of standard dashboards include the JVM process uptime / start time. The default Ktor Micrometer Plugin doesn't include this metric, causing panels referencing it to be empty.
**Solution**
Add the incredibly simple [UptimeMetrics](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/UptimeMetrics.java) MeterBinder. It adds the `process.uptime` and `process.start.time` metrics.
=> KTOR-8061 MicrometerMetricsConfig add UptimeMetrics to standard meterBinders

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/CloseToken.kt, ktor-io/common/src/io/ktor/utils/io/SinkByteWriteChannel.kt, ktor-io/common/test/ByteChannelTest.kt, ktor-io/common/test/ByteReadChannelOperationsTest.kt, ktor-io/common/test/CoroutinesTest.kt, ktor-io/common/test/ReadUtf8LineTest.kt, ktor-io/common/test/SinkByteWriteChannelTest.kt, ktor-io/common/test/WriterReaderTest.kt, ktor-io/jvm/src/io/ktor/utils/io/charsets/CharsetJVM.kt, ktor-io/jvm/src/io/ktor/utils/io/streams/Streams.kt, ktor-io/jvmAndPosix/src/io/ktor/utils/io/ByteReadChannelSource.kt, ktor-io/jvmAndPosix/src/io/ktor/utils/io/ByteWriteChannelSink.kt, ktor-io/jvmAndPosix/test/ByteReadChannelSourceTest.kt, ktor-io/jvmAndPosix/test/ByteWriteChannelSinkTest.kt
Fix [KTOR-7327](https://youtrack.jetbrains.com/issue/KTOR-7327) Support conversion between byte channel interfaces and kotlinx-io primitives
=> KTOR-7327 Support conversion between byte channel interfaces and kotlinx-io primitives

ktor-server/ktor-server-plugins/ktor-server-double-receive/common/src/io/ktor/server/plugins/doublereceive/ByteArrayCache.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/http/ApplicationRequestContentTestJvm.kt
**Subsystem**
Server, DoubleReceive
**Motivation**
[KTOR-8045](https://youtrack.jetbrains.com/issue/KTOR-8045) DoubleReceive: NullPointerException caused by race condition
**Solution**
Moving the body's discard call outside the coroutine avoids the race condition when dispose is called twice.
=> KTOR-8045 Fix for NPE race condition in dispose

ktor-client/ktor-client-plugins/ktor-client-logging/api/ktor-client-logging.api, ktor-client/ktor-client-plugins/ktor-client-logging/api/ktor-client-logging.klib.api, ktor-client/ktor-client-plugins/ktor-client-logging/build.gradle.kts, ktor-client/ktor-client-plugins/ktor-client-logging/common/src/io/ktor/client/plugins/logging/Logging.kt, ktor-client/ktor-client-plugins/ktor-client-logging/jvm/test/io/ktor/client/plugins/logging/NewFormatTest.kt, ktor-client/ktor-client-plugins/ktor-client-logging/jvm/test/io/ktor/client/plugins/logging/OkHttpFormatTest.kt
https://youtrack.jetbrains.com/issue/KTOR-7806
=> KTOR-7806 Add logging with standard Okhttp-like format

ktor-server/ktor-server-plugins/ktor-server-swagger/api/ktor-server-swagger.api, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/Swagger.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/src/io/ktor/server/plugins/swagger/SwaggerConfig.kt, ktor-server/ktor-server-plugins/ktor-server-swagger/jvm/test/io/ktor/server/plugins/swagger/SwaggerTest.kt
**Subsystem**
Ktor server plugin
**Motivation**
Customer asked at work if we could provide deeplinks to the Swagger documentation. Found that it was a setting in Javascriptt (https://swagger.io/docs/open-source-tools/swagger-ui/usage/deep-linking/) that was not exposed by the plugin.
**Solution**
Add a boolean variable to SwaggerConfig to enable deep linking. It defaults to false (which is also the default for SwaggerUI).
=> KTOR-8074 Add deepLinking configuration variable to Swagger plugin (reopen from main)

build.gradle.kts, buildSrc/src/main/kotlin/JvmConfig.kt, gradle/libs.versions.toml, ktor-server/build.gradle.kts, ktor-server/ktor-server-cio/build.gradle.kts, ktor-server/ktor-server-core/build.gradle.kts, ktor-server/ktor-server-jetty-jakarta/build.gradle.kts, ktor-server/ktor-server-jetty-jakarta/ktor-server-jetty-test-http2-jakarta/build.gradle.kts, ktor-server/ktor-server-jetty/build.gradle.kts, ktor-server/ktor-server-jetty/ktor-server-jetty-test-http2/build.gradle.kts, ktor-server/ktor-server-netty/build.gradle.kts, ktor-server/ktor-server-plugins/build.gradle.kts, ktor-server/ktor-server-servlet-jakarta/build.gradle.kts, ktor-server/ktor-server-servlet/build.gradle.kts, ktor-server/ktor-server-test-base/build.gradle.kts, ktor-server/ktor-server-test-base/jvm/resources/logback-test.xml, ktor-server/ktor-server-test-host/build.gradle.kts, ktor-server/ktor-server-test-suites/build.gradle.kts, ktor-server/ktor-server-tests/build.gradle.kts, ktor-server/ktor-server-tomcat-jakarta/build.gradle.kts, ktor-server/ktor-server-tomcat/build.gradle.kts
**Subsystem**
Infrastructure
**Motivation**
Cleanup before moving JVM target configs to the `build-logic` in [KTOR-7743](https://youtrack.jetbrains.com/issue/KTOR-7743).
**Solution**
- Remove jetty-apln-boot as it is not necessary anymore
- Move test logback config to `ktor-server-test-base` and remove `testOutput` configuration
=> KTOR-7743 Remove redundant configurations for JVM target

buildSrc/src/main/kotlin/TargetsConfig.kt
**Subsystem**
Infrastructure
**Motivation**
[KTOR-8091](https://youtrack.jetbrains.com/issue/KTOR-8091) ktor-client-curl artifacts aren’t published after EAP 1146
**Solution**
Aggregating tasks relay on the flags declared in `TargetsConfig`. Unfortunately, these flags were out of sync a bit (#4616 should fix this problem) and this caused `ktor-client-curl` not to be published.
```kotlin
private fun Project.configureAggregatingTasks() {
// ...
// These three were false if only "desktop" source-set is present.
if (hasLinux) registerAggregatingTask("Linux", linuxTargets)
if (hasWindows) registerAggregatingTask("Windows", windowsTargets)
if (hasDarwin) registerAggregatingTask("Darwin", darwinTargets)
// ...
}
```
=> KTOR-8091 Fix ktor-client-curl publishing

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt
**Subsystem**
Client, HttpRequestRetry
**Motivation**
[KTOR-8051](https://youtrack.jetbrains.com/issue/KTOR-8051) HttpRequestRetry: race condition for isClosedForRead leads to EOFException: Channel is already closed
**Solution**
This was actually caused by some unnecessary checks in byte read operations.  When the read buffer is closed, then it should fail through the normal path, throwing a `ClosedReadChannelException`.
=> KTOR-8051 Fix EOFException on retry body check

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/request/ApplicationReceiveFunctions.kt, ktor-server/ktor-server-core/jsAndWasmShared/src/io/ktor/server/request/ApplicationReceiveFunctions.jsAndWasmShared.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/request/ApplicationReceiveFunctionsJvm.kt, ktor-server/ktor-server-core/posix/src/io/ktor/server/request/ApplicationReceiveFunctions.posix.kt
Fix [KTOR-8082](https://youtrack.jetbrains.com/issue/KTOR-8082) Read mutipart upload regression from 2.x to 3.x
=> KTOR-8082 Add formFieldLimit system property

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/WasmJsClientEngine.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/compatibility/Utils.kt
**Subsystem**
Client (JS, WasmJS)
**Motivation**
[KTOR-7734](https://youtrack.jetbrains.com/issue/KTOR-7734) "AbortError: BodyStreamBuffer was aborted" error when canceling parent job
**Solution**
The problem was caused by calling `controller.abort()` after request fetching was already completed (together with its coroutine). It resulted in propagation of this exception to the global level without any possibility to catch it.
Unfortunately, I didn't manage to write a test for this case.
=> KTOR-7734 Do not abort fetch after its completion

ktor-http/common/src/io/ktor/http/URLParser.kt, ktor-http/common/test/io/ktor/tests/http/UrlTest.kt
**Subsystem**
Core, ktor-http
**Motivation**
Resolves [KTOR-6709](https://youtrack.jetbrains.com/issue/KTOR-6709) Fail to parse url: file:/path/to/file.txt. URLParser does not support file urls with a single leading `/`.
**Solution**
Add when clause to `URLBuilder.parseFilefor` extension function to match a single leading slash. 
It sets the host to empty string and the rest of the url as encodedPath.
Does **not** modify how URLBuilders `toString()` is implemented. Leading to `Url("file:/var/www").toString()` returning `"file:///var/www"`.
=> KTOR-6709 Fix URLParserException on minimal file url

ktor-network/jvm/src/io/ktor/network/sockets/NIOSocketImpl.kt, ktor-network/jvm/test/io/ktor/network/sockets/tests/ServerSocketTest.kt
**Subsystem**
Client, CIO
**Motivation**
Should solve all of our concurrency woes:
- [KTOR-8105](https://youtrack.jetbrains.com/issue/KTOR-8105) Race condition when writing to a buffer leads to NPE inside CIOReaderKt.readFrom
- [KTOR-8086](https://youtrack.jetbrains.com/issue/KTOR-8086) NPE in readBuffer
- [KTOR-8096](https://youtrack.jetbrains.com/issue/KTOR-8096) ArrayIndexOutOfBounds kotlinx-io
**Solution**
I found that the NIOSocketImpl is flushing the same channel as the TLS encoder coroutine, which can potentially lead to corruption due to the encoder writing the "close" message, then performing its own flushAndClose.
The stack traces in question:
```
[1318671573] write @ call-context#1025
io.ktor.utils.io.ByteChannel.flush(ByteChannel.kt:91) …
```
=> KTOR-8105 Fix concurrent flush attempts corrupting segment pool

ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt
**Subsystem**
Core, I/O
**Motivation**
Reverts the change in https://github.com/ktorio/ktor/pull/4619 that removes these exceptions.  My original assumption is that the closed channel exception would make more sense to throw since it's consistent with the rest of the library and contains some more context, but I found some websocket client code that relies on this behaviour, so it'd be best to keep this as is.
**Solution**
Rolled back this change, but with an extra check to ensure readFully with empty bounds is a no-op.
=> KTOR-8051 Revert EOFException change

ktor-network/nix/src/io/ktor/network/selector/SelectUtilsNix.kt, ktor-network/windows/src/io/ktor/network/selector/SelectUtilsWindows.kt
[KTOR-7299](https://youtrack.jetbrains.com/issue/KTOR-7299) IOException: Fail to select descriptor for ACCEPT
Unfortunately it does not resolve my specific issue, but I noticed this race condition when investigating the issue. 
I cannot consistently reproduce this in a test so I did not add it, but I was able to reproduce it sometimes throwing `kotlinx.io.IOException: Bad descriptor 5 for ACCEPT`. This means the descriptor was closed multiple times, which should never happen. With the changes in this PR (and after #4637 is merged which I discovered due to this issue) it will throw `kotlinx.io.IOException: Selectable closed` instead. This is in line with JVM which throws ClosedChannelException (so IOException).
Explanation of race condition before this PR:
1. Closing selectormanager closes …
=> KTOR-7299 Fix close race condition causing descriptor to be closed while select is still busy

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/browser/BrowserFetch.kt, ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/browser/BrowserFetch.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/compatibility/Utils.kt
**Subsystem**
Client (JS/WasmJS)
**Motivation**
[KTOR-7734](https://youtrack.jetbrains.com/issue/KTOR-7734) "AbortError: BodyStreamBuffer was aborted" error when canceling parent job
**Solution**
Solution in #4629 wasn’t correct.
The actual root cause of the issue was an uncaught exception thrown inside a `Promise` returned by `reader.cancel()`. Added catching for this exception and reformatted code a bit.
It's better to review these two commits separately.
=> KTOR-7734 JS: Catch error on channel reader closure

build-logic/src/main/kotlin/ktorbuild/internal/Version.kt, renovate.json
**Subsystem**
Renovate
**Motivation**
Renovate stopped creating PRs with Ktor EAP updates.
**Solution**
Manually specify registries for Ktor.
Also fix a versioning issue when Ktor is built locally.
=> Renovate: Fix Ktor EAP updates

ktor-network/api/ktor-network.api, ktor-network/api/ktor-network.klib.api, ktor-network/common/src/io/ktor/network/sockets/SocketAddress.kt, ktor-network/common/src/io/ktor/network/sockets/Sockets.kt, ktor-network/common/test/io/ktor/network/sockets/tests/TCPSocketTest.kt
[KTOR-8136](https://youtrack.jetbrains.com/issue/KTOR-8136) Introduce ServerSocket.port to simplify port access for the bound server
=> KTOR-8136 Introduce ServerSocket.port to simplify port access for the bound server

ktor-network/common/test/io/ktor/network/sockets/tests/TCPSocketTest.kt, ktor-network/jsAndWasmShared/src/io/ktor/network/sockets/ServerSocketContext.kt, ktor-network/nix/src/io/ktor/network/selector/SelectUtilsNix.kt, ktor-network/windows/src/io/ktor/network/selector/SelectUtilsWindows.kt
[KTOR-8135](https://youtrack.jetbrains.com/issue/KTOR-8135) Socket accept not throwing error on socket close on native
Test failed before on native macosArm64 but was successful on JVM, so native specific bug
=> KTOR-8135 Socket accept not throwing error on socket close on native

ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt
**Subsystem**
Core, I/O
**Motivation**
[KTOR-8133](https://youtrack.jetbrains.com/issue/KTOR-8133) Audit Ktor codebase for potential byte channel race conditions
**Solution**
This extra close can lead to two concurrent writes.  Normally, the consumer closes the channel, which finishes this job.
Note: This is the last sketchy looking spot I've found in the core code.  I'll keep combing through the rest of the project, but with a lower priority.
=> KTOR-8133 Fix concurrent flush and close

ktor-io/common/src/io/ktor/utils/io/ByteWriteChannelOperations.kt, ktor-io/common/test/ByteWriteChannelOperationsTest.kt, ktor-io/jvm/test/ByteWriteChannelOperationsTest.kt, ktor-server/ktor-server-jetty-jakarta/jvm/test/io/ktor/tests/server/jetty/jakarta/JettyIdleTimeoutTest.kt, ktor-server/ktor-server-jetty/jvm/test/io/ktor/tests/server/jetty/JettyIdleTimeoutTest.kt
**Subsystem**
Core, I/O
**Motivation**
[KTOR-6185](https://youtrack.jetbrains.com/issue/KTOR-6185) OutOfMemoryError when sending a large binary file through ByteReadChannel converted from InputStream
**Solution**
The problem was caused by directory transferring the entire contents of a `RawSource` to the `ByteChannel`'s `writeBuffer`, causing the application to run out of memory.  To avoid this, we instead transfer up to our maximum flush buffer size then suspend until we have room to write more.
=> KTOR-6185 Fix for OutOfMemoryError when uploading large files

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/engine/js/WasmJsClientEngine.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
**Subsystem**
Client (WasmJS)
**Motivation**
[KTOR-8163](https://youtrack.jetbrains.com/issue/KTOR-8163) WasmJS WebSocket client sometimes drops a frame received immediately after handshake
**Solution**
Cherry-pick fix made for JS engine: #4012
=> KTOR-8163 WasmJS: Add callbacks before awaiting connection

ktor-client/ktor-client-darwin/build.gradle.kts, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/DarwinUtils.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/KtorNSURLSessionDelegate.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/certificates/CertificatePinner.kt, ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/internal/DarwinTaskHandler.kt, ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt, ktor-client/ktor-client-test-base/common/src/io/ktor/client/test/base/CommonClientTestUtils.kt, ktor-network/ktor-network-tls/api/ktor-network-tls.api, ktor-network/ktor-network-tls/api/ktor-network-tls.klib.api, ktor-network/ktor-network-tls/common/src/io/ktor/network/tls/CipherSuites.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/CipherSuitesJvm.kt, ktor-network/ktor-network-tls/nonJvm/src/io/ktor/network/tls/CipherSuites.nonJvm.kt
**Subsystem**
Client, Darwin
**Motivation**
[KTOR-6759](https://youtrack.jetbrains.com/issue/KTOR-6759) Darwin: Ambiguous DarwinHttpRequestException for SSL Pinning failure
The problem is that we call `completionHandler` with `NSURLSessionAuthChallengePerformDefaultHandling` on SSL pinning failure and then third-party API throws an exception. There are no mechanisms to attach additional data to this exception (or at least I don't know any).
The place where the actual error occurs and the place where `DarwinHttpRequestException` is constructed are two completely different places.
**Solution**
Save actual failure thrown during challenge handling to a`DarwinTaskHandler` and throw it later instead of creating a generic one. Throw specific exception from `CertificatePinner` to make it possible …
=> KTOR-6759 Darwin: Throw specific exception for SSL Pinning failure

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/contentnegotiation/JsonContentTypeMatcher.kt, ktor-client/ktor-client-plugins/ktor-client-json/common/src/io/ktor/client/plugins/json/JsonContentTypeMatcher.kt, ktor-http/api/ktor-http.api, ktor-http/api/ktor-http.klib.api, ktor-http/common/src/io/ktor/http/ContentTypes.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/Multipart.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/request/ApplicationRequestProperties.kt, ktor-server/ktor-server-jetty-jakarta/jvm/src/io/ktor/server/jetty/jakarta/JettyKtorHandler.kt, ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyKtorHandler.kt
**Subsystem**
Core
**Motivation**
[KTOR-8145](https://youtrack.jetbrains.com/issue/KTOR-8145) Add operator contains to ContentType objects
Add a simple way to check if a content type has one of the well-known types. This check should be case-insensitive, that is why it is error-prone to check content type using `contentType.startsWith(...)`
**Solution**
Add an operator `contains` to ContentType objects checking that the content type prefix is equal to the expected type name ignoring its casing.
=> KTOR-8145 Add contains operator to ContentType objects

ktor-io/jvm/src/io/ktor/utils/io/ByteReadChannelOperations.jvm.kt, ktor-io/jvm/test/ByteReadChannelOperationsJvmTest.kt
**Subsystem**
Core, I/O
**Motivation**
[KTOR-8172](https://youtrack.jetbrains.com/issue/KTOR-8172) ByteChannel read issue on min > 1
I found this problem when looking through the code for potential infinite loops.  There were no references to the function where min > 1 so it's not causing problems internally, but it's part of our public API so it seems important to fix.
**Solution**
When the min is supplied, we ought to use this as an argument for the `awaitContent()` function and throw EOF accordingly when said content is unavailable.
=> KTOR-8172 Fix issue in JVM byte channel read function

ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/src/io/ktor/server/plugins/calllogging/CallLogging.kt, ktor-server/ktor-server-plugins/ktor-server-call-logging/jvm/test/io/ktor/server/plugins/calllogging/CallLoggingTest.kt
**Subsystem**
Server (CallLogging plugin) 
**Motivation**
UX improvement, as lifecyclke logs are already present even without this plugin
=> KTOR-7797 Remove application lifecycle logs from CallLogging plugin

ktor-client/ktor-client-plugins/ktor-client-auth/api/ktor-client-auth.api, ktor-client/ktor-client-plugins/ktor-client-auth/api/ktor-client-auth.klib.api, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BasicAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BearerAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/DigestAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/BasicProviderTest.kt
**Subsystem**
Client, Basic Auth
**Motivation**
[KTOR-7775](https://youtrack.jetbrains.com/issue/KTOR-7775) Auth: BasicAuthProvider caches credentials until process death
**Solution**
Add `BasicAuthProvider.clearToken` similarly to `BearerAuthProvider`. So now the token can be cleared the following way:
```kotlin
import io.ktor.client.plugins.auth.authProvider
client.authProvider<BasicAuthProvider>()?.clearToken()
```
Probably, we should come up with a common solution for clearing authorization tokens, but unlikely in 3.1.0.
=> KTOR-7775 BasicAuth: Add clearToken method

ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsClientEngine.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentEncodingIntegrationTest.kt
**Subsystem**
Client, Browser / JS
**Motivation**
[KTOR-7934](https://youtrack.jetbrains.com/issue/KTOR-7934) JS/WASM fails with "IllegalStateException: Content-Length mismatch" on requesting gzipped content
**Solution**
Update the JS compile target as well.  I had only updated wasmJs last time.
=> KTOR-7934 Apply fix for Js target

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/UnlimitedCacheStorage.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/cache/storage/FileCacheStorage.kt, ktor-client/ktor-client-core/jvm/test/CachingCacheStorageTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/Cache.kt
**Subsystem**
Client, Cache
**Motivation**
[KTOR-7104](https://youtrack.jetbrains.com/issue/KTOR-7104)
In the issue it's said:
> Cache isn't updated when Vary header for 304 response matches but is not equal to Vary for 200 response (however, it's answering with cached response)
But actually, it shouldn't update the cache as well as it shouldn't respond with cached data because in documentation we can find the next:
> The same Vary header value should be used on all responses for a given URL, including [304](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) Not Modified responses and the "default" response.
=> KTOR-7104 Fix saving caches with different vary header

ktor-network/common/src/io/ktor/network/sockets/SocketBase.kt
The actualClose call could be called twice due to race condition when closing. Seems highly unlikely, but this could cause a descriptor to be closed twice, causing errors.
This piece of code was moved from JVM, where a double actualClose call would not have caused an issue (because closing jvm channel twice is ok), but on Native closing a descriptor twice is a serious issue.
Was able to reproduce this issue by adding `runBlocking { delay(1000) }` on line 85 just before `checkChannels()` call
=> Fix double actualClose call

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/utils.kt, ktor-network/common/src/io/ktor/network/sockets/SocketBase.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSClientHandshake.kt, ktor-network/ktor-network-tls/jvm/src/io/ktor/network/tls/TLSClientSessionJvm.kt
**Subsystem**
Client, CIO
**Motivation**
Once again fixing these issues:
- [KTOR-8105](https://youtrack.jetbrains.com/issue/KTOR-8105) Race condition when writing to a buffer leads to NPE inside CIOReaderKt.readFrom
- [KTOR-8086](https://youtrack.jetbrains.com/issue/KTOR-8086) NPE in readBuffer
- [KTOR-8096](https://youtrack.jetbrains.com/issue/KTOR-8096) ArrayIndexOutOfBounds kotlinx-io
**Solution**
Previously, I removed a redundant close from the base socket implementation, but it would seem there is some other parts of the code base that rely on this behaviour.  So, I instead defer the close call to after the encoder job is finished closing.  Bonus fix: I noticed we're not encrypting our close records after the handshake is complete.  This is incorrect behaviour, so I fixed that as …
=> KTOR-8105 Fix for concurrent flush attempts breaking CIO client (again)

ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/ChunkedTest.kt, ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteChannel.kt, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-io/common/src/io/ktor/utils/io/CloseToken.kt, ktor-io/common/src/io/ktor/utils/io/LineEndingMode.kt, ktor-io/common/src/io/ktor/utils/io/SinkByteWriteChannel.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
Server (CIO)
**Motivation**
[KTOR-8015](https://youtrack.jetbrains.com/issue/KTOR-8015) Server accepts \r without a following \n as a valid line terminator in chunked transfer encoding
**Solution**
Add a parameter `lineEnding` to `readUTF8Line` to make it possible to ensure that a proper line ending is used.
=> KTOR-8015 CIO: Do not accept CR as line delimiter in requests

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteReadChannelOperations.kt, ktor-network/common/src/io/ktor/network/sockets/SocketBase.kt
**Subsystem**
Core, I/O
**Motivation**
[KTOR-8201](https://youtrack.jetbrains.com/issue/KTOR-8201) Fix socket channel close handling
**Solution**
This introduces a suspending close for reader jobs, which will cancel the nested job, wait for it to join, then perform the flush and close.  This should prevent two coroutines from writing / flushing simultaneously.
=> KTOR-8201 Add safe close for readerJob

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpTimeout.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
**Subsystem**
Client
**Motivation**
[KTOR-8206](https://youtrack.jetbrains.com/issue/KTOR-8206) WebSocket and SSE don't respect connection timeout set in the HttpTimeout plugin
**Solution**
Previously all timeout settings were ignored for WS and SSE requests. I've changed this behavior to ignore only request timeout.
=> KTOR-8206 Apply socket and connect timeouts to WS and SSE

ktor-network/nix/src/io/ktor/network/selector/SelectUtilsNix.kt, ktor-network/nix/src/io/ktor/network/selector/SignalPoint.kt, ktor-network/posix/src/io/ktor/network/util/NativeUtils.kt, ktor-network/windows/src/io/ktor/network/selector/SelectUtilsWindows.kt
**Subsystem**
ktor-network
**Motivation**
Received a crash on iOS:
```
Non-fatal Exception: InvalidArgumentException: EINVAL (22): Invalid argument
0  RemoteGamepad                  0x75237c kfun:io.ktor.utils.io.errors.PosixException.Companion#forErrno(kotlin.Int;kotlin.String?){}io.ktor.utils.io.errors.PosixException + 30 (Throwable.kt:30)
1  RemoteGamepad                  0x15564a0 kfun:io.ktor.network.selector.SelectorHelper.selectionLoop#internal + 163 (SocketUtils.kt:163)
2  RemoteGamepad                  0x1558a84 kfun:io.ktor.network.selector.SelectorHelper.SelectorHelper$start$2.invoke#internal + 53 (SelectUtilsNix.kt:53)
3  RemoteGamepad                  0x328494 kfun:kotlin.coroutines.intrinsics.createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$2.invokeSus …
```
=> Remove unnecessary maxDescriptor + 1; Improve posix call debug information in SelectorManager

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/DefaultClientSSESession.kt, ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpSSESession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/ServerSentEvents.kt
Fixed an issue where canceling the incoming flow of OkHttpSSESession failed to disconnect the SSE session.
**Subsystem**
Client
ktor-client/ktor-client-okhttp
**Motivation**
Refer to a bug/ticket #4692.
In the OkHttpSSESession implementation of SSESession, cancel incoming flow will NOT trigger serverSentEventsSource.cancel(), which will keep SSE still connecting !
**Solution**
- First, ```val incoming: Flow<ServerSentEvent>``` in  OkHttpSSESession should always return the same Flow instance, just as DefaultClientSSESession did.
- Second, cancel ```_incoming.receiveAsFlow()``` will just cancel the Flow but will **NOT** cancel the _incoming Channel, so we should use ```_incoming.consumeAsFlow()``` instead.
- Third, if ```incoming.trySendBlocking(ServerSentEvent(data, type, id))``` fails …
=> Fixed an issue where canceling the incoming flow of OkHttpSSESession/DefaultClientSSESession failed to disconnect the SSE session.

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/websocket/WebSockets.kt, ktor-server/ktor-server-plugins/ktor-server-websockets/common/src/io/ktor/server/websocket/WebSocketUpgrade.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/WebSocketExtensionHeader.kt
According to RFC 6455 protocols are delimited by comma and arguments by semicolon, not the other way around
https://datatracker.ietf.org/doc/html/rfc6455#page-48
**Subsystem**
Client/Server, Websocket extension
**Motivation**
Fixes a bug KTOR-6384
**Solution**
Just swap the delimeters for protocols and their arguments.
=> KTOR-6384 Fix Websocket Extension negotiation -

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingNode.kt, ktor-server/ktor-server-core/common/test/io/ktor/server/routing/RouteTest.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/api/ktor-server-metrics-micrometer.api, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/src/io/ktor/server/metrics/micrometer/MicrometerMetrics.kt, ktor-server/ktor-server-plugins/ktor-server-metrics-micrometer/jvm/test/io/ktor/server/metrics/micrometer/MicrometerMetricsTests.kt
**Subsystem**
Server, server-core & metrics-micrometer
**Motivation**
[KTOR-8183](https://youtrack.jetbrains.com/issue/KTOR-8183) Add a simplified route string
**Solution**
Add `path` extension property to RoutingNode. It returns a String representation of the path matched by the route. RoutingNodes not related to the path, i.e. from the authorization plugin or the http method are ommited here.
Make the route label string of micrometer metrics configurable with the `transformRoute` function in `MicrometerMetricsConfig` and use `RoutingNode.path` as default.
This fixes the issue of unwanted path elements, like `/(authenticate "default")/uri`, in the metrics route label.
The original behaviour can be configured by setting
```kotlin
transformRoute { 
parent.toString() 
}
```
in the …
=> KTOR-8183 Add a simplified route string

.editorconfig, .github/workflows/auto-approve.yml, renovate.json
**Subsystem**
Infrastructure
**Motivation**
1. Make it possible to merge PRs without review (for "Ship" PRs from [Ship/Show/Ask](https://martinfowler.com/articles/ship-show-ask.html))
2. Merge renovate PRs automatically when possible
**Solution**
Automatically approve PRs from Renovate or having label "ship!".
Enable automerge for non-major updates and for test/infrastucture dependencies.
(Added tag "ship" to this PR as a demo)
=> Auto-approve and auto-merge renovate PRs

.github/workflows/auto-approve.yml
**Subsystem**
Infrastructure
**Motivation**
The bot approves PRs too zealous:
**Solution**
- Auto-approve PR only if it's current review decision is "REQUIRES_REVIEW".
- Trigger the workflow only on event `labeled` as it is also triggered when PR with label was created.
- Remove "Enable auto-merge" step as it doesn't work with `GITHUB_TOKEN`
=> Prevent double auto-approve

ktor-utils/common/src/io/ktor/util/Base64.kt, ktor-utils/common/test/io/ktor/util/Base64Test.kt
**Subsystem**
ktor-utils
**Motivation**
In a unit test for a Ktor project I was encoding and decoding some data with `ByteArray.encodeBase64(): String` and `String.decodeBase64Bytes(): ByteArray` and was wondering why the result was not what I was expecting. After decoding and encoding, the resulting data was very slightly different from what I put in.
Turns out that the issue was, that I was using URL-safe base64 (i.e. same as normal base64, but all `+` characters are replaced by `-` and all `/` replaced by `_`, also no `=` padding at the end).
After looking at the source code, I found that `String.decodeBase64Bytes(): ByteArray` treats every character that is not a valid Base64 character as if it were the character `/`. That's because the decoded character is determined using …
=> Decode URL safe base64 correctly

ktor-server/ktor-server-plugins/ktor-server-di/api/ktor-server-di.api, ktor-server/ktor-server-plugins/ktor-server-di/api/ktor-server-di.klib.api, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyConflictPolicy.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyInjection.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyProvider.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/test/io/ktor/server/plugins/di/DependencyInjectionTest.kt, ktor-server/ktor-server-plugins/ktor-server-di/jvm/test/io/ktor/server/plugins/di/DependencyInjectionJvmTest.kt
**Subsystem**
Server, DI
**Motivation**
[KTOR-8306](https://youtrack.jetbrains.com/issue/KTOR-8306) Dependency injection tooling for tests
This was requested in the design doc review as a possible improvement for test tooling.
**Solution**
Now, when the DI plugin is installed from the test engine, it will use a custom conflict policy that allows overriding implementations.
When writing tests, you can now do something like:
```kotlin
fun test() = testApplication {
// 1. Install modules as they'd normally appear
installProductionTypes()
// 2. Replace specific implementations with mocks
dependencies {
provide<Database> { MockDatabaseInstance() }
}
// 3. Run tests
}
```
=> KTOR-8306 Dependency injection tooling for tests

build-logic/src/main/kotlin/ktorbuild.kmp.gradle.kts, build-logic/src/main/kotlin/ktorbuild.publish.gradle.kts, build-logic/src/main/kotlin/ktorbuild/CInterop.kt, build-settings-logic/src/main/kotlin/ConfigurationCacheWorkarounds.kt, build-settings-logic/src/main/kotlin/ktorbuild.configuration-cache.settings.gradle.kts, build-settings-logic/src/main/kotlin/ktorbuild.develocity.settings.gradle.kts, gradle.properties, ktor-test-server/src/main/kotlin/test-server.gradle.kts, settings.gradle.kts
**Subsystem**
Infrastructure
**Motivation**
[KTOR-7667](https://youtrack.jetbrains.com/issue/KTOR-7667) Enable Gradle configuration cache
**Solution**
Finally, I've found a hackaround for [KT-72933](https://youtrack.jetbrains.com/issue/KT-72933), and we can enable configuration cache 🎉 
It will work only for tasks not involving `MetadataDependencyTransformationTask`.
Some benchmark results for scenario "Rerun `:ktor-client:ktor-client-core:jvmTest` after a change in JVM source set."
_default_ - optimizations disabled
_COD_ - configuration on demand enabled
_CC_ - configuration cache enabled
Scenarios `default` and `COD` represent the case when there is no configuration cache that could be reused, let's call it "initial configuration".
Results show that configuration on demand …
=> KTOR-7667: Enable Gradle configuration cache

renovate.json
Added Develocity plugin id to the list of exceptions. It is required because of https://github.com/ktorio/ktor/commit/8a8b1867a503bdd539348cb10b03976fa719635f
=> Don't update develocity plugin automatically

build-logic/src/main/kotlin/ktorbuild.publish.gradle.kts, build-logic/src/main/kotlin/ktorbuild/internal/LimitedParallelismService.kt
**Subsystem**
Publishing Infrastructure
**Reason**
Publishing fails as `gpgAgentLock` is stored in the root project's `extra`
**Solution**
Remove usage of `rootProject.extra`. Use shared build service instead.
=> Replace ReentrantLock with shared service with limited parallelism

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpTimeout.kt
**Subsystem**
Client, Core
**Motivation**
[KTOR-8358](https://youtrack.jetbrains.com/issue/KTOR-8358) HttpTimeout: Reference to nonexistent INFINITE_TIMEOUT_MS in the exception message
**Solution**
Replaced refereces to `HttpTimeout.INFINITE_TIMEOUT_MS` with `HttpTimeoutConfig.INFINITE_TIMEOUT_MS` on the exception message and kdocs
=> KTOR-8358 Fix Reference to nonexistent INFINITE_TIMEOUT_MS in the exception message on HttpTimeout

build-settings-logic/settings.gradle.kts, gradle/libs.versions.toml, renovate.json
**Subsystem**
Infrastructure
As soon as our Develocity server has been updated to 2024.2, we can use Develocity v3.18.*
=> Update Develocity plugin to 3.18.2

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/application/Application.kt, ktor-server/ktor-server-core/jsAndWasmShared/src/io/ktor/server/engine/EmbeddedServer.jsAndWasmShared.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/ShutDownUrl.kt, ktor-server/ktor-server-core/posix/src/io/ktor/server/engine/EmbeddedServerNix.kt, ktor-server/ktor-server-test-host/api/ktor-server-test-host.api, ktor-server/ktor-server-test-host/api/ktor-server-test-host.klib.api, ktor-server/ktor-server-test-host/common/src/io/ktor/server/testing/TestApplication.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
Server, Core
**Motivation**
[KTOR-8291](https://youtrack.jetbrains.com/issue/KTOR-8291) Application job is not joined during shutdown
**Solution**
Added a `disposeAndJoin()` internal API function on `Application` which waits for the application job to join after cancelling, then replaced all relevant references.  This is important for properly cleaning up resources when the server is closed or refreshed, because otherwise the process will stop before executing any `onCancelled` hooks are executed.
Note [KTOR-8338](https://youtrack.jetbrains.com/issue/KTOR-8338) will need to wait for 3.2.0, because it will require some more significant changes because only the CIO engine uses the application job as the parent for jobs spawned from the call context.
=> KTOR-8291 Fix for coroutines not joined on shutdown

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt, ktor-server/ktor-server-test-suites/common/src/io/ktor/server/testing/suites/WebSocketEngineSuite.kt, ktor-shared/ktor-websockets/common/src/io/ktor/websocket/RawWebSocketCommon.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/FrameParser.kt, ktor-shared/ktor-websockets/jvm/src/io/ktor/websocket/RawWebSocketJvm.kt
**Subsystem**
Server, Netty, Websockets
**Motivation**
[KTOR-7965](https://youtrack.jetbrains.com/issue/KTOR-7965) Netty/Websockets: server processes hanging in CLOSE_WAIT state after many concurrent requests
**Solution**
This was caused by an invalid client frame header causing an exception in the server that would miss closing the underlying Netty channel, which would leak socket connections.
We'd also have some uncaught coroutine exceptions from this due to using `IllegalArgumentException` for invalid opcodes.  There was also a problem with exceptions thrown from trying to send the error close frame after the client has hung up.
=> KTOR-7965 Fix for connection leak in Netty websockets

ktor-http/common/src/io/ktor/http/content/CompressedContent.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/PreCompressed.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/CompressionTest.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
**Subsystem**
ktor-http, ktor-server-core
**Motivation**
KTOR-8326. Added support for 'Vary' header in responses.
**Solution**
Append 'Accept-Encoding' header to 'Vary' if response was compressed based on Accept-Encoding values received from client call.
=> KTOR-8236: support for 'Vary' header

ktor-http/common/src/io/ktor/http/HttpHeaderValueParser.kt, ktor-http/common/test/io/ktor/tests/http/CommonHeadersTest.kt
**Subsystem**
HTTP - header parsing
**Motivation**
I want to replace HTTP Header parsing within Intellij Platform (specifically collab tools subsystems) with Ktor parsing.
Sadly, we are currently blocked by this bug: parsing a header value with parameters surrounded by double-annotation marks, immediately followed by a comma fails. Ex: `k: "v", k2: "v2"` does not correctly parse after the first `"`.
**Solution**
Add the comma exception to the list of characters that can follow `"`
=> Add ',' to parameter quoting terminals in HttpHeaderValueParser

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteChannel.kt, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannel.kt, ktor-io/common/src/io/ktor/utils/io/CloseHookByteWriteChannel.kt, ktor-io/common/src/io/ktor/utils/io/CountedByteWriteChannel.kt, ktor-network/common/test/io/ktor/network/sockets/tests/TCPSocketTest.kt
autoFlush of the source channel doesn't make the channel auto flushing
**Subsystem**
ktor-io
**Motivation**
I reported the bug [KTOR-8411](https://youtrack.jetbrains.com/issue/KTOR-8411/CountedByteWriteChannel-autoFlush-of-the-source-channel-doesnt-make-the-channel-auto-flushing) yesterday and took a deeper look to get it fixed, since it looked simple.
**Solution**
I decided to move the `autoFlush` property higher up the hierarchy so that all implementations may actually have access to it and a cast to ByteChannel won't be necessary. The cast fails for some implementations due to the inheritance hierarchy, hence the bug.
=> KTOR-8411 CountedByteWriteChannel: fix autoFlush not working

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/DefaultClientSSESession.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt, ktor-http/ktor-http-cio/jvm/test/io/ktor/tests/http/cio/ChunkedTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/ServerSentEvents.kt
**Subsystem**
Client, SSE, I/O
**Motivation**
[KTOR-8204](https://youtrack.jetbrains.com/issue/KTOR-8204) CIO: Exception Chunked stream has ended unexpectedly
**Solution**
It seems to be fairly common to experience connection hangups before events start writing which can lead to this chunked transfer encoding validation error.  Instead of throwing the exception now, we'll just return when there's no chunk size.
Also, I added a catch for closed channels to avoid throwing on normal disconnects when parsing, and I updated the SSE tests a little to shorten up the time they're taking to run.
=> KTOR-8204 Fix for exception on empty chunked body response

ktor-client/ktor-client-plugins/ktor-client-auth/common/src/io/ktor/client/plugins/auth/providers/BearerAuthProvider.kt, ktor-client/ktor-client-plugins/ktor-client-auth/common/test/io/ktor/client/plugins/auth/AuthTest.kt
**Subsystem**
Client BearerAuthProvider
**Motivation**
This PR fixes [KTOR-8107](https://youtrack.jetbrains.com/issue/KTOR-8107/Dont-send-Authorization-header-for-requests-marked-with-markAsRefreshTokenRequest)
**Solution**
When AuthCircuitBreaker attribute is found on request, Authorization header is not appended.
=> KTOR-8107 Don't add auth header for requests with AuthCircuitBreaker

ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpSSESession.kt, ktor-client/ktor-client-okhttp/jvm/test/io/ktor/client/engine/okhttp/OkHttpHttpClientTest.kt
Currently, when the outer coroutine context is canceled, the OkHttp connection thread is leaked. This is because the connection is never canceled when the session job is completed. This is also because the OkHttp SSE session doesn't have it's own Job for use within the SSE session block and was defaulting to the open call request
**Subsystem**
OkHttp Client
**Motivation**
KTOR-8409
**Solution**
I followed the pattern from `DefaultClientSSESession` of creating a new `Job` for the coroutine context of the session and added a `invokeOnComplete` callback to close the OkHttp SSE connection when the `Job` is complete.
I added 2 tests to make sure that reading or not reading from the incoming messages has no effect on the OkHttp connection being closed.
=> KTOR-8409 Fix closing of OkHttp SSE connection

ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt
**Subsystem**
Server, core
**Motivation**
Route rendering is important in several places, for example in metrics collection.
Currently for static files we have metrics like
```
ktor_http_server_requests_seconds_sum{method="GET",route="/io.ktor.server.http.content.StaticContentKt$staticContentRoute$1@70830e08/images/{...}",status="404",
throwable="n/a"} 0.227668303
```
**Solution**
Provide correct toString implementation for anonymous Route subclass, created in `staticContentRoute` method.
=> KTOR-8451: Fix toString for staticContentRoute

ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
**Subsystem**
Server, Netty
**Motivation**
[KTOR-8338](https://youtrack.jetbrains.com/issue/KTOR-8338) Coroutines launched from RoutingContext are not cancelled upon server shutdown
**Solution**
This avoids using the netty dispatcher for the user context within routing calls.  Previously, the underlying executor for the netty dispatcher would get closed, then `onComplete` would fail to trigger because of the missing executor.  Now, the netty dispatcher will only be used for handling the calls themselves, and not other coroutines launched from the call.
=> KTOR-8338 Fix for call context coroutines not being cancelled

ktor-server/ktor-server-plugins/ktor-server-di/api/ktor-server-di.api, ktor-server/ktor-server-plugins/ktor-server-di/api/ktor-server-di.klib.api, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyConflictPolicy.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyInjection.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyKeyCovariance.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyProvider.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyRegistry.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyResolution.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/utils/Types.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/test/io/ktor/server/plugins/di/DependencyInjectionTest.kt, ktor-server/ktor-server-plugins/ktor-server-di/jvm/src/io/ktor/server/plugins/di/utils/Types.jvm.kt, ktor-server/ktor-server-plugins/ktor-server-di/jvm/test/io/ktor/server/plugins/di/DependencyInjectionJvmTest.kt, ktor-server/ktor-server-plugins/ktor-server-di/jvm/test/io/ktor/server/plugins/di/utils/TypesTest.kt, ktor-server/ktor-server-plugins/ktor-server-di/nonJvm/src/io/ktor/server/plugins/di/utils/Types.nonJvm.kt
**Subsystem**
Server, DI
**Motivation**
- [KTOR-8305](https://youtrack.jetbrains.com/issue/KTOR-8305) Optional dependencies and nullable type support
- [KTOR-8434](https://youtrack.jetbrains.com/issue/KTOR-8434) Dependency injection - type parameter covariance supertypes
**Solution**
Now, you can optionally resolve dependencies using nullables (like `resolve<Foo?>()`).  This applies only when the dependency is not provided, and will continue to fail if some other exception was thrown when trying to resolve it.
I've also introduced support for resolving covariant type parameter arguments, so declaring `MutableList<String>` will work with resolving `List<CharSequence>` by checking the type bounds on the supertypes.
I discovered during testing that it was very easy to hit ambiguity …
=> Improved DI for nullables, parameterized types

build-logic/src/main/kotlin/ktorbuild/targets/JsConfig.kt
**Subsystem**
Infrastructure
**Motivation**
A lot of weird messages during project sync
> Mocha test framework for Wasm target is not supported. For KotlinWasmNode used
**Solution**
Don't try to configure the Mocha framework for Wasm targets, as [it is unsupported](https://github.com/JetBrains/kotlin/blob/v2.1.20/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/targets/js/testing/KotlinJsTest.kt#L124).
=> Fix the annoying warning about the Mocha framework not being used

ktor-server/ktor-server-plugins/ktor-server-di/api/ktor-server-di.api, ktor-server/ktor-server-plugins/ktor-server-di/api/ktor-server-di.klib.api, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyInjection.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/src/io/ktor/server/plugins/di/DependencyRegistry.kt, ktor-server/ktor-server-plugins/ktor-server-di/common/test/io/ktor/server/plugins/di/DependencyInjectionTest.kt
**Subsystem**
Server, DI
**Motivation**
[KTOR-8447](https://youtrack.jetbrains.com/issue/KTOR-8447) Dependency injection - cleanup support
**Solution**
- Added `onShutdown` property to `DependencyInjectionConfig` that closes any `AutoCloseable` declarations, or can be replaced to provide other general functionality.
- Added `cleanup` function to the registry for handling individual hooks for executing when the server shuts down.  See the additions in `DependencyInjectionTest.kt` for an example of how it looks in the DSL.
=> KTOR-8447 DI cleanup support

ktor-http/common/src/io/ktor/http/content/Multipart.kt
**Subsystem**
Server, common module
**Motivation**
The KDoc for `Multipart.dispose()` misspells "longer".
**Solution**
Fix the typo accordingly.
=> Fix a small KDoc typo (longed -> longer)

gradle.properties, teamcity.default.properties
**Subsystem**
Infrastructure
**Motivation**
[KTOR-8035](https://youtrack.jetbrains.com/issue/KTOR-8035) Investigate CI failures due to insufficient RAM
**Solution**
- Apply a workaround for [TW-93433](https://youtrack.jetbrains.com/issue/TW-93433) "TeamCity ignores system properties specified in org.gradle.jvmargs"
- Limit heap size for K/N utilities
- Reduce the default max idle time for Kotlin Daemons from 3 hours to 30 minutes
=> KTOR-8035 Refine JVM args

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/ByteWriteChannelOperations.kt, ktor-network/common/src/io/ktor/network/sockets/SocketBase.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/config/MapApplicationConfig.kt
**Subsystem**
Client/Server
**Motivation**
[KTOR-8525](https://youtrack.jetbrains.com/issue/KTOR-8525) ktor-network produces ProGuard warning
**Solution**
The warning was caused by a lambda created inside the inline function. I've moved the lambda to the class field.
Also fixed another warning on the recently changed `combine(String, Any)` function
=> Fix some ProGuard warnings

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingIntrospection.kt
The routing root node is hardly discoverable, so navigating over existing API endpoints is complicated
=> Add extension to discovery routing root node

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCache.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/HttpCacheLegacy.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/cache/storage/UnlimitedCacheStorage.kt, ktor-client/ktor-client-core/jvm/src/io/ktor/client/plugins/cache/storage/FileCacheStorage.kt, ktor-client/ktor-client-core/jvm/test/CachingCacheStorageTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/CacheTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/Cache.kt
**Subsystem**
Client, Caching
**Motivation** & **Solution**
This PR fixes https://youtrack.jetbrains.com/issue/KTOR-8345/HttpCache-InvalidCacheStateException-thrown-when-Vary-header-has-different-entries-is-overly-severe
Let me explain:
All starts with [this](https://youtrack.jetbrains.com/issue/KTOR-7104).
Someone requested to update cache in case the Vary header differs.
Actually this violates the Vary header spec.
See https://developer.mozilla.org/de/docs/Web/HTTP/Reference/Headers/Vary
> The same Vary header value should be used on all responses for a given URL, including [304](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/304) Not Modified responses and the "default" response.
To make Ktor more compliant with the specs, [this …
=> Ktor 8345: Make VaryHeader check lenient

ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpMethodTest.kt, ktor-http/common/src/io/ktor/http/HttpMethod.kt, ktor-test-server/src/main/kotlin/test/server/ClientTestServer.kt, ktor-test-server/src/main/kotlin/test/server/tests/Echo.kt
**Subsystem**
Client, Android
**Motivation**
[KTOR-8352](https://youtrack.jetbrains.com/issue/KTOR-8352) Android: "ProtocolException: TRACE does not support writing" when sending TRACE request
**Solution**
Added test checking that all clients are able to send requests with any default HTTP header.
Fixed the Android client by using recently added `!method.supportsRequestBody` instead of checking `METHODS_WITHOUT_BODY` list.
=> KTOR-8352: Fix TRACE method handling in AndroidClientEngine

ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/CurlProcessor.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlAdapters.kt, ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/internal/CurlMultiApiHandler.kt, ktor-client/ktor-client-test-base/common/src/io/ktor/client/test/base/ClientLoader.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/WebSocketTest.kt
**Subsystem**
`ktor-client-curl`
**Motivation**
[KTOR-8259](https://youtrack.jetbrains.com/issue/KTOR-8259) Linux curl engine doesn't work for simultaneous websocket and http request
**Solution**
The root cause was in `CurlMultiApiHandler.perform` implementation. It was waiting for `transfersRunning == 0` to exit and for websocket connections it happend only after they're closed. So `drainRequestQueue` was never called again until websocket connection is closed.
Another problem was in `cancelRequest`. It was calling `curl_multi_remove_handle` instead of `handleCompleted` and handle could be removed twice from a `multiHandle`. I removed this call and added `handleCompleted` call in `close` to ensure all completed and cancelled requests are handled.
Also enabled some flaky tests to check if …
=> KTOR-8259 Make CurlMultiApiHandler.perform non-blocking

ktor-io/api/ktor-io.api, ktor-io/api/ktor-io.klib.api, ktor-io/common/src/io/ktor/utils/io/Annotations.kt, ktor-server/ktor-server-plugins/ktor-server-htmx/common/src/io/ktor/server/htmx/HxHeaders.kt, ktor-server/ktor-server-plugins/ktor-server-htmx/common/src/io/ktor/server/htmx/HxRouting.kt, ktor-server/ktor-server-plugins/ktor-server-htmx/common/test/io/ktor/server/htmx/HxRoutingTest.kt, ktor-shared/ktor-htmx/api/ktor-htmx.api, ktor-shared/ktor-htmx/api/ktor-htmx.klib.api, ktor-shared/ktor-htmx/common/src/io/ktor/htmx/Annotations.kt, ktor-shared/ktor-htmx/ktor-htmx-html/common/src/io/ktor/htmx/html/HxAttributes.kt, ktor-shared/ktor-htmx/ktor-htmx-html/common/test/io/ktor/htmx/html/HxAttributesTest.kt
**Subsystem**
Shared, HTMX
**Motivation**
[KTOR-7584](https://youtrack.jetbrains.com/issue/KTOR-7584) First-class HTMX support
I realized having a specific flag doesn't make sense since we can't remove it without breaking the API.
**Solution**
Moved the annotation to a common type so we can mark other things as such when we want to solicit some feedback before committing to a stable API.
=> KTOR-7584 Moved experimental htmx annotation to a common type

ktor-client/ktor-client-mock/api/ktor-client-mock.api, ktor-client/ktor-client-mock/api/ktor-client-mock.klib.api, ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt, ktor-client/ktor-client-mock/jvm/test/io/ktor/client/tests/mock/MockEngineTests.kt
**Subsystem**
Client testing
**Motivation**
I recently started using Ktor as a replacement for OkHttp for various reasons, and I came across MockEngine as an apparent replacement for [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver). One thing that I did quite a lot with MockWebServer was to:
1. initialise the client in a test's `@Before` block
2. pass it into the rest of the system under test
3. specify HTTP behaviour on a per-test basis
4. make the call
6. verify the behaviour
7. maybe repeat steps 3-6 several times, depending on test complexity
But with MockEngine as it is I need to pass in an initial MockRequestHandler, otherwise an exception is thrown.
**Solution**
This change adds the option to intialise MockEngine without a MockRequestHandler using the …
=> Better configurability for MockEngine

ktor-server/ktor-server-plugins/ktor-server-di/common/test/io/ktor/server/plugins/di/DependencyInjectionTest.kt
Because `dependency.resolve()` is called within the endpoint handlers, it's possible that the instantiation is invoked twice for the greeting service because there's no internal mutex for instantiation.
=> Fix DI async flaky test

ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/SaveBody.kt
**Subsystem**
Android, R8
**Motivation**
[KTOR-8583](https://youtrack.jetbrains.com/issue/KTOR-8583) "Space characters in SimpleName" error when executing R8 mergeExtDex task with 3.2.0
**Solution**
Even though these constants are inlined at compile time, D8 fails to transform the class.
Remove spaces from constant names.
=> KTOR-8583 Remove spaces from constant names

ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/src/io/ktor/server/thymeleaf/RespondTemplate.kt, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/src/io/ktor/server/thymeleaf/Thymeleaf.kt, ktor-server/ktor-server-plugins/ktor-server-thymeleaf/jvm/test/io/ktor/server/thymeleaf/ThymeleafTest.kt
**Subsystem**
Server `Thymeleaf` plugin.
**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-8559
Allows `null`/nullable values to be passed to the model used for thymeleaf.
imo this is a bugfix as it does not involve any breaking api changes & is just matching features with what thymeleaf already supports (ie. if you do an unchecked cast to `Map<String, Any>` and pass a null value, everything will work just fine), however the issue in youtrack was marked as "Feature" rather than "Bug", so I named my branch following that.
**Solution**
`Any` -> `Any?`
=> KTOR-8559 Thymeleaf: Allow null values in template model

gradle/libs.versions.toml, kotlin-js-store/yarn.lock, ktor-server/ktor-server-plugins/ktor-server-default-headers/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-default-headers/common/src/io/ktor/server/plugins/defaultheaders/DefaultHeaders.kt
**Subsystem**
Server, ktor-server-default-headers
**Motivation**
[KTOR-8635](https://youtrack.jetbrains.com/issue/KTOR-8635/Replace-kotlinx.datetime-APIs-with-kotlin.time) Replace kotlinx.datetime APIs with kotlin.time
**Solution**
Bump API version for the `ktor-server-default-headers` module and drop usage of the kotlinx-datetime.
Fixes #4969
=> KTOR-8635 Use kotlin.time.Clock instead of kotlinx.datetime.Clock

ktor-server/ktor-server-plugins/ktor-server-sse/common/test/io/ktor/server/sse/ServerSentEventsTest.kt, ktor-shared/ktor-sse/common/src/io/ktor/sse/ServerSentEvent.kt
Ticket: [KTOR-8627](https://youtrack.jetbrains.com/issue/KTOR-8627) Change the order of SSE field serialization: put `event` before `data`
**Subsystem**
SSE: ktor-shared/ktor-sse
**Motivation**
Currently, the `data` field comes before the `event` field in the SSE payload. If the streaming parser used the `event` field as a discriminator to determine the deserializer, it must buffer the `data`. Moving `event` before `data` would allow streaming SSE parsers to avoid buffering SSE's `data` field and choosing the right deserializer before reading the data field. In the [reference](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) `event` field also comes before the `data`.
**Solution**
Change the order of field serialization to …
=> [KTOR-8627] Reorder SSE fields for streaming deserialization

build-logic/src/main/kotlin/ktorbuild.dokka.gradle.kts, build-logic/src/main/kotlin/ktorbuild/internal/Version.kt
**Motivation**
Save some time when publishing snapshots and EAPs.
**Solution**
Enable dokka generation only if the version is stable (matches the regex `\d+\.\d+\.\d+`).
=> Do not generate dokka for snapshots and EAPs

ktor-server/ktor-server-plugins/ktor-server-status-pages/build.gradle.kts, ktor-server/ktor-server-plugins/ktor-server-status-pages/common/src/io/ktor/server/plugins/statuspages/StatusPages.kt, ktor-server/ktor-server-plugins/ktor-server-status-pages/common/test/io/ktor/server/plugins/statuspages/StatusPagesTest.kt
**Subsystem**
Server, StatusPages plugin
**Motivation**
[KTOR-8232](https://youtrack.jetbrains.com/issue/KTOR-8232) 
**Solution**
Append OutgoingContent headers in the `ResponseBodyReadyForSend` hook
=> Fix KTOR-8232 StatusPages: OutgoingContent headers aren't available in the status handlers

ktor-server/ktor-server-plugins/ktor-server-sse/common/test/io/ktor/server/sse/ServerSentEventsTest.kt
This flaky test doesn't really test anything because there's no synchronization between the server and client for SSE, and there are other tests that ensure the messages arrive in order.
=> Drop broken SSE test

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/ShutDownUrl.kt, ktor-server/ktor-server-core/jvm/test/io/ktor/server/engine/ShutDownUrlTest.kt
**Subsystem**
Server, ShutdownUrl
**Motivation**
[KTOR-8674](https://youtrack.jetbrains.com/issue/KTOR-8674) ShutDownUrl: The server cannot shut down since 3.2.0
**Solution**
The improvements for structured concurrency introduced in 3.2 a deadlock in this plugin due to the shutdown coroutine being launched on the application's context and waiting for the context to join.
=> KTOR-8674 Fix ShutdownUrl plugin

ktor-client/ktor-client-core/js/src/io/ktor/client/plugins/websocket/JsWebSocketSession.kt, ktor-client/ktor-client-core/wasmJs/src/io/ktor/client/plugins/websocket/JsWebSocketSession.kt
**Subsystem**
Client
**Motivation**
[KTOR-8700](https://youtrack.jetbrains.com/issue/KTOR-8700/Websocket-binary-frames-have-fin-always-set-to-false)
**Solution**
Described in KTOR-8700
=> KTOR-8700 fix Websocket binary frames fin on wasm and js

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/jvm/src/io/ktor/server/http/content/StaticContent.kt, ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt
**Subsystem**
Server, StaticContent
**Motivation**
[KTOR-8496](https://youtrack.jetbrains.com/issue/KTOR-8496)
**Solution**
Add `fallback`:
```kotlin
staticFiles("/static", File("files")) {
fallback { requestedPath, call ->
when {
requestedPath.endsWith(".php") -> call.respondRedirect("/static/index.html")
requestedPath.endsWith(".xml") -> call.respond(HttpStatusCode.Gone)
else -> call.respondFile(File("files/index.html"))
}
}
}
```
=> KTOR-8496 Add fallback logic for StaticContent

build-logic/src/main/kotlin/ktorbuild/targets/JsConfig.kt, build.gradle.kts, gradle/libs.versions.toml, kotlin-js-store/wasm/yarn.lock, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt
**Subsystem**
Infrastructure
**Motivation**
[KTOR-8774](https://youtrack.jetbrains.com/issue/KTOR-8774) Fix browser tests running on CI
**Solution**
The reason why browser tests weren't working is that our Docker image doesn't have preinstalled chrome. Previously it had been working the following way:
1. Add `puppeteer` as a test dependency
2. Set flag `ignoreSripts = false`
3. NPM installs Chrome automatically together with puppeteer
The problem is that some time ago the flag `ignoreScripts` was accidentally removed.
Quick solution is to enable this flag back. The proper solution is to provide Chrome with the image used to run tests:
- #5048
This PR implements the quick solution.
=> KTOR-8774 Fix browser tests running on CI

gradle/libs.versions.toml
**Subsystem**
Server.
**Motivation**
To address vulnerability [CVE-2025-55163](https://www.cve.org/CVERecord?id=CVE-2025-55163).
**Solution**
Perform Netty version update as suggested.
=> CVE-2025-55163: Update netty to `4.2.4.Final`

ktor-utils/jvm/src/io/ktor/util/Nonce.kt
Run nonceGeneratorJob on the Default dispatcher to avoid coroutine deadlock. 
**Subsystem**
Client, ktor-utils
**Motivation**
Ktor client is used for load testing, where a big number of outbound websocket connections are created simultaneously (no delay). If the number of connections is greater than the number of threads in IO dispatcher, neither connection progresses and all of them are stuck in [blocking read of nonce value](https://github.com/ktorio/ktor/blob/main/ktor-utils/jvm/src/io/ktor/util/CryptoJvm.kt#L75) from the channel.
A global job [nonceGeneratorJob](https://github.com/ktorio/ktor/blob/main/ktor-utils/jvm/src/io/ktor/util/Nonce.kt#L32) calculates the nonce value and publishes the result via the channel, however, as the job is launched on IO dispatcher, at this point all …
=> Fix KTOR-8829

ktor-server/ktor-server-core/api/ktor-server-core.api, ktor-server/ktor-server-core/api/ktor-server-core.klib.api, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingPipelineCall.kt, ktor-server/ktor-server-core/common/src/io/ktor/server/routing/RoutingRoot.kt, ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt, ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1Handler.kt
**Subsystem**
Server, Core
**Motivation**
[KTOR-8821](https://youtrack.jetbrains.com/issue/KTOR-8821) Autoreloading: it doesn't reload rebuilt classes since 3.2.0
[KTOR-8810](https://youtrack.jetbrains.com/issue/KTOR-8810) Autoreloading: JobCancellationException when app is reloaded in the debugger since 3.2.0
**Solution**
Fix 1: dynamic module wrapping for lambdas would cause errors on reloads
Fix 2: Netty was using the old application instance in the coroutine context, which caused auto-reloading to fail when debugging.
This also fixes the issue with the static resources.
=> KTOR-8821 Fix auto-reload issue / exception on lambda

ktor-client/ktor-client-cio/common/src/io/ktor/client/engine/cio/Endpoint.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/call/SavedCall.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/engine/Utils.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt, ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpRequestRetryTest.kt, ktor-utils/jvm/src/io/ktor/util/Deflater.kt, ktor-utils/jvm/src/io/ktor/util/EncodersJvm.kt
**Subsystem**
Server
**Motivation**
[KTOR-8820](https://youtrack.jetbrains.com/issue/KTOR-8820) Performance regression when using ContentEncoding and HttpRequestRetry since 3.2.0
The bug was caused by a combination of `ContentEncoding`, `HttpRequestRetry` and `SaveBody` plugins.
1. `SaveBody`: creates a new channel on each `HttpResponse.rawContent` call
2. `ContentEnconding`: starts a coroutine for each created channel, and this coroutine exists until the entire body has been read
3. `HttpRequestRetry`: calls `rawContent` and then reads only one byte, leaving the channel not closed
As a result, the coroutine started by the `ContentEncoding` plugin hangs until the request fails by timeout (the default timeout is 15 seconds).
**Solution**
Added cancellation of the `rawContent` channel in …
=> KTOR-8820 Performance regression when using ContentEncoding and HttpRequestRetry since 3.2.0

ktor-client/ktor-client-plugins/ktor-client-content-negotiation/common/src/io/ktor/client/plugins/contentnegotiation/ContentNegotiation.kt, ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/ServerSentEventsTest.kt, ktor-test-server/src/main/kotlin/test/server/tests/ServerSentEvents.kt
**Subsystem**
Client, ContentNegotiation, SSE
**Motivation**
[KTOR-7631](https://youtrack.jetbrains.com/issue/KTOR-7631)
**Solution**
Skip `ContentNegotiation` plugin for SSE sessions
=> KTOR-7631 Fix SerializationException when ContentNegotiation installed before SSE
